### ISSUE TITLE
Use type.Specifier for gateway RPC IDs

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1004]

**Comment by lukechampine** [comment]
maintaining compatibility is going to be pretty tricky here. Not sure what the best approach is. Knowing the version of each of your peers helps a lot, but it might get ugly regardless.

**Comment by DavidVorick** [comment]
did we ever address this?

**Comment by lukechampine** [comment]
no. But imo it's not a big deal, especially since name collision is increasingly unlikely as the platform matures.
