### ISSUE TITLE
/explorer 404 - Refer to API.md

### ISSUE THREAD

**Issue by wiseguy12851** [NebulousLabs/Sia#1005]
Upon setting up an app to hook into the siad api, I ran into an unusual problem where /explorer endpoint doesn't work giving the error `404 - Refer to API.md`. However I'm going straight by the documentation saying `/explorer` is the correct endpoint and that its not suppose to contain any parameters as it displays several non-block or hash specific details.

Actually further testing shows I'm unable to get any of the /explorer api, /explorer, /explorer/hashes/{hash}, /explorer/blocks/{height}

I'm using siad version 0.5.1, any ideas on what to do or is this a bug?

**Comment by DavidVorick** [comment]
you need to run siad with the explorer module enabled. there's a `-M` flag that lets you choose which modules to enable. You'll probably want all of them `-M "cghmrtw"`

**Comment by pmknutsen** [comment]
@DavidVorick Should the letters really be enclosed in double-quotes? I've always done without.

**Comment by lukechampine** [comment]
they are optional, yeah. The only reason to use quotes is if the argument contains spaces or other special characters

**Comment by wiseguy12851** [comment]
Thanks, I didn't know about the module flags, adding the "e" to the rest fixed it for me.
