### ISSUE TITLE
Siad - more help information on the -M flag

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1006]
The current help doesn't even tell you the full list of modules that are available, let alone what the letters mean or why you might enable/disable them.

**Comment by VoidingWarranties** [comment]
I was going to add this when I originally added the flag, but one line wasn't enough to list all the options for the flag. I have a fork of [pflag](https://github.com/spf13/pflag) with support for multiline usage strings. It needs a little more work before I make a PR for it.

In the mean time we can add the information somewhere else, such as in the examples section for `siad`.

Unfortunately there's no other place to put the information and have it be specific to that flag.
`siad --modules --help` doesn't work. Alternatively we could split up the `--modules` flag into one flag per module. So running just a gateway could look something like: `siad -G` or `siad --gateway`. Running `siad` without any module flags would run the default modules (cghmrtw).
