### ISSUE TITLE
managedRPCSettings() can deadlock

### ISSUE THREAD

**Issue by david60** [NebulousLabs/Sia#1009]
I've seen managedRPCSettings() deadlock with master (fda4e228); and probably also with the 0.5.1 release. (On linux). The problem is seems to be that managedRPCSettings() takes a read lock on h.mu, and then calls h.Settings() which in turn also takes a read lock. The deadlock happens if a second goroutine attempts to take a write lock during in the interval between the two read locks; the write lock and the second read lock both start waiting.

**Comment by VoidingWarranties** [comment]
Good catch! The read lock in managedRPCSettings is unnecessary and should be removed.
