### ISSUE TITLE
possible races (may be worth while checking)

### ISSUE THREAD

**Issue by david60** [NebulousLabs/Sia#1010]
Hi,

While trying to understand #1009 I noticed a couple of places which may be data races. I've not seen any problems caused by these; but I thought I'd mention them so you can consider if they're something worth changing.

(i) increment of h.fileCounter and subsequent read (during filepath.Join()), in a couple of places. Maybe these should be within a write lock, not only a read lock.
(ii) data race in managedRPCRevise() during call obligation.fileSize(). Race was with ProcessConsensusChange(), on write of ob.OriginTransaction. [This one was flagged by the golang race detector]

Thanks.

**Comment by lukechampine** [comment]
The host code is being change significantly on the [renter-host-upgrades](https://github.com/NebulousLabs/Sia/tree/renter-host-upgrades) branch, so it's unlikely that these races will recur there. But we'll be on the lookout! Thanks.
