### ISSUE TITLE
panic: negative currency not allowed

### ISSUE THREAD

**Issue by david60** [NebulousLabs/Sia#1012]
Hi,

While running a debug build of siad (looking for #1009) I once had a panic:

panic: negative currency not allowed

So I record it here. I don't definitely understand what happened, but afterwards gave a brief look to see if I could see a path where that might happen: Perhaps one possibility is that during threadedProbeHosts() a hostEntry.weight can be recalculated; if the host is already in hdb tree, the summed weights aren't changed. But I acknowledge I may have missed something, anyway hope the report might be of help.

Thanks.

(More of the trace below:)

```go
negative currency not allowed
panic: negative currency not allowed



goroutine 320 [running]:
github.com/NebulousLabs/Sia/build.Critical(0xc823c29bb8, 0x1, 0x1)
        /home/goworkspace/src/github.com/NebulousLabs/Sia/build/critical.go:14 +0xe0
github.com/NebulousLabs/Sia/types.Currency.Sub(0x0, 0xc822734a50, 0x5, 0x9, 0x0, 0xc822476550, 0x5, 0x9, 0x0, 0xc822734a50, ...)
        /home/goworkspace/src/github.com/NebulousLabs/Sia/types/currency.go:155 +0x1f2
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*hostNode).removeNode(0xc822734e60)
        /home/goworkspace/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/weightedlist.go:143 +0xd3
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).decrementReliability(0xc8201c0340, 0xc821320600, 0x12, 0x0, 0xc82013e8a0, 0x1, 0x5)
        /home/goworkspace/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:85 +0x323
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedProbeHosts.func2(0xc8201c0340, 0xc823c29f60, 0x7ff8283dc8d8, 0xc824bf45f0, 0xc835fec140)
        /home/goworkspace/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:155 +0x28f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedProbeHosts(0xc8201c0340)
        /home/goworkspace/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:172 +0x122
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
        /home/goworkspace/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:133 +0x4a6)
```

**Comment by DavidVorick** [comment]
:< drat.

I've been ignoring this bug for a while, because nobody has been running debug mode. As best I can tell, it's not very severe, and doesn't cause problems in production, other than occasionally complaining.

But, perhaps that's been a bad plan. I really should get to the bottom of it. I think it triggers randomly every few hours, which means it'll make running debug mode basically impossible until we fix it.

**Comment by lukechampine** [comment]
Has this been resolved?

**Comment by DavidVorick** [comment]
not quite, #1315 dives deeper into the issue. #1317 fixes the issue, but does not have testing to prove that the issue is fixed (doing that now)

**Comment by DavidVorick** [comment]
Should be good now
