### ISSUE TITLE
0.5.2 RC release schedule

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1017]
The 0.5.2 RC will change the way consensus synchronizing works. The changes are mostly bug fixes and efficiency improvements, but in order to maintain backwards compatibility we need to roll out the release in a specific order. Specifically, the SendBlocks timeout introduced by the IBD improvements in #1013 would prevent 0.5.2 peers from synchronizing with older peers because of bug #1001. We have two options:

1: Don't include the IBD changes in this RC, and only include them in the next release once the majority of peers have updated to 0.5.2.

OR

2: Update the bootstrap peers to 0.5.2, but without the IBD changes, but do include the IBD changes in this RC. This will work because the IBD changes will only attempt to do IBD from outbound peers, at least one of which will be a bootstrap peer.

@DavidVorick and I talked about this offline and decided on option 2. Here's the planned release schedule:
- [x] Update bootstrap peers 1 by 1 to 3994d7050910d6ed649f5ea126de3def51449e90
- [x] Release 0.5.2 RC1 built from 3994d7050910d6ed649f5ea126de3def51449e90
- [x] Release 0.5.2 RC2 built from HEAD, but with a 45 minute SendBlocks timeout
- [x] Release 0.5.2 after RC is shown to be stable
- [ ] Update bootstrap peers to 0.5.2 once most peers have updated to 0.5.2
- [ ] In the next release (0.5.3 or 0.6.0) change the SendBlocks timeout back to 5 minutes

RC2 peers that are more than one block behind might only be able to sync with the updated bootstrap peers and other RC peers (if there connection is not fast enough to download the entire blockchain within the 2 hour SendBlocks timeout).

**Comment by DavidVorick** [comment]
FWIW nobody has reported trouble syncing :)

I've seen numbers as high as 13 hours, but the people who are taking 13 hours have been completely unable to use Sia prior to this release. In general people are reporting significant improvements in sync time and total network traffic.
