### ISSUE TITLE
/wallet/unlock direct REST call documentation 

### ISSUE THREAD

**Issue by easye** [NebulousLabs/Sia#1018]
The need to specify the "dictionary" parameter in the /wallet/unlock call is undocumented in <https://github.com/NebulousLabs/Sia/blob/master/doc/API.md>

**Comment by easye** [comment]
Actually, this is an optional parameter.  

My apologies for "rubber ducking" my problems with a github issue request.

**Comment by lukechampine** [comment]
Do you mean `/wallet/init`? `/wallet/unlock` does not take a dictionary.

**Comment by easye** [comment]
That's not what I am observing via wireshark.

```
cat wallet-secret | siac wallet unlock
```

produces the following REST request as grabbed via wireshark. 

Notice that the 'encryptionpassword' is also not correctly url-encoded (the 0x20 characters should be 0x2b).

```
POST /wallet/unlock HTTP/1.1
Host: localhost:9980
User-Agent: Sia-Agent
Content-Length: 243
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

encryptionpassword=jobs kiwi guide balding dads vehicle behind ripped language biweekly topic reunion kangaroo ruined pipeline liar toaster gown dinner biggest absorb roles idiom prying ceiling pipeline cunning scuba abnormal&dictonary=english
```

**Comment by lukechampine** [comment]
Gotcha. This is simply an error in siac. Note that the parameter isn't even spelled correctly. It should be removed.

I figured that Go would handle the URL-encoding internally, but I guess not. At any rate, it doesn't seem to be causing problems.
