### ISSUE TITLE
Official Network Spec

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#102]
Specifically, we need to define the exact byte layouts of all protocol-level network traffic. Blocks, transactions, contract negotiation, everything.

This can sit on the back burner for a while

**Comment by DavidVorick** [comment]
I do think that I'd rather not have issues open for a long time. It makes it harder to focus on the immediately desirable stuff, and I'm sure longer term wants are going to change anyway. I don't think that we'll forget to make a network spec.

**Comment by DavidVorick** [comment]
All the various ways we communicate will eventually be documented.
