### ISSUE TITLE
New .sia format

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1025]
With the transition to hash-based retrieval, we must design a new .sia format. The current format is a standard binary encoding of the `Renter.file` type:

``` go
struct {
    Name      string
    Size      uint64
    MasterKey crypto.SecretKey
    PieceSize uint64
    Mode      os.FileMode

    // generally the string "Reed-Solomon", plus data and parity integers
    ErasureCode modules.ErasureCode

    Contracts []struct {
        ID          types.FileContractID
        IP          modules.NetAddress
        WindowStart types.BlockHeight

        Pieces []struct {
                Chunk  uint64
                Piece  uint64
                Offset uint64
        }
    }
}
```

The simplest possible change would be to replace the `Offset` field with the piece's Merkle root. However, this would bloat the filesize significantly.
To reduce size, one strategy would be to store hashes in a flat array. This allows us to determine the `Chunk` and `Piece` values based on the array index. As a consequence of this, we would need to use a lookup table so that the hashes could efficiently reference their corresponding contract. The resulting format would look something like this:

``` go
struct {
    // name, encryption key, erasure code...

    Contracts []struct {
        ID          types.FileContractID
        IP          modules.NetAddress
        WindowStart types.BlockHeight
    }

    Sectors []struct {
        MerkleRoot crypto.Hash
        Contract   uint64 // indexes the Contracts field
    }
}
```

Unfortunately, this only saves 8 bytes per sector, since all we've done is replace the `Chunk` and `Piece` values with `Contract`. If we use a `uint16` for `Contract`, we save another 6 bytes, bringing the total increase down to 34/24 = 1.41.
Another opportunity for saving bytes is the `ID` field, which (IIRC) is not necessary for retrieval in the new protocol. This would save 32 bytes per contract, which works out to less than a kilobyte total for our current redundancy parameters. Since the ID is used elsewhere in the Renter (e.g. when renewing), removing it from the .sia format would mean storing it in the Renter persistence. So I'm opposed to removing the ID field.
We also need a way to deal with missing sectors. We could either use an empty Merkle root, or change the sector type to `[]*struct`, with `nil` indicating a missing sector (this adds one byte to each sector). I'm not sure which one I prefer. The latter saves lots of bytes when sectors are missing, but wastes bytes when they are not. Shouldn't .sia files be treated as though all their sectors will eventually be uploaded? I don't know.

Another aspect to consider is the bundling of multiple files. Currently, the format has a header which specifies the number of files it contains. I propose that we instead leverage the existing (and well-supported) `.tar` and `.gz` formats, like so:

| Filename | Type |
| :-- | :-- |
| foo.sia | Normal .sia file |
| foo.sia.gz | gzipped .sia file |
| foobar.tar | Archive containing foo.sia and bar.sia |
| foobar.tar.gz | gzipped archive containing foo.sia and bar.sia |

Finally, @DavidVorick has also suggested switching to JSON. This would make it easier for other people to use the format, and it might make compatibility a little easier too. My major concern here is filesize. Obviously, using JSON would increase the filesize, but perhaps compression would mitigate this. We should run tests with real-world .sia files to establish whether a JSON .sia is viable.

**Comment by pmknutsen** [comment]
@lukechampine `foobar.tgz` is an alternative to `foobar.tar.gz`

**Comment by DavidVorick** [comment]
JSON should not blow up the filesize by more than 2x. The compatibility gain from using json would be fantastic, especially if we get companies or clients that want to add extra information like permissions or something to their '.sia' files.

**Comment by lukechampine** [comment]
Synthetic benchmark looks promising:
| Encoding | Compression Ratio |
|:-------------|:-------------------------|
| Sia (binary) | 1.0003929138183594 |
| Hex | 1.1404573440551757 |
| Base64 | 1.0100781631469726 |
| JSON (`[][32]byte`) | 1.3305186462402343 |
| JSON (`[][]byte`) | 1.0658016967773438 |

The benchmark was performed by populating a `[][32]byte` with random data, encoding it, and compressing it with `gzip.BestCompression`. Since JSON encodes arrays very inefficiently, I converted the arrays to byte slices. JSON encodes byte slices in base64, so I was surprised to see that the JSON encoding (which included a `,` delimiter between each slice) outperformed the standard base64 encoding.

At any rate, it seems that if done properly, gzipped JSON does not add appreciable overhead to the filesize. Compared to Sia's binary encoding, gzipped JSON is about 6.5% larger.

**Comment by DavidVorick** [comment]
those are great numbers. gzip isn't even that great of a compression algorithm. Thanks for the benchmarks!

**Comment by lukechampine** [comment]
superseded by #2204
