### ISSUE TITLE
Reduce gateway logging

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1047]
Users have reported gateway logs on the order of gigabytes. There are lots of unnecessary logs like: `WARN: incoming RPC "RelayNod" from conn <peer> failed: node already added`.

**Comment by DavidVorick** [comment]
how is the gateway logging currently? As best I can tell, it's not typically a source of errors, so the logging in the gateway should be okay to be pretty minimal. For all the stuff that's buggy in v1.0, the gateway is holding up well.
