### ISSUE TITLE
siad hangs when having to deal with existing consensus.db

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia#1054]
Running the latest 0.5.2 release on El Capitan

If I start a fresh instance with an empty Sia folder, everything works fine. Siad runs, the blockchain syncs great, etc...

If however I start Sia with an existing consensus folder, siad hangs. Quitting and restarting makes Sia show these messages, in order:

"Loading Sia..."
"Siad has stopped responding: undefined"
"Siad has stopped responding: 1"

This makes the latest release completely unusable for me. The only fix I've found is to delete the consensus folder and start the sync all over again. If I quit Sia, I have to start all over again.

Here is what sys diagnostic spits out after a little bit of siad being unresponsive:

[siad_2016-04-09-154059_MBA.wakeups_resource.diag.zip](https://github.com/NebulousLabs/Sia/files/211275/siad_2016-04-09-154059_MBA.wakeups_resource.diag.zip)

**Comment by pmknutsen** [comment]
This happened to me too, after my first IBD (Linux 64bit). I think my mistake was to send a SIGKILL to terminate `siad`, rather than using `siac stop`.

**Comment by VoidingWarranties** [comment]
We fixed up a lot of module closing/shutdown code but might have broken
something in the process. The proper way to cleanly shutdown siad is to use
`siac stop` but sending a SIGKILL should also cleanly shutdown. I'll look
into this.

**Comment by DavidVorick** [comment]
I think I know what's happening here now. When there's an existing consensus db, some of the updates mean that sia occasionally needs to perform rescans to bring the modules up to speed. This causes siad to appear to hang, when really it's just doing a bunch of processing. Older versions of Sia could hang for several hours, although we've got it to the point where it shouldn't be more than 30 minutes.

That's still a long time, and there should be some output or responsiveness from the api to let the user know what is happening. Most of these updates are growing pains, it should be extremely rare that siad would need to do a rescan following the conclusion of our changes.

**Comment by DavidVorick** [comment]
closing this for now, we do have some rescan stuff in the pipeline but it's far enough away that I want to close this issue.
