### ISSUE TITLE
Miner saving

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1055]
It was determined that the miner saving to disk every block was causing performance issues during initialization, but now we've got a different problem, miner's files don't update for a while. I'm not sure what natural triggers (other  than closing) cause a disk save in the miner, but we should make sure that it's got an opportunity to regularly save the miner.

Same with the other modules. This is falling into the realm of premature optimization, let's focus on 1.0 first and performance after that's out.

**Comment by DavidVorick** [comment]
fixed to the degree that it needs to be in #1091

**Comment by lukechampine** [comment]
issues should be closed via commit message in merged PRs
