### ISSUE TITLE
Negative addresses remaining in wallet

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1066]
```
$ siac wallet seeds
Primary Seed: ***
Addresses Remaining -16891
All Seeds:
***
```

**Comment by DavidVorick** [comment]
As an extension of this, the 'Addresses Remaining' field should be made obsolete. For the purposes of the API, it should probably always return the value '1000' (to preserve compatibility).

**Comment by lukechampine** [comment]
Maybe we should define a sentinel value for numbers/strings that are obsolete. Kinda feels like cheating if we alter API semantics without altering structure, but oh well.

**Comment by DavidVorick** [comment]
As long as whatever value we choose does not risk breaking old apps

**Comment by DavidVorick** [comment]
Not done yet, needs updates in the api docs
