### ISSUE TITLE
v060-rc1 UX Stuff

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1083]
1. Contracts have a duration, but it appears that files also have a duration. Does the renter automatically delete a file after the duration has ended? Does it make sense to set the duration to zero? But, on top of 'duration' there's also a 'renew' field. I find this confusing. The api doc does explain it pretty well, but it doesn't seem that intuitive.

2. ~~I got the error 'insufficient balance for upload', but that's confusing because the problem related to the allowance. The wallet had enough money, but the renter did not have enough allowance. Just need to improve the error message I think.~~

3. Renter complains about not having enough hosts when you set the allowance. I found this confusing, though I can see why if you are trying to set the parameters really high (say 50 or 250 hosts) and the contractor knows that it can't make that many contracts reliably, you would want an error to be returned. My initial expectation was that errors should not be returned until you try to upload files, and that the renter should be in observation of how many contracts the contractor has successfully made before trying to erasure code things. If there aren't enough hosts, the contractor should accept the allowance call and then just make more contracts as more hosts appear. I'm definitely open for further discussion on this one. The api doc does not do a good job of explaining this error case.

**Comment by DavidVorick** [comment]
negotiation time for `formContract` is not long enough

**Comment by DavidVorick** [comment]
I will PR some of these

**Comment by lukechampine** [comment]
The idea was that when the file's duration ends, its sectors can be deleted, making room for new files to be uploaded. I think we can drop this idea in favor of simply deleting files manually when you need to free up space. So the duration and renew fields can be removed.

The renter should drop that balance check, yeah. That check is handled by the contractor now.

3 is the trickiest of the bunch. There are lots of conflicting concerns. I'm not sure what the best approach is, but I can tell you that both your suggestions would be difficult to implement (not in theory, just wrt the current code). I think the current approach is good enough for the RC, but the contractor's behavior absolutely warrants thorough discussion.

**Comment by lukechampine** [comment]
I'm imagining this sort of UX:

1. Open renter view for the first time
2. Popup window: `Before uploading files, you need to set an allowance. How many GB to you plan to upload per month? Your current wallet balance can support 1 TB per month. ______`
3. User enters value, UI converts it to siacoins (via host average) and multiplies it by 24 hosts.
4. Loading spinner while contracts are formed...
5. Popup window: `You are now ready to upload! You can change your allowance via the [UI element]. Changes to the allowance may not take effect immediately.`

**Comment by pmknutsen** [comment]
> User enters value, UI converts it to siacoins (via host average) and multiplies it by 24 hosts.

24 refers to redundancy? If so, should it not be 6 hosts?

**Comment by DavidVorick** [comment]
I believe that it should be 6 hosts, yeah
