### ISSUE TITLE
Nondeterministic build failure TestCallingRPCFromRPC

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1099]
```
--- FAIL: TestCallingRPCFromRPC (0.41s)

	rpc_test.go:373: expected FOO RPC to be called

FAIL

FAIL	github.com/NebulousLabs/Sia/modules/gateway	10.686s
```

**Comment by VoidingWarranties** [comment]
Hopefully that PR fixes this. Please reopen this issue if you encounter this test failure again.

**Comment by VoidingWarranties** [comment]
This test failed again randomly, so that PR did not fix it. I can't reproduce the test failing locally so it's difficult to debug. If you can reliably reproduce this test failure please let me know.
