### ISSUE TITLE
Strange anticipated revenue values

### ISSUE THREAD

**Issue by aspect** [NebulousLabs/Sia#1105]
```
Host info:
        Storage:      53.687 GB (4.312 GB used)
        Price:        140.000 SC per GB per month
        Max Duration: 25920 Blocks

        Contracts:           2331
        Accepting Contracts: Yes
        Anticipated Revenue: 1227385331974128597694813189
        Revenue:             68578326755554708124
        Lost Revenue:        0
```

**Comment by DavidVorick** [comment]
Yeah, the cli currently displays revenue in terms of our base unit. If you divide by 10^24 you'll get the actual value, 1227 SC.

**Comment by lukechampine** [comment]
Perhaps the exact amount should be displayed if you use `-v`?

**Comment by VoidingWarranties** [comment]
At the very least we should display the units. Displaying the exact amount with `-v` is a good idea.

**Comment by lukechampine** [comment]
My only concern would be overloading the meaning of `-v`. That is, IIRC `siac host` already displays extra information if you use `-v`. So there's the possibility that some values are *only* viewable in Hastings.

**Comment by VoidingWarranties** [comment]
Some tools (can't remember which off the top of my head) have a flag to display human readable units instead of exact units. Alternatively we could do the opposite and have a `--exact` flag to display exact amounts.

**Comment by DavidVorick** [comment]
I would be favor of `--exact`, though I can't really imagine many practical situations where you'd need an exact value. 1 SC is already much less than a penny.
