### ISSUE TITLE
--no-bootstrap still connects to bootstrap nodes

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1110]
The `--no-bootstrap` prevents Sia from connecting to 3 random boostrap nodes on startup, but all the bootstrap nodes are still added to the gateway's node list.

**Comment by DavidVorick** [comment]
is this still an issue?

**Comment by VoidingWarranties** [comment]
Yes, see [`modules/gateway.go:120`](https://github.com/NebulousLabs/Sia/blob/91eb549d5783344c70c0505756a8783e7eb0cf1f/modules/gateway/gateway.go#L120).

Currently to prevent Sia from connecting to bootstrap nodes you need to:
1. pass the `--no-bootstrap` flag to siad
AND
2. build such that `build.Release != "standard"`

**Comment by DavidVorick** [comment]
pending further investigation, I believe this was fixed the most resent set up gateway upgrades.
