### ISSUE TITLE
Siad has stopped responding: undefined

### ISSUE THREAD

**Issue by poiuty** [NebulousLabs/Sia#1131]
try upload files => upload /test/xxx.file and /xxx.file
When sync => delete test folder, and restart sia
When start => Siad has stopped responding: undefined
(Sia-UI v0.5.2 )

**Comment by DavidVorick** [comment]
How long did you wait? Sia v0.5.2 can take a while to startup, multiple minutes at least.

v0.6.0 starts up much faster.

**Comment by poiuty** [comment]
2~4 min

<img src="https://poiuty.com/img/9c/0c445656ab4467ad4f09952d22789a9c.png">

<img src="https://poiuty.com/img/cf/414ecb30003ccc7f4bb88afed0d2ddcf.png">

**Comment by DavidVorick** [comment]
this bug likely relates to older versions, and not the current GUI + siad
