### ISSUE TITLE
Blockchain synchronization frozen

### ISSUE THREAD

**Issue by HoteiLife** [NebulousLabs/Sia#1133]
Hello,

I have a sia system on which blockchain synchronization seems to have completely stalled. I left it overnight; no change in the morning. I restarted siad, still no movement. And I tried restarting the entire machine (actually a few times), still no movement.

It performed the initial synchronization fine when I first installed & it apparently kept itself updated for some time after that. Not sure what might have triggered the stall.

I'm not really sure what to look for to give you guys useful information. If there's something that can help I'm happy to do it.

**Comment by HoteiLife** [comment]
The system was a brand new install from the repository 2 days ago. So I believe version 0.6.0. It's a Linux system.

**Comment by lukechampine** [comment]
When you say "stall," what behaviors are you observing? Is your block height significantly lower than the one reported on http://explore.sia.tech? Does running `siac` output `Synced: No`?

A common cause of desychronization is lack of peers. Can you check that your peer list is "healthy" by running `siac gateway list`? It usually takes a few minutes to acquire 8 peers.

**Comment by HoteiLife** [comment]
Yes to both: Synced says No, and block height is lower than the current height reported on the explorer. The explorer reports 49711; my sia is at 49588 & hasn't changed from that number since last night.

The `gateway list` command does indeed say "No peers to show."

I have 3 other sia installations so I tried them all. 2 on other networks, I fired them up & they started syncing very quickly. Both are already showing `Synced: Yes`

And a 3rd on the same network. I tried it to make sure it wasn't some network issue. It also acquired peers very quickly (8 already) & started syncing. It's been down longer so it's still running but the block height is showing clear movement, incrementing about 1 per second.

The 4th machine is still at the same block height (49588) & still shows no peers.

**Comment by HoteiLife** [comment]
Tried some network activity from the problem machine to make sure it wasn't a connectivity problem. A ping out to the internet went through fine.

**Comment by HoteiLife** [comment]
Sorry, this was my fault. I was trying to set this machine up as a host & somehow my firewall lines for that were preventing communication. As soon as I cleared them it got hosts & started syncing. Seems to be moving fine now. I'm closing this issue.

**Comment by DavidVorick** [comment]
Perhaps we should have some warning if there are zero peers

**Comment by HoteiLife** [comment]
Might be useful. "Can't seem to connect to the Sia network, maybe check you're connectivity". Maybe somewhere to see reasons for connection attempt failures would also help. Nudge you in the right direction to finding the problem.
