### ISSUE TITLE
Automatic SafeFile recovery

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1140]
The `SafeFile` type first saves to `filename + "_temp"`, then atomically renames it, removing the suffix. The benefit of this is that if your file is corrupt or missing, you can load the `_temp` version instead. It may not be the most recent version, but at least it will work.

However, our persist code does not currently load the `_temp` backup if the normal load fails. In the past, we have instructed users to manually rename the `_temp` file and restart siad. Should the persist package do this automatically? If it does, perhaps it should return a special error value to signify that it loaded a backup. That way we can log the recovery.

**Comment by DavidVorick** [comment]
SafeFiles are not meant to be recovered, they are meant to guarantee that a partial-write does not cause corruption that destroys previously saved data.
