### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by ByronAP** [NebulousLabs/Sia#1153]
There seems to be a huge performance issue when loading. Balance remains at 0 for a very long time and transactions don't show. I have not dug into the issue but it seems that it is a address/transaction scanning issue as it seems the problem increases with more transactions and addresses.

**Comment by DavidVorick** [comment]
You have to unlock the wallet, currently unlocking the wallet takes in the ballpark of 10 minutes, longer on slow machines. There's a plan already in place to speed the wallet up. It's not going to be ready by June, but the wallet unlocking performance issues should be ready in July.
