### ISSUE TITLE
`siac host folder add` UX feedback

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1163]
- [ ] It's not clear how to specify the size of a folder using the `siac host folder add` command. Is the size specified in bytes, GB, or can you specify the units?
- [ ] The minimum storage requirement is displayed in bytes instead of the more readable GB.
- [ ] It's not clear whether 1KB = 1024B or 1000B, although it seems like it's the latter.
- [ ] `siac host folder add` doesn't complain when you add a folder with more storage than the drive has capacity.

**Comment by DavidVorick** [comment]
There's not an easy way to determine drive capacity, other than outright creating a file that has that size.

**Comment by surinder83singh** [comment]
just gives hint when size = 1, so file size is in bytes

> Could not add folder: minimum allowed size for a storage folder is 34359738368 bytes
