### ISSUE TITLE
`siac renter setallowance` UX feedback

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1191]
From the usage string `siac renter setallowance [amount] [period] [flags]` it isn't clear that the period should be in weeks. You need to do `siac renter setallowance --help` to find this out. Maybe `period` could be renamed to `weeks`? Perhaps this won't be an issue once autorenew is out.

**Comment by DavidVorick** [comment]
setallowance should now really be 'set settings'
