### ISSUE TITLE
Renter Renewing

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1194]
Currently renew is not fully enabled in the renter. This is because when the renter forms contracts, multiple calls to `setallowance` will result in multiple active file contracts. For renew to be successful, all active file contracts would need to be renewed, meaning that the number of open contracts that a renter has would continue to grow.

Renew must work in a way that after each cycle, there is only one file contract remaning with the host (until `setallowance` is called again, at which point multiple is okay until renewing again).

**Comment by lukechampine** [comment]
fixed in https://github.com/NebulousLabs/Sia/pull/1207
