### ISSUE TITLE
Suggested New Convention

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1206]
If you're going to be calling a `threaded` function in a module that's using a `ThreadGroup`, you need to call `tg.Add` before you spawn the goroutine, and then the `threaded` function needs to call `tg.Done` internally once it has closed.

This is necessary if we wish to fully enforce that all extra threads be terminated before `Stop()` returns.

**Comment by lukechampine** [comment]
What's the issue with calling `tg.Add` inside the function? Isn't that what exported functions do?

Another convention: `tg.Done` should always be called with `defer`.

**Comment by DavidVorick** [comment]
It interferes with the goal of having all goroutines shut down before the `Stop()` call returns. Exported functions do not spawn threads, they are called from an outside process. Exported functions are blocking, which means their closing responsibility falls on whoever is doing the calling, not on the object being closed.

**Comment by lukechampine** [comment]
I don't see why it would interfere, so long as `Add` is the first call made by the function. Worst case: you call `Stop` before the threaded function is spawned, `Stop` returns, then the threaded function calls `Add`, sees the error, and returns a millisecond later. All else being equal, I would prefer to pair the `Add` and `Done` together; seems less bug-prone.

One advantage of your style did occur to me though: long-running functions can take advantage of `Add` errors to return early, e.g.:
```go
func (m *module) foo() {
    for {
        // do work
        // ...
        err := m.threads.Add()
        if err != nil {
            return
        }
        go m.threadedWorker()
    }
}
```
This would not be possible if the `Add` were inside the function.

**Comment by VoidingWarranties** [comment]
Long running functions should have the `StopChan` for exiting early, no need to use `Add` for that.

**Comment by DavidVorick** [comment]
It depends on how pedantic you want to be about closing goroutines before `Stop()` returns. As it stands we have edge cases where `Stop()` will return while there are still spawned goroutines alive, even if they will be exiting soon.

**Comment by lukechampine** [comment]
Can we confirm that we're talking about the same thing here, i.e. sub-millisecond delay? That is:
```go
go threadedFoo()  // the time between here...

func (m *module) threadedFoo() {
    err := m.threads.Add()
    if err != nil {
        return    // ...and here?
    }
    defer m.threads.Done()
    // ...
}
```

I think both approaches have merit, because they both do "pairing" to some degree. This way pairs `Add` and `Done`, while David's way pairs `Add` and `go`. It's hard to say for sure that one is more error-prone than the other. In both cases, avoiding error relies on adherence to convention.

**Comment by VoidingWarranties** [comment]
@DavidVorick what is the edge case? I don't see how `Stop` can return while there are still spawned goroutines alive, assuming we hold to the convention of `defer m.threads.Done()`

**Comment by DavidVorick** [comment]
`threadedFoo` and the call to it are already paired because you need to call `threaded` in a goroutine.

Having a short delay where goroutines are still open after calling `Close` is not a big deal, but screwing up a call to `Add` or `Done` is a big deal.

**Comment by lukechampine** [comment]
It's inconsistent if we sometimes call `Add` outside the goroutine, and sometimes inside it. If we mix-and-match, there's a potential for calling `Add` twice (outside and inside the function), which would lead to deadlock.
Seems like what we really want is something like:
```go
func (tg *ThreadGroup) Go(fn func()) error {
    if tg.Add(); err != nil {
        return err
    }
    go func() {
        fn()
        tg.Done()
    }()
    return nil
}
```
```go
func (m *module) Foo() {
    m.tg.Go(func() { m.threadedFoo(bar) })
}
```
Then we don't need to worry about `Add` or `Done`; in most cases, they are handled automatically. Unfortunately this hurts syntax since in most cases you'll need a function literal. But it might be worth it.

**Comment by DavidVorick** [comment]
Definitely worth thinking about some more. A function literal is not so bad.

**Comment by DavidVorick** [comment]
going to close this for now, we can come back to the programming architecture in a few weeks
