### ISSUE TITLE
Create a 'consts.go' file in the gateway

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1208]
consts.go would house all of the constants in the gateway, partially to clean up the files but more importantly to make it so that all of the constants are in one place, which makes life easier when reviewing them and reconsidering their values.

**Comment by VoidingWarranties** [comment]
I can see the advantage of having all the exported consts in a single file, but most of the gateway's consts are unexported and only used once or twice within the file they are declared. Separating their declaration from where they're used doesn't seem advantageous to me. The exported consts are grouped together in godoc too.

Is this common practice in other go projects? I couldn't find any instance in the standard library except for the crypto sub packages which have large byte arrays in `const.go`.

**Comment by DavidVorick** [comment]
I don't think other projects mess with their consts as much as we mess with ours. It's less about putting the consts next to where they are used and more about clumping them together so you can get a better overall picture of what's happening at 10,000 feet.

I feel like usually you want to write the code so that it's more or less agnostic to the actual value of the constant, which means you don't need to see the constant while coding, only while you're trying to adjust the overall behavior of the program.

**Comment by DavidVorick** [comment]
off the shortlist, though I really would like to see the constants in more easily accessible places.
