### ISSUE TITLE
Close host tester in tests

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1209]
By implementing the `Close` method on the `hostTester` type. `consensusSetTester.Close` is an existing example.

**Comment by mnsl** [comment]
`transactionPoolTester` needs a Close method too.  

Why does `consensusSetTester` only call `Close` on the gateway and consensus set?  Do the miner and transaction pool close automatically?  And there is no `Close` method at all for the wallet -- should there be?
