### ISSUE TITLE
Use a lockfile to ensure safe read/writes to the Sia directory

### ISSUE THREAD

**Issue by johnathanhowell** [NebulousLabs/Sia#1225]
Related issue: https://github.com/NebulousLabs/Sia-UI/issues/243

In my current understanding, it is possible for multiple instances of Siad to work from the same data directory, which can cause data loss.  I propose that we implement a `lockfile` for the data directory to ensure that only one instance of `siad` can work off a given data directory.

**Comment by lukechampine** [comment]
worth noting: bolt uses a lock file to protect its database, so if you try to run two `siad`s pointing at the same db, one will fail.

**Comment by DavidVorick** [comment]
considering this one 'good enough' for the time being.
