### ISSUE TITLE
Block gateway connection attempts / requests from exiting until the peer has confirmed the connection

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1229]
This caused issue #1099 and I suspect could be the cause of other non-deterministic test failures.

Here's an example which would be fixed by this issue.

``` go
g1 := gateway.New(...)
g2 := gateway.New(...)

g1.Connect(g2.Address())

g1.RPC(g2.Address(), ...) // This may fail if `g2.threadedListenPeer` hasn't spawned yet.
g2.RPC(g1.Address(), ...) // This may fail if `g1.threadedListenPeer` hasn't spawned yet.
```

**Comment by VoidingWarranties** [comment]
Remove [this block of code](https://github.com/NebulousLabs/Sia/blob/07076189287665d9332de562d88f1cf31ad74f1b/modules/gateway/rpc_test.go#L510-L516) in the PR that closes this issue.

**Comment by DavidVorick** [comment]
what is the status on this?
