### ISSUE TITLE
Upgrade muxado to muxado v2, Yamux, or SPDY

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1231]
And consider using [Protocol Lab's go-stream-muxer](https://github.com/jbenet/go-stream-muxer/)

**Comment by lukechampine** [comment]
`go-stream-muxer` doesn't seem to provide much benefit to us, and it adds a dependency. We don't need interop with multiple stream protocols.

**Comment by VoidingWarranties** [comment]
I don't think `go-stream-muxer` provides interop between protocols. I think it simply provides a common go-interface that conforms to https://github.com/diasdavid/interface-stream-muxer

We will either have to write a similar wrapper ourselves, or write more version branching to deal with backwards compatibility.

**Comment by lukechampine** [comment]
`go-stream-muxer` doesn't appear to be go-gettable, which makes it even more of a hassle to use. We'd need to install their `gx` dependency management tool.

Wrappers are easy to write, and we would need to perform version branching anyway.

**Comment by VoidingWarranties** [comment]
Ah, I forgot they used `gx`. Wrappers are easy to write, I just didn't want to write them myself :P

**Comment by GlenDC** [comment]
This issue is now a bit deprecated now, as we're now going for smux, or has that already changed?

**Comment by lukechampine** [comment]
indeed. I'll close this once we merge the smux PR (I'm currently putting it together mostly using your code, should be ready soon).
