### ISSUE TITLE
OSX 10.11.4 Crash

### ISSUE THREAD

**Issue by chanc3r** [NebulousLabs/Sia#1237]
siad repeatedly crashes while 'syncing', tried deleting and reinstalling it still seems to happen.
attached said crash dump, if you want any more detail you can find me on siatalk slack with same username.
[sia-crash-log.txt](https://github.com/NebulousLabs/Sia/files/310911/sia-crash-log.txt)

**Comment by lukechampine** [comment]
can you run the [bolt](https://github.com/NebulousLabs/bolt) test suite and see if it fails?

**Comment by chanc3r** [comment]
Travelling at the moment but I will try to do it in the next day or so
Ian


Sent from my iPhone

On 13 Jun 2016, at 02:49, Luke Champine <notifications@github.com<mailto:notifications@github.com>> wrote:


can you run the bolt<https://github.com/NebulousLabs/bolt> test suite and see if it fails?

-

**Comment by chanc3r** [comment]
this is the bolt-test log
[bolt-test.txt](https://github.com/NebulousLabs/Sia/files/315694/bolt-test.txt)

**Comment by DavidVorick** [comment]
From the forum:

```


I am getting the following error when starting the siad daemon (v0.6.0) on Debian.
From what I can tell it cannot fully load the blockchain, therefore I cannot use the wallet, host etc.

Below are the first messages I get when executing ./siad -M gc

Loading...
(1/2) Loading gateway...
(2/2) Loading consensus...
Finished loading in 0.442046251 seconds
unexpected fault address 0x77697040
fatal error: fault
[signal 0xb code=0x1 addr=0x77697040 pc=0x82f8bf6]

After that, I get a lot of goroutine messages until it exits the program.



Here are the first four goroutines:

goroutine 26 [running]:
runtime.throw(0x860c088, 0x5)
/usr/local/go/src/runtime/panic.go:530 +0x7f fp=0x18da916c sp=0x18da9160
runtime.sigpanic()
/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x27c fp=0x18da9198 sp=0x18da916c
github.com/NebulousLabs/bolt.(*Tx).rollback(0x19006a80)
/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:245 +0x66 fp=0x18da91b8 sp=0x18da9198
github.com/NebulousLabs/bolt.(*Tx).Commit(0x19006a80, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x1f2 fp=0x18da9274 sp=0x18da91b8
github.com/NebulousLabs/bolt.(*DB).Update(0x18c7d8c0, 0x18da92cc, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:580 +0xf4 fp=0x18da92a0 sp=0x18da9274
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0x18c6f080, 0x0, 0xe80e0000, 0x177d340d, 0xcbb749aa, 0x475fa958, 0xe93e48cf, 0x57d54dac, 0xd5733133, 0x3d0a09c8, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:183 +0xde fp=0x18da9328 sp=0x18da92a0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock(0x18c6f080, 0x0, 0xe80e0000, 0x177d340d, 0xcbb749aa, 0x475fa958, 0xe93e48cf, 0x57d54dac, 0xd5733133, 0x3d0a09c8, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:259 +0x108 fp=0x18da9408 sp=0x18da9328
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedReceiveBlocks(0x18c6f080, 0xb769d2a8, 0x18c53508, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:215 +0x72e fp=0x18da9d98 sp=0x18da9408
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.threadedReceiveBlocks)-fm(0xb769d2a8, 0x18c53508, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:146 +0x3c fp=0x18da9db0 sp=0x18da9d98
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0x18d22600, 0x865d8f0, 0x11, 0x863ba70, 0xa, 0x18c534f8, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:53 +0x3d5 fp=0x18da9e58 sp=0x18da9db0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0x18c6f080)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:479 +0x580 fp=0x18da9fa0 sp=0x18da9e58
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x18c6f080, 0xb7665970, 0x18d22600)
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:138 +0x25 fp=0x18da9fb8 sp=0x18da9fa0
runtime.goexit()
/usr/local/go/src/runtime/asm_386.s:1585 +0x1 fp=0x18da9fbc sp=0x18da9fb8
created by github.com/NebulousLabs/Sia/modules/consensus.New
/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:152 +0x617

goroutine 1 [IO wait]:
net.runtime_pollWait(0xb7666898, 0x72, 0x0)
/usr/local/go/src/runtime/netpoll.go:160 +0x55
net.(*pollDesc).Wait(0x18ec8db8, 0x72, 0x0, 0x0)
/usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x18ec8db8, 0x0, 0x0)
/usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x18ec8d80, 0x0, 0xb7666bd0, 0x18c10280)
/usr/local/go/src/net/fd_unix.go:426 +0x20b
net.(*TCPListener).AcceptTCP(0x18c53348, 0x1, 0x0, 0x0)
/usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net.(*TCPListener).Accept(0x18c53348, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/net/tcpsock_posix.go:264 +0x39
net/http.(*Server).Serve(0x18d2ef00, 0xb7665ab8, 0x18c53348, 0x0, 0x0)
/usr/local/go/src/net/http/server.go:2117 +0x100
github.com/NebulousLabs/Sia/api.(*Server).Serve(0x18d2c850, 0x0, 0x0)
/home/luke/go/src/github.com/NebulousLabs/Sia/api/server.go:91 +0x1ed
main.startDaemon(0x8652f00, 0xe, 0x86057a0, 0x5, 0x86057a8, 0x5, 0xbfeec9f6, 0x2, 0x0, 0x863bd40, ...)
/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:181 +0x1e59
main.startDaemonCmd(0x18c98300, 0x18ca3500, 0x0, 0x2)
/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:204 +0x1bd
github.com/spf13/cobra.(*Command).execute(0x18c98300, 0x18c58088, 0x2, 0x3, 0x0, 0x0)
/home/luke/go/src/github.com/spf13/cobra/command.go:565 +0x678
github.com/spf13/cobra.(*Command).ExecuteC(0x18c98300, 0x18c98300, 0x0, 0x0)
/home/luke/go/src/github.com/spf13/cobra/command.go:651 +0x43b
github.com/spf13/cobra.(*Command).Execute(0x18c98300, 0x0, 0x0)
/home/luke/go/src/github.com/spf13/cobra/command.go:610 +0x2b
main.main()
/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:172 +0x762

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
/usr/local/go/src/runtime/sigqueue.go:116 +0x11e
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
/usr/local/go/src/os/signal/signal_unix.go:28 +0x36

goroutine 19 [sleep]:
time.Sleep(0xf8475800, 0xd)
/usr/local/go/src/runtime/time.go:59 +0xe6
github.com/NebulousLabs/Sia/sync.(*RWMutex).threadedDeadlockFinder(0x18d225c0)
/home/luke/go/src/github.com/NebulousLabs/Sia/sync/lock.go:78 +0x468
created by github.com/NebulousLabs/Sia/sync.New
/home/luke/go/src/github.com/NebulousLabs/Sia/sync/lock.go:47 +0xb0

```

**Comment by tophensen** [comment]
I am getting similar errors, siad is therefore stuck at block 41674 and cannot sync any further. I attached the console output below. Just to add a few more data points: 
- I am using an i686 Debian 8.5 (3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) i686 GNU/Linux) 
- The Sia release is 1.0, but I received a similar error (at I think the same block) with v0.6

> ./siad 
Loading...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.403029279 seconds
unexpected fault address 0x75a00040
fatal error: fault
[signal 0xb code=0x1 addr=0x75a00040 pc=0x831129e]

goroutine 13 [running]:
runtime.throw(0x8636410, 0x5)
	/home/sia/install/go/src/runtime/panic.go:547 +0x7f fp=0x18e8d120 sp=0x18e8d114
runtime.sigpanic()
	/home/sia/install/go/src/runtime/sigpanic_unix.go:27 +0x27c fp=0x18e8d14c sp=0x18e8d120
github.com/NebulousLabs/bolt.(*DB).meta(0x18c69c20, 0xa2d8)
	/home/sia/install/src/github.com/NebulousLabs/bolt/db.go:808 +0x2e fp=0x18e8d18c sp=0x18e8d14c
github.com/NebulousLabs/bolt.(*Tx).rollback(0x1928ad00)
	/home/sia/install/src/github.com/NebulousLabs/bolt/tx.go:255 +0x6b fp=0x18e8d1a0 sp=0x18e8d18c
github.com/NebulousLabs/bolt.(*Tx).Commit(0x1928ad00, 0x0, 0x0)
	/home/sia/install/src/github.com/NebulousLabs/bolt/tx.go:164 +0x1f2 fp=0x18e8d270 sp=0x18e8d1a0
github.com/NebulousLabs/bolt.(*DB).Update(0x18c69c20, 0x18e8d2c8, 0x0, 0x0)
	/home/sia/install/src/github.com/NebulousLabs/bolt/db.go:602 +0xf4 fp=0x18e8d29c sp=0x18e8d270
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0x18c5f1e0, 0x0, 0x973c0000, 0x1fe9ee9c, 0x247b032f, 0xddf1f464, 0xefdfcc6a, 0x244c3aef, 0x5c415e3f, 0x356ab31f, ...)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:183 +0xeb fp=0x18e8d324 sp=0x18e8d29c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock(0x18c5f1e0, 0x0, 0x973c0000, 0x1fe9ee9c, 0x247b032f, 0xddf1f464, 0xefdfcc6a, 0x244c3aef, 0x5c415e3f, 0x356ab31f, ...)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:259 +0x116 fp=0x18e8d404 sp=0x18e8d324
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedReceiveBlocks(0x18c5f1e0, 0xb6bac8e8, 0x19034250, 0x0, 0x0)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:215 +0x73c fp=0x18e8dd94 sp=0x18e8d404
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.threadedReceiveBlocks)-fm(0xb6bac8e8, 0x19034250, 0x0, 0x0)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:146 +0x3c fp=0x18e8ddac sp=0x18e8dd94
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0x18c86400, 0x18d26ec0, 0x14, 0x8666e00, 0xa, 0x18c0a5d0, 0x0, 0x0)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:58 +0x467 fp=0x18e8de58 sp=0x18e8ddac
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0x18c5f1e0)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:479 +0x580 fp=0x18e8dfa0 sp=0x18e8de58
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x18c5f1e0, 0xb6ba28f0, 0x18c86400)
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:138 +0x25 fp=0x18e8dfb8 sp=0x18e8dfa0
runtime.goexit()
	/home/sia/install/go/src/runtime/asm_386.s:1585 +0x1 fp=0x18e8dfbc sp=0x18e8dfb8
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/sia/install/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:152 +0x617

...
>

**Comment by lukechampine** [comment]
We no longer support 386 platforms. Our blockchain database is mmap'd, which seems to be a problem on 32-bit systems when the database grows larger than the 32-bit address space.

**Comment by chanc3r** [comment]
But OSX is 64bit - has been longer than windows?
Mac’s are intel core i7 64bit
So where is the 32bit?
Also Go is supposed to be platform independent
Are you saying that Sia no longer runs on OSX?

On 1 Jul 2016, at 13:24, Luke Champine <notifications@github.com<mailto:notifications@github.com>> wrote:


We no longer support 386 platforms. Our blockchain database is mmap'd, which seems to be a problem on 32-bit systems when the database grows larger than the 32-bit address space.

**Comment by lukechampine** [comment]
sorry, I was only looking at @tophensen's comment.
Go is indeed platform independent, but not all libraries are platform independent.

Can you confirm that you are still having issues syncing with the latest 1.0 darwin release? I noticed the occurrence of `/usr/local/go/src/runtime/asm_386.s`, which points to a 32-bit binary.

**Comment by chanc3r** [comment]
Only got a chance to start 1.0 today.
I’ve suspend/resumed the mac while its syncing and its synced with no issues so far :))
So it looks like this build it working well.


On 1 Jul 2016, at 13:51, Luke Champine <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry, I was only looking at @tophensen<https://github.com/tophensen>'s comment.
Go is indeed platform independent, but not all libraries are platform independent.

Can you confirm that you are still having issues syncing with the latest 1.0 darwin release? I noticed the occurrence of /usr/local/go/src/runtime/asm_386.s, which points to a 32-bit binary.
