### ISSUE TITLE
API examples

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1242]
It would be nice for new developers to have a short list of examples for common API endpoints, like changing the host's price. I imagine we would include examples in the `doc/api/*.md` files and structure them similarly to godoc (Overview, Index of routes, Examples). Linking to the examples from the main `API.md` doc would be good too.

**Comment by VoidingWarranties** [comment]
#1223 added examples for the gateway and is a good template for writing examples for other modules.

**Comment by DavidVorick** [comment]
To me this feel like it just belongs as a part of the general 'api finalization' issue.

**Comment by DavidVorick** [comment]
Though, perhaps documentation and code could be considered two separate things. I guess it just depends on how much you want to break it down.
