### ISSUE TITLE
`siac renter list` shows files as done uploading before they reach 100%

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1244]
`siac` only shows the upload progress in the `(uploading, x%)` when `available` is false. This is potentially problematic as a user might expect to be able to delete their local copy of the file as soon as uploading completes. If the user deletes their local copy as soon as it is "available", but not 100% uploaded, the file will fail to upload to other hosts and the redundancy will be forever stuck below full redundancy. The change is to branch based off of `file.UploadProgress < 100` instead of `!file.Available`.

Thanks @johnathanhowell for finding this.

**Comment by lukechampine** [comment]
>If the user deletes their local copy as soon as it is "available", but not 100% uploaded, the file will fail to upload to other hosts

This is no longer the case, now that repairing is implemented. However, it would still be bad if users deleted the file on disk as soon as the `(uploading)` disappeared. Not sure what the best UX for this is.

**Comment by eddiewang** [comment]
On `siac renter list -v` this is not an issue. What if we flipped from `(uploading)` to `(boost redundancy)` while the redundancy is under 3x?

**Comment by tbenz9** [comment]
If I understand it right with repairing implemented and "boosting redundancy" language in place I think this can be closed.
