### ISSUE TITLE
Non-deterministic test failure in TestStorageProofBoundaries

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1258]
```
--- FAIL: TestStorageProofBoundaries (11.51s)
	validtransaction_test.go:186: bad storage proof got accepted into the transaction pool
```

**Comment by DavidVorick** [comment]
Was this reported by Travis?

**Comment by DavidVorick** [comment]
This is a pretty significant error, as it relates to the recent hardfork code.

**Comment by DavidVorick** [comment]
I've been trying to reproduce this, without success.

**Comment by lukechampine** [comment]
yes, I've only seen it once, on a Travis OS X build.

**Comment by DavidVorick** [comment]
Just managed to reproduce it on my local machine.

Darn. I am investigating further.
