### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by roymj88** [NebulousLabs/Sia#1260]
Hi,

Tried installing using the steps given:

```
git clone https://github.com/NebulousLabs/Sia-UI.git
npm install
npm start
```

But it shows the following error:

```
Uncaught Exception:
TypeError: protocol.interceptBufferProtocol is not a function
    at initializeProtocolHook (/home/roy/projects/Sia-UI/node_modules/electron-compile/lib/protocol-hook.js:115:12)
    at EventEmitter.protoify (/home/roy/projects/Sia-UI/node_modules/electron-compile/lib/config-parser.js:317:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

Note: I am on ubuntu with node version `v6.2.2` and npm version`3.9.5`

Kindly advice as to what should be done.

![sc](https://cloud.githubusercontent.com/assets/2633799/16172663/6dc590d8-35aa-11e6-8139-3e5d15d519bf.png)

**Comment by DavidVorick** [comment]
This issue belongs in this repo: https://github.com/NebulousLabs/Sia-UI/issues

The UI dev will probably see the issue regardless, we check all the repos.

**Comment by roymj88** [comment]
Okay posted it there: https://github.com/NebulousLabs/Sia-UI/issues/248
