### ISSUE TITLE
siac host config doesn't check types, and is unable to read the values

### ISSUE THREAD

**Issue by Krakonos** [NebulousLabs/Sia#1269]
Based on the help line:

```
  siac host config [setting] [value] [flags]
```

I'd expect this to error out, as blah is not really a bool:

```
sia@shade ~ $ siac host config acceptingcontracts blah
Host settings updated.
```

Moreover, this should probably show the current set value

```
sia@shade ~ $ siac host config acceptingcontracts
Usage:
[...]
```

Also, the following should probably list all the current config values...

```
sia@shade ~ $ siac host config
Usage:
[...]
```

**Comment by lukechampine** [comment]
I like your suggestions. Good catch with `acceptingcontracts blah` -- it's probably only checking for `!= "false"`. The config values can be viewed with `siac host`, but it wouldn't hurt to display them in `siac host config` as well.

**Comment by DavidVorick** [comment]
Looks like a lot of the parsing is incomplete with the errors. For example `siac host config maxduration 15weeks` seems to set the configuration to 15 blocks instead of returning an error.

**Comment by lukechampine** [comment]
I believe that is a failing of `fmt.Sscanf`: it will stop scanning as soon as it consumes a value. Not sure what the best approach is for handling that. There's `strconv.Atoi`, but that only works for `int`.

**Comment by Krakonos** [comment]
@lukechampine Not everything is displayed in ```siac host```, for example the bandwidth parameters (I'm not even sure what they are and what should be the values)

**Comment by DavidVorick** [comment]
@Krakonos everything is displayed as of the master branch. The bandwidth parameters got removed altogether because there's actually no support for them on the backend, they were misleading because they did not actually do anything.

We'll add the bandwidth parameters back once the backend can actually respect the settings.

**Comment by Krakonos** [comment]
@DavidVorick Thanks, I'm running 6f72438, updated few moments ago, with the competitive price calculation (great!), but additional parameters are still in the help. I'm looking forward to the bandwidth prices, as I'd utilize it in the future, as my bandwidth is a bit limited, but still stuitable for log term backups (which would hopefully never accessed for example..).

**Comment by DavidVorick** [comment]
oh, good to know. I will make a PR to update the help string right now.

**Comment by lukechampine** [comment]
I don't think this is the current behavior. Please reopen if it can be reproduced.
