### ISSUE TITLE
renewal sequence

### ISSUE THREAD

**Issue by david60** [NebulousLabs/Sia#1286]
Hi,

I've seen some problems when renters have tried to renew contracts on my host (running a recent master build): I wanted to explain it here in the hope it helps. (I don't rule out there's something wrong on my host, or this particular renter was suffering a problem, apologies in advance in that case).

A renter renewed a contract on my host. The original contract's storageobligation had 4 SectorRoots and filesize 16777216 (total revisions 5). The renewal created a new contract, with the same filesize and filemerkleroot, as recorded in both the initial transaction set and no-op revision - expected behavior I think. But my host had entered nil SectorRoots for the storageobligation. The  renter then tried to revise the new contract with ActionInsert with SectorIndex 0; then 4MB of data and a revised contract number 2 with newfilesize 20971520. My host gave them them the error "propsed file contract revision has a bad filesize".

I'm not sure but my guess is that both the host and the renter may be doing something unintended: I believe my host should keep the sectorroots of the previous contract in the renewed contract storageobligation, and probably the renter should have kept the MerkleRoots when it replaces its RenterContract, i.e. so that its SectorIndex in the Insert would have been 4 in this case.

David

**Comment by lukechampine** [comment]
Thanks for these bug reports David. Not many people have been willing to dive into the Sia codebase yet, so we appreciate you taking the extra effort.
We will investigate this right away. Any bugs with the renewal process are pretty serious, because they can cause data loss. We have renewal integration tests that seem to be working fine, so I'm hoping this is just an edge case.

**Comment by david60** [comment]
Thanks Luke.

**Comment by lukechampine** [comment]
This has been partially addressed in https://github.com/NebulousLabs/Sia/pull/1314. We're looking into the host side now.

**Comment by lukechampine** [comment]
Fully fixed as of #1318
