### ISSUE TITLE
blockHeight comparison for file contract revision submission

### ISSUE THREAD

**Issue by david60** [NebulousLabs/Sia#1289]
Hi,

I noticed the action item for file contact revision is placed at so.expiration()-revisionSubmissionBuffer. The check in handleActionItem() is

```go
        // Check if the file contract revision is ready for submission. Check for death.
        if !so.RevisionConfirmed && len(so.RevisionTransactionSet) > 0 && h.blockHeight > so.expiration()-revisionSubmissionBuffer {
```

should it be greater or equal to that height? Or quite possibly I've missed something. :)

David

**Comment by DavidVorick** [comment]
The codepath inside the `if` statement is supposed to be triggered if there's a file contract revision, the revision hasn't been confirmed on the blockchain, and the time has come to submit the revision.

To save on transaction fees and help with scalability, the host does not submit the file contract revision until the end of the contract. `revisionSubmissionBuffer` is a constant that the host uses to make sure the revision has time to get into the blockchain in the event of full blocks or other network congestion. In production, it's currently 288 blocks, or 2 days.

Also worth pointing out that the host will stop accepting revisions to that contract 288 blocks ahead of time.

```go
	// Check that the time to finalize and submit the file contract revision
	// has not already passed.
	if so.expiration()-revisionSubmissionBuffer <= blockHeight {
		return errLateRevision
	}
```

I believe the code is correct here.

**Comment by david60** [comment]
Hi,

I'm still not sure; there's an action item set at height so.expiration()-revisionSubmissionBuffer. e.g. after a storageobligation is added:

storageobligations.go:

```go
        // Queue an action item to submit the file contract revision - if there is
        // never a file contract revision, the handling of this action item will be
        // a no-op.
        err2 := h.queueActionItem(so.expiration()-revisionSubmissionBuffer, soid)
```

And I believe that means handleActionItem() will be called for this storageobligation when h.blockHeight is exactly equal to so.expiration()-revisionSubmissionBuffer. But my reading is that handleActionItem() won't consider submitting the revision at that height, but only 1 block later, whereas it should submit it. Otherwise it appears the action item won't have an effect. (Other than to check the origin transaction was confirmed, which should have been long since been done).

**Comment by DavidVorick** [comment]
You may be correct, but I believe that we have tests in place which would fail if revisions weren't being submitted properly to the blockchain. I will double check.

**Comment by david60** [comment]
OK. And of course, close the ticket whenever you like, once you've decided if anything does need changing or not.
Thanks for following up my tickets, and checking.

**Comment by DavidVorick** [comment]
#1300 has some additional test structures that verify the storage proofs are making it onto the blockchain.

The code here is not super clean, but I'm pretty sure that the action items are set out correctly, there's a decent amount of testing which should be complaining if the action items are not being triggered at the right time.
