### ISSUE TITLE
Revisit alternative API authentication methods

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1307]
A few are mentioned in #1065

**Comment by droghio** [comment]
In the short term I wonder what we are gaining by allowing binding to a non-localhost port? It forces us to implement some form of API security to prevent attacks on mis-configured users, and I see this as one massive rabbit hole filled with tls woes and the like.

What are the expected use cases for enabling api auth + non-localhost binding? From what I can tell right now it is mostly used by miners to mine across multiple rigs or monitor their systems. If that is true then it might make more sense to lock down api access to local ports and write a short guide for users on how to use better suited technologies, like ssh or a VPN setup like hamachi.

I am concerned that if we continue to allow the api to be exposed and we will then then either spend a large portion of time locking it down properly or implement a partial, vulnerable, solution.

I am not sure if there is a long-term feature that may benefit from an external facing api, but for now I see it as a security risk that we gain little from (but I can be missing something of course).

**Comment by lukechampine** [comment]
Bitcoin provides these flags:
```
-rpcbind=<addr> 	Bind to given address to listen for JSON-RPC connections. Use [host]:port notation for IPv6. This option can be specified multiple times (default: bind to all interfaces)
-rpcuser=<user> 	Username for JSON-RPC connections
-rpcpassword=<pw> 	Password for JSON-RPC connections
-rpcauth=<userpw> 	Username and hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is included in share/rpcuser. This option can be specified multiple times
-rpcport=<port> 	Listen for JSON-RPC connections on <port> (default: 8332 or testnet: 18332)
-rpcallowip=<ip> 	Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24). This option can be specified multiple times 
```
By default, they bind to all interfaces using the specified port number, but only allow connections from localhost. On top of that, they use basic auth. I like this approach because most users should only care about `-rpcport`, and external IPs are whitelisted rather than being completely open.

**Comment by DavidVorick** [comment]
*spoofable

**Comment by lukechampine** [comment]
good point. If you spoof your IP, you won't be able to inspect the response, but for some actions (e.g. "send X coins to this address") you don't need to see the response; you only care about the side-effect.
I'm guessing the password is used to mitigate such attacks. Bitcoin (I believe) requires a password for all RPC actions, unlike us. So our strategy would need to be a little different.
