### ISSUE TITLE
critical error: negative currency not allowed

### ISSUE THREAD

**Issue by Chehands** [NebulousLabs/Sia#1321]
I've been getting this error a fair number of times in the siad window.

**Comment by lukechampine** [comment]
Are you running a release binary? That error should have been fixed in https://github.com/NebulousLabs/Sia/pull/1317. There could be another cause, though.

**Comment by mnsl** [comment]
I think funny things happen if you've installed v1.0.0 but haven't deleted the v0.6.0 executables. The `siac version` command returns `Sia Client v1.0.0`, but `siac consensus` gives v0.6.0-style output and `siad` produces the `negative currency not allowed error` when you try to unlock and lock the wallet.  I suspect v0.6.0 `siad` is trying to talk to v1.0.0 `siac`.

This is what I managed to produce:
```
$ siad
Loading...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.165631625 seconds
negative currency not allowed
negative currency not allowed
negative currency not allowed
negative currency not allowed
Rescanning consensus set...
Scanned to height 57765...
Done!
```

```
$ siac
Synced: No
Height: 57756
Progress (estimated): 99%
$ siac consensus
Synced: No
Height: 57756
Progress (estimated): 99%
$ siac version
Sia Client v1.0.0
$ siac wallet unlock
Wallet password: 
Unlocking the wallet. This may take several minutes...
Could not unlock wallet: 
$ siac wallet unlock
Wallet password: 
Unlocking the wallet. This may take several minutes...
Could not unlock wallet: {"message":"error when calling /wallet/unlock: wallet has already been unlocked"}
$ siac wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   [omitted; correct value]
Unconfirmed Delta:  +0 H
Exact:               [omitted; correct value]
Siafunds:            [omitted; correct value]
Siafund Claims:      [omitted; correct value]
$ siac wallet lock
Could not lock wallet: 
$ siac wallet
Wallet status:
Encrypted, Locked
Unlock the wallet to view balance
$ siac wallet unlock
Wallet password: $ siac wallet unlock
Wallet password: 
Unlocking the wallet. This may take several minutes...
Could not unlock wallet: 
$ siac wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   [omitted; correct value]
Unconfirmed Delta:  +0 H
Exact:               [omitted; correct value]
Siafunds:            [omitted; correct value]
Siafund Claims:      [omitted; correct value]
$ siac wallet lock
Could not lock wallet: 
$ siac wallet
Wallet status:
Encrypted, Locked
Unlock the wallet to view balance
$ siac stop
Could not stop daemon: 
$ siac
Could not get current consensus state: no response from daemon
$
```

**Comment by betaboot** [comment]
I get the same message now: Critical error: negative currency not allowed

What i can see is that i get that message each time i 'lose' a contract. So the Contract Count goes down by one and there is such an error message.
I'm using v.1.0.0. Not sure why my number of contracts goes down but in the beginning i set maxduration to different (small) values. Could be that some contracts were formed with a short contract time. Now it's set to 13 weeks.

I got the error message 3 times and in host log i have the following entry also 3 times:
storageobligations.go:556: Succesfully submitted a storage proof. Revenue is 421941285061211113694167040.

**Comment by DavidVorick** [comment]
`siac version` displays the `siac` version, not the `siad` version. The logic could probably be more complex to report compatibility issues between `siac` and `siac` - if `siac` has a higher version you can assume that there will be weird output and an error should be reported.

**Comment by lukechampine** [comment]
>i get that message each time i 'lose' a contract

Thanks, this is helpful. It points a bug in the host, perhaps when submitting storage proofs.

**Comment by DavidVorick** [comment]
The host does a lot of subtraction when an obligation is removed/rejected/finalized. It's possible that one of those subtractions is unwittingly unsafe.

`build.Critical` should start displaying the line that produced the error.

**Comment by lukechampine** [comment]
we can copy code from my [caller](https://github.com/lukechampine/caller) package to accomplish this.

**Comment by betaboot** [comment]
oh oh, my Contract Count has been going down slowly in the past hours. In the end there was only one contract left. Then i got another of those error messages and i thought that Contract Count would now be Zero but actually it is showing 18446744073709551615 :-D


D:\Sia-v1.0.0>siac host -v
General Info:
        Estimated Competitive Price: 740.2 SC

Host Internal Settings:
        acceptingcontracts:   Yes
        maxduration:          13 Weeks
        maxdownloadbatchsize: 17.83 MB
        maxrevisebatchsize:   17.83 MB
        netaddress:           xxx (automatically determined)
        windowsize:           0 Weeks

        collateral:       250 SC / TB / Month
        collateralbudget: 2 MS
        maxcollateral:    100 KS Per Contract

        mincontractprice:         30 SC
        mindownloadbandwithprice: 250 SC / TB
        minstorageprice:          1.999 KS / TB / Month
        minuploadbandwidthprice:  100 SC / TB

Host Financials:
        Contract Count:               18446744073709551615
        Transaction Fee Compensation: 720 SC
        Transaction Fee Expenses:     0 H

        Storage Revenue:           29.23 SC
        Potential Storage Revenue: 560.4 mS

        Locked Collateral: 154 SC
        Risked Collateral: 70.18 mS
        Lost Collateral:   0 H

        Download Revenue:           0 H
        Potential Download Revenue: 6.291 mS
        Upload Revenue :            8.023 SC
        Potential Upload Revenue:   155.2 mS

RPC Stats:
        Error Calls:        2876
        Unrecognized Calls: 8
        Download Calls:     25
        Renew Calls:        27
        Revise Calls:       2457
        Settings Calls:     17589
        FormContract Calls: 714

Storage Folders:
    Used        Capacity     % Used    Path
    1.514 GB    50.000 GB    3.03      D:\SiaHostFolder1

**Comment by DavidVorick** [comment]
714 form contract calls, 1.514 GB, -1 file contracts?

hmm. 

Can you post your host.log?

**Comment by betaboot** [comment]
[host.txt](https://github.com/NebulousLabs/Sia/files/344418/host.txt)

It looks like the Contract Count goes down each time i submit a storage proof. Eventually, Contract count is 1 and then -1, -2, and so on.
If i restart the client i see the correct number again but as soon as i submit a storage proof again it goes down.
That's how i see it, not sure if that's correct. So i don't think that contracts are terminated, because the hosted files are still there, could be just a displaying error. And of course each time that happens there is a message 'negative currency not allowed' as posted in the beginning.

Another thing i wanted to mention: I see that i already have a lot of addresses in my wallet. I started a fresh wallet with v1.0.0_RC2 and only uploaded 10 small files.
Yesterday, before going to bed i had around 8'000 addresses, this morning already 11'000. Without doing anything...

**Comment by betaboot** [comment]
I looked at the number of addresses now. It seems that new addresses are generated each time the storage proof happens and i get the 'negative currency not allowed'.
Could it be that the storage proof code triggers some code that normally ends contracts and therefore new payout addresses are generated and the Contract Count goes down by 1?

**Comment by DavidVorick** [comment]
It might be that as soon as the storage proof makes it into the transaction pool (but not the blockchain), the contract count is decreased, and if the storage proof needs to be submitted again it will try again.

If you are adding fees to the transaction, that would explain why you are getting so many addresses. I'm not sure why the storage proofs would not be making it onto the blockchain though.

**Comment by betaboot** [comment]
here i have two times the `siac host -v` output, before and after such an event:

----------------------------------------------------------------------------------------
D:\Sia-v1.0.0>siac host -v
General Info:
        Estimated Competitive Price: 668.5 SC

Host Internal Settings:
        acceptingcontracts:   Yes
        maxduration:          13 Weeks
        maxdownloadbatchsize: 17.83 MB
        maxrevisebatchsize:   17.83 MB
        netaddress:           85.7.252.119:9982 (automatically determined)
        windowsize:           0 Weeks

        collateral:       250 SC / TB / Month
        collateralbudget: 2 MS
        maxcollateral:    100 KS Per Contract

        mincontractprice:         30 SC
        mindownloadbandwithprice: 250 SC / TB
        minstorageprice:          999 SC / TB / Month
        minuploadbandwidthprice:  100 SC / TB

Host Financials:
        Contract Count:               18446744073709551562
        Transaction Fee Compensation: 5.73 KS
        Transaction Fee Expenses:     0 H

        Storage Revenue:           232.6 SC
        Potential Storage Revenue: 1.108 SC

        Locked Collateral: 385.5 mS
        Risked Collateral: 1.787 mS
        Lost Collateral:   0 H

        Download Revenue:           0 H
        Potential Download Revenue: 7.34 mS
        Upload Revenue :            63.85 SC
        Potential Upload Revenue:   173.2 mS

RPC Stats:
        Error Calls:        5408
        Unrecognized Calls: 13
        Download Calls:     31
        Renew Calls:        50
        Revise Calls:       4428
        Settings Calls:     24081
        FormContract Calls: 1302

Storage Folders:
    Used        Capacity     % Used    Path
    1.694 GB    50.000 GB    3.39      D:\SiaHostFolder1

----------------------------------------------------------------------------------------

D:\Sia-v1.0.0>siac host -v
General Info:
        Estimated Competitive Price: 708 SC

Host Internal Settings:
        acceptingcontracts:   Yes
        maxduration:          13 Weeks
        maxdownloadbatchsize: 17.83 MB
        maxrevisebatchsize:   17.83 MB
        netaddress:           85.7.252.119:9982 (automatically determined)
        windowsize:           0 Weeks

        collateral:       250 SC / TB / Month
        collateralbudget: 2 MS
        maxcollateral:    100 KS Per Contract

        mincontractprice:         30 SC
        mindownloadbandwithprice: 250 SC / TB
        minstorageprice:          999 SC / TB / Month
        minuploadbandwidthprice:  100 SC / TB

Host Financials:
        Contract Count:               18446744073709551561
        Transaction Fee Compensation: 5.76 KS
        Transaction Fee Expenses:     0 H

        Storage Revenue:           233.8 SC
        Potential Storage Revenue: 1.108 SC

        Locked Collateral: 385.5 mS
        Risked Collateral: 1.787 mS
        Lost Collateral:   0 H

        Download Revenue:           0 H
        Potential Download Revenue: 7.34 mS
        Upload Revenue :            64.18 SC
        Potential Upload Revenue:   173.2 mS

RPC Stats:
        Error Calls:        5419
        Unrecognized Calls: 13
        Download Calls:     31
        Renew Calls:        50
        Revise Calls:       4436
        Settings Calls:     24109
        FormContract Calls: 1306

Storage Folders:
    Used        Capacity     % Used    Path
    1.694 GB    50.000 GB    3.39      D:\SiaHostFolder1
----------------------------------------------------------------------------------------

maybe that helps.
Storage Revenue is also going up, strange...

**Comment by DavidVorick** [comment]
I've lost the plot a bit in all the posts here. Is the primary concern the decreasing contract count or the negative currency message?

Both of those have been fixed in a recent pull request, #1333

**Comment by DavidVorick** [comment]
I believe that this is fixed now, following some added safety to the hostdb

**Comment by fab-io** [comment]
I'm running:
Sia Client v1.0.4
Sia Daemon v1.0.4

and I've just got this:

```
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 3905390 [running]:
runtime/debug.Stack(0x7a, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc452f185b0, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:19 +0xb7
github.com/NebulousLabs/Sia/types.Currency.Sub(0xc420176600, 0xc454080990, 0x0, 0x6, 0x0, 0xc4367290e0, 0x2, 0x5, 0x0, 0xc454080990, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:183 +0x16c
github.com/NebulousLabs/Sia/modules/host.(*Host).removeStorageObligation(0xc4202b2680, 0x0, 0x0, 0x0, 0x0, 0xc4367290e0, 0x2, 0x5, 0x0, 0xc436729110, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/storageobligations.go:528 +0x1ca0
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleActionItem(0xc4202b2680, 0x54badf66d20777d3, 0xcaef17cba5b29ba3, 0x84d20b3d5a72ac91, 0x6522c658fff91e71, 0xc425ff0ce0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/storageobligations.go:671 +0x2ebf
created by github.com/NebulousLabs/Sia/modules/host.(*Host).ProcessConsensusChange
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/update.go:309 +0x249
```

**Comment by MeijeSibbel** [comment]
Please reopen, we just got the same error on v1.3.1 RC2:

[DEBUG io.goobox.sync.sia.SiaDaemon -Critical error negative currency not allowed.txt](https://github.com/NebulousLabs/Sia/files/1560787/DEBUG.io.goobox.sync.sia.SiaDaemon.-Critical.error.negative.currency.not.allowed.txt)

**Comment by KaiRo-at** [comment]
I think it's better to file a new issue when a symptom appears again such a long time later

**Comment by MeijeSibbel** [comment]
thanks, let me do that: https://github.com/NebulousLabs/Sia/issues/2543

**Comment by tbenz9** [comment]
Linking #2346
