### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by hosiawak** [NebulousLabs/Sia#1322]
```
$:~/Downloads/Sia-v1.0.0-darwin-amd64 $ ./siad
Loading...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.013999521000000001 seconds
panic: runtime error: slice bounds out of range

goroutine 19 [running]:
panic(0x6cb560, 0xc82000a0d0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/NebulousLabs/Sia/modules/gateway.myExternalIP(0x0, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:38 +0x489
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedLearnHostname(0xc8201881a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/upnp.go:62 +0x113
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:157 +0xa35
```

**Comment by mnsl** [comment]
My guess is that the call to http://myexternalip.com/raw returned an empty `resp` string. Then `buf[:n-1]` in the return statement at the end of `myExternalIP` would have a negative index.

**Comment by VoidingWarranties** [comment]
Thanks for reporting this! I've made a PR that fixes it. Does this happen every time you start siad or was this a one off error?

**Comment by hosiawak** [comment]
@VoidingWarranties It happened every time

**Comment by VoidingWarranties** [comment]
@hosiawak should be fixed now. If you recompile the master branch and try running siad again can you post the gateway's log? `<sia-dir>/gateway/gateway.log`

It's possible that `myexternalip.com` is returning an empty body. This isn't an issue for the gateway but would be problematic for the host module.

**Comment by hosiawak** [comment]
$ cat bin/gateway/gateway.log
    2016/07/01 05:51:16.772478 gateway.go:105: STARTUP: Logging has started.
    2016/07/01 05:51:16.773093 gateway.go:152: INFO: gateway created, started logging
    2016/07/01 05:51:20.984222 upnp.go:100: WARN: could not automatically forward port 9981: no UPnP-enabled devices found
    2016/07/01 05:51:21.881555 upnp.go:68: WARN: failed to discover external IP: myexternalip.com returned a 0 length IP address

    $ curl -v http://myexternalip.com/
    *   Trying 78.47.139.102...
    * Connected to myexternalip.com (78.47.139.102) port 80 (#0)
    > GET / HTTP/1.1
    > Host: myexternalip.com
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Date: Fri, 01 Jul 2016 05:55:04 GMT
    < Server: Apache
    < X-Frame-Options: SAMEORIGIN
    < Last-Modified: Tue, 26 Jan 2016 13:18:14 GMT
    < Accept-Ranges: bytes
    < Content-Length: 0
    < Connection: close
    < Content-Type: text/html; charset=UTF-8
    <
    * Closing connection 0

**Comment by VoidingWarranties** [comment]
Something isn't right. Does using https in the curl request change anything? Otherwise we could add another fallback like https://api.ipify.org
