### ISSUE TITLE
Unexpected directory upload behavior

### ISSUE THREAD

**Issue by mnsl** [NebulousLabs/Sia#1334]
When a user attempts to upload a directory, they expect to upload the contents of that directory.  Therefore siac should warn that recursive directory upload is not yet implemented for siac (see #913), instead of uploading the directory itself, which is just a list of inodes and their assigned names.

We should implement recursive directory upload ASAP, but in the meantime we should at least warn the user that it is not yet implemented.

**Comment by DavidVorick** [comment]
it's probably easy enough to do recursive directory uploads that we don't need to warn the user.

**Comment by lukechampine** [comment]
fixed in https://github.com/NebulousLabs/Sia/pull/1677
