### ISSUE TITLE
API encoding errors

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1342]
If the API fails to encode a response, no details about the encoding failure are retrievable. The error should be included in the HTTP error response. `build.Critical` is another reasonable option, since response encoding is something that should really never fail.
Also note that since these errors are not JSON, siac fails to properly parse them.

**Comment by DavidVorick** [comment]
Was this ever addressed?

**Comment by lukechampine** [comment]
partially; see https://github.com/NebulousLabs/Sia/blob/master/api/api.go#L268

however, siac still does not handle the error properly, as it is not JSON. The `http.Error` should be converted to a `WriteError`.

**Comment by DavidVorick** [comment]
Would fixing this be considered breaking compatibility?

**Comment by lukechampine** [comment]
Hmm. Not sure. The API spec says that we return a JSON-encoded error if a request fails "for any reason." Going by that, I'd say our code currently breaks the spec. Are we breaking compatibility if we change the code to correctly implement the spec?

My guess is that no one is relying on these errors being non-JSON, so it's better to fix them than to leave it for compatibility reasons. It would be a different story if the code matched the API docs.

**Comment by DavidVorick** [comment]
ok, let's fix this ASAP then, and see how many people complain.
