### ISSUE TITLE
Moving from Sia-UI: Siad.exe only seem to use one CPU core therefore it's very slow to sync/start. Also, high memory usage.

### ISSUE THREAD

**Issue by droghio** [NebulousLabs/Sia#1352]
Moving issue provided by @bathrobehero. Original issue: https://github.com/NebulousLabs/Sia-UI/issues/300

> The CPU usage of siad.exe always seem to top out at 25% on a quadcore CPU so it only ever uses one core. It takes 3-5 minutes to start the wallet on a quadcore i3 CPU.
> 
> It should use all cores to work faster.
> 
> It also uses too much memory (~2GB) probably putting the whole consensus.db into the memory. Over time memory usage decreases to ~600 MB though.

**Comment by DavidVorick** [comment]
Easier said than done. There are a few places we could parallize things but a lot of the operations are inherently sequential. 

Same with the memory. We're not sure where all of the memory consumption is happening, but he's incorrect about it putting the whole consensus.db into memory. Sia does not do that.

**Comment by DavidVorick** [comment]
Still, after lots of playing around we were able to get `-M cge` down below 200MB of memory, if we do the same sorts of changes we should be able to get all the rest of Sia that low as well.
