### ISSUE TITLE
renter renewing

### ISSUE THREAD

**Issue by david60** [NebulousLabs/Sia#1354]
Hi,

I've seen some effects around renewing on the renter side which may be problems with the renter renewing logic.

(i) while uploading, a contract being used by a long running upload and which becomes eligible for renewing may be renewed twice (or more) in rapid succession, e.g. within a few blocks.

When trying to understand that I also noticed this

(ii) fileContacts aren't updated with the IDs of renewed contracts

The first I saw, the second is only something I think will happen. These might deserve two separate tickets, but I'm opening it as one - to let you think about if there is a problem and how you want to track it.  Anyway, what I believe is happening during these is:

(i) The contractor will periodically renew contracts as they enter the renew window. The new contract is formed (with a new ID) and the existing one is removed from the contractor. However if there's an upload in progress, the host/proto Editor have copies of the original contract and will usually re-add it back to the contractor after the upload of the sector. The contractor will then again pick up the contract during the next update scan, and renew it again. Possibly doing this several times.

(ii) I didn't notice any mechanism for the the new contract ID for a renewed contract to be updated in individual fileContracts. The same is true of some other fields in the fileContract, e.g. the IP & WindowStart. Although the I don't think there's currently any way for the NetAddress of contracts in the contractor to change, and my reading was that the fileContract WindowStart is only used during reporting. (Maybe intended for some per-file driven renewing I saw mentioned in the comments).

**Comment by lukechampine** [comment]
Thanks again for the thorough report. The renter is a complex beast, and unfortunately, renewing throws quite a wrench in the works. As far as I can tell, you correct on both points: editors will re-add the contract, resulting in multiple renewals, and fileContracts are not properly updated when a renewal occurs.

Potential solutions for (i):
- Don't renew while a contract is being revised. This is fairly simple to implement, but you run the risk of missing the renewal window if the revision takes too long.
- Interrupt editors when a renewal is desired, causing them to return an error. The caller would then need to create a new editor with the renewed contract ID.

Potential solutions for (ii):
- Make renewal the responsibility of the renter. Currently, the contractor is responsible for renewing, but it doesn't have access to the renter's fileContracts. The problem with this is that renewal can also occur when setting the allowance, which is also the contractor's job.
- Use a channel or callback to signal the renter whenever a contract is renewed. This seems reasonable, although you're in trouble if you kill the process between renewing the contract and updating the fileContracts.
- Have the contractor maintain a mapping of old contract -> new contract. Whenever the renter needs to use a contract, it asks the contractor for the latest version.

Feel free to suggest alternative solutions. None of these feel very elegant to me. :|

**Comment by lukechampine** [comment]
Actually, I think the host is supposed to prevent you from simultaneously renewing and revising a contract. @DavidVorick, can you confirm?

**Comment by DavidVorick** [comment]
The host is *supposed* to, but has some leaks where it might not always. I will be patching these in a future pull request. The renter though should on its own be able to manage a separation between renewing and revising. If the renew window is nearby, the revisions should probably stop until the renew has completed. It should be safe to wait until a single iteration completes, but each iteration you should probably re-check the renew window to see if you should release the lock and allow the renew to happen.

Renew should definitely wait until all open revise calls have completed, which does mean adding a method of interruption. This adds a lot of syncing complexity, so there should be a lot of testing to accompany that.

For making sure that the renter and contractor are on the same page, the real solution should be that the renter recognizes hosts by their public key, and the contractor maps a public key to a file contract id.

**Comment by david60** [comment]
Hi Luke. Thanks for the information. I don't have the definitive timing for the sequence which happened. It may be that the renter upload was not actually revising with the host when the renew happened, e.g. the renter may have been waiting for the chunk pieces to upload to other, slower hosts. The Editor in the hostPool would still have the old contract, so for the next chunk it would have revised the old contract (ok if the renew has finished) and then at the end add the contract back to the contractor.

**Comment by david60** [comment]
I'll add ideas or alternatives about the approaches you mention if I can (I certainly should think more beforehand). I might try a few approaches and see if I can make a renewal sequence run smoothly. For this ticket it's up to you if you want to keep this open and/or later merge it into other renter improvements. I wanted to mention the effect of multiple renews, so that you have it in mind.

Thanks for your work!

**Comment by david60** [comment]
I wrote:

>  The Editor in the hostPool would still have the old contract, so for the next chunk it would have revised the old contract 

@lukechampine Actually you're probably right, as I wrote it I don't think my explanation is consistent. For most of the time the Editor exists within the renter, the storage obligation should be locked on the host. And to create the Editor the contact should be in the contractor. There are probably small periods were it is possible; but if I can reproduce the effect again, and the find the actual sequence which goes wrong I'll add it for you.

**Comment by lukechampine** [comment]
Another point of interest:
It seems like after renewing, you can still use the old contract ID to access the new data. That is, this will work:
- Form contract (id: 0)
- Renew contract (id: 1)
- Create editor with id 1
- Upload data (root: 0) and close editor
- Create downloader with id 0
- Download root 0

@DavidVorick, is this behavior intentional? I was not expecting this to work.

**Comment by DavidVorick** [comment]
The host is fine with you using old contracts, it does not track which contracts have been renewed, only which ones have expired.

**Comment by DavidVorick** [comment]
but it's going to cause the renter loss next time it tries to renew, as it'll renew the latest contract, which won't have the data that you uploaded to the previous contract. Then when the previous contract expires, the data will be unrecoverable.

**Comment by DavidVorick** [comment]
I believe we fixed all of these issues in the days leading up to the v1.0.3 release. Sorry it took so long to get to, definitely needed to be a high-priority item.
