### ISSUE TITLE
Specifying a blank host bypasses API security check

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1376]
e.g. `siad --api-addr :9980` is equivalent to `siad --api-addr [::]:9980`, but only the latter will get caught by the API security check.

**Comment by DavidVorick** [comment]
If you specify `siad --api-addr :9980` it should only be serving on localhost. A brief test showed that this is not the case.

**Comment by DavidVorick** [comment]
If that's too confusing, then it should at least deny the usage of `--api-addr :9980`, forcing you to add the full address.

**Comment by johnathanhowell** [comment]
note that the new `sia.js` calls siad with a set of default flags, one of them being `--api-addr :9980`.  It's critical that this binds only to localhost for our UI users, although new `sia.js` probably won't be released in the UI until after 1.0.2

**Comment by VoidingWarranties** [comment]
We should also consider how any changes we make would affect the other addr flags, `--rpc-addr` and `--host-addr`. For those flags it is much more convenient to specify `:xxxx` than `0.0.0.0:xxxx` or `[::]:xxxx`. I think using `:xxxx` is also the only way to listen on both IPv4 and IPv6 interfaces.

In general a blank host means "all available interfaces" (see [`net.Listen`](https://golang.org/pkg/net/#Listen)). I think a reasonable solution (and the solution presented in the PR) is to require the `--disable-api-security` flag if the host is blank.

**Comment by johnathanhowell** [comment]
alright, I'll change `sia.js`'s default flags to `localhost:998*`

**Comment by VoidingWarranties** [comment]
Only the API address should be localhost. The other addresses' hosts should be unspecified.

**Comment by johnathanhowell** [comment]
roger that, looks like that's how it was regardless.  For some reason I thought the api was bound to `:9980`
