### ISSUE TITLE
Possible File Corruption In Windows

### ISSUE THREAD

**Issue by droghio** [NebulousLabs/Sia#1380]
There are at least four reports of users being unable to restart Sia-UI after what appears to be a siad issue. The story goes siad/Sia-UI launched fine, crashed at some point, and refuses to restart with the same data path.

It seems the issue affects Windows users and might be related to the file renaming inside the persist module, but it is difficult to tell as I have been unable to reproduce the error firsthand.

The closest explanation for the crash comes from [OlegG's Forum post](http://forum.sia.tech/topic/304/1-01-wont-load/6):

```
miner could not save during startup: rename C:\Wallets\SIA\Sia-UI-win32-x64\resources\app
Sia\miner\miner.json_temp C:\Wallets\SIA\Sia-UI-win32-x64\resources\app\Sia\miner\miner.js
on: Access is denied.
```

With a similar error being posted by [Monaco](http://forum.sia.tech/topic/231/what-does-this-error-mean)

Related forum posts:
http://forum.sia.tech/topic/323/what-the-sia-is-going-on-with-the-miner-and-wallet
http://forum.sia.tech/topic/304/1-01-wont-load
http://forum.sia.tech/topic/279/sia-stuck-in-loading-sia
http://forum.sia.tech/topic/253/my-interface-wallet-is-loading-and-loading

Possibly related post:
http://forum.sia.tech/topic/231/what-does-this-error-mean

**Comment by DavidVorick** [comment]
My interpretation of most of these problems is that at some point one of the modules desynchronized with the consensus set and then had to do a rescan. Rescans can take >10 minutes to complete, and even longer if multiple modules are doing it.

**Comment by lukechampine** [comment]
We should try to reproduce this now that we have Windows builds

**Comment by droghio** [comment]
Good idea. Microsoft also provides VMs for testing compatibility with different versions of Windows. I was going to see if I couldn't reproduce the issue on one of those.

**Comment by droghio** [comment]
More reports of data corruption have come in. These seem different but again are affecting Windows users. After looking at one of the corrupted files it seems the writing process was interrupted leaving half finished .json files with plenty of null bytes.

@johnathanhowell thinks this is related to #1399

Example issue; http://forum.sia.tech/topic/323/what-the-sia-is-going-on-with-the-miner-and-wallet/6

**Comment by DavidVorick** [comment]
A corrupted hostdb.json isn't supposed to be possible, as the hostdb uses safe files when saving. It writes all of the data to a temporary file, then copies it over (atomically) to a new filename once complete. That should mean that any file that is ever read from disk is complete and uncorrupted.

Unless the save process is not working correctly in Windows, there have been some questions about whether Windows was performing the rename correctly.

Do you have an example of a corrupted file? Would help to see what types of corruption are happening.

**Comment by droghio** [comment]
Certainly, I have a corrupted node.json and a corrupted hosts.json. I am trying to get the corrupted hostdb.json file but am waiting to hear back from the user.

[Totally not sketchy: corruptedFiles.zip](https://github.com/NebulousLabs/Sia/files/407263/corruptedFiles.zip)

**Comment by lukechampine** [comment]
Interesting. Inspecting the provided files with hexdump, We can observe the following:
```
00000000  22 53 69 61 20 4e 6f 64  65 20 4c 69 73 74 22 0a  |"Sia Node List".|
00000010  22 30 2e 33 2e 33 22 0a  00 00 00 00 00 00 00 00  |"0.3.3".........|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```
```
00000000  22 53 69 61 20 48 6f 73  74 22 0a 22 30 2e 35 22  |"Sia Host"."0.5"|
00000010  0a 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```
```
00000000  22 48 6f 73 74 44 42 20  50 65 72 73 69 73 74 65  |"HostDB Persiste|
00000010  6e 63 65 22 0a 22 30 2e  35 22 0a 00 00 00 00 00  |nce"."0.5"......|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```
In other words, the header is being written properly, but the remainder of the file is not -- it's just thousands of NUL bytes. The relevant code is:
```go
func Save(meta Metadata, data interface{}, w io.Writer) error {
	b, err := json.MarshalIndent(data, "", "\t")
	if err != nil {
		return err
	}

	enc := json.NewEncoder(w)
	if err := enc.Encode(meta.Header); err != nil {
		return err
	}
	if err := enc.Encode(meta.Version); err != nil {
		return err
	}
	if _, err = w.Write(b); err != nil {
		return err
	}

	return nil
}
```
I'm at a loss as to why this would happen. Even if the `Write` was failing, why would the file be filled with zeros? And why would it fail on the `Write`, but not the `Encode`?

**Comment by droghio** [comment]
I think it might be related to Windows syscalls, and possibly an unsafe termination.

Food for thought, the corrupted files have about the same size as uncorrupted files.
````
his corrupted host.json:      2163 bytes
my uncorrupted host.json:     2156 bytes

his corrupted hostdb.json:    1176629 bytes
my uncorrupted hostdb.json:   1095800 bytes

his corrupted nodes.json:      6491 bytes
my uncorrupted nodes.json:    21583 bytes
````

Given the variances between different peers I think it is pretty safe to say the corrupted files are the same length as if they were uncorrupted.

The only similar case I have found was here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/eb9f1ed1-8c2c-496e-9b5a-f6640c3374c4/object-serialization-corruption-file-bytes-set-to-null?forum=csharpgeneral

I have been trying to track down the specific Windows write sys call that golang is using but I haven't had much luck.

**Comment by lukechampine** [comment]
https://mail-archives.apache.org/mod_mbox/subversion-dev/201506.mbox/%3CCA+t0gk316GoGiF9J3-_mEUr0nWE4zTnN0ZaO_p_qM_U_jRS3Sg@mail.gmail.com%3E

Seems like syncing may indeed be causing it. It doesn't explain why the corruption would only occur after the header bytes, though.

**Comment by DavidVorick** [comment]
http://stackoverflow.com/a/660679

Overall my research seems to indicate that atomic fine operations on Windows cannot be fully guaranteed. The rename call does a delete operation followed by a rename operation. Maybe we could write the file in full twice, and then on startup check which one is uncorrupted. (You'd have to sync one before starting the other)

**Comment by DavidVorick** [comment]
http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/

This says FlushFileBuffers

**Comment by DavidVorick** [comment]
I think my vote is that we re-write the persist package to do double-files in Windows. When saving, it'll write to the temp and sync, then to the primary and sync. When loading, it'll check the primary, then the temp. Corruption detected by using a checksum on the file
