### ISSUE TITLE
./siac host conig acceptingcontracts yes

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1383]
from a user on irc:

```
<twopercent> I found my issue, I was trying ./siac host config acceptingcontracts yes
<twopercent> Seems natural as ./siac host -v indicates "no"
<twopercent> should be ./siac host config acceptingcontracts true
```

The config command should accept the variables as they get displayed in the siac output.

**Comment by twopercent** [comment]
It seems whatever you enter, the response is "Host settings updated". You could maybe add a "Didn't understand you, use "true" or "false"

After trying some more values, it seems anything with a "t" in it will set true. Anything with an "f" will set false. 
"tf" = true
"ft" = false
"truft" returns "Could not update host settings: Malformed acceptingcontracts"

**Comment by lukechampine** [comment]
We use `fmt.Scan` for scanning these values. Its boolean scanning function is here: https://golang.org/src/fmt/scan.go#L545

`siac host -v` should probably output "true/false" instead of "yes/no", despite the latter seeming more natural.

**Comment by VoidingWarranties** [comment]
I think it's reasonable to accept both as some people would expect yes/no and others would expect true/false. It would be simple enough to rename `yesNo` to `BooleanToYesNo` and also add a `YesNoToBoolean` function.

**Comment by lukechampine** [comment]
I'm not keen on going down the path of guessing all the different ways someone might want to specify a boolean. I'm in favor of changing the output from "yes" to "true".

**Comment by DavidVorick** [comment]
did we implement this?

**Comment by lukechampine** [comment]
doesn't look like it: https://github.com/NebulousLabs/Sia/blob/master/siac/hostcmd.go#L307

easy to add, though. Just add another branch to the switch statement.
