### ISSUE TITLE
siac host announce prompts for API password twice

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1390]
When the user runs `siac host announce` when API password authentication is enabled, it prompts the user for their password twice:

```
$ ./siac host announce
API password:
Host announcement submitted to network.
API password:

The host has also been configured to accept contracts.
To revert this, run:
        siac host config acceptingcontracts false
```

Expected: `siac` should prompt once and remember the password for the duration of the command.

Observed on 1.0.1

**Comment by VoidingWarranties** [comment]
I see two possible easy solutions.

1. Cache the password in memory in siac the first time it asks for the API password and reuse the cached password for future API calls.
2. Move the behavior of auto-accepting contracts on announce from siac to the host module.

**Comment by DavidVorick** [comment]
Better to cache the password. If a custom app like Sia-Cluster does not want to change the acceptingcontracts value after announcing, it shouldn't have to. Especially since re-announcing after an IP address change is required if people are going to be able to download their files from you (which brings you revenue, so you want to do it)

**Comment by lukechampine** [comment]
it ain't pretty, but we could easily define a global:
```go
var apiPassword = ""

func apiGet() {
    resp := api.HttpGET()
    if resp.StatusCode == http.StatusUnauthorized {
        if apiPassword == "" {
            apiPassword = speakeasy.Ask("API password: ")
        }
        resp = api.HttpGETAuthenticated(apiPassword)
    }
}
```

**Comment by DavidVorick** [comment]
hmmm. I guess it's that, return the password using apiGet, or have some sort of stateful object that siac creates.

A global variable seems like the best option, but you need to remember to wipe the memory on shutdown.
