### ISSUE TITLE
Offer tar.gz release for 1.0.1

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1391]
All previous releases served the Linux binary as a `.tar.gz` file, but the 1.0.1 switched to a `.zip` file. Can we have a `.tar.gz` file as well? Switching formats for different releases breaks install scripts (like [mine](https://gist.github.com/mtlynch/54d71bff4c33270c1cd6c0ddf0218558#file-dockerfile)).

If `.zip` is the new permanent format, I can update my script to work with that, but it'd be nice for Sia to use consistent file formats for the releases.

**Comment by lukechampine** [comment]
`.zip` is the new permanent format, because our auto-update code expects a zip archive. Apologies for the inconvenience

**Comment by DavidVorick** [comment]
Sorry to break compatibility. There will probably be a few more compatibility bumps in the future, but we're trying to preserve compatibility as much as possible.

I definitely appreciate you making the issue, it's good to see what things we are accidentally breaking.
