### ISSUE TITLE
Add "difficulty" field to /consensus API response

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1396]
As @DavidVorick mentioned in #1389 it is probably more useful for clients to have a difficulty field than it is to have a target field.

On the other hand if the difficulty is easily calculated maybe we shouldn't return two fields that are trivially different representations of the same number.

**Comment by lukechampine** [comment]
It is a trivial calculation; just a divide or multiply. (ok, you need a divide-by-zero check when dividing.) I don't think we need to return both. It would be easy for us to display both in siac, though.

**Comment by DavidVorick** [comment]
It's a divide or multiply on a 32-byte integer that's presented to you as a byte-array, seems like a lot to ask from a third party developer. If you aren't giving both values you'd want the documentation to specify how to move between them. Especially b/c the conversion is not necessarily obvious when working from first principles, and you might not even know that a conversion is possible if you aren't familiar with some of the theory behind PoW.
