### ISSUE TITLE
consider blake2b-simd

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1402]
https://github.com/minio/blake2b-simd

It should be identical, except way faster on amd-64. I checked and it doesn't speed up testing very much, most of our bottlenecks are I/O. But for things like taking merkle roots, it's almost 2x as fast. I'm guessing that in-production users would notice speedups for file handling.

For receiving blocks, probably not. The CPU is basically idle right now when downloading the blockchain. It's all waiting for boltdb synchronization.

**Comment by DavidVorick** [comment]
credit to @axu for bringing this repository to my attention

**Comment by lukechampine** [comment]
I have already tried this out and confirmed that it does boost synthetic benchmarks quite a bit. We should try doing a full IBD or similar to evaluate its real-world impact.

**Comment by aead** [comment]
Just for reference: 
The "offical" golang [x/crypto](https://godoc.org/golang.org/x/crypto) sub-repo now contains both - [BLAKE2b](https://godoc.org/golang.org/x/crypto/blake2b) and [BLAKE2s](https://godoc.org/golang.org/x/crypto/blake2s)

**Comment by lukechampine** [comment]
excellent, with the backing of `/x/` I think there is no reason not to switch to that implementation.

**Comment by DavidVorick** [comment]
we should benchmark it vs. the simd version, but in general I agree that we should use stdlib where possible.

But also note we'll have to vendor it the same way we had to vendor the twofish library.

**Comment by lukechampine** [comment]
@aead: I'm observing very slow hashing speed when using AVX2 compared to SSE4:

AVX2:
```
BenchmarkWrite128-4   	 1000000	      1787 ns/op	  71.59 MB/s
BenchmarkWrite1K-4    	  100000	     13812 ns/op	  74.14 MB/s
BenchmarkSum128-4     	 1000000	      1784 ns/op	  71.74 MB/s
BenchmarkSum1K-4      	  100000	     13795 ns/op	  74.22 MB/s
```
SSE4:
```
BenchmarkWrite128-4   	10000000	       189 ns/op	 676.91 MB/s
BenchmarkWrite1K-4    	 1000000	      1397 ns/op	 732.79 MB/s
BenchmarkSum128-4     	10000000	       216 ns/op	 591.16 MB/s
BenchmarkSum1K-4      	 1000000	      1363 ns/op	 750.93 MB/s
```
Generic:
```
BenchmarkWrite128-4   	 5000000	       277 ns/op	 461.52 MB/s
BenchmarkWrite1K-4    	 1000000	      2097 ns/op	 488.12 MB/s
BenchmarkSum128-4     	 5000000	       309 ns/op	 413.93 MB/s
BenchmarkSum1K-4      	 1000000	      2186 ns/op	 468.38 MB/s
```
Any ideas?

**Comment by aead** [comment]
On which machine do you run the benchmarks CPU and which go version do you use?

On my i76500U running on linux (kernel 4.4) I see the following for AVX2:
```
BenchmarkSum128-4     	10000000	       190 ns/op	 673.42 MB/s
BenchmarkSum1K-4      	 1000000	      1219 ns/op	 839.81 MB/s
```

The minio blake2b-simd:
```
BenchmarkSize128-4             	 5000000	       297 ns/op	 429.95 MB/s
BenchmarkSize1K-4              	 1000000	      1437 ns/op	 712.48 MB/s
```

**Comment by lukechampine** [comment]
I'm also using v1.7.1 on an i5-4670K with kernel 4.4.0.

I think it must be a CPU thing. I'm seeing expected speeds on my laptop (v1.7.1, i7-6500U, kernel 4.4.0) and confirmed that it is also running the AVX2 branch. The weird part is that the minio package works fine. I'll try to confirm that it is running AVX2 code.

**Comment by aead** [comment]
Hm, okay...
Maybe you can keep updating the x/crypto packages (there are some pending changes about the stack and frame pointers and the ABI from Austin Clements). Perhaps one influence the speed on "older" AVX2 machines...
70 MB/s is so slow, there must be some weird behavior of the CPU/Go-Assembler etc. The minio implementation uses the BYTE representation of all instructions - so myabe there's a subtle assembler bug or something like that...

Maybe you can open an issue at [golang](https://github.com/golang/go/issues)?

**Comment by lukechampine** [comment]
@aead: we're seeing the expected speeds now and have switched to using the x/crypto package in [fastrand](https://github.com/NebulousLabs/fastrand). Thanks!
