### ISSUE TITLE
MenuBar in Tab "Files" are moving strange at resize

### ISSUE THREAD

**Issue by ma68546** [NebulousLabs/Sia#1404]
![image](https://cloud.githubusercontent.com/assets/18228325/17506666/0ceed88a-5e0b-11e6-99d7-a47bac651989.png)

The MenuBar is behaving strange when resizing the window to a small size

**Comment by johnathanhowell** [comment]
This should be in the Sia-UI repo (here: https://github.com/NebulousLabs/Sia-UI), but I also noticed you're using an earlier release of Sia-UI.  We added a minimum window width in the latest version, I think that fixed the button layout bug, you can download it here: https://github.com/NebulousLabs/Sia-UI/releases/tag/v1.0.2
