### ISSUE TITLE
Allow contract to prevent renter from deleting files

### ISSUE THREAD

**Issue by Tails** [NebulousLabs/Sia#1425]
I have a use-case where miners from a specific blockchain network upload files. However, an ethereum contract is supposed to keep paying the hosts to control which files should remain online and the renters should relinquish control over their uploads. Is this possible somehow?

**Comment by lukechampine** [comment]
There is nothing at the protocol level that prevents this, but you would need to fork our host implementation and add the necessary logic yourself. Specifically, it sounds like you need some way to whitelist who can form contracts with your host, some way for the contract to interface with the host, and some way to disable any revision actions other than uploading and downloading (this part is easy).

I would like to make this sort of extension easier in the future. The host modules already does a good job of separating the data management code from the RPC handler code, but it could be made even more modular by explicitly splitting the RPC protocol into its own package.

**Comment by DavidVorick** [comment]
Is the smart contract the one signing the file contract? That's a cryptographically difficult problem, because you would want the secret key protecting the contract to be... secret. I think what you are asking for here is more powerful than what the Sia framework can offer - to have exclusive control over what data the host is storing, you need exclusive control over the key that protects the file contract.

**Comment by Tails** [comment]
As you state, for now it wouldn't be possible to have the smart contract sign the storage contract, but the smart contract could keep financing the contract to prevent it from being deleted (unless this also requires signing by the original renter).

I was hoping for a method to transfer ownership to non-ownable addresses and allow external funding, but that seems far off still.

I guess I'll have to allow renters to have control but let my hypothetical network check the storage chain for REVISION or DELETE (are these recorded on chain?) messages and punish it's nodes.

**Comment by lukechampine** [comment]
Revision actions are not recorded on the blockchain; they use a payment channel, such that only one transaction has to be submitted to the blockchain at the contract's conclusion.
You would need some way of configuring the hosts themselves to disable those actions.
