### ISSUE TITLE
move build/testing.go to the persist package

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1426]
TmpDir, CopyFile, CopyDir all seem like functions to me that belong in the package which is doing other filesystem operations

**Comment by lukechampine** [comment]
seems reasonable to me, except perhaps the "delete-old-directory" behavior of `TempDir`

**Comment by DavidVorick** [comment]
That's why it's called `TempDir`, but I guess the name is not super telling. `DebugDir` maybe?

**Comment by lukechampine** [comment]
the `TempDir` in the stdlib has different behavior (choosing a random suffix to avoid collisions). I guess "Temp" means different things to different people.

I think `TempDir` is fine as long as its behavior is properly documented. However, there are some cases during testing where I want to reuse a `TempDir` without deleting the old one, which usually means reconstructing its path manually. It's not a common case (and you can almost always just reference `m.persistDir`) but we might want to consider it when moving the functions over.
