### ISSUE TITLE
API can't accept paths with spaces in it right now

### ISSUE THREAD

**Issue by javajared** [NebulousLabs/Sia#1434]
Right now I am working to upload a file to Sia via the siad API. However, my file source path has multiple spaces in it. This forces me to encode the spaces with "%20" in order to make a valid POST request to http://localhost:9980/renter/upload/path 

The problem is that siad on the receiving end responds by saying that /file%20one.file does not exist. Instead, siad needs to decode the "%20" back into a space.

**Comment by johnathanhowell** [comment]
Does the call to `/renter/upload` succeed?  What's the output of `/renter/files`?

**Comment by DavidVorick** [comment]
Can I also ask what version you are using? I think we fixed this recently but it didn't make into `v1.0.1`

**Comment by javajared** [comment]
Yes, call to `/renter/upload` is successful for files that do not have any spaces in the path. These changes are reflected in the `/renter/files` call. 

I am using `v1.0.1` so I suppose that may be the cause of my troubles.

**Comment by johnathanhowell** [comment]
What happens with files that have spaces in the path?

**Comment by javajared** [comment]
If I have a file such as below:
C:/path/to/file with spaces.png

I post to http://localhost:9980/renter/upload/C:/path/to/file with spaces.png

In return I get the following message:
`{"message": "Upload failed: GetFileAttributesEx C:/path/to/file%20with%20spaces.png: The system cannot find the file specified."}`

The only way I can successfully make this request on my end is to encode the spaces with `%20`, but siad on the receiving end isn't decoding the `%20` back into spaces.

**Comment by VoidingWarranties** [comment]
Proposed fix:
Use [`url.QueryUnescape`](https://golang.org/pkg/net/url/#QueryUnescape) in the API.

**Comment by javajared** [comment]
That would probably fix this.

**Comment by lukechampine** [comment]
I'm surprised it's not unescaped by default. I guess query params are, but paths aren't.

**Comment by lukechampine** [comment]
seems like this works fine as long as the requests are URL-encoded. This will be implicitly required for API users.
