### ISSUE TITLE
Siad network connectivity problems

### ISSUE THREAD

**Issue by aspect** [NebulousLabs/Sia#1438]
My current analysis of the problem described below indicate high probability of a problem in siad network stack that prevents siad from functioning correctly in certain network conditions.  As nodes are fully synced this seems to apply specifically to host (hostdb) connectivity layer.

We have 4 siad nodes (alpha, beta, gamma, delta) running under Sia Cluster control.  1 node (delta) runs on a static public IP in a DC, another 3 nodes (alpha, beta, gamma) are running each on a different static IP mapped to my internal LAN segment.

Alpha, beta, gamma running on LAN seem to show on the network after siad restart but very quickly disappear and are never seen again.  Given that they disappear of the network, they are incapable of accepting contracts.  Delta runs perfectly and accepts storage contracts.

Additional information:
- All nodes are running latest 1.0.1 release
- This problem has been present since we've deployed all nodes in July 2016 with v1.0.0
- Upgrading to v1.0.1 and doing re-announce caused these nodes to show up on the network (visible in hostdb of other nodes, even on SiaPulse), however as described, they have quickly disappeared.
- As they showed up on the network after upgrade/restart, they seem to have managed to accept few contracts before disappearing.
- Given that all 4 nodes are under Sia Cluster control, they have same pricing configuration and all manually configurable parameters are identical. (whatever is going on is not related to pricing parameters, this does not seem to be related to #1324)
- All nodes look healthy (blockchain is synced, there is no visible indication of any problem whatsoever, nor anything specific is present in log files)

Network Configuration: 
- External IPs are mapped to the LAN segment using a ubiquity router.
- IPv6 is disabled
- Internal LAN IPs are 10.10.10.10 ... 10.10.10.12
- Public static IPs are assigned to FQDN subdomains such as alpha.sia.aspectron.com; beta.sia.aspectron.com etc.
- UPnP is disabled for this LAN segment
- Nodes have full network access and I am able to SSH into these nodes via their external IP at any point. These systems have full network connectivity at all times.
- So far I have excluded ISP as a potential source of the problem since connectivity to other ports from external IPs work and nodes do seem to operate fine for a while following restart+announce

In overall, all looks 100% healthy, except the nodes in question do not appear in hostdb records of other nodes.

Currently, the only hypothesis that I have is as follows:  In the past I have built large client-server systems that were interconnecting hundreds of computers in different geographical locations using custom TCP/IP connectivity.  We've encountered (numerous times) a problem where established TCP connections would get terminated but our servers would never receive TCP FIN bit notification (at least this is the best conclusion my team was able to reach)…  in other words the connection would get terminated due to an intermediary but nor client nor server would know about this until they tried to transmit any type of data.  Defunct TCP connection would remain "connected" indefinitely.  This problem was solved by introducing a periodic ping data exchange.  Maybe this was something specific to the DC networking equipment, don't now, but this somehow feels very similar.

I would hypothesize that maybe there is a problem with a local IP being different from a public IP and when UPnP is disabled this causes some type of confusion... but nodes do become briefly visible after siad restart and re-announce, so that shouldn't be the case.

Other than that, I am at a loss as to what is going on.  I will gladly provide Sia team with access to these nodes to run any test version of siad in effort to get to the bottom of this.

**Comment by lukechampine** [comment]
Do the logs provide any indication? Running in debug mode will enable more logging info. The first thing we should determine is whether the nodes are intentionally disconnecting from each other, or if they wish to connect and are being disrupted somehow. @DavidVorick may have suggestions for where to add logging statements if some are missing.

As for the heartbeat ping, our multiplexing library (muxado) should handle that automatically, although I'm not 100% sure.

My gut says the nodes are kicking each other on purpose, perhaps because they are on the same network.

**Comment by johnathanhowell** [comment]
We noticed and fixed a number of connectivity problems that act similarly to what you're describing recently, you could try to pull and build the latest master branch, it may fix your problems.

**Comment by aspect** [comment]
@lukechampine logs do not provide any indication, everything looks perfectly happy.  Is there a way to run siad in debug mode?  or I have to build the project?  @DavidVorick has already suggested building master, I am going to try to find some time this or next week to do this.

As we do see nodes come to life upon restart and re-announce I presume some type of disruption is happening later on.  Mind you, this seems to apply only on host communication layer as p2p layer seems to work just fine (they keep sync and gateway logs show that they periodically relay transaction sets to 8 peers.

Mind you p2p layer might be more aggressive in terms of networking connectivity, hiding the problem.

@johnathanhowell `host.log` contains `INFO: Successfully announced...`.  (followed 2 days later by `upnp.go:70: WARN: failed to discover external IP` (probably unrelated).  There is a bunch of UPnP erros but I presume they are benign as this is a static IP mapping setup.

I did encounter a rather interesting behavior on 2 separate PCs (both win64) behind NAT+UPnP where starting node A and node B right after would prevent node B from syncing and vice versa. Once node A would be shut down, B would start syncing immediately. Re-starting A would result in A not syncing until B is down.  In other words p2p connectivity on A & B was mutually exclusive, as if UPnP allocated same ports for both nodes.  I haven't had time to try to replicate these conditions and thus haven't filed this issue yet.

Anyways, I am going to try to find some time hopefully this week to build and run the latest master.  But if you guys do testing, please consider adding one of these nodes to your test setup.  I will gladly give you access as these are dedicated (79Tb) storage nodes built specifically for Sia.

**Comment by DavidVorick** [comment]
@lukechampine this seems to be relating to the hostdb, not the gateway. Based on some screenshots I've seen the gateway's are working fine - all have the same block height and it's the correct block height.

Seems to me that the hostdb is finding the hosts, then deciding to kick them for some reason. From what I remember the hostdb should only be kicking hosts in the event of unreachability, or if they shared a public ip address with another host.

The easiest way to tell would be to flag the IP addresses in the hostdb and print some logs any time that the hostdb interacts with those addresses. I will do that today to figure out what's up.

**Comment by betaboot** [comment]
I started a new wallet with 1.0.3RC and made contracts with 24 hosts. **alpha.sia.aspectron** and **delta.sia.aspectron** are both in my contracts list.
Then, i uploaded some files but both of them did not get the files yet.

The renter.log is telling:
`2016/10/10 16:27:50.184337 repair.go:301: failed to upload to host alpha.sia.aspectron.com:9982: host did not accept transaction signature: host unable to add sector despite having the storage capacity to do so`

The same for **delta.sia.aspectron**.

Just wanted to report, maybe i can help solving the problem...

**Comment by DavidVorick** [comment]
Thanks for the information! Definitely helps.

From what I can tell, packets are being dropped or connections are being interrupted. There was some speculation about a potential bandwidth throttler that could be causing issues. It seems like the majority of connections fail, but not all of them, which is why the behavior is so strange.

**Comment by aspect** [comment]
I am away at scaling, so don't have time to look at this in detail right
now, but delta is a straight IP in an NYC DC.  So unless the host RAID6
(+hot spare) has failed I am not sure what this can be.  Delta has been
operating flawlessly up to now, but due to travel I have not had a chance
to upgrade to the latest RC.

**Comment by DavidVorick** [comment]
No those errors will start appearing due to a bug somewhere in the host code. Unfortunately, that drive won't be able to accept data anymore as a result, and I'm not entirely sure where the bugs reside.

When host2 is merged into master (eta ~2 weeks), we'll have resolved this problem.

**Comment by lukechampine** [comment]
Closing this due to age, please reopen if it's still a problem.
