### ISSUE TITLE
Mount a sia folder to my filesystem

### ISSUE THREAD

**Issue by faddat** [NebulousLabs/Sia#1447]
Hi guys, I'll admit that at first I wrote this project off, and then I looked into the pricing.  Seems you have Google beat by more than a fair stretch, so it'd simply be unfair not to give it a try.  

Can I mount a Sia folder to my filesystem?

I'm looking to use it to back up docker containers en masse.

**Comment by lukechampine** [comment]
Mounting a Sia folder would require writing FUSE bindings. It's a feature we've wanted to implement for a while, but we want to make the storage backend as solid as possible first. I believe at least one person has written FUSE bindings for Sia, but they are outdated now. In the meantime, if I were you I would wait for the next release (1.0.2) which should improve stability somewhat, and then test out the platform with manual uploads to see if it meets your requirements.

**Comment by faddat** [comment]
Well, $2.25/tb-mo is a game-changer.  If I can access that 24/7 @1MBPS, 
then yeah, I want to write FUSE bindings, even if I'm only using them 
personally.

**Comment by faddat** [comment]
How is $2.25/tb-mo even possible?  This seems to not reflect the price of storage today....

Let's see, checking newegg:

Hm.  You may be right.  A 4tb disk would pay itself off in about a year.  3% failure rate.. well, hosting files with Sia at least breaks even.  Am I right that you are tapping into the world's abundance of legacy data centers?

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/19220691/9caca7ae-8e5d-11e6-9b98-51377afb9cef.png)

![image](https://cloud.githubusercontent.com/assets/7142025/19220696/a57d53c4-8e5d-11e6-94d6-2681b3c7eded.png)

![image](https://cloud.githubusercontent.com/assets/7142025/19220706/ca0def3c-8e5d-11e6-9c34-18853b5c9b03.png)

**Comment by faddat** [comment]
????

**Comment by lukechampine** [comment]
The estimated cost includes a flat 2KS to cover transaction fees. Each contract requires a separate transaction, and you are forming 24 contracts. If you subtract the fee, you can see that the cost is proportional to the storage (looks like approx. 10 SC/GB).

**Comment by DavidVorick** [comment]
We should probably remove the 10GB option, maybe have 50, 250, and 1000.

Not that the software can support 1000, but at least it seems to be getting higher than 10.

**Comment by Fornax96** [comment]
The UI also seems to massively overestimate the price. When I last chose the 100 GB option I got 350 GB of space (according to the UI). It may be a good idea to let the user manually enter the spendings too, and show an estimate of the amount of space you can get with that money. Since that is also how siad works internally.

**Comment by pmknutsen** [comment]
My guess is that hosts are still very cheap so that small absolutely
variations between hosts translate into huge relative differences, e.g. 10
vs 15 SC/gb is a 50% difference. Until hosts stabilize on more realistic
prices cost estimates therefore might fluctuate. Or there is a bug :-p

10. okt. 2016 11:40 a.m. skrev "Fornax" <notifications@github.com>:

**Comment by faddat** [comment]
Well, let's dig a little deeper then:  Look, 

**Sia proved to be unusably slow.  1MBPS would have been a dream compared to actual performance.**

**Comment by pmknutsen** [comment]
I am seeing about 1MiB/S on average, with large fluctuations around that up to 4 MiB/S top. What speeds are you seeing? Users also report that uploading large files (GBs) is faster per GB than uploading many small files.

**Comment by lukechampine** [comment]
The uploading algorithm is really overdue for some optimization. Our goal is to saturate your upload bandwidth, and I think we can achieve that within a few iterations if we focus our efforts on the renter.

**Comment by faddat** [comment]
If you do, then your network of nodes shall surely get my business.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by DavidVorick** [comment]
@faddat: Are you using the release candidate, or are you using version 1.0.1?

The release candidate is a lot more stable, seems to be able to maintain a blazing 1mbps. Not sure where your minimums are, but if you check back in a month or two we should have another 5x-10x speedup on that.

**Comment by faddat** [comment]
I'm not using any any more, but if you give me a link to the latest version or a link to instructions on how to install the latest version, then I'll be using the latest version.

**Comment by DavidVorick** [comment]
CLI: https://github.com/NebulousLabs/Sia/releases

UI: https://github.com/NebulousLabs/Sia-UI/releases


The current release (as of writing) is v1.0.3, and it's a substantial upgrade in terms of stability and usability. I strongly recommend you try it out, you will probably find it to be night + day in terms of frustration + bugs, though the feature set is largely the same.

**Comment by daniel-lucio** [comment]
Can anyone share the like for the FUSE mount point. I know its broken, but maybe I can fix that.

**Comment by lukechampine** [comment]
Closing due to age. If anyone wants to pick up the task of writing FUSE bindings, drop us a line on Slack.

**Comment by faddat** [comment]
Some of us are undoubtedly still waiting.

**Comment by starius** [comment]
See https://github.com/SiaExtensions/SiaDrive
(Not in Go unfortunately.)

**Comment by mkeedlinger** [comment]
Man, dead threads and links like this are always depressing :cry:
I guess I'll go looking for some more links about fuse support and brb!
