### ISSUE TITLE
Calls to /gateway/connect with peers on the same IP but different ports fail

### ISSUE THREAD

**Issue by johnathanhowell** [NebulousLabs/Sia#1452]
These calls fail with `already connected to this peer`

**Comment by VoidingWarranties** [comment]
I'm not able to reproduce this. I have confirmed locally that connecting to multiple peers with the same IP but different ports succeeds and both peers show up in the peer list. As we talked about offline, this may be an issue with the antfarm attempting to connect to the same peer.
