### ISSUE TITLE
Javascript API

### ISSUE THREAD

**Issue by faddat** [NebulousLabs/Sia#1453]
Is it possible to interact with Sia-stored files via javascript?

**Comment by lukechampine** [comment]
Depends on what you mean. You can interact with a Sia node via the API, which lets you upload and download files -- but you need to refer to filenames in the node's filesystem.\* On the other hand, if you want to download a file using only its metadata, things are a bit trickier. You would need to speak the renter-host protocol, and on top of that you need to decrypt the data and reverse the erasure-coding. I'm sure there are node libraries for all of this, but doing it in the browser is a different story.

\* We plan to add API routes for streaming file downloads, which would have a number of benefits. The tradeoff is potentially slower download speeds; this tradeoff also affects BitTorrent streaming, and for the same reasons.

**Comment by johnathanhowell** [comment]
Hi @faddat, Sia has a standard HTTP api. Check out the docs here: https://github.com/NebulousLabs/Sia/blob/master/doc/API.md. We have a Node library we use to interact with the API that handles errors, user agents, and a few other minor things here: https://github.com/NebulousLabs/Nodejs-Sia. Sia-UI uses this library pretty extensively.

**Comment by DavidVorick** [comment]
http://blog.sia.tech/2016/10/20/api-quickstart-guide/

Some additional guidance
