### ISSUE TITLE
Fast wallet unlock

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1465]
A user must be able to unlock their wallet within 1 second, regardless of how many addresses they have.

This means that the persistence needs to store the seed index alongside the unlock hash - 1 second is not enough to do key derivation more than a few thousand deep, and some users have tens-of-thousands of addresses. Instead, the seed key should be kept and derivation should be performed on a per-address basis as the secret keys are needed.

For scanning purposes, initialization / rescanning should cache all of the addresses that are discoverable. No reason to derive them every time.

**Comment by lukechampine** [comment]
>persistence needs to store the seed index alongside the unlock hash

Depends on whether loading the seeds from disk is faster than rederiving them. I imagine that for small n, it's faster to rederive, but a benchmark would be better.

Another approach would be to delay seed loading/derivation until the first ProcessConsensusChange (or other method that needs them). The wallet would then unlock immediately, but there would be a one-time delay later on.

**Comment by DavidVorick** [comment]
I forget the exact benchmark, but I think it's in the ballpark of 2000 keys derived per second per core.

Reading from disk is ~80MB per second for slow disks. Assuming 40 bytes (32 for unlock hash, 8 for derivation index), that's 2 million per second.

You have to read from disk anyway, so you are not saving on latency.
