### ISSUE TITLE
Rescan, IBD, Startup Progress for Wallet

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1468]
The wallet must be able to display rescan progress + startup progress, including through the API.

Startup is going to be trickier, because the /wallet route will not be available, and progress is not just a smooth number like # of blocks. But things like 'performing compat upgrades' should be somehow accessible to the UI so the user knows what's taking so long.

**Comment by lukechampine** [comment]
won't the compat upgrade only happen once you unlock? You need the encryption password.

Unlocking should be very fast unless you are rescanning, so we could do what some other software does: if unlocking takes more than a few seconds, the UI will add a message below the loading spinner that says "If you are upgrading from a older version, your wallet will be converted to the newest format. This may take a few minutes."
