### ISSUE TITLE
Atomic + Durable wallet (as seen by user)

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1469]
This mostly pertains to user actions. If the user creates a transaction, the wallet should remember. Durable is technically a lie because there's no guarantee that a transaction hits the blockchain, but the wallet should have reasonable bounds on how long it will try, and should clearly report to a user when a transaction has been determined a failure.

**Comment by lukechampine** [comment]
what does "Atomic" mean in the context of the wallet? Atomic means a set of actions either happen entirely or not at all. So either a transaction makes it onto the chain, or not at all. That part is easy. It's harder if you have to chain multiple transactions together (I think?). You need to ensure that all the transactions make it, not just a few of them.
