### ISSUE TITLE
Consider encrypting + signing all gateway messages

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1482]
This would require giving gateways a public key.

Encryption was previously considered unnecessary because all the data being passed around is supposed to be public anyway, but it turns out that you can hijack an in-process communication in ways that enable various nefarious activities. There are reports of Bitcoin miners losing significant amounts of money to these attacks.

So maybe we should be encrypting the messages.

**Comment by lukechampine** [comment]
Are there examples of this that you can link? I'm curious what the actual attack looks like.

How would the public keys be distributed? As part of the initial connection handshake, or included in shared address lists, or both, or neither?

**Comment by DavidVorick** [comment]
Supposedly this is an issue caused by putting the tarfile inside a directory that's being tarred. I'm putting it in the dom0 homedir.

Makes sense, Qubes should provide a warning, clearly a lot of people are running into this.

**Comment by lukechampine** [comment]
I think you posted this on the wrong issue

**Comment by DavidVorick** [comment]
ah man this is why you don't post while you're still sleeping. I was wondering why that comment didn't make it into the qubes issue.

I wonder how many times I've done this?

**Comment by DavidVorick** [comment]
re: examples

http://bgpmon.net/the-canadian-bitcoin-hijack/

https://arxiv.org/pdf/1605.07524v1.pdf

Somewhere it's mentioned that authenticated communication between nodes would have prevented this.

**Comment by lukechampine** [comment]
I think this is off the table for the time being
