### ISSUE TITLE
Take another look at gateway peer policy

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1483]
Protection against things like eclipse attacks requires having a robust set of peers. Ideally, you'd be connected to as many peers as possible so that it's very difficult for an attacker to prevent you from hearing about blocks. But connecting to lots of peers has a big impact on performance.

Various research papers have proposed alternative strategies for bucketing and anchoring peers in ways that provide better protection against potential attackers. We should take another look at implementing some of those into our gateway.

**Comment by lukechampine** [comment]
Closing as this is too long-term to attempt in the near future
