### ISSUE TITLE
Duplicate nicknames

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#150]
This isn't a big deal, but we probably want to protect people from accidentally overwriting files, i.e. `e.renter.Files[nickname]` already exists. I'm not sure what the best way to do this is. We could make `ClientProposeContract` throw an error, but then you can't overwrite at all. Maybe a client-side warning would be better. Do we have a process in place for deleting files/early termination of contracts? My feeling is that the proper interaction is:
- "That nickname is already in use. Overwrite? (Y/N)"
- If Y: create the new contract and call Delete() on the old contract
- If N: cancel

We may also want to do away with nicknames entirely. Most cloud storage applications don't use them, preferring instead to just use the original filename.

**Comment by DavidVorick** [comment]
There's nothing wrong with the backend supporting nicknames and the frontend ignoring that fact.

You can't overwrite nicknames on the backend, because you can't delete things. We can add some functionality to rename stuff though.
