### ISSUE TITLE
Make the web interface one "page"

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#151]
i.e. the only the focused section is shown, the rest is hidden/cached. So instead of having `/mine.html`, you have `#mine`. This would let us share state between pages, like the `stats` variable. I think the overall design would be cleaner.

**Comment by DavidVorick** [comment]
seveibar what are your thoughts on this?

**Comment by seveibar** [comment]
I personally prefer single page web applications because the UI has the opportunity to kind of "flow" and kind of give the feel of a desktop application.

As Luke mentioned we could essentially have different URLs by using anchor tags (#mine, #files etc.)
