### ISSUE TITLE
Better cpu miner

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#153]
The miner should stop (nearly) immediately when given the StopMining signal, instead of churning through potentially 10 million additional nonces.

**Comment by DavidVorick** [comment]
I might rewrite the miner to simplify it as much as possible, even at the cost of efficiency. I expect most people to be GPU mining anyway.

**Comment by lukechampine** [comment]
I agree with that decision. I think optimizing our CPU miner would be mostly wasted effort. At the same time, I stand by my reasoning in #325 that the GPU mining code should live outside the main repo.

**Comment by DavidVorick** [comment]
I'm defining 'better cpu miner' as 'easy to understand, but not necessarily efficient'

also, probably not multithreaded anymore. That's up in the air. Or maybe it pulls all cores by default. Idk.

**Comment by DavidVorick** [comment]
Our cpu miner has withstood the test of time. It will be a pain to replace it and be sure that it's as battle hardened as the existing one.
