### ISSUE TITLE
Port from NebulousLabs/ed25519 to golang.org/x/crypto

### ISSUE THREAD

**Issue by anonymous09** [NebulousLabs/Sia#1544]
I think golang.org/x/crypto will be better choice because it is more general, widely used and standard solution.

Also, will be easily maintaining packages in different GNU/Linux distributives.

**Comment by lukechampine** [comment]
I believe the crypto/x/ed25519 package did not exist when we started the project. If the functionality is identical, I see no reason not to switch. :+1:

**Comment by DavidVorick** [comment]
We should do the switch to the golang blake at the same time.
