### ISSUE TITLE
Renter shows >100% upload progress

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#1557]
sometimes sia is more than 100% done uploading files

**Comment by vevarm** [comment]
Sia is 103% done, that is great.
...
58.70 MB  Yes       *103.12%*        4.12  Yes       backup-20161019-filelist-0007.tar
...

**Comment by vevarm** [comment]
Seems this is very common. I have a script count completness ( for the purpose of upload status). 

x@nicke:~$ bash sia-count.sh 
     16     102.50%
     25     103.91%
     29     102.34%
     31     102.08%
     34     104.17%
     87     104.69%
     92     101.56%
    209     100.00%
    301     106.25%
    782     103.12%

**Comment by DavidVorick** [comment]
We are looking into the issue, among a couple of other issues that we are investigating.

Though, it's not a super high priority because having an extra 3-5% uploaded does not seem like a huge deal to me.

**Comment by vevarm** [comment]
agree 
not prio

**Comment by vevarm** [comment]
https://m.youtube.com/watch?v=hW008FcKr3Q

i just had to link it

**Comment by DavidVorick** [comment]
I have looked into this more, and what's happening is that Sia is replacing hosts that go offline. Basically, while uploading, some of the hosts have already disappeared, so you've had to replace them. The total uploaded counter does not decrease though. This I guess is a good way then to measure the total churn on your files.

106.25% = over the lifetime of the file 6.25% has disappeared, and you've had to repair it.

The redundancy is following something similar, though it's a less useful metric.

**Comment by vevarm** [comment]
Ok cool I find this value intressting, however ... 

This is totally unintuative for most, this needs to be presented in a way all will understand. But I have no idea how.

**Comment by tbenz9** [comment]
Recommendation to devs: label "Bug"

**Comment by avahowell** [comment]
Fixed in #2429
