### ISSUE TITLE
Does bolt need to be vendored?

### ISSUE THREAD

**Issue by freeekanayaka** [NebulousLabs/Sia#1565]
Hello,

first, thanks for this great work! I've been using version 1.0.3 for a while now and it's amazingly stable (upgrade to 1.0.4 in my TODO).

I'm packaging sia for Debian, see [bug 847706](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847706).

The fact that sia currently vendors some of its dependencies makes this job a bit harder, since some of the official non-vendored dependencies are already packaged for Debian, for example bolt, which is currently at version [1.3.0 in sid](https://packages.debian.org/source/sid/golang-github-boltdb-bolt).

It seems that [sia's fork of bolt](https://github.com/NebulousLabs/bolt/commits/master) is a plain copy of version 1.2.1. I compiled sia against 1.3.0 and it builds fine.

At first glance, bolt seems a well-maintained and dependable package. Would you consider dropping sia's vendored copy? Or at least try to keep that copy in sync with the latest upstream release.

Also, for my Debian packaging work, would you recommend against patching sia source code to compile against stock bolt 1.3.0? Or is it fine?

Thanks

**Comment by lukechampine** [comment]
Great to hear that Sia is finally making its way into a package manager! :)

We forked bolt a while back due to some instability issues. Those issues have since been resolved. I am in favor of dropping the vendor, but we'll wait for @DavidVorick's input.

Re: patching, I'm guessing you can do it pretty easily with a `sed` command that replaces imports of `NebulousLabs/bolt` with `boltdb/bolt`. The API is identical so you shouldn't run into any trouble. But I'd much prefer that we drop the vendor instead, or find some other way of handling the dependency that doesn't require processing the source code :P

**Comment by DavidVorick** [comment]
I am still against dropping the vendor for bolt. While bolt is more stable, it's consensus critical code and we really need to be immediately on top of any change which might fork the network. I don't want to do any upgrades that don't first run through our testing process. There's a really high danger factor here, which when combined with Bolt's previous history of instability, makes me think it's better to hold off.

**Comment by freeekanayaka** [comment]
Thanks for your reply David. I'll make sure to stick to the vendored version then. Hopefully that won't be questioned by other Debian developers and this doesn't become a blocker.

**Comment by lukechampine** [comment]
At the very least, we can pull the latest Bolt changes and test that it still performs IBD.

**Comment by DavidVorick** [comment]
We should do that anyway, I believe bolt has had both performance upgrades and bugfixes since we last upgraded.

@freeekanayaka please let us know if it does become a blocker, and we will work to a more debian-friendly solution.

**Comment by freeekanayaka** [comment]
Hi guys,

I didn't get complains about the sia-specific bolt 1.2.1 package that I uploaded and that duplicates the "stock" one. So I'm happy to report that sia is now in Debian:

https://packages.debian.org/sid/sia

I'll update it to 1.0.4 as time permits.

You might want to close this ticket and/or update your documentation to point to "apt install sia" as possible installation method.

Cheers

**Comment by DavidVorick** [comment]
That's very exciting, thanks for doing this for us.

**Comment by vevarm** [comment]
Yes very nice,can I somehow help to keep it up to date?

**Comment by freeekanayaka** [comment]
@vevarm yes, absolutely, that requires a bit of Debian packaging knowledge tho. Happy to provide pointers if you are interested.

**Comment by lukechampine** [comment]
Due to paranoia about upstream dependencies breaking, we're going to stick with the vendor until there is a standard Go dependency management tool.
