### ISSUE TITLE
Sia blog broke all its links

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1568]
It looks like you moved blogging platforms at some point and broke all your old links, including in the main Sia README:

```text
- [How to Become a Sia Host](http://blog.sia.tech/2016/05/26/how-to-run-a-host-on-sia)
- [Using the Sia API](http://blog.sia.tech/2016/10/20/api-quickstart-guide)
```

Is it possible to [add 301s](https://help.medium.com/hc/en-us/articles/213475208-Can-I-redirect-URLs-from-older-posts-from-my-site-) for the old URLs so you don't break all the sites that linked to your original post?

**Comment by DavidVorick** [comment]
We did the migration the way the link you provided suggested, but clearly the old links were not preserved. Maybe they didn't have Ghost compatibility? (Ghost is the platform we were using previously).

In the meantime, we'll keep playing whac-a-mole with the dead links. Thanks for pointing them out.

**Comment by mtlynch** [comment]
Is it possible for you to add HTTP redirects for the old URLs? Or are sites that linked to you just SOL?

**Comment by DavidVorick** [comment]
From what I can tell they are SOL, but I will look into it and see if there's something we can set up from the side of Cloudflare to get redirects working. I'm not sure if we have enough page rules remaining.
