### ISSUE TITLE
Erasure Coding

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#159]
Need to be able to split files up and store them in multiple places, and perhaps have some sort of file health indicator or whatever. Files need to go up and be healthy.

I don't currently know if the regenerating codes are finished/ready, so we should probably just use the longhair library again (if we can manage cross-compilation) or some slower library that has been written in go.

It's not a big deal to require the user to have the file to do repairs, especially since it's only a temporary requirement thanks to regenerating codes.

**Comment by Kroese** [comment]
On Usenet its very normal to use PAR2 files for this, so I am not sure if this should be in Sia itself, since it would be the same as adding automatic unzip-support to Sia, because it's an responsibility of the client to add PAR files (or not) for erasure codes, or use ZIP on their data or not.
