### ISSUE TITLE
ERROR: the renter is idle , but tracking active pieces: 8

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#1601]
goroutine 160 [running]:
runtime/debug.Stack(0x445727, 0x0, 0xc42d5ddc28)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42d5ddd80, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc423295f00, 0xc42d5ddd80, 0x2, 0x2)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc422068780, 0xc42d5ddf20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:312 +0x5be
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc422068780)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:576 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3ae
Critical error: ERROR: the renter is idle , but tracking active pieces: 8
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

**Comment by vevarm** [comment]
Duplicate to #1591 sorry.

**Comment by lukechampine** [comment]
Closing as duplicate, thanks!
