### ISSUE TITLE
Tab completion when using siac

### ISSUE THREAD

**Issue by RNabel** [NebulousLabs/Sia#1613]
It would be nice to be able to use tab completion when navigating the siac commands.

**Comment by DavidVorick** [comment]
This could be done by someone with no knowledge of Sia, as the existing help menus are quite thorough.

**Comment by lukechampine** [comment]
Looks like [cobra has built-in support for this](https://github.com/spf13/cobra/blob/dc208f4211e7f6df7ec8cb62640f57d3e154910d/bash_completions.md), so it should be really easy to add. Ideally we could even have tab completion for Sia filenames, though I'm not sure if it's possible to add completions at runtime.

**Comment by vevarm** [comment]
This one would be nice, yes.
