### ISSUE TITLE
Can't set the maxduration

### ISSUE THREAD

**Issue by lhirlimann** [NebulousLabs/Sia#1625]
I'm following : https://blog.sia.tech/how-to-run-a-host-on-sia-2159ebc4725

[root@poney Sia-v1.1.2-linux-amd64]# ./siac host config maxduration 15weeks
Host settings updated.
[root@poney Sia-v1.1.2-linux-amd64]# ./siac host -v
General Info:
	Estimated Competitive Price: Unavailable

Host Internal Settings:
	acceptingcontracts:   No
	maxduration:          0 Weeks
	maxdownloadbatchsize: 17.83 MB
	maxrevisebatchsize:   17.83 MB
	netaddress:           [2001:bc8:3364:200::]:9982 (automatically determined)
	windowsize:           24 Hours

	collateral:       100 SC / TB / Month
	collateralbudget: 10 KS 
	maxcollateral:    5 KS Per Contract

	mincontractprice:          20 SC
	mindownloadbandwidthprice: 250 SC / TB
	minstorageprice:           1.7 KS / TB / Month
	minuploadbandwidthprice:   10 SC / TB

Host Financials:
	Contract Count:               0
	Transaction Fee Compensation: 0 H
	Potential Fee Compensation:   0 H
	Transaction Fee Expenses:     0 H

	Storage Revenue:           0 H
	Potential Storage Revenue: 0 H

	Locked Collateral: 0 H
	Risked Collateral: 0 H
	Lost Collateral:   0 H

	Download Revenue:           0 H
	Potential Download Revenue: 0 H
	Upload Revenue :            0 H
	Potential Upload Revenue:   0 H

RPC Stats:
	Error Calls:        0
	Unrecognized Calls: 0
	Download Calls:     0
	Renew Calls:        0
	Revise Calls:       0
	Settings Calls:     0
	FormContract Calls: 0

[root@poney Sia-v1.1.2-linux-amd64]# ./siac version
Sia Client v1.1.2
Sia Daemon v1.1.2

**Comment by lukechampine** [comment]
`maxduration` is specified in blocks. You can see units for each config setting by running `siac help host config`. 1 week is about 1000 blocks, so in your example you'd want `siac host config maxduration 15000`.

**Comment by DavidVorick** [comment]
We should change the unit parsing inside siac. I actually have it on my to-do list for v120 already
