### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#163]
We need a way for users to automatically update. This would be especially helpful during closed/open beta: instead of publishing each new release and asking people to update, we could just push out an update and be confident that everyone saw it.

There's a service I saw a while ago called [Equinox](https://equinox.io), which might be our best bet, though I don't fully know how it works. The alternative would be to roll our own updater.

EDIT: Equinox is a paid service. It basically just provides servers for users to download from. The actually update library is called [go-update](https://github.com/inconshreveable/go-update). Incidentally, it looks like the binary patching algorithm used by go-update was designed by Colin Percival.

I wonder how Bitcoin handles updates. Having people download updates from (our) centralized servers seems reasonable for the beta, but after that we'll probably want something more decentralized. I can imagine nodes sharing updates (signed, of course) with their peers.

**Comment by lukechampine** [comment]
There are quite a few more features I'd like to implement before considering this "closed." I can just make new issues for them if that makes more sense though.

**Comment by DavidVorick** [comment]
I think that I would prefer that.

Having these large scope issues makes me uneasy, not because they're bad but just because it makes it seem like no progress is being made.
