### ISSUE TITLE
Host, upload use all disks

### ISSUE THREAD

**Issue by poiuty** [NebulousLabs/Sia#1645]
Add new disk.
```
Storage Folders:
    Used          Capacity     % Used    Path
    280.209 GB    5.0000 TB    5.60      /home/sia/storage
    0 B           5.0000 TB    0.00      /home/sia/storage2
```

A few days later.
```
Storage Folders:
    Used          Capacity     % Used    Path
    280.209 GB    5.0000 TB    5.60      /home/sia/storage
    21.454 GB     5.0000 TB    0.43      /home/sia/storage2
```

New files upload only to the second disk. Let's use all disks.

**Comment by DavidVorick** [comment]
This is intended. It'll load balance between the disks so that each has the same fill percent. This is to minimize the chance of a single disk failure wiping out everything.

**Comment by S-anasol** [comment]
@DavidVorick then theres another case

![image](https://cloud.githubusercontent.com/assets/1709666/24629061/60737f2c-18c0-11e7-903d-1d426176cc59.png)

since installing new HDD first one got 10+ GB of uploads, but new one still 0

I see one possible case - new uploaded files were uploaded via old contract, thats why it goes to first hdd.
Am i right?

**Comment by DavidVorick** [comment]
Hmm. I think it actually looks for the drive with the most free space and not the drive with the most free percentage. Which maybe is not the optimal way to do it, but would explain what you are seeing.

**Comment by S-anasol** [comment]
also found that i forgot change folder owner, so sia actually couldn't write to new folder :D
Fixed.
Will check new uploads distribution.

**Comment by DavidVorick** [comment]
Ok. I will re-open the issue if distribution is suboptimal

**Comment by DavidVorick** [comment]
Oh, but the whole everything changed in v1.2.0 so actually I will not, we will see if v1.2.0 has issues separately. I think it will not though

**Comment by S-anasol** [comment]
![image](https://cloud.githubusercontent.com/assets/1709666/24638373/81d2998e-18f0-11e7-875e-3347780f1fbb.png)
yeah probably were problem with write access to folder.
