### ISSUE TITLE
add consensus code for gateway hostname discovery

### ISSUE THREAD

**Issue by GlenDC** [NebulousLabs/Sia#1649]
> Gateway hostname discovery currently has significant centralization, namely the fallback is a single third-party website that can easily form any response it wants. Instead, multiple TLS-protected third party websites should be used, and the plurality answer should be accepted as the true hostname. - [Relevant TODO](https://github.com/NebulousLabs/Sia/blob/master/modules/gateway/gateway.go#L95-L99)

TLS-protected websites:

+ https://icanhazip.com (IPv6)
+ https://myexternalip.com/raw (IPv6)

Plain websites:

+ http://checkip.dyndns.org (requires extra parsing) (IPv4);
+ http://checkip.amazonaws.com (IPv4);

We probably need to find more websites. On top of that we'll also need to find a way to find consensus between IPv4 and IPv6 addresses. So probably the best idea is to convert all IPv4 addresses to IPv6 addresses. Although I'm not sure if this works for everyone, as there might be situations where only IPv4 is possible, so we'll need to figure this out as well.

**Comment by GlenDC** [comment]
I'm however not too sure how we can convert IPv4 correctly to IPv6.

For example icanhazip (`A`) returns IPv6, and amazonaws (`B`) returns IPv4. You can manually convert an IPv4 address to a IPv6 address, by zero-padding it. However, that is not the address that `A` returns.

@DavidVorick, @lukechampine: do you guys have any idea how we could convert the IPv4 address of `B` correctly, such that it equals to the result of `A`? Or is this impossible?

**Comment by GlenDC** [comment]
Implementation wise, I think we could add it as a submodule of the gateway module. We could implement each website as a `Source`:

```go
type Source interface {
    IP() modules.NetAddress // returns IPv4/IPv6 address
}
```

such that we could then have a `Voter` type:

```go
type Voter struct {
    source Source   // provides the IP (see: vote)
    weight int      // provides the weight of its vote (acts as a multiplier)
}
```

With all of this in place, we could easily have the 1 public method of this submodule:

```go
func GetExternalIP() modules.NetAddress {
     // 1. collect all votes in a `map[modules.NetAddress]int`,
     //    where each address is linked to its amount of votes.
     // 2. do a linear scan to find the most voted `modules.NetAddress`
     // 3. return the most voted `modules.NetAddress`
}
```

That's more or less the implementation I propose. Keeping all logic private to the submodule, except for this 1 function. As all our sources are simply websites accessed via a `GET` _HTTP_ call, we only need _one_ `Source` implementation, which also has an optional parser that converts a `raw` string into a `final` string. For some/most websites that will equal to an identity function, but for others it will require some actual work.

The only remaining open questions are:

+ How do we assign the weights to each voter? How do we know which website is more/equally/less thrust worthy then another?
+ How do we know when we should return an IPv4 and when to return an IPv6 address? Or will an environment which only supports IPv4, only ever return IPv4 addresses, and thus it is clear that we are limited to IPv4, if none of the returned addresses is IPv6?
+ How do we convert our IPv4 address to the actual returned IPv6 address. We know that zero-padding doesn't deliver the result we are seeking for, as that does not equal the IPv6 address returned by other sources. So while it is a valid method of converting an IPv4 address to an IPv6 address, it is not desired in our situation. We do however need a better method if we don't want to count 2 addresses as being different, simply because one source returns our address as IPv4, while another does it as IPv6. Or is it not important, and do we simply choose to count them as being different?
   + In my case for example, 2/4 of the website sources listed above give me the same IPv4 address, while the other 2/4 website sources listed above give me the same IPv6 address, making me thing that all 4 our correct, and thus completely agree with each other, which would only something that would be clear to our consensus algorithm, if we somehow can normalize all address to the same IPv6 address.

One choice that could eliminate the 2 last questions, could be to simply let this submodule not worry about the actual value of the NetAddresses in question, and thus know whether it is IPv4 or IPv6, and instead count every address in its original form, without 'normalizing' them, so  to speak.

**Comment by lukechampine** [comment]
I don't think it's super critical that the gateway's hostname be accurate anymore. IIRC it used to be more important because the gateway would send its address to other peers, but now the peers just call `conn.RemoteAddr`, so there's no trust involved.

Currently, the main motivation for learning the hostname is to avoid adding ourself as a peer. But the new handshake protocol will prevent that in a much more robust way. We also report the hostname to the user, which is useful if you want to manually connect some peers to each other. That's probably the main attack vector: if you can influence the hostname, you can make the user think your address is something it isn't. I'm not sure what sort of attacks this enables, though. @DavidVorick thoughts?

**Comment by GlenDC** [comment]
That makes sense I guess. Do we still need to check our address in fact, with the new handshake protocol, or would it make sense to remove that check?

**Comment by DavidVorick** [comment]
I left a comment on this but it looks like that comment got eaten.

The host needs to know it's own hostname, and I think any 'what's my hostname' code should be implemented as a library, not as code that gets thrown in the gateway or host (which is the way we are currently doing it). The gateway I don't think needs to know its own hostname at all, though it's possible that there's something important I'm forgetting.

I think it'd be fine though once we are able to identify ourselves by the nonce.

**Comment by lukechampine** [comment]
Closing for now since this isn't actionable
