### ISSUE TITLE
Critical error: Host entry scan history not sorted

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia#1650]
I updated to v1.2.0-RC1 on a Win10 box with 220GB of host data.

The update took around 10 hours and in the end there were ~300 4-MB-files left that were not converted.

In the log files i can see the following entries (one for each missed file update i guess):

**hostdb.log:** 2017/04/05 01:01:22.533382 hostweight.go:269: CRITICAL: Host entry scan history not sorted.

**wallet.log:** 2017/04/05 01:20:05.339523 update.go:297: ERROR: failed to apply consensus change: could not get historic output: could not decode type types.Currency: EOF

**siad-output.log:** goroutine 1 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc055d223f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc055d22570, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0a773cc00, 0xc055d22570, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc0a7ca5040, 0x0, 0x1100000, 0x3330, 0x1100000, 0x0, 0x0, 0xba43b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:269 +0x267
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc0a7ca5040, 0x0, 0x1100000, 0x3330, 0x1100000, 0x0, 0x0, 0xba43b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:323 +0x219
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x0, 0x1100000, 0x3330, 0x1100000, 0x0, 0x0, 0xba43b7400, 0x400000, 0xba43b7400, 0xe2869bd3e2b1e97e, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x66
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Insert(0xc0a773cc20, 0x0, 0x1100000, 0x3330, 0x1100000, 0x0, 0x0, 0xba43b7400, 0x400000, 0xba43b7400, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:214 +0xd6
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).load(0xc0a7ca5040, 0xc0a4323040, 0xc0a7c9d1d0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:65 +0x248
github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB(0xd8e160, 0xc04205cdc0, 0xd8ed00, 0xc042176000, 0xc0a7c9d110, 0x2f, 0xd8d340, 0xeb06c8, 0x1, 0xc0a7c9d110, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:111 +0x451
github.com/NebulousLabs/Sia/modules/renter/hostdb.New(0xd8e160, 0xc04205cdc0, 0xd8ed00, 0xc042176000, 0xc0a7c9d110, 0x2f, 0xc055d239c8, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:69 +0xbb
github.com/NebulousLabs/Sia/modules/renter.New(0xd8e160, 0xc04205cdc0, 0xd8ed00, 0xc042176000, 0xd902c0, 0xc04205d4a0, 0xd8db20, 0xc04200d200, 0xc0a7c9d110, 0x2f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:157 +0x88
main.startDaemon(0x0, 0x0, 0xc04200266b, 0xe, 0xc0420026ab, 0x5, 0xc04200268c, 0x5, 0x0, 0xc0420026ca, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:250 +0xcbc
main.startDaemonCmd(0xc042063200, 0xc0420132c0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x74
github.com/spf13/cobra.(*Command).execute(0xc042063200, 0xc042034070, 0x5, 0x5, 0xc042063200, 0xc042034070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x238
github.com/spf13/cobra.(*Command).ExecuteC(0xc042063200, 0xac0e29, 0x3b, 0xc042122b40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc042063200, 0xe93840, 0xaaa1cf)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7b3
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

**Comment by betaboot** [comment]
What i just realized: The files that were not converted all start with 'z...', so those were the very last ones that should have been converted. My host is 100% full, could this be the issue? Maybe space for the big new file is allocated but then not all 4MB files fit into it?

**Comment by DavidVorick** [comment]
This could be a coincidence if the above errors all happened in a row.

**Comment by DavidVorick** [comment]
None of these entries would have caused the host upgrade to hiccup. Perhaps you ran out of storage space on your drive? Though, the upgrade is supposed to protect against running out of storage space.

There may have also been disk hiccups, though it seems like nothing got logged in your host.log.

**Comment by betaboot** [comment]
Don't know about those messages but i think i know now why some 4MB-pieces were left over after the conversion. My host folders are full. So i have for example a host folder with 65GB allocated. Before v1.2.0 i remember that the UI showed 65GB, now after the upgrade it shows 64GB (64.961GB to be exact).
So my guess is that with v1.2.0 the host folders got resized a bit and not all 4MB-pieces found space during the conversion. That would only be a problem for full hosts i guess.

**Comment by betaboot** [comment]
There are 7 of those messages in the host.log

2017/04/04 13:00:12.536427 persist_compat_1.2.0.go:184: Unable to read a sector from the legacy storage manager during host upgrade: open C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\storagemanager\6505d037\0QuwhCwaImDo4Mh8: The system cannot find the file specified.

2017/04/04 13:00:12.537415 persist_compat_1.2.0.go:190: unable to remove sector from the legacy storage manager, be sure to remove manually: remove C:\Users\Cube\AppData\Roaming\Sia-UI\sia\host\storagemanager\6505d037\0QuwhCwaImDo4Mh8: The system cannot find the file specified.
