### ISSUE TITLE
Critical error: negative currency not allowed

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia#1653]
v1.2.0-RC1, Win10: Now i got tons of those messages:

goroutine 144388 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc047135160)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc047135208, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/types.Currency.Sub(0xc0463a3a00, 0x0, 0x0, 0x0, 0x1410900, 0xc044c99d40, 0x2, 0x6, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:183 +0x164
github.com/NebulousLabs/Sia/modules/wallet.(*Wallet).ConfirmedBalance.func2(0xcb9d9d2803ebe4c0, 0x4bf7b5b04229e57a, 0x25e32b40568bf2d8, 0xedf41d2d87c6255, 0x0, 0xc044c99d10, 0x1, 0x5, 0xf6e46cf53aecadf0, 0x1eac9cb037051e2a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/money.go:30 +0x13b
reflect.Value.call(0x9d1dc0, 0xc042b92200, 0x13, 0xa9361a, 0x4, 0xc047135798, 0x2, 0x2, 0x0, 0xc042b92760, ...)
	/usr/local/go/src/reflect/value.go:434 +0x926
reflect.Value.Call(0x9d1dc0, 0xc042b92200, 0x13, 0xc047135798, 0x2, 0x2, 0x0, 0xc047135778, 0x72843d)
	/usr/local/go/src/reflect/value.go:302 +0xab
github.com/NebulousLabs/Sia/modules/wallet.dbForEach.func1(0x156452b6, 0x20, 0x20, 0x156452d6, 0x3e, 0x3e, 0x3e, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/database.go:140 +0x326
github.com/NebulousLabs/bolt.(*Bucket).ForEach(0xc044b2cb40, 0xc0471358c8, 0x9d1dc0, 0xc042b92200)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:390 +0x106
github.com/NebulousLabs/Sia/modules/wallet.dbForEach(0xc044b2cb40, 0x9d1dc0, 0xc042b92200, 0x14, 0xc044b2cb40)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/database.go:142 +0x212
github.com/NebulousLabs/Sia/modules/wallet.dbForEachSiafundOutput(0xc042c43340, 0xc042b92200, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/database.go:188 +0x7e
github.com/NebulousLabs/Sia/modules/wallet.(*Wallet).ConfirmedBalance(0xc04206b4a0, 0xc0420f4500, 0x0, 0x0, 0x0, 0xffffffffffffff00, 0x0, 0x0, 0x0, 0xc0420f4600, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/wallet/money.go:31 +0x29b
github.com/NebulousLabs/Sia/api.(*API).walletHandler(0xc0426aaab0, 0xd8a8a0, 0xc04215c700, 0xc04325b600, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/wallet.go:114 +0x53
github.com/NebulousLabs/Sia/api.(*API).(github.com/NebulousLabs/Sia/api.walletHandler)-fm(0xd8a8a0, 0xc04215c700, 0xc04325b600, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:241 +0x6d
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0432e9180, 0xd8a8a0, 0xc04215c700, 0xc04325b600)
	/home/luke/go/src/github.com/julienschmidt/httprouter/router.go:344 +0x81a
github.com/NebulousLabs/Sia/api.RequireUserAgent.func1(0xd8a8a0, 0xc04215c700, 0xc04325b600)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:98 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc0431576e0, 0xd8a8a0, 0xc04215c700, 0xc04325b600)
	/usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/NebulousLabs/Sia/api.(*API).ServeHTTP(0xc0426aaab0, 0xd8a8a0, 0xc04215c700, 0xc04325b600)
	/home/luke/go/src/github.com/NebulousLabs/Sia/api/api.go:138 +0x5f
net/http.(*ServeMux).ServeHTTP(0xc0420f1560, 0xd8a8a0, 0xc04215c700, 0xc04325b600)
	/usr/local/go/src/net/http/server.go:2238 +0x137
net/http.serverHandler.ServeHTTP(0xc04208cc60, 0xd8a8a0, 0xc04215c700, 0xc04325b600)
	/usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc042aaef00, 0xd8b220, 0xc04508b8c0)
	/usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2d5
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

**Comment by lukechampine** [comment]
I believe this is just another symptom of the other issue you reported (#1650). The wallet tried to process a block but failed partway through, which lead to the siafund pool being incorrect. After I track down why it failed to process the block, I will try to mitigate these failures by adding code to continue processing blocks even if part of the processing fails.
