### ISSUE TITLE
Host Storage Folders are reordering

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia#1668]
v1.2.0-RC1, Win 10
If you have more than one host storage folders configured you will see that they are changing their order in the list all the time (every couple of seconds). That is really disturbing to look at in the UI as well.

![1](https://cloud.githubusercontent.com/assets/20227362/24800479/9e880714-1ba0-11e7-97d0-949448e2cc5e.PNG)

and a couple of seconds later...

![2](https://cloud.githubusercontent.com/assets/20227362/24800488/a509438c-1ba0-11e7-85fe-3b5e46a7c868.PNG)

**Comment by DavidVorick** [comment]
They get returned from a map I think. So siac should probably sort by name
