### ISSUE TITLE
factor of 64 sectors

### ISSUE THREAD

**Issue by S-anasol** [NebulousLabs/Sia#1671]
error **Could not add folder: storage folder must be a factor of 64 sectors**
really annoying.

**folder add** doesn't accept any size, except exact byte size sectorSize*64
and then **folder resize** accept any size...

![image](https://cloud.githubusercontent.com/assets/1709666/24825655/75619176-1c2b-11e7-8683-027ce43bc272.png)

**Comment by lukechampine** [comment]
I just pushed a fix for this in #1670. Once it's merged, the size will be rounded down to the nearest multiple of 64 sectors.
