### ISSUE TITLE
error "synchronize.go:554: WARN: disconnecting from peer 192.168.30.233:9981 because IBD failed: Stream reset by peer with error 4"

### ISSUE THREAD

**Issue by woodking1521** [NebulousLabs/Sia#1673]
when i build a sia testnet, i got this error,i dont know where is wrong.

**Comment by DavidVorick** [comment]
My guess is that you are connecting to the peers on mainnet, because right now the peer handshake has no way of detecting if you are talking to someone on the same network. There's a PR open right now to fix this (#1641), should be merged in 1-2 weeks.

**Comment by lukechampine** [comment]
closing since we have switched to smux
