### ISSUE TITLE
storatge in host/storagemanager

### ISSUE THREAD

**Issue by tlightsky** [NebulousLabs/Sia#1676]
I have a "Add Storage Folder",which all 40GB host data should be there.
But only 7.52GB found,other 29.9GB in host/storagemanager I think.
And add all that up would not make a 40GB,that's confusing.

**Comment by lukechampine** [comment]
Can you clarify the problem? What did you do, what was the expected outcome, and what actually happened?

**Comment by tlightsky** [comment]
that's the case long ago, haven't seen it in any new version
