### ISSUE TITLE
When Uploading, I experienced a crash

### ISSUE THREAD

**Issue by gwar11d2** [NebulousLabs/Sia#1683]
Loading...
(0/7) Loading siad...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 32.5733132 seconds
goroutine 952 [running]:
runtime/debug.Stack(0x44433e, 0x0, 0xc042475c28)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc042475d80, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc0427f4100, 0xc042475d80, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc0428ef440, 0xc042475f20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320 +0x5c5
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc0428ef440)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585 +0x385
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3b5
Critical error: ERROR: the renter is idle , but tracking active pieces: 2
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 34 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc042469a68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc042469bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0421f9160, 0xc042469bf0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04205a668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:108 +0x73b
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04205a668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:146 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04205a668, 0xc0421aade0, 0xc0421aae40)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:269 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:216 +0x103
Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\Brian\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal_temp C:\Users\Brian\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.wal: Access is denied.
panic: unable to copy-on-write the WAL temporary file, crashing to prevent data corruption

goroutine 34 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc04205a668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:109 +0x78b
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc04205a668)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:146 +0x47
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc04205a668, 0xc0421aade0, 0xc0421aae40)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:269 +0x149
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:216 +0x103

**Comment by DavidVorick** [comment]
This is actually the same error as #1651, should be fixed in the master branch. (RC3, which also has the fix, will be released in the next few hours).

**Comment by gwar11d2** [comment]
Sweet.  Thanks David

**Comment by lukechampine** [comment]
should be fixed in v1.3.0
