### ISSUE TITLE
Provide snap package

### ISSUE THREAD

**Issue by oparoz** [NebulousLabs/Sia#1684]
Snaps are packages which work very well on IoT devices. Would be great to have Sia available as a snap.

https://snapcraft.io/create/

**Comment by lukechampine** [comment]
added in https://github.com/NebulousLabs/Sia/pull/1940

**Comment by elopio** [comment]
Hello!

I've just seen that the packaging was removed from the repo in https://github.com/NebulousLabs/Sia/commit/efee1b1afa5d5f0645232445006a91d20d7d1658

I'm wondering why. We have just seen an amazing increase in the download stats with the releases of spotify, slack and skype into the store. I'm particularly interested in getting more decentralized apps in there, and I looking at how [parity is doing](https://github.com/paritytech/parity#install-from-the-snap-store) it seems to me that it will also be a nice bump in users and testers for you. If there's something I can do to help you releasing, just let me know.

**Comment by tbenz9** [comment]
@DavidVorick could you explain your reasoning for removing the snap?
