### ISSUE TITLE
too much time and ram to open

### ISSUE THREAD

**Issue by paolomeraviglia** [NebulousLabs/Sia#1693]
Hi, I'm testing sia on a LXC environment with hdd storage. Isolating siad / siac, I see that after consensus / transaction / host sync, to unlock a wallet the host needs at least 3 GB ram, and too much time to open (near 25 mins in ram or, if swapping 2 of 3 gigs, near 6 hours). Is there a way to use it without waiting all this time and without using 3 gb of ram?

**Comment by DavidVorick** [comment]
Using v1.1.2?

We have a release coming out tomorrow that fixes this. It's already fixed in the master branch, just putting on the final round of testing. As long as that goes well, we'll be releasing tomorrow. :) 

Requirements will drop to around 1.5 GB of RAM, unlock time will be a few seconds.

**Comment by DavidVorick** [comment]
Released
