### ISSUE TITLE
Connectability Status: not connectable

### ISSUE THREAD

**Issue by DcyMatrix** [NebulousLabs/Sia#1704]
I am running siad v1.2.0 and getting the following problem after some minutes of checking

via: siac host -v
_Connectability Status: not connectable_
_Working Status: working_

I am sure the ports 9981 & 9982 are open in both my router and the ufw firewall on my Ubuntu server 16.04LTS
Tested it with canyouseeme.org, and it see the services on both ports.
I also checked that the router is using NAT loopback/reflection on the right interfaces in my LAN.

Is it a problem I have the status of "not connectable"?
any chance it might not be correct in what it says?
(I have gotten some contracts, and some 14GB data attached to them)

**Comment by DavidVorick** [comment]
If it says 'working', that probably means that the 'connectability status' check can sometimes return false negatives. You aren't the only user experiencing this.

If you are getting file contracts then everything is definitely working. We'll look at the connectability status code and see if there's something we missed. (Maybe the check doesn't work behind certain types of firewalls or something).

**Comment by johnathanhowell** [comment]
Just to make sure, did you test that the ports areopen on your host's `NetAddress:9982`, not just your firewall's address at port 9982? It's possible, though unlikely, that your host's netaddress is different than your firewall's address and the connectability check uses your `NetAddress`.

**Comment by DcyMatrix** [comment]
@DavidVorick Thanks for the reply, still getting contracts. So I will assume it to be a false negative.

@johnathanhowell It was tested with the router's wan IP, I used the service [www.canyouseeme.org](www.canyouseeme.org) and it confirmed that both ports were indeed opened, and that the services on both ports were there. Also the IP address the command "siac host -v" returns include my external wan ip of the router not the local IP of the server :-)
