### ISSUE TITLE
Peer culling

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#171]
Peers currently stick around forever after they are added. There should be some set of conditions that, once satisfied, make a peer eligible for culling. A naive example would be to remove any peer that does not respond to a broadcast.

The issue here is that unresponsive peers are being shared with bootstrappers, who then waste a lot of time pinging dead addresses.

Depending on how frequently we intend to perform culling, the algorithm should be reasonably efficient.

**Comment by DavidVorick** [comment]
how is this different from #84, and is there progress?

**Comment by lukechampine** [comment]
As of now, peers are never removed automatically. They are only removed if `RemovePeer` is called explicitly. It will be difficult to confidently remove peers until we can accurately assess their behavior; this will come with the networking tweaks I've been formulating.

#84 seems a bit more general, but the bootstrapping protocol you described there has already been implemented (except for asking for new peers on a timer).

**Comment by DavidVorick** [comment]
Hmm. Maybe we could have a week delay or something for removing peers?
