### ISSUE TITLE
After restarting Sia, consensus believes it is not sync'ed

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1714]
If I do `siac stop` then restart siad, it doesn't believe that it's sync'ed even if its height matches the public blockchain height. It seems to figure it out after a minute or so:

![image](https://cloud.githubusercontent.com/assets/7783288/25073723/3c4b0d28-22ba-11e7-8483-b084874a6c6f.png)

**Comment by DavidVorick** [comment]
Not an error.

The consensus package will only believe that it is synced if:

+ it has more than 5 outbound peers that say it is synced
+ OR all outbound peers say it is synced and also it's been more than 10 minutes (might be 15 or something)

Basically, it won't report as synced until you have at least 5 outbound peers. This makes it harder for an attacker to convince you that you are synced when you are not.

**Comment by lukechampine** [comment]
I will grant that this is kind of unfortunate. For some setups, it means you're barred from doing certain actions (forming contracts, sweeping seeds) for 10 minutes after startup. It would be nice if we could find a way to safely reduce that number.

**Comment by DavidVorick** [comment]
We could add a command line flag or a gateway configuration that allows it to be happy after just 1 sync'd connection?

**Comment by DavidVorick** [comment]
Most setups that can't get to 5 are unable to get to 5 simply because their network config means they will only ever have.
