### ISSUE TITLE
siac host output should warn if wallet is locked

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#1715]
Can the output of `siac host -v` warn the user if they're accepting contracts but their wallet is locked? Currently, it prints out this:

```
$ siac host -v
General Info:
        Estimated Competitive Price: 8.728 KS

Host Internal Settings:
        acceptingcontracts:   Yes
```

This is misleading because if the host's wallet is locked, they're not really accepting contracts.

**Comment by DavidVorick** [comment]
Yeah. In general I think Sia doesn't have enough warnings if the user is shooting themselves in the foot.

If your wallet is locked the renter can't replace dud hosts.

If your wallet is locked the host can't form new contracts.

You host may be set to 'acceptingcontracts: No' but you don't want it that way (maybe some misconfiguration happened or something),

etc.

We should be able to flag the user's attention if they are doing something that seems undesirable.
