### ISSUE TITLE
x-compiled 1.2.0 linux arm fastrand panic

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#1718]
Crosscompiled for linux arm runing on rasbpi B model arm v6 cpu. 

pi@ronny ~/linux_arm $ ./siad version ; ./siad
Sia Daemon v1.2.0
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
panic: fastrand: argument to Intn is <= 0

goroutine 46 [running]:
github.com/NebulousLabs/fastrand.Intn(0xef798000, 0x10c39a0c)
	/home/bjdo/go/src/github.com/NebulousLabs/fastrand/fastrand.go:127 +0x174
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedScan(0x10cb4b60)
	/home/bjdo/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:335 +0x53c
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
	/home/bjdo/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:180 +0x630

**Comment by lukechampine** [comment]
since you are able to compile+run, can you insert a statement that shows what the argument to `Intn` is? Curious if it's `0` or `1` or something more suspicious (like an overflow).

Also, can you paste the syntax you use to do the cross compilation?

**Comment by DavidVorick** [comment]
we should probably have the panic report the received value

**Comment by DavidVorick** [comment]
Looks to me like an overflow. The time.Duration values being used overflow a 32bit integer, so the fastrand library overflowed and got a negative number.

**Comment by lukechampine** [comment]
yup, that seems accurate to me. So we either use `fastrand.BigIntn`, or we add a `fastrand.Uint64n` function?

**Comment by vevarm** [comment]
I registered this one on request from taek. Since sia requires 64bit to allow for mmap of large data, limiting the lib to require 64bit arithmetrrics is no limit to sia until the mmap is changed. Just saying. 

It was compiled by setting env vars GOOS=linux GOARCH=arm then calling your makefile.

**Comment by lukechampine** [comment]
Ah, that is a good point. Officially we only support 64-bit. Still, it's best to keep the code as flexible as possible in the event that we do support 32-bit someday.

**Comment by vevarm** [comment]
I write it again regarding emulation since this was an edit. Dont the compiler emulate 64bit if needed. Seems stupid not to, no?

**Comment by vevarm** [comment]
Like c compilers emulate float on non float cpus ( long time ago)

**Comment by lukechampine** [comment]
Go can perform 64-bit arithmetic on 32-bit machines, yes. However, in this case we are explicitly casting a 64-bit type to an `int`, and the size of `int` depends on the architecture. And of course `mmap` is limited by the 32-bit address space.

**Comment by vevarm** [comment]
So if this fastrand lib explicitly use 64ints allover there is no problem in the libary. It will always work. (but the calling code of this lib need to be careful about the downcast which is likely needed )

**Comment by DavidVorick** [comment]
We've fixed the problem.
