### ISSUE TITLE
Host parameters are too low level

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#1722]
I'm confused by all parameters of a host. Can you make a tool that takes storage size and available bandwidth (upstream and downstream) and infers all the parameters by solving an optimization problem about maximizing profits?

**Comment by DavidVorick** [comment]
It's on the todo list. We're more worried about enabling renters to actually delete their local files and recover from old backups at the moment though.

**Comment by lukechampine** [comment]
Closing this for now since it's a long-term issue and we're well aware of it internally
