### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by stricq** [NebulousLabs/Sia#1730]
OS: Windows Server 2012 R2

This is a first run of the daemon after copying the files out of the zip to a new directory.  This does not happen on Windows 10 only on Server 2012 R2.

siad v1.2.0 and v1.2.1

E:\Sia\Sia Daemon>siad -M gc
Loading...
(0/2) Loading siad...
(1/2) Loading gateway...
(2/2) Loading consensus...
Finished loading in 0.0350005 seconds
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x71fbde]

goroutine 15 [running]:
github.com/NebulousLabs/bolt.(*Bucket).Get(0x0, 0xd4b610, 0xb, 0xb, 0x0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:268 +0x3e
github.com/NebulousLabs/Sia/modules/consensus.blockHeight(0xc04217c0e0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:125 +0xad
github.com/NebulousLabs/Sia/modules/consensus.blockHistory(0xc04217c0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ..
.)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:72 +0x65
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks.func2(0xc04217c0e0, 0xaa2780, 0xc0421
7c0e0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:139 +0x52
github.com/NebulousLabs/bolt.(*DB).View(0xc0420e0780, 0xc0422c7b88, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/bolt/db.go:626 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042117b80, 0xd57c60, 0xc042433d40,
 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:141 +0x25e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedRece
iveBlocks)-fm(0xd57c60, 0xc042433d40, 0x9d4da0, 0xc042193d70)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:355 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04205adc0, 0xc04212c470, 0x10, 0xa782be, 0xa, 0xc04
2193d40, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:57 +0x266
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04205adc0, 0xc04212c470, 0x10, 0xa782be, 0xa, 0xc042193d40
, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:67 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042117b80, 0xc0
422c7ee8, 0xc0422c7ea8, 0xc0422c7eb0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:540 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042117b80, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:566 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04225ba10, 0xc042117b80, 0xd57f60, 0xc04205adc0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:140 +0x4e0
created by github.com/NebulousLabs/Sia/modules/consensus.New
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:173 +0x641

**Comment by lukechampine** [comment]
closing for now. Please reopen if this can be reproduced on v1.3.0
