### ISSUE TITLE
Setting mining address

### ISSUE THREAD

**Issue by miningpoolhub** [NebulousLabs/Sia#1743]
I see that sia wallet creates new address for mining endlessly.
I would like to set fixed mining address at wallet launch.
This is mandatory thing to accomplish if I try to run two mining server.

Can you please implement it?

**Comment by miningpoolhub** [comment]
Any idea??

**Comment by S-anasol** [comment]
you can use any of prev. addresses, it work always.

There is no option to set address. It generates automatically.

**Comment by tbenz9** [comment]
Version 1.3.1 is going to reuse the same address until you explicitly request a new one.  I'm going to recommend they close this issue since I think it's already implemented, just waiting for the release.

Recommendation to devs: close.
