### ISSUE TITLE
v1.2.1 download failed: insufficient hosts to recover file

### ISSUE THREAD

**Issue by tlightsky** [NebulousLabs/Sia#1760]
![image](https://cloud.githubusercontent.com/assets/429211/25650016/91801bb2-300c-11e7-9d88-d56ed6471832.png)

a lot file give me this hint when download, even those redundency reaches 4

**Comment by lasat** [comment]
Same error as on my headless server: https://forum.sia.tech/topic/959/after-upgrade-to-1-2-1-all-file-downloads-fail

**Comment by tlightsky** [comment]
@lasat 
my allowance also confuse me:
![image](https://cloud.githubusercontent.com/assets/429211/25651437/a783fe66-3015-11e7-81aa-9919e3056ad8.png)

**Comment by tlightsky** [comment]
after upgrade to 1.2.2, still meet this problem,
can't download file that uploaded(even repair file locally exist)
@DavidVorick

**Comment by nitronick600** [comment]
I'm also seeing this problem.

**Comment by lukechampine** [comment]
this error means you have lost too much redundancy. If the file is present locally, it should repair itself and eventually be available for download again.

Please reopen if this is reproducible in v1.3.0
