### ISSUE TITLE
Siad has exited unexpectedly 

### ISSUE THREAD

**Issue by Chehands** [NebulousLabs/Sia#1761]
![screen shot 2017-05-03 at 08 06 50](https://cloud.githubusercontent.com/assets/16878637/25650857/9f95446e-2fd7-11e7-8046-96c4637dd8c8.png)

**Comment by DavidVorick** [comment]
@johnathanhowell do you have ideas why it would say that Sia has existed unexpectedly without dropping an error?

I guess it's actually the file handle limit thing, I think these reports are only coming from Mac users.

@Chehands if it is the file handle limit thing, we've already got a fix ready that we'll be pushing out in v1.2.2.

**Comment by johnathanhowell** [comment]
Another process killing `siad` would cause this, the file handle thing would have turned up a `panic: too many open files`.

**Comment by Chehands** [comment]
I'll try again, i had a slightly different error before, lets see if that one comes up.
