### ISSUE TITLE
Balance missing

### ISSUE THREAD

**Issue by mhingston** [NebulousLabs/Sia#1766]
Hi,

I'm running Sia-v1.2.1-linux-amd64

siad is running as follows `siad -M gctwh`

I have deposited some SC to my wallet address (see [here](https://explore.sia.tech/hash.html?hash=ffd62b1448f9c2b7e595d4e54d0e563d2fb5cbd5f9b9baea6a780472fe33b653c8b013abed42)) but it isn't being picked up by `siac`

    $ siac wallet addresses
    5628a19cbe6a2a87e765efbd300128745114084bdb3e2810b4805dda744fc6e7953062732b55
    ffd62b1448f9c2b7e595d4e54d0e563d2fb5cbd5f9b9baea6a780472fe33b653c8b013abed42

    $ siac wallet balance
    Wallet status:
    Encrypted, Unlocked
    Confirmed Balance:   0 H
    Unconfirmed Delta:  +0 H
    Exact:               0 H
    Siafunds:            0 SF
    Siafund Claims:      0 H

I have tried restarting `siad` and unlocking my wallet again but it still shows 0, any ideas?

**Comment by johnathanhowell** [comment]
are you fully synced?

**Comment by mhingston** [comment]
siac consensus
    Synced: No
    Height: 53099
    Progress (estimated): 51.4%

That'll be why, thanks!
