### ISSUE TITLE
0 data contracts & malicious hosts

### ISSUE THREAD

**Issue by dim-geo** [NebulousLabs/Sia#1772]
`siac renter contracts`
prints that many hosts do not have data from me, although I have spent some fees for them.
When the contract expires will these coins return to me?

In other words, can malicious hosts form contracts and fetch money without providing any data storage (no uploading)?
What about those that have only one piece of my files?
Sia version 1.2.1, contracts created all on 1.2.1

```
Contracts:
Host                         Remaining Funds  Spent Funds  Spent Fees  Data       End Height
sia.fck.world:9982           158.1 SC              0 H     39.96 SC    0 B        115492    
209.11.180.182:9982            158 SC          76.8 mS     55.72 SC    4.19 MB    115492    
82.18.46.32:9982               158 SC          76.8 mS     52.51 SC    4.19 MB    115492    
sundown.servebeer.com:9982   131.7 SC         63.67 mS     30.34 SC    4.19 MB    115492    
siacoinvienna.ddns.net:9982  105.4 SC              0 H     27.67 SC    0 B        115492    
216.75.121.9:9982             92.2 SC              0 H     27.14 SC    0 B        115492    
64.31.31.106:9982            79.03 SC              0 H     37.54 SC    0 B        115492    
williamscloud.de:9988         73.4 SC         5.623 SC      28.2 SC    608.17 MB  115492    
75.82.191.146:9982           52.69 SC              0 H     26.07 SC    0 B        115492    
sia.cwnage.net:9982          52.68 SC              0 H     27.14 SC    0 B        115492    
sia.fifthgrid.com:9982       52.66 SC         25.88 mS     27.14 SC    4.19 MB    115492    
163.172.209.161:9982         52.66 SC         25.68 mS     11.53 SC    4.19 MB    115492    
chemsorly.selfhost.eu:9982   52.66 SC          26.5 mS     15.66 SC    4.19 MB    115492    
85.195.246.182:9982          52.66 SC         25.49 mS     26.07 SC    4.19 MB    115492    
sia.acbilibilifun.cc:9982    49.09 SC         3.585 SC     10.46 SC    608.17 MB  115492    
37.97.42.134:9982            48.05 SC         23.37 mS     26.95 SC    4.19 MB    115492    
52.169.11.109:9982           46.07 SC         22.32 mS     25.26 SC    4.19 MB    115492    
181.188.77.33:9982            39.5 SC         19.13 mS        25 SC    4.19 MB    115492    
24.59.60.93:9982             39.49 SC         19.13 mS     24.57 SC    4.19 MB    115492    
sia.backupfarm.com:9982       36.8 SC         2.719 SC      26.6 SC    603.98 MB  115492    
62.210.93.142:9982           26.34 SC              0 H     13.66 SC    0 B        115492    
217.65.8.75:9982             26.34 SC              0 H      35.4 SC    0 B        115492    
sanasol.sknt.ru:9983         26.33 SC         12.77 mS     8.427 SC    4.19 MB    115492    
85.26.43.160:9982            24.58 SC         1.768 SC     24.04 SC    608.17 MB  115492    
stor2.sia.rivine.io:19982    23.95 SC         2.395 SC      34.6 SC    608.17 MB  115492    
marfeusftp.myftp.org:9982    23.04 SC         11.18 mS     8.187 SC    4.19 MB    115492    
82.196.124.91:9982           19.76 SC              0 H     23.77 SC    0 B        115492    
68.204.102.193:9982          19.75 SC              0 H     8.159 SC    0 B        115492    
188.244.40.69:9982           19.75 SC         9.589 mS     23.77 SC    4.19 MB    115492    
50.90.179.33:9982            19.75 SC         9.589 mS     23.77 SC    4.19 MB    115492    
j2b.ddns.net:9982            19.75 SC         9.594 mS     23.77 SC    4.19 MB    115492    
176.12.20.111:9982           19.75 SC         9.589 mS     8.373 SC    4.19 MB    115492    
80.117.29.241:9982           19.74 SC         9.589 mS     23.77 SC    4.19 MB    115492    
176.12.18.241:9982            19.1 SC         661.2 mS     23.77 SC    306.18 MB  115492    
68.175.125.235:9982           18.6 SC         1.166 SC     10.19 SC    608.17 MB  115492    
75.84.184.198:9982           18.43 SC         8.952 mS     8.106 SC    4.19 MB    115492    
91.144.168.250:9982          18.41 SC         1.349 SC      24.2 SC    608.17 MB  115492    
217.23.193.212:9982          13.17 SC              0 H     34.07 SC    0 B        115492    
68.5.24.44:9982              13.17 SC              0 H     7.892 SC    0 B        115492    
97.94.206.85:9982            13.17 SC         6.573 mS     14.06 SC    4.19 MB    115492    
87.243.7.189:9982            13.16 SC          6.41 mS     23.93 SC    4.19 MB    115492    
217.182.84.175:9982          13.15 SC         22.36 mS       112 SC    12.58 MB   115492    
162.211.163.187:9982         13.12 SC              0 H      23.5 SC    0 B        115492    
69.120.4.58:9982             10.54 SC              0 H     23.45 SC    0 B        115492    
100.8.168.63:9982            6.583 SC         3.225 mS     7.732 SC    4.19 MB    115492    
46.4.17.11:9982              2.635 SC              0 H     23.18 SC    0 B        115492    
84.194.185.71:9982           2.633 SC         1.314 mS     23.07 SC    4.19 MB    115492    
78.46.64.86:9982             1.977 SC              0 H     3.718 SC    0 B        115492    
212.77.177.47:9982           658.6 mS         360.1 uS      23.1 SC    4.19 MB    115492    
98.116.75.84:9982            632.4 mS              0 H     3.382 SC    0 B        115492 
   ```

**Comment by DavidVorick** [comment]
How much data have you uploaded?

The hosts don't get the fees you paid unless they keep your files, but they will be able to get some of your fees even if you never upload.

But, if they don't take your files, (in an upcoming release, it's not out just yet) they will be blacklisted and you will never use them again.

We are in the process of overhauling the contract formation process.

**Comment by dim-geo** [comment]
less than 1Gb.
![untitled](https://cloud.githubusercontent.com/assets/5956557/25773052/8f2ff290-327f-11e7-9d4f-bcc70296339f.png)

- 1 directory of photos that's stuck for days. (582 MB)
- a small file
- a file of 41 MB (I tried to align it to chunk size, is this correct?)

Needless to say that I 've left Sia open for days but to no avail. My upload speed is around 100KB/s

Unfortunately, individual blocklisting will not be enough. The first contract money would be lost...
We need a history factor for each host: Has this host increased the used storage in last contracts?
If not, he doesn't have enough speed or he is malicious.
If a host is brand new (without history) you can assign to him a default score.

Please note that malicious hosts can fetch only one piece of my files and therefore they will not be blacklisted!

The only way malicious hosts would cheat history factor is to create new wallets and transfer money to the new wallets. Therefore the default 'history' score should be low.

Since the Sia code is open, malicious hosts can only be stopped by ultra-smart contract formation.
Otherwise, Sia will not fly.

**Comment by DavidVorick** [comment]
I'm on my phone (no computer) for the next few days so I can't go too much in detail but Sia has a lot in place to protect against malicious hosts. It's harder in many ways than most people realize, and also easier in many ways than most people realize.

If you form a malicious contract, you only stand to lose the fees. Then you will never use that host again. Any host looking to optimize for profit will want to store your data.

Sia doesn't just form contracts with random hosts there's a huge set of weightings and criteria used to find the best hosts. Code here: https://github.com/NebulousLabs/Sia/blob/master/modules/renter/hostdb/hostweight.go

One thing we haven't added yet is proof of burn. Another thing is geographic diversity. We will be adding both, which will both further help against malicious hosts.

Have you tried restarting Sia? That may help the downloads to resume. We're making a lot of improvements to that code for the next release.

**Comment by johnathanhowell** [comment]
Another thing worth noting is that your photo uploads may not be stuck but simply taking a long time, 100 KB/s is not very fast and each photo in that directory will be padded out to 40MB and uploaded at 3x redundancy, meaning you're likely uploading many gigabytes.

**Comment by dim-geo** [comment]
Yes, I have restarted Sia(every night I close my PC).
Yes, I 've seen the code and I am in favour of Sia as a platform for both hosts and renters :+1: 
What I suggest is a walk through the file contracts for each host and check his background/behaviour.

For example, as siahub calculates the info, we can calculate the slope of used storage overtime.
[http://siahub.info/host/1360](http://siahub.info/host/1360)

fullPenalty := collateralReward * pricePenalty * storageRemainingPenalty * versionPenalty * lifetimePenalty * uptimePenalty * _rate_of_filecontractsPenalty_

I'm not pointing the finger, I just try to help as a fellow programmer.
Have a nice day and of course you know better how you can tackle this!

**Comment by DavidVorick** [comment]
The tough thing about checking a host's background is that you can't tell whether the contracts in the host's history are real contracts, or if they are fake contracts put there by the host to make the host seem reliable.

**Comment by dim-geo** [comment]
Then, what we can do is this:

at the end of the contract calculate the mean value of data in the contracts.
Then calculate a factor |host data - mean data|/mean data.
New hosts should have a sane default value, for example 0.5

Use that factor as a penalty. This shall prevent creating new contracts not only to malicious hosts but also to the slow ones.

**Comment by DavidVorick** [comment]
> There is no penalty if they reject file pieces or if they limit their speed.

Penalties for this is in the works.

> Forging fake host history would force the host to pay transaction costs.

This is fundamentally equivalent to proof of burn, which is also in the works.

> at the middle/end of the contract calculate the mean value of data in the contracts. Then calculate a factor |host data held in this contract - mean data|/mean data. New hosts should have a sane default value, for example 0.5

You don't want to be holding hosts to an absolute standard, you want to be discovering the hosts that are going to be useful to you. Most on-blockchain contracts are going to have a data value of 0 anyway - there's no need to update the blockchain with the most recent version of the contract (expensive!) unless the renter and host are in disagreement. By keeping the actual data value at 0, the host doesn't have to submit a storage proof, which saves the host from transaction fees. The renter is happy to give the host a break if the host has privately already performed the storage proof (much cheaper than doing it publicly), the blockchain is only necessary if the renter is unhappy with the host.

> A similar approach should be followed for downloaded pieces.

There is no download operation that makes it into the blockchain. You would be unable to measure this except for downloads you have performed yourself. But there's no need for a host factor, you can just keep track of their speeds and uptime history and decide whether that's fast enough to be beneficial for the price they are charging.

>  I'm surprised that from all 50 contracts, uploading a file of 40MB (120MB) takes hours. it should take half an hour.

If you've got a bad set of contracts, the only way to get things moving again is to delete them and get a new set of contracts. We've got a pull request open right now that does this automatically, but it's not ready to be merged yet.

My server has been uploading to the network at a sustained 200mbps using just a vanilla set of contracts, no special code. So at the very least, it demonstrates that it's possible. We recognize that some people end up with a bunch of bad contracts, but as said above we've got fixes in the works, just ironing out the testing.
