### ISSUE TITLE
Siad exited when trying to open wallet.

### ISSUE THREAD

**Issue by droidalex** [NebulousLabs/Sia#1774]
I had Siad UI 1.2.0 and then upgraded to 1.2.1. I'm using the Linux version. This is the error output (this happens always):
`
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.496362162 seconds

Wallet: scanned to height 87346...
Wallet: scanned to height 87353...
Wallet: scanned to height 87355...
Wallet: scanned to height 87358...
Wallet: scanned to height 87359...
Wallet: scanned to height 87362...
Wallet: scanned to height 87364...
Wallet: scanned to height 87365...
Wallet: scanned to height 87369...
Wallet: scanned to height 87373...
Wallet: scanned to height 87375...
Wallet: scanned to height 87376...
Wallet: scanned to height 87377...
Wallet: scanned to height 87378...
Wallet: scanned to height 87379...
Wallet: scanned to height 87385...
Wallet: scanned to height 87388...
Wallet: scanned to height 87391...
Wallet: scanned to height 87393...
Wallet: scanned to height 87395...
Wallet: scanned to height 87399...
Wallet: scanned to height 87400...
Wallet: scanned to height 87403...
Wallet: scanned to height 87405...
Wallet: scanned to height 87407...
Wallet: scanned to height 87413...
Wallet: scanned to height 87414...
Wallet: scanned to height 87417...
Wallet: scanned to height 87420...
Wallet: scanned to height 87429...
Wallet: scanned to height 87432...
Wallet: scanned to height 87433...
Wallet: scanned to height 87434...
Wallet: scanned to height 87436...
Wallet: scanned to height 87439...
Wallet: scanned to height 87443...
Wallet: scanned to height 87446...
Wallet: scanned to height 87447...
Wallet: scanned to height 87450...
Wallet: scanned to height 87453...
Wallet: scanned to height 87454...
Wallet: scanned to height 87456...
Wallet: scanned to height 87457...
Wallet: scanned to height 87460...
Wallet: scanned to height 87461...
Wallet: scanned to height 87463...
Wallet: scanned to height 87466...
Wallet: scanned to height 87467...
Wallet: scanned to height 87468...
Wallet: scanned to height 87470...
Wallet: scanned to height 87471...
Wallet: scanned to height 87473...
Wallet: scanned to height 87477...
Wallet: scanned to height 87479...
Wallet: scanned to height 87482...
Wallet: scanned to height 87487...
Wallet: scanned to height 87488...
Wallet: scanned to height 87490...
Wallet: scanned to height 87491...
Wallet: scanned to height 87492...
Wallet: scanned to height 87495...
Wallet: scanned to height 87497...
Wallet: scanned to height 87503...
Wallet: scanned to height 87504...
Wallet: scanned to height 87506...
Wallet: scanned to height 87508...
Wallet: scanned to height 87512...
Wallet: scanned to height 87518...
Wallet: scanned to height 87519...
Wallet: scanned to height 87520...
Wallet: scanned to height 87522...
Wallet: scanned to height 87525...
Wallet: scanned to height 87528...
Wallet: scanned to height 87529...
Wallet: scanned to height 87531...
Wallet: scanned to height 87532...
Wallet: scanned to height 87534...
Wallet: scanned to height 87535...
Wallet: scanned to height 87538...
Wallet: scanned to height 87541...
Wallet: scanned to height 87546...
Wallet: scanned to height 87551...
Wallet: scanned to height 87561...
Wallet: scanned to height 87572...
Wallet: scanned to height 87582...
Wallet: scanned to height 87602...
Wallet: scanned to height 87606...
Wallet: scanned to height 87609...
Wallet: scanned to height 87616...
Wallet: scanned to height 87617...
Wallet: scanned to height 87620...
Wallet: scanned to height 87621...
Wallet: scanned to height 87623...
Wallet: scanned to height 87625...
Wallet: scanned to height 87628...
Wallet: scanned to height 87630...
Wallet: scanned to height 87631...
Wallet: scanned to height 87633...
Wallet: scanned to height 87636...
Wallet: scanned to height 87639...
Wallet: scanned to height 87640...
Wallet: scanned to height 87641...
Wallet: scanned to height 87647...
Wallet: scanned to height 87648...
Wallet: scanned to height 87649...
Wallet: scanned to height 87651...
Wallet: scanned to height 87656...
Wallet: scanned to height 87658...
Wallet: scanned to height 87660...
Wallet: scanned to height 87661...
Wallet: scanned to height 87665...
Wallet: scanned to height 87667...
Wallet: scanned to height 87669...
Wallet: scanned to height 87671...
Wallet: scanned to height 87672...
Wallet: scanned to height 87673...
Wallet: scanned to height 87675...
Wallet: scanned to height 87676...
Wallet: scanned to height 87679...
Wallet: scanned to height 87681...
Wallet: scanned to height 87683...
Wallet: scanned to height 87685...
Wallet: scanned to height 87686...
Wallet: scanned to height 87687...
Wallet: scanned to height 87689...
Wallet: scanned to height 87692...
Wallet: scanned to height 87694...
Wallet: scanned to height 87696...2017/05/06 20:25:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms

Wallet: scanned to height 87697...2017/05/06 20:25:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/06 20:25:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/06 20:25:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/06 20:25:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/06 20:25:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/06 20:25:54 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms

Wallet: scanned to height 87699...2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/06 20:25:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/06 20:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/06 20:25:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/06 20:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/06 20:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 87702...2017/05/06 20:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/06 20:26:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/06 20:26:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/06 20:26:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 87705...2017/05/06 20:26:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
 `

**Comment by DavidVorick** [comment]
@johnathanhowell looks like you need a more aggressive backoff strategy. (start at 20ms, and instead of doubling use an rng to do between 1.5x and 2.5x of the prev. time. This prevents a bunch of calls from hitting at the same time repeatedly.) Or is this fixed in the most recent master already?

**Comment by johnathanhowell** [comment]
This was fixed in in the latest master in this pr https://github.com/NebulousLabs/Nodejs-Sia/pull/47 but was not pushed out in 1.2.1
