### ISSUE TITLE
Sia exits unexpectedly

### ISSUE THREAD

**Issue by niex2** [NebulousLabs/Sia#1776]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.520014768 seconds
goroutine 61793 [running]:
runtime/debug.Stack(0x4456d7, 0x0, 0xc4203dbc80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4203dbe58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42020d5c0, 0xc4203dbe58, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc427d8e620, 0xc420390308, 0x0, 0x0, 0x0, 0xeb9360, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:195 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:203 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: write /home/user/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
goroutine 61793 [running]:
runtime/debug.Stack(0x4456d7, 0x0, 0xc4203dbaa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc4203dbc18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:29 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42020d5c0, 0xc4203dbc18, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420390308, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc427d8e620, 0xc420390308, 0x0, 0x0, 0x0, 0xeb9360, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:202 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:203 +0x1e5
Severe error: Unable to write state change to WAL: write /home/user/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 61793 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420390308, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc427d8e620, 0xc420390308, 0x0, 0x0, 0x0, 0xeb9360, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:202 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:203 +0x1e5

**Comment by lukechampine** [comment]
>`Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: write /home/user/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device`

This is the source of the error. Make sure you have enough space on your disk to support the amount of storage you want to host.

**Comment by DavidVorick** [comment]
Was this compiled from master? Severe errors shouldn't crash the program in the binaries we released

**Comment by lukechampine** [comment]
This may have been an older release that included the `panic: crashing to prevent corruption`
