### ISSUE TITLE
Siad should handle logoff/shutdown events in Windows to prevent data loss 

### ISSUE THREAD

**Issue by ghost** [NebulousLabs/Sia#1777]
If 'siad' is in the middle of a critical operation, implementing a handler can prevent the shutdown from occurring. 'Ctrl-C' is being handled properly, but not sure how 'Go' actually implements it. I've provided some Win32 API links for reference.

**References**
_Console Applications_
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685049(v=vs.85).aspx

_Window Applications_
https://msdn.microsoft.com/en-us/library/windows/desktop/aa376890(v=vs.85).aspx

**Comment by lukechampine** [comment]
Our current signal handling code is [here](https://github.com/NebulousLabs/Sia/blob/9f7e087c01ff431e8bb30940f1c00a72d2f86d45/siad/daemon.go#L282):

```go
// stop the server if a kill signal is caught
sigChan := make(chan os.Signal, 1)
signal.Notify(sigChan, os.Interrupt, os.Kill)
```
Are there more signals we need to handle? Also, siad can take a while to shutdown gracefully. We've made strides towards faster shutdown but it can still take up to a few minutes.

**Comment by SiaExtensions** [comment]
It looks like Go can also handle CTRL_CLOSE_EVENT which occurs when someone tries to close the console window without Ctrl-C [here](https://github.com/golang/go/issues/7479).
 
The more daunting task is handling logoff and shutdown events. The most reliable way is to create a hidden window which processes the WM_QUERYENDSESSION message. This post describes it pretty well: [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/abf09824-4e4c-4f2c-ae1e-5981f06c9c6e/windows-7-console-application-has-no-way-of-trapping-logoffshutdown-event?forum=windowscompatibility)

**Comment by lukechampine** [comment]
Too much work required for this right now
