### ISSUE TITLE
Host Data degradation management

### ISSUE THREAD

**Issue by nmehraein** [NebulousLabs/Sia#1781]
Hi,

My question from point of view of big datas systems in general is how Sia host manage the data degradation on storage medium ?

# Hadoop

Big data systems like Hadoop check every 20/21 days file md5 because the on read check strategy work for frequent file access. For cold data with unfrequent access pattern, the check of consistency on read can be too late ...

https://en.wikipedia.org/wiki/Data_degradation

# Erasure code

The erasure code can answer partialy the question because by nature permit loss of portions of datas, but with limit. A planned check permit a stronger system.

# Loss responsability

The other question is, how uncharge the responsability of hosts for binary data degradation ? If i host a file and the file on my hard drive is partialy corrupted by a natural loss of magnetic charge, is that my responsibility?

# Enhancement proposition

Like hadoop system, the host schedule a consistency check of files, and has the capacity with other network members to restore the data with erasure coding.

Thanks to all for your work.

**Comment by DavidVorick** [comment]
Hey! The host stores checksums of all the data, so it has the ability to check if something has corrupted, but...

We actually don't believe that the host is the right place to put these checks. File safety and such should be handled by your filesystem. ZFS, btrfs, RAID, or some combination of them will handle data degradation more effectively than we could handle it ourselves.

Renters are already doing high redundancy on the network, hosts should focus on optimizing for profit. That is, when a host loses data they pay a fine. So they should have enough parity and data checking that the expected cost of (fines + parity + verification) is minimized. If hosts are doing that, the renters will take care of the rest :)

**Comment by nmehraein** [comment]
Hi,

ZFS, btrfs, and Raid dont purpose proactive system for detect corruption on inactive data.
If a data is not read, the data is not checked for consistency in my knowledge.

I just say that a simple process like check file hash every 20/21days after upload (and not all file at time) permit to gain easyly in data integrity.

I say that because no file system can prevent that.
On the classical host vision without raid or big investment, the risk is included in price proposed.
On the advanced host vision, a raid is configured and the price of raid is included in price, then same impact on price then classical host with lower risk for host.
On biggest advanced host, a ceph cluster with erasure coding and periodical redondancy check, the price of host parity is lowered than RAID but present, but it reserve Sia to biggest advanced host with high investment (several nodes with several disks and knowledge to make that).

It's a shame because in final, the renter use erasure coding for make redondancy on network.
My reflexion is, if the network has big redondancy, why the host don't profit to that ?

Is just a proposal :)

**Comment by olcto** [comment]
ZFS does have a proactive system for file system integrity checking that includes inactive data, [scrubbing](https://docs.oracle.com/cd/E18752_01/html/819-5461/gbbwa.html).

> This operation traverses all the data in the pool once and verifies that all blocks can be read.

There is debate on how often one should scrub.
