### ISSUE TITLE
Upgrading Sia-UI 1.1.2 to Sia-UP-1.2.1 throws error during wallet unlock

### ISSUE THREAD

**Issue by JamesM424** [NebulousLabs/Sia#1784]
[HostLog.txt](https://github.com/NebulousLabs/Sia/files/988531/HostLog.txt)  Edited to remove IP addresses from log

This is a Win7 x64 box.  
[ConsensusLog.txt](https://github.com/NebulousLabs/Sia/files/988481/ConsensusLog.txt)

Scanning height seems to increase with every failure.

Appears similar to report in NebulousLabs/Nodejs-Sia#47 however that was reported as "Fedora and OSX"

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.2960742 seconds

Wallet: scanned to height 67644...
Wallet: scanned to height 67710...
Wallet: scanned to height 69381...
Wallet: scanned to height 71455...
Wallet: scanned to height 71536...
Wallet: scanned to height 71538...

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.2960742 seconds

Wallet: scanned to height 67644...
Wallet: scanned to height 67710...
Wallet: scanned to height 69381...
Wallet: scanned to height 71455...
Wallet: scanned to height 71536...
Wallet: scanned to height 71538...
Wallet: scanned to height 72101...
Wallet: scanned to height 72183...
Wallet: scanned to height 72683...
Wallet: scanned to height 72755...
Wallet: scanned to height 72789...
Wallet: scanned to height 73450...
Wallet: scanned to height 73562...
Wallet: scanned to height 74256...
Wallet: scanned to height 74640...
Wallet: scanned to height 74967...
Wallet: scanned to height 75225...
Wallet: scanned to height 75229...
Wallet: scanned to height 75630...
Wallet: scanned to height 75931...
Wallet: scanned to height 76036...
Wallet: scanned to height 76736...
Wallet: scanned to height 76935...
Wallet: scanned to height 76937...
Wallet: scanned to height 77004...
Wallet: scanned to height 77019...
Wallet: scanned to height 77019...
Wallet: scanned to height 77031...
Wallet: scanned to height 77031...
Wallet: scanned to height 77766...
Wallet: scanned to height 77766...
Wallet: scanned to height 78299...
Wallet: scanned to height 78299...
Wallet: scanned to height 78302...
Wallet: scanned to height 78302...
Wallet: scanned to height 78485...
Wallet: scanned to height 78485...
Wallet: scanned to height 79054...
Wallet: scanned to height 79054...
Wallet: scanned to height 79236...
Wallet: scanned to height 79236...
Wallet: scanned to height 80041...
Wallet: scanned to height 80041...
Wallet: scanned to height 80159...
Wallet: scanned to height 80159...
Wallet: scanned to height 80507...
Wallet: scanned to height 80507...
Wallet: scanned to height 80856...
Wallet: scanned to height 80856...
Wallet: scanned to height 81449...
Wallet: scanned to height 81449...
Wallet: scanned to height 81742...
Wallet: scanned to height 81742...
Wallet: scanned to height 81802...
Wallet: scanned to height 81803...
Wallet: scanned to height 82042...
Wallet: scanned to height 82042...
Wallet: scanned to height 82149...
Wallet: scanned to height 82149...
Wallet: scanned to height 83017...
Wallet: scanned to height 83017...
Wallet: scanned to height 83098...
Wallet: scanned to height 83098...
Wallet: scanned to height 83259...
Wallet: scanned to height 83259...
Wallet: scanned to height 83268...
Wallet: scanned to height 83268...
Wallet: scanned to height 83355...
Wallet: scanned to height 83355...
Wallet: scanned to height 83425...
Wallet: scanned to height 83425...
Wallet: scanned to height 83808...
Wallet: scanned to height 83808...
Wallet: scanned to height 83880...
Wallet: scanned to height 83880...
Wallet: scanned to height 84045...
Wallet: scanned to height 84045...
Wallet: scanned to height 84674...
Wallet: scanned to height 84674...
Wallet: scanned to height 84692...
Wallet: scanned to height 84692...
Wallet: scanned to height 85336...
Wallet: scanned to height 85336...
Wallet: scanned to height 85548...
Wallet: scanned to height 85548...
Wallet: scanned to height 85551...
Wallet: scanned to height 85552...
Wallet: scanned to height 85915...
Wallet: scanned to height 85915...
Wallet: scanned to height 86402...
Wallet: scanned to height 86402...
Wallet: scanned to height 86926...
Wallet: scanned to height 86926...
Wallet: scanned to height 86949...
Wallet: scanned to height 86949...
Wallet: scanned to height 86951...
Wallet: scanned to height 86951...
Wallet: scanned to height 87225...
Wallet: scanned to height 87225...
Wallet: scanned to height 87529...
Wallet: scanned to height 87529...
Wallet: scanned to height 87975...
Wallet: scanned to height 87975...
Wallet: scanned to height 87977...
Wallet: scanned to height 87977...
Wallet: scanned to height 88357...
Wallet: scanned to height 88357...
Wallet: scanned to height 88455...
Wallet: scanned to height 88455...
Wallet: scanned to height 88460...
Wallet: scanned to height 88460...
Wallet: scanned to height 88559...
Wallet: scanned to height 88559...
Wallet: scanned to height 88620...
Wallet: scanned to height 88620...
Wallet: scanned to height 88676...
Wallet: scanned to height 88676...
Wallet: scanned to height 88689...
Wallet: scanned to height 88689...
Wallet: scanned to height 88693...
Wallet: scanned to height 88693...
Wallet: scanned to height 88708...
Wallet: scanned to height 88708...
Wallet: scanned to height 88710...
Wallet: scanned to height 88710...
Wallet: scanned to height 88801...
Wallet: scanned to height 88801...
Wallet: scanned to height 88803...
Wallet: scanned to height 88803...
Wallet: scanned to height 88855...
Wallet: scanned to height 88855...
Wallet: scanned to height 88993...
Wallet: scanned to height 88993...
Wallet: scanned to height 88997...
Wallet: scanned to height 88997...
Wallet: scanned to height 89629...
Wallet: scanned to height 89629...
Wallet: scanned to height 89746...
Wallet: scanned to height 89746...
Wallet: scanned to height 89748...
Wallet: scanned to height 89748...
Wallet: scanned to height 90125...
Wallet: scanned to height 90125...
Wallet: scanned to height 90222...
Wallet: scanned to height 90222...
Wallet: scanned to height 90228...
Wallet: scanned to height 90228...
Wallet: scanned to height 90483...
Wallet: scanned to height 90483...
Wallet: scanned to height 91140...
Wallet: scanned to height 91140...
Wallet: scanned to height 91142...
Wallet: scanned to height 91142...
Wallet: scanned to height 91173...
Wallet: scanned to height 91173...
Wallet: scanned to height 91651...
Wallet: scanned to height 91651...
Wallet: scanned to height 91923...
Wallet: scanned to height 91923...
Wallet: scanned to height 91925...
Wallet: scanned to height 91925...
Wallet: scanned to height 92210...
Wallet: scanned to height 92210...
Wallet: scanned to height 92695...
Wallet: scanned to height 92695...
Wallet: scanned to height 92699...
Wallet: scanned to height 92699...
Wallet: scanned to height 92795...
Wallet: scanned to height 92795...
Wallet: scanned to height 93229...
Wallet: scanned to height 93229...
Wallet: scanned to height 93672...
Wallet: scanned to height 93672...
Wallet: scanned to height 93680...
Wallet: scanned to height 93680...
Wallet: scanned to height 94535...
Wallet: scanned to height 94535...
Wallet: scanned to height 94537...
Wallet: scanned to height 94537...
Wallet: scanned to height 94894...
Wallet: scanned to height 94894...
Wallet: scanned to height 94994...
Wallet: scanned to height 94994...
Wallet: scanned to height 95002...
Wallet: scanned to height 95002...
Wallet: scanned to height 95006...
Wallet: scanned to height 95006...
Wallet: scanned to height 95018...
Wallet: scanned to height 95018...
Wallet: scanned to height 95023...
Wallet: scanned to height 95023...
Wallet: scanned to height 95233...
Wallet: scanned to height 95233...
Wallet: scanned to height 95245...
Wallet: scanned to height 95245...
Wallet: scanned to height 95448...
Wallet: scanned to height 95448...
Wallet: scanned to height 95474...
Wallet: scanned to height 95474...
Wallet: scanned to height 95492...
Wallet: scanned to height 95492...
Wallet: scanned to height 95498...
Wallet: scanned to height 95498...
Wallet: scanned to height 95666...
Wallet: scanned to height 95666...
Wallet: scanned to height 96129...
Wallet: scanned to height 96129...
Wallet: scanned to height 96213...
Wallet: scanned to height 96213...
Wallet: scanned to height 96734...
Wallet: scanned to height 96734...
Wallet: scanned to height 96766...
Wallet: scanned to height 96766...
Wallet: scanned to height 96819...
Wallet: scanned to height 96819...
Wallet: scanned to height 96825...
Wallet: scanned to height 96825...
Wallet: scanned to height 96918...
Wallet: scanned to height 96918...
Wallet: scanned to height 96922...
Wallet: scanned to height 96922...
Wallet: scanned to height 97103...
Wallet: scanned to height 97103...
Wallet: scanned to height 97612...
Wallet: scanned to height 97612...
Wallet: scanned to height 97724...
Wallet: scanned to height 97724...
Wallet: scanned to height 98058...
Wallet: scanned to height 98058...
Wallet: scanned to height 98119...
Wallet: scanned to height 98119...
Wallet: scanned to height 98147...
Wallet: scanned to height 98147...
Wallet: scanned to height 98247...
Wallet: scanned to height 98247...
Wallet: scanned to height 98801...
Wallet: scanned to height 98801...
Wallet: scanned to height 99395...
Wallet: scanned to height 99395...
Wallet: scanned to height 99399...
Wallet: scanned to height 99399...
Wallet: scanned to height 100087...
Wallet: scanned to height 100087...
Wallet: scanned to height 100928...
Wallet: scanned to height 100928...
Wallet: scanned to height 100930...
Wallet: scanned to height 100930...
Wallet: scanned to height 101820...
Wallet: scanned to height 101820...
Wallet: scanned to height 102574...
Wallet: scanned to height 102574...
Wallet: scanned to height 103242...
Wallet: scanned to height 103242...
Wallet: scanned to height 103395...
Wallet: scanned to height 103395...
Wallet: scanned to height 103570...
Wallet: scanned to height 103570...
Wallet: scanned to height 103795...
Wallet: scanned to height 103795...
Wallet: scanned to height 104211...
Wallet: scanned to height 104211...
Wallet: scanned to height 104214...
Wallet: scanned to height 104214...
Wallet: scanned to height 105285...
Wallet: scanned to height 105285...
Wallet: scanned to height 105442...
Wallet: scanned to height 105442...
Wallet: scanned to height 105637...
Wallet: scanned to height 105637...
Wallet: scanned to height 105918...
Wallet: scanned to height 105918...
Wallet: scanned to height 105966...
Wallet: scanned to height 105966...
Wallet: scanned to height 106381...
Wallet: scanned to height 106381...
Wallet: scanned to height 106731...
Wallet: scanned to height 106731...
Wallet: scanned to height 108321...
Wallet: scanned to height 108321...
Wallet: scanned to height 108330...
Wallet: scanned to height 108330...
Wallet: scanned to height 108705...
Wallet: scanned to height 108705...
Wallet: scanned to height 109457...
Wallet: scanned to height 109457...
Wallet: scanned to height 109841...
Wallet: scanned to height 109841...
Wallet: scanned to height 109845...
Wallet: scanned to height 109845...
Wallet: scanned to height 110174...
Wallet: scanned to height 110174...
Wallet: scanned to height 110298...
Wallet: scanned to height 110298...
Wallet: scanned to height 110310...
Wallet: scanned to height 110310...

**Comment by lukechampine** [comment]
What is the actual error?

**Comment by JamesM424** [comment]
Possibly I should have been a bit more clear.

That was the error instructed to copy/paste here whilst upgrading from 1.1.2 to 1.2.1.  While attempting to unlock the wallet with the newest version downloaded and 'unlocking wallet' it would respond with siad has stopped displaying only a button to "start siad".

After a few attempts, siad would crash instantly after attempting to unlock the wallet.  [assuming it reached the top of the blockchain].

(I should make a note now, that at that point I rolled back today's changes to yesterdays automatic backup.  Our intention is to use this in a corporate environment and 'unexpected behavior' causes piles of paperwork)

**Comment by DavidVorick** [comment]
@lukechampine looks like there's a double subscribe issue here, the wallet has scanned past the actual height of the blockchain by quite a bit.

**Comment by lukechampine** [comment]
Likely caused by concurrent unlock calls. All the more reason to add that trylock we discussed.

**Comment by pdroalves** [comment]
Same happening here.

**Comment by JamesM424** [comment]
I'm upgrading my other client location tonight.  I noticed one of the first steps during the upgrade is the changes to the file handling (from many 4MB files to one large file).  

It's highly possible this error was caused by https://github.com/NebulousLabs/Sia/issues/1792

**Comment by JamesM424** [comment]
Upgraded my primary location ( from 1.1.2 to 1.2.2) and can confirm I do not have a repro on this issue.  Either caused by bug noted above or resolved in some other fashion.  

Feel free to close at any time.  Good work, men.

**Comment by JamesM424** [comment]
I haven't had a repro on this on either machine, and seems to be going fine.  It's highly possible it was caused by https://github.com/NebulousLabs/Sia/issues/1792, so if you guys want to hit "close", it'd be fine by me.
