### ISSUE TITLE
Prefer forming contracts with independent hosts

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#1791]
I found this in `renter/contractor.log`:

```
formcontract.go:114: Formed contract with sanasol.sknt.ru:9985 for 10 SC
...
formcontract.go:114: Formed contract with sanasol.sknt.ru:9987 for 10 SC
```

I think it is suboptimal from redundancy POV to form two contracts with nodes that are obviously managed by the same person/company.

Tor has the following mechanisms to avoid forming circuits from dependent nodes:

  * prefer different /16 prefixes / AS names of nodes
  * prefer different nodes families

Probably we need both. Families are filled manually by node operators, so they can't be always trusted. On the other hand /16 prefixes and AS names don't make much sense if [onion sites could be used as hosts](https://github.com/NebulousLabs/Sia/issues/1785).

**Comment by S-anasol** [comment]
already asked in Slack for tor-like node "signing", not sure that we got some response.

![image](https://cloud.githubusercontent.com/assets/1709666/26030336/706140fa-3859-11e7-9bc0-103ad84534ed.png)

**Comment by DavidVorick** [comment]
I agree, but don't have a great idea about how to implement this. One thought was to split hosts into geographic regions, another to do string matching in the domain name.

If someone wants to hide the fact that they own multiple hosts, there's not much you can do about it. Proof of burn is our ultimate defense against Sybil attacks, but it's not implemented yet (soon!)

**Comment by starius** [comment]
Simple cases like many hosts on a single IP can be addressed now for free. The following heuristics is rather simple to implement and significantly increases price of Sybil: check that the following is different for all the hosts taking part in one redundancy group:
* /16 IP network
* second-level domain
