### ISSUE TITLE
Drive letter change broke symbolic link for host storage location

### ISSUE THREAD

**Issue by JamesM424** [NebulousLabs/Sia#1792]
Sia Version 1.2.1
Windows x64

I recently added a new drive to a system that is hosting Sia.  Sia host storage folders were stored on an external drive.  Before the new addition, the Boot drive was "C:" and storage drive was "D:".  After the new addition, the boot drive was "C:", the new [unused] drive became "D:" and Sia storage became "E:".  Because windows handles gives priority to internal drives over "removable"

After some other maintenance, I launched the Sia-UI.  The Sia-UI client had indicated that the Storage folder had "732GB Free" in the hosting tab.  Same as before.

In actuality, the drive that storagemanager.json had in record, was no longer correct after the drive letter change.

In the log file had these error messages for every file attempted for 5 days:
2017/05/06 17:47:42.728589 sector.go:200: Unable to accept sector open C:\Users\system1\AppData\Roaming\Sia-UI\sia\host\storagemanager\89746661\3jEo-88AxIZ1cIbr: The system cannot find the path specified. into folder 89746661
2017/05/06 19:08:02.459262 sector.go:200: Unable to accept sector open C:\Users\system1\AppData\Roaming\Sia-UI\sia\host\storagemanager\89746661\7ZbKR_OssNZZMtRc: The system cannot find the path specified. into folder 89746661

I manually edited the storagemanager.json file to reflect the correct path.  I broke and recreated the symbolic directory link pointing to the storage folder.  

I haven't seen any activity to the storage folders, so I can't say if this is correct yet.

The UI never complained that the path did not exist, or that the files were not accessible.  Which I think it should have.

**Comment by DavidVorick** [comment]
agreed, it should have complained. Fix for this is actually already in progress, #1767 

UI and siac will not be reporting errors on this mistake for a while, but at the very least it won't do the wrong thing. We will leave this issue open until the UI and siac both can display to the user when a storage folder appears to be inaccessible.

**Comment by lukechampine** [comment]
is this fixed?

**Comment by JamesM424** [comment]
Was going to attempt to test today but I'm behind schedule.  Will give it a
try on Monday.

**Comment by JamesM424** [comment]
Going to close this.  Seems good to me.
