### ISSUE TITLE
doc: consensus.md incorrectly says that a signature change requires a hardfork

### ISSUE THREAD

**Issue by apoelstra** [NebulousLabs/Sia#1793]
https://github.com/NebulousLabs/Sia/blob/master/doc/Consensus.md

Grep for 'hard fork' and you will find a line saying that a signature change requires a hardfork. Note that a couple paragraphs down, it is correctly stated that a signature change requires only a softfork :)

**Comment by lukechampine** [comment]
Good catch, thanks!
