### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by quinsmacqueen** [NebulousLabs/Sia#1794]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.355784367 seconds

**Comment by DylanVerstraete** [comment]
This is due to low free space on your disk. Try moving the folder in Appdata to a location with more free memory

**Comment by pdroalves** [comment]
Same issue here. It happens during wallet unlocking (that never complete). Have 40GB free on disk.
