### ISSUE TITLE
Peering Ideas

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#180]
We were discussing RPCs and I've been altering the Core's structure to be more modular, one of the things that I think should happen is that all of the peer management code get split into its own package and interface.

The peer code could have a bunch of RPCs for talking to everyone, and internally the Core just uses whatever interface functions, which are not RPCs. The peer code would be given a channel down which it could drop blocks. I'm not sure what other things would be needed, the state would need a channel down which it could drop its own blocks and transactions I imagine (after it verfies or rejects them). But most of the management could be internal to the peer package and invisible to the Core.

Does that make sense?

**Comment by DavidVorick** [comment]
I think this has been taken care of?

**Comment by lukechampine** [comment]
Yeah, this has been implemented almost verbatim; just replace "network" with "Gateway" in my comment above.
