### ISSUE TITLE
Where blockchains are stored in Ubuntu?

### ISSUE THREAD

**Issue by mertimiks** [NebulousLabs/Sia#1800]
I asked this question before, and you guys have told me that it was stored in Consensus.md file. But there is one problem. The size of my Consensus.md file is 20kb, very very small, so it cannot be stored there. And currently my blockchain is synced.

**Comment by DavidVorick** [comment]
.config/Sia-UI/Sia/

**Comment by mertimiks** [comment]
Okay thanks I see where it is now.

One more question, is there anyway to move these files to external drive to turn this a cold wallet?

**Comment by lukechampine** [comment]
See https://github.com/johnathanhowell/sia-coldstorage
