### ISSUE TITLE
Cannot add host folder (Could not parse size: unable to parse size)

### ISSUE THREAD

**Issue by geckogecko** [NebulousLabs/Sia#1805]
I am receiving this error message when trying to add an 20gb host folder:

`Could not parse size: unable to parse size`

Command:
`"./siac host folder add /root/sia/Sia-v1.2.1-linux-amd64/host_folder 20"` on Ubuntu 14.04.4 LTS

**Comment by lukechampine** [comment]
you need to provide a unit. `20GB` should work.
