### ISSUE TITLE
Funds Not Appearing in Wallet

### ISSUE THREAD

**Issue by Hewg74** [NebulousLabs/Sia#1807]
Hi,

 I sent a whole bunch of funds to my wallet Via Shapeshift but it does not seem to have gone through. The below links are the hashes linked to my previous transactions. Only 1 of the 5 successful transactions can be found in my wallet. I used the tool located here
https://github.com/NebulousLabs/Sia-UI/issues/581#issuecomment-299747969
to update my wallet but it still looks like funds are missing. Can you please let me know what I can do to track the funds?

You made a deposit to this address: Lcyso86NnNesXdeGcjjDQ2jYCdBtzyuQFi that completed successfully as you can see here:  https://explore.sia.tech/hash.html?hash=309e62db84398fab451bd457e8318997d35356b5569340c851d3ebfd26f5d610

You made a deposit to this address: LQM8Mn9Fq96GE4H1nNeNjkvz8Tqxank91F that completed successfully as you can see here: https://explore.sia.tech/hash.html?hash=5e6db69ad18109e29080bbb51573595869423ec450c0f0060fdf6a938bb08c75

You made a deposit to this address: that completed successfully as you can see here: https://explore.sia.tech/hash.html?hash=23a240d2a32d1b4184edc654b8d91fdfad4ea4798613310e197c2320beef62b9 .

The transaction to this address: 0xdc410d5307af4c0ce062fe2f3dc65867cc1e37df failed because the deposit was over the limit. Upon failing we returned the funds as you can see here: https://etherscan.io/tx/0x986633ed6265e4cfe08736d5c5473f020202a0aa8da235b9335c9a63b67d8f79

The transaction to this address: 0x809b2690157d8e6613684035795cae58e1e59f4f completed successfully as you can see here: https://explore.sia.tech/hash.html?hash=e2b028684e0a8670619f45a964b4c95224ce5e9f816861b9ec4e9556528a124f

The transaction to this address: 0x38686f9b3355e6b3c0e2627ec1288db7ada579e2 completed successfully as you can see here: https://explore.sia.tech/hash.html?hash=115ff83bbc62c72ecc2eb31408f681a766d726993ecf130f71c3ce9fa9daa837 .

**Comment by Hewg74** [comment]
Bump? Can someone please assist?

**Comment by Bojak4616** [comment]
Issue appears to be on Polo's end, which is where Shapeshift exchanges SC. I'd suggest contacting Shapeshift support if the coins have not bounced back to your client.

https://forum.sia.tech/topic/965/lost-transfer-of-siacoin-from-poloniex

**Comment by Hewg74** [comment]
Hi, I contacted shapeshift help, and they sent me the message below.

They are also copied on this email. Only the 1st link went through, which
you can see in my snap. Please let me know if theres anything else I can do
[image: Inline image 1]


You made a deposit to this address: Lcyso86NnNesXdeGcjjDQ2jYCdBtzyuQFi that
completed successfully as you can see here:  https://explore.sia.tech/hash
.html?hash=309e62db84398fab451bd457e8318997d35356b5569340c851d3ebfd26f5d610

You made a deposit to this address: LQM8Mn9Fq96GE4H1nNeNjkvz8Tqxank91F that
completed successfully as you can see here: https://explore.sia.
tech/hash.html?hash=5e6db69ad18109e29080bbb51573595869423ec4
50c0f0060fdf6a938bb08c75

You made a deposit to this address: that completed successfully as you can
see here: https://explore.sia.tech/hash.html?hash=23a240d2a3
2d1b4184edc654b8d91fdfad4ea4798613310e197c2320beef62b9 .

The transaction to this address: 0xdc410d5307af4c0ce062fe2f3dc65867cc1e37df
failed because the deposit was over the limit. Upon failing we returned the
funds as you can see here: https://etherscan.io/tx/
0x986633ed6265e4cfe08736d5c5473f020202a0aa8da235b9335c9a63b67d8f79

The transaction to this address:
0x809b2690157d8e6613684035795cae58e1e59f4f completed
successfully as you can see here: https://explore.sia.
tech/hash.html?hash=e2b028684e0a8670619f45a964b4c95224ce5e9f
816861b9ec4e9556528a124f

The transaction to this address: 0x38686f9b3355e6b3c0e2627ec1288db7ada579e2
completed successfully as you can see here: https://explore.sia.
tech/hash.html?hash=115ff83bbc62c72ecc2eb31408f681a766d72699
3ecf130f71c3ce9fa9daa837 .

If you could send us the specific transactions that are in question I'd be
happy to look at them.

Cheers,
Cameron

**Comment by tbenz9** [comment]
This looks like an issue with the exchange, and if it's an issue with Sia it's likely an isolated case.

Recommendation to devs: Close
