### ISSUE TITLE
WALLET

### ISSUE THREAD

**Issue by Smash08** [NebulousLabs/Sia#1812]
Every time I try to unlock the wallet it gives an error and it starts to synchronize again, I also sent coins to the wallet and the balance continues 0. What can I do about it?

Log error only appears this

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.071850292 seconds

**Comment by DavidVorick** [comment]
Do you know what error it gives?
