### ISSUE TITLE
Can not open my wallet

### ISSUE THREAD

**Issue by harryburli** [NebulousLabs/Sia#1815]
Hi,

I updated Sia-UI-v1.0.4-lts-linux-x64 to Sia-UI-v1.2.1-linux-x64
after trying to unlock my wallet I got the following errors.

What can I do to be able to access my wallet.

Thanks in advance.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.320494606 seconds

Wallet: scanned to height 70779...
Wallet: scanned to height 70844...
Wallet: scanned to height 70854...
Wallet: scanned to height 70861...
Wallet: scanned to height 70874...
Wallet: scanned to height 70880...
Wallet: scanned to height 70888...
Wallet: scanned to height 70893...
Wallet: scanned to height 70898...
Wallet: scanned to height 70907...
Wallet: scanned to height 70913...
Wallet: scanned to height 70917...
Wallet: scanned to height 70933...
Wallet: scanned to height 70937...
Wallet: scanned to height 70941...
Wallet: scanned to height 70951...
Wallet: scanned to height 70957...
Wallet: scanned to height 70963...
Wallet: scanned to height 70965...
Wallet: scanned to height 70972...
Wallet: scanned to height 70977...
Wallet: scanned to height 70984...
Wallet: scanned to height 70990...
Wallet: scanned to height 71001...
Wallet: scanned to height 71003...
Wallet: scanned to height 71016...
Wallet: scanned to height 71020...
Wallet: scanned to height 71024...
Wallet: scanned to height 71042...
Wallet: scanned to height 71045...
Wallet: scanned to height 71051...
Wallet: scanned to height 71060...
Wallet: scanned to height 71062...
Wallet: scanned to height 71070...
Wallet: scanned to height 71091...
Wallet: scanned to height 71108...
Wallet: scanned to height 71113...
Wallet: scanned to height 71122...
Wallet: scanned to height 71132...
Wallet: scanned to height 71138...
Wallet: scanned to height 71159...
Wallet: scanned to height 71163...
Wallet: scanned to height 71169...
Wallet: scanned to height 71184...
Wallet: scanned to height 71204...
Wallet: scanned to height 71224...
Wallet: scanned to height 71230...
Wallet: scanned to height 71248...
Wallet: scanned to height 71256...
Wallet: scanned to height 71260...
Wallet: scanned to height 71268...
Wallet: scanned to height 71276...
Wallet: scanned to height 71290...
Wallet: scanned to height 71308...
Wallet: scanned to height 71316...
Wallet: scanned to height 71330...
Wallet: scanned to height 71343...
Wallet: scanned to height 71358...
Wallet: scanned to height 71397...
Wallet: scanned to height 71417...
Wallet: scanned to height 71447...
Wallet: scanned to height 71466...
Wallet: scanned to height 71496...
Wallet: scanned to height 71512...
Wallet: scanned to height 71523...
Wallet: scanned to height 71554...
Wallet: scanned to height 71577...
Wallet: scanned to height 71584...
Wallet: scanned to height 71595...
Wallet: scanned to height 71625...
Wallet: scanned to height 71655...
Wallet: scanned to height 71672...
Wallet: scanned to height 71679...
Wallet: scanned to height 71686...
Wallet: scanned to height 71696...
Wallet: scanned to height 71706...
Wallet: scanned to height 71750...
Wallet: scanned to height 71773...
Wallet: scanned to height 71788...
Wallet: scanned to height 71791...
Wallet: scanned to height 71803...
Wallet: scanned to height 71818...
Wallet: scanned to height 71824...
Wallet: scanned to height 71877...
Wallet: scanned to height 71896...
Wallet: scanned to height 71904...
Wallet: scanned to height 71931...
Wallet: scanned to height 71945...
Wallet: scanned to height 71963...
Wallet: scanned to height 72005...
Wallet: scanned to height 72022...
Wallet: scanned to height 72077...
Wallet: scanned to height 72079...
Wallet: scanned to height 72115...
Wallet: scanned to height 72122...
Wallet: scanned to height 72184...
Wallet: scanned to height 72200...
Wallet: scanned to height 72222...
Wallet: scanned to height 72235...
Wallet: scanned to height 72268...
Wallet: scanned to height 72293...
Wallet: scanned to height 72324...
Wallet: scanned to height 72341...
Wallet: scanned to height 72368...
Wallet: scanned to height 72376...
Wallet: scanned to height 72383...
Wallet: scanned to height 72389...
Wallet: scanned to height 72419...
Wallet: scanned to height 72434...
Wallet: scanned to height 72457...
Wallet: scanned to height 72497...
Wallet: scanned to height 72542...
Wallet: scanned to height 72578...
Wallet: scanned to height 72636...
Wallet: scanned to height 72690...
Wallet: scanned to height 72716...
Wallet: scanned to height 72746...
Wallet: scanned to height 72762...
Wallet: scanned to height 72781...
Wallet: scanned to height 72820...
Wallet: scanned to height 72893...
Wallet: scanned to height 72940...
Wallet: scanned to height 72965...
Wallet: scanned to height 73050...2017/05/20 17:34:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/20 17:34:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/20 17:34:18 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/20 17:34:18 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/20 17:34:18 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/20 17:34:19 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:20 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:21 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:22 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:23 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:24 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:27 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/20 17:34:28 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

**Comment by TheRoliYogi** [comment]
Hi.
I have the same Problem with the same Version.
Any glue?
Thanks,
Roland

**Comment by johnathanhowell** [comment]
This has been fixed in the latest master, but hasn't been pushed out in a major release yet. We built a release candidate this week, it should fix this issue. We uploaded the RC here: https://pixeldra.in/l/KT8dJH

**Comment by harryburli** [comment]
Thank you for the info, I'm going to test it.

**Comment by harryburli** [comment]
Johnathan you made my day!
It worked :-)
please give me your SIA-address I wanna send you some coins.

**Comment by johnathanhowell** [comment]
That's not necessary, glad that your problem is fixed.
