### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by yuandi0823** [NebulousLabs/Sia#1816]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.3644361 seconds

**Comment by DavidVorick** [comment]
Is there more context? Out of memory maybe? What version are you running?

Perhaps we should make an issue template for these.

**Comment by tetreault** [comment]
possible duplicate #1818, #1817, #1819, #1893
