### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by satur-9** [NebulousLabs/Sia#1817]
start siaui, wait for blockchain to synch, go to wallet, enter password, get the message and this log file. any help appreciated:

[sia satur9.txt](https://github.com/NebulousLabs/Sia/files/1016478/sia.satur9.txt)

**Comment by lukechampine** [comment]
Looks like an obscure boltdb error. What is your OS and architecture?

**Comment by satur-9** [comment]
windows 7 home premium, 64bit
![alienware m11x](https://cloud.githubusercontent.com/assets/28830464/26322188/b9a4a60c-3f21-11e7-95e9-9b89c7bde8a0.jpg)

**Comment by tetreault** [comment]
possible duplicate #1816, #1818, #1819, #1893
