### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by Sl0wmind** [NebulousLabs/Sia#1818]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.302249203 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0x421f8f5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x421f8f948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd04, 0xe, 0x7fff5fbffd30, 0x5, 0x7fff5fbffd1f, 0x5, 0x0, 0x7fff5fbffd40, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0x421c37200, 0x421c39270, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0x421c37200, 0x421c10070, 0x5, 0x5, 0x421c37200, 0x421c10070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0x421c37200, 0x16c6004, 0x3b, 0x421d0aaa0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c37200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by nicexe** [comment]
I got something similar and the error matches:

```Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.181307457 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0x421d475f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0x421d47948, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:15 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcfc, 0xe, 0x7fff5fbffd28, 0x5, 0x7fff5fbffd17, 0x5, 0x0, 0x7fff5fbffd38, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0x421c15200, 0x421bbf4a0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0x421c15200, 0x421bb60d0, 0x5, 0x5, 0x421c15200, 0x421bb60d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:648 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0x421c15200, 0x16c6004, 0x3b, 0x421cdeaa0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0x421c15200, 0x1aa4520, 0x16af49d)
	/home/luke/go/src/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7ac
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
```

**Comment by johnathanhowell** [comment]
What versions are these from? 1.2.2 fixed problems related to `too many open files in system`

**Comment by nicexe** [comment]
That was on 1.2.1

**Comment by johnathanhowell** [comment]
1.2.2 should resolve this issue. Please report back if this happens again on 1.2.2.

**Comment by tetreault** [comment]
possible duplicate #1816, #1817, #1819, #1893
