### ISSUE TITLE
Linux ARM builds

### ISSUE THREAD

**Issue by Teesla** [NebulousLabs/Sia#1825]
Can we have linux ARMv7 builds too please? Very useful for running on low power boards like RPi and such. Thanks!

**Comment by lf94** [comment]
Why not build your own with a cross-platform compiler?

**Comment by johnathanhowell** [comment]
actually, you can build your own arm binaries easily:

`GOOS=linux GOARCH=arm64 go build -o siad-arm ./siad`
`GOOS=linux GOARCH=arm64 go build -o siac-arm ./siac`

**Comment by lf94** [comment]
Ah, and building the dependencies is no issue?

**Comment by johnathanhowell** [comment]
correct, you just need to run `go get -u github.com/NebulousLabs/Sia/...` as indicated in the README first.

**Comment by lf94** [comment]
Very awesome.

I don't know a whole lot about Go, but is there MIPS support? Is there Sia-specific assembly written or none?

**Comment by johnathanhowell** [comment]
There is no Sia-specific assembly written. The Go compiler supports mips64 and mips64le as build targets (`GOARCH`)

**Comment by lukechampine** [comment]
Closing for now. We can make a serious effort to get Sia compiling on ARM if there's enough interest+resources to do so.

**Comment by Teesla** [comment]
At the moment siad easily consumes 2-3 GB of RAM during blockchain catching up. There are too few consumer ARM devices that can handle that :(

**Comment by tehfink** [comment]
An arm64 version would be great!
FYI, storj runs on a Raspberry Pi:
https://docs.storj.io/v1.1/docs/setting-up-storj-share-on-a-raspberry-pi
