### ISSUE TITLE
Explorer backend returns 502

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#1826]
See https://explore.sia.tech/explorer/blocks/100500

Other blocks return 200, e.g. https://explore.sia.tech/explorer/blocks/1
I guess the backend is down but Cloudflare cached some pages.

**Comment by tbenz9** [comment]
This is certainly a bug but would probably be more appropriate in the sia.tech repo.

Recommendation to devs: move issue (if possible) or close

**Comment by tbenz9** [comment]
This has been fixed with the new explorer from Luxor.
