### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by Pixon** [NebulousLabs/Sia#1830]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.9329326 seconds

**Comment by lf94** [comment]
You need to post the rest of the error log.
