### ISSUE TITLE
Host Unreachable

### ISSUE THREAD

**Issue by leucinedreams** [NebulousLabs/Sia#1832]
While almost everything appears functional on Linux, when I attempt to host, I'm told that "Host Unreachable" and "Your host is not connectable at the configured net address. Check your UPNP or NAT settings." I've tried on two different internet access points and received the same result each time.

**Comment by and282882** [comment]
I'm currently trying to set up a host on arch linux and have the same issue. I need to spend some more time looking into the issue since my knowledge is kind of rough with ports/networking etc but will post any updates.

**Comment by lukechampine** [comment]
"Host Unreachable" is slightly misleading. It not only checks that your ports are open, but also that peers are able to connect and form contracts with you. This can shed light on certain errors that a port check cannot. I recommend using a separate port checking tool to verify whether your ports are open. If they are, and you haven't formed any contacts in a reasonable time period, check your host log.

**Comment by pacuna** [comment]
I had the same issue in Fedora. I checked the ports to see if they were listening (with netstat) and they were open. 5 minutes later the error went away and now it says Host Online. Maybe it just needs some time?

**Comment by legleux** [comment]
I'm having this issue with  Sia 1.2.2 on Windows 10.
Immediately after syncing the host seems to be reachable and fine and as long as I look at it. An indeterminate time later, the host is unreachable.
I have ports forwarded correctly but the sia log seems to say that upnp isn't working.
netstat shows that sia is listening on the correct ports but I'm not sure which port is necessary for advertising as being a host.

**Comment by legleux** [comment]
and yet I see this in the logs:
gateway:
```
2017/06/01 02:38:16.454682 gateway.go:241: STARTUP: Logging has started.
2017/06/01 02:38:16.455684 gateway.go:253: INFO: gateway created, started logging
2017/06/01 02:38:29.081544 upnp.go:83: INFO: our address is <x.x.x.x>:9981
2017/06/01 02:38:29.121148 upnp.go:110: INFO: successfully forwarded port 9981
```
host:
```
2017/06/01 02:38:16.535897 dependencies.go:105: STARTUP: Logging has started.
2017/06/01 02:38:32.149670 upnp.go:131: INFO: successfully forwarded port 9982
```
Am I even looking at the right thing?

**Comment by Slapbox** [comment]
Any update on this?

**Comment by Odoardo** [comment]
I'm having exactly the same issue with Sia 1.2.2 in macOS Sierra on a 27-inch iMac from late 2013. Like legleux, after syncing the host I see "Host Online" at the top of the screen. However, after maybe 10 or 15 minutes the host suddenly becomes unreachable and I see "Host Unreachable" at the top of the screen. I have logged into my modem and checked that Sia is listening on ports 9981 and 9982. Does anyone have any suggestions as to how I may be able to resolve this issue?

**Comment by legleux** [comment]
I'm not sure what the underlying problem was or exactly how to fix it.
At some point I wiped out the %appdata%\Sia-UI\sia\host\host.json file, restarted and when the file was generated again, the ip address was different and I'm not connectable consistently.
Sorry I couldn't be more helpful!

**Comment by Odoardo** [comment]
Lucky you. I thought I'd give the Sia UI another go. Unfortunately, as per my earlier message nothing has changed. Suffice to say I'm still getting the "Host Unreachable" message about 15 minutes after synchronization has finished. Someone must know what is causing this and how to fix it. Is there anyone out there who can help me to get this working?
