### ISSUE TITLE
Where the blockchains are stored in Windows7?

### ISSUE THREAD

**Issue by mertimiks** [NebulousLabs/Sia#1833]
Hi,

I download wallet on win 7 but then I accidently create a new wallet instead of restoring the old one. So I deleted the SIA files, and download and installed the wallet again. And now it is downloading its blockchains.

So my question is in my previous download, there were some blochains were download as well, and I am not sure I deleted them. Or do I need to delete them? Would I have any problem using the wallet when I redownload blockchains for different wallet? thanks.

**Comment by mertimiks** [comment]
Actually, I just find out I cannot create a new wallet. I need to delete blockchains I think, but I do not know where they are stored.

**Comment by johnathanhowell** [comment]
The data for Sia-UI is stored under `%APPDATA%\Sia-UI\sia`. You can restore your existing wallet without deleting the blockchain data by entering `wallet init-seed --force` in the Terminal view (on 1.2.2).
