### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report

### ISSUE THREAD

**Issue by aaronmda** [NebulousLabs/Sia#1838]
every time i try to add a storage folder this is what i get:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.316432518 seconds
2017/05/25 10:25:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/25 10:25:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/25 10:25:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/25 10:26:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/25 10:26:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/25 10:26:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

**Comment by lf94** [comment]
Apparently this is fixed in Sia 1.2.2

**Comment by aaronmda** [comment]
well that's the version i'm using on Ubuntu so apparently it has not been resolved

**Comment by aaronmda** [comment]
Sia-UI-v1.2.2-linux-x64.zip

**Comment by lf94** [comment]
All I can say is try again. There are too many file handles that are being kept open.

**Comment by johnathanhowell** [comment]
Did you upgrade from 1.2.1, or start with 1.2.2?

**Comment by aaronmda** [comment]
i started with it

**Comment by johnathanhowell** [comment]
Is it possible you can try doing this without the UI, to isolate the problem?

Start siad from the command line:
`siad --sia-directory=~/.config/Sia-UI/sia`

Use siac to add a storage folder:
`siac host folder add [path] [size]`

**Comment by aaronmda** [comment]
ill try it out when i have time. maybe give windows a try i just really wanted to run it on my linux machine

**Comment by johnathanhowell** [comment]
Looked into this, looks like the bug fix for this did not get correctly compiled into the release. We'll update the release binaries soon

**Comment by aaronmda** [comment]
no worries managed to get the folder added. turns out Sia does not like spaces in the folder name

**Comment by droghio** [comment]
Looks like this is related to #1860 and #1840.
