### ISSUE TITLE
Setting fee for transaction

### ISSUE THREAD

**Issue by miningpoolhub** [NebulousLabs/Sia#1841]
I couldn't find any API for setting fee for transaction.
Please advice me if there's any API for it.

**Comment by lukechampine** [comment]
This is planned for the next release. It should be pretty simple to implement. If you have an immediate need to set the fee, you can manually change the fee value in the Send siacoins function (modules/wallet/money.go) and recompile.

**Comment by miningpoolhub** [comment]
Thanks!

**Comment by lukechampine** [comment]
This is now supported
