### ISSUE TITLE
cant start with my wallet

### ISSUE THREAD

**Issue by garryang89** [NebulousLabs/Sia#1857]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.7100406 seconds

**Comment by droghio** [comment]
Can you be more detailed with the behavior you are seeing? That message seems to indicate Sia launched fine. What version of Sia and which OS are you using?
