### ISSUE TITLE
Siad has stopped

### ISSUE THREAD

**Issue by amirheavy666** [NebulousLabs/Sia#1866]
when my wallet open, after 2-5 second this Error has been showed : " Siad has stopped "  
i click on" start siad " but it is again showed.

my version wallet is V 1.0.2

can i upgrade my wallet for solving this Error ? how can? my coins in  this wallet will be lost??
please guide me

**Comment by droghio** [comment]
You can upgrade, any coins in your wallet are safe as long as you have your seed.
