### ISSUE TITLE
Unable to load Wallet

### ISSUE THREAD

**Issue by rv888** [NebulousLabs/Sia#1874]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.141312177 seconds

Wallet: scanned to height 39722...
Wallet: scanned to height 39822...
Wallet: scanned to height 39966...
Wallet: scanned to height 40537...
Wallet: scanned to height 40553...
Wallet: scanned to height 40585...
Wallet: scanned to height 40629...
Wallet: scanned to height 40665...
Wallet: scanned to height 40704...
Wallet: scanned to height 40732...
Wallet: scanned to height 40774...
Wallet: scanned to height 40823...
Wallet: scanned to height 40830...
Wallet: scanned to height 40864...
Wallet: scanned to height 40893...
Wallet: scanned to height 40944...
Wallet: scanned to height 41007...
Wallet: scanned to height 41085...
Wallet: scanned to height 41202...
Wallet: scanned to height 41238...
Wallet: scanned to height 41326...
Wallet: scanned to height 41376...
Wallet: scanned to height 41461...
Wallet: scanned to height 41541...
Wallet: scanned to height 41571...
Wallet: scanned to height 41578...
Wallet: scanned to height 41617...
Wallet: scanned to height 41623...
Wallet: scanned to height 41628...
Wallet: scanned to height 41641...
Wallet: scanned to height 41641...
Wallet: scanned to height 41648...
Wallet: scanned to height 41657...
Wallet: scanned to height 41666...
Wallet: scanned to height 41673...
Wallet: scanned to height 41679...
Wallet: scanned to height 41700...
Wallet: scanned to height 41711...
Wallet: scanned to height 41731...
Wallet: scanned to height 41735...
Wallet: scanned to height 41745...
Wallet: scanned to height 41753...
Wallet: scanned to height 41759...
Wallet: scanned to height 41770...
Wallet: scanned to height 41775...
Wallet: scanned to height 41826...
Wallet: scanned to height 41857...
Wallet: scanned to height 41874...
Wallet: scanned to height 41890...
Wallet: scanned to height 41913...
Wallet: scanned to height 41955...
Wallet: scanned to height 41966...
Wallet: scanned to height 41998...
Wallet: scanned to height 42020...
Wallet: scanned to height 42043...
Wallet: scanned to height 42063...
Wallet: scanned to height 42105...
Wallet: scanned to height 42134...
Wallet: scanned to height 42149...
Wallet: scanned to height 42180...
Wallet: scanned to height 42198...
Wallet: scanned to height 42233...
Wallet: scanned to height 42276...
Wallet: scanned to height 42310...
Wallet: scanned to height 42337...
Wallet: scanned to height 42353...
Wallet: scanned to height 42359...
Wallet: scanned to height 42396...
Wallet: scanned to height 42428...
Wallet: scanned to height 42450...
Wallet: scanned to height 42476...
Wallet: scanned to height 42490...
Wallet: scanned to height 42601...
Wallet: scanned to height 42705...
Wallet: scanned to height 42818...
Wallet: scanned to height 42935...
Wallet: scanned to height 42950...
Wallet: scanned to height 43008...
Wallet: scanned to height 43097...
Wallet: scanned to height 43197...
Wallet: scanned to height 43273...
Wallet: scanned to height 43298...
Wallet: scanned to height 43339...
Wallet: scanned to height 43408...
Wallet: scanned to height 43449...
Wallet: scanned to height 43473...
Wallet: scanned to height 43484...
Wallet: scanned to height 43522...
Wallet: scanned to height 43560...
Wallet: scanned to height 43601...
Wallet: scanned to height 43627...
Wallet: scanned to height 43637...
Wallet: scanned to height 43697...
Wallet: scanned to height 43722...
Wallet: scanned to height 43737...
Wallet: scanned to height 43778...
Wallet: scanned to height 43784...
Wallet: scanned to height 43795...
Wallet: scanned to height 43803...
Wallet: scanned to height 43821...
Wallet: scanned to height 43838...
Wallet: scanned to height 43854...
Wallet: scanned to height 43890...
Wallet: scanned to height 43931...
Wallet: scanned to height 43993...
Wallet: scanned to height 44050...
Wallet: scanned to height 44082...
Wallet: scanned to height 44146...
Wallet: scanned to height 44162...
Wallet: scanned to height 44182...
Wallet: scanned to height 44226...
Wallet: scanned to height 44267...
Wallet: scanned to height 44273...
Wallet: scanned to height 44286...
Wallet: scanned to height 44291...
Wallet: scanned to height 44299...
Wallet: scanned to height 44302...
Wallet: scanned to height 44318...
Wallet: scanned to height 44340...
Wallet: scanned to height 44355...
Wallet: scanned to height 44374...
Wallet: scanned to height 44386...
Wallet: scanned to height 44404...
Wallet: scanned to height 44408...
Wallet: scanned to height 44429...
Wallet: scanned to height 44456...
Wallet: scanned to height 44476...
Wallet: scanned to height 44513...
Wallet: scanned to height 44524...
Wallet: scanned to height 44536...
Wallet: scanned to height 44538...
Wallet: scanned to height 44543...
Wallet: scanned to height 44548...
Wallet: scanned to height 44567...
Wallet: scanned to height 44575...
Wallet: scanned to height 44579...
Wallet: scanned to height 44588...
Wallet: scanned to height 44598...
Wallet: scanned to height 44600...
Wallet: scanned to height 44619...
Wallet: scanned to height 44628...
Wallet: scanned to height 44639...
Wallet: scanned to height 44655...
Wallet: scanned to height 44663...
Wallet: scanned to height 44690...
Wallet: scanned to height 44713...
Wallet: scanned to height 44722...
Wallet: scanned to height 44756...
Wallet: scanned to height 44789...
Wallet: scanned to height 44797...
Wallet: scanned to height 44799...
Wallet: scanned to height 44808...
Wallet: scanned to height 44831...
Wallet: scanned to height 44837...
Wallet: scanned to height 44842...
Wallet: scanned to height 44845...
Wallet: scanned to height 44855...
Wallet: scanned to height 44858...
Wallet: scanned to height 44875...
Wallet: scanned to height 44885...
Wallet: scanned to height 44904...
Wallet: scanned to height 44926...
Wallet: scanned to height 44931...
Wallet: scanned to height 44948...
Wallet: scanned to height 44965...
Wallet: scanned to height 44986...
Wallet: scanned to height 44991...
Wallet: scanned to height 45001...
Wallet: scanned to height 45012...
Wallet: scanned to height 45025...
Wallet: scanned to height 45026...
Wallet: scanned to height 45056...
Wallet: scanned to height 45098...
Wallet: scanned to height 45106...
Wallet: scanned to height 45125...
Wallet: scanned to height 45159...
Wallet: scanned to height 45183...
Wallet: scanned to height 45218...
Wallet: scanned to height 45235...
Wallet: scanned to height 45270...
Wallet: scanned to height 45279...
Wallet: scanned to height 45291...
Wallet: scanned to height 45310...
Wallet: scanned to height 45340...
Wallet: scanned to height 45351...
Wallet: scanned to height 45367...
Wallet: scanned to height 45389...
Wallet: scanned to height 45408...
Wallet: scanned to height 45419...
Wallet: scanned to height 45435...
Wallet: scanned to height 45458...
Wallet: scanned to height 45487...
Wallet: scanned to height 45491...
Wallet: scanned to height 45497...
Wallet: scanned to height 45503...
Wallet: scanned to height 45522...
Wallet: scanned to height 45540...
Wallet: scanned to height 45564...
Wallet: scanned to height 45583...
Wallet: scanned to height 45606...2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/03 07:47:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/03 07:47:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms

Wallet: scanned to height 45626...2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/03 07:47:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/03 07:47:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/03 07:47:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 45636...2017/06/03 07:47:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/03 07:47:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/06/03 07:47:10 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

Wallet: scanned to height 45663...2017/06/03 07:47:11 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
goroutine 16665 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc425f19c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc425f19e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42046ec20, 0xc425f19e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc425118360, 0xc420468548, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: ERROR: unable to create write-ahead-log: open /home/rvbox1/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: too many open files
goroutine 16664 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc423774d68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc423774ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42046ec20, 0xc423774ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc425118360, 0xc420468548)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
Severe error: Unable to open temporary settings file for writing: open /home/rvbox1/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files
goroutine 16665 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc425f19c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc425f19e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42046ec20, 0xc425f19e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc425118360, 0xc420468548, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 16665 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc425f19aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc425f19c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42046ec20, 0xc425f19c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420468548, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc425118360, 0xc420468548, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 16665 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc420468548, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc425118360, 0xc420468548, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by droghio** [comment]
Probably dup of #1840. Try redownloading Sia.
