### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tigerz7z** [NebulousLabs/Sia#1875]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.420833647 seconds

Wallet: scanned to height 6024...
Wallet: scanned to height 9137...
Wallet: scanned to height 11236...
Wallet: scanned to height 14982...
Wallet: scanned to height 17873...
Wallet: scanned to height 20450...
Wallet: scanned to height 22690...
Wallet: scanned to height 23463...
Wallet: scanned to height 26266...
Wallet: scanned to height 28509...
Wallet: scanned to height 30486...
Wallet: scanned to height 32510...
Wallet: scanned to height 33396...
Wallet: scanned to height 34034...
Wallet: scanned to height 34371...
Wallet: scanned to height 34555...
Wallet: scanned to height 34662...
Wallet: scanned to height 34776...
Wallet: scanned to height 34895...
Wallet: scanned to height 34998...
Wallet: scanned to height 35156...
Wallet: scanned to height 35323...
Wallet: scanned to height 35727...
Wallet: scanned to height 36118...
Wallet: scanned to height 36429...
Wallet: scanned to height 36789...
Wallet: scanned to height 37023...
Wallet: scanned to height 37351...
Wallet: scanned to height 37576...
Wallet: scanned to height 38100...
Wallet: scanned to height 38485...
Wallet: scanned to height 38627...
Wallet: scanned to height 38830...
Wallet: scanned to height 39199...
Wallet: scanned to height 39382...
Wallet: scanned to height 39572...
Wallet: scanned to height 39785...
Wallet: scanned to height 40028...
Wallet: scanned to height 40445...
Wallet: scanned to height 40879...
Wallet: scanned to height 41608...
Wallet: scanned to height 41706...
Wallet: scanned to height 41781...
Wallet: scanned to height 42000...
Wallet: scanned to height 42224...
Wallet: scanned to height 42423...
Wallet: scanned to height 43427...
Wallet: scanned to height 43830...
Wallet: scanned to height 44293...
Wallet: scanned to height 44365...
Wallet: scanned to height 44489...
Wallet: scanned to height 44614...
Wallet: scanned to height 44741...
Wallet: scanned to height 44896...
Wallet: scanned to height 45031...
Wallet: scanned to height 45207...
Wallet: scanned to height 45450...
Wallet: scanned to height 45615...
Wallet: scanned to height 45830...
Wallet: scanned to height 46134...
Wallet: scanned to height 46734...
Wallet: scanned to height 47196...
Wallet: scanned to height 47497...
Wallet: scanned to height 47646...
Wallet: scanned to height 48069...
Wallet: scanned to height 48694...
Wallet: scanned to height 49477...
Wallet: scanned to height 50546...
Wallet: scanned to height 51053...
Wallet: scanned to height 51684...
Wallet: scanned to height 52993...
Wallet: scanned to height 53387...
Wallet: scanned to height 53768...
Wallet: scanned to height 54195...
Wallet: scanned to height 54513...
Wallet: scanned to height 55475...
Wallet: scanned to height 56306...
Wallet: scanned to height 56895...
Wallet: scanned to height 57721...
Wallet: scanned to height 58738...
Wallet: scanned to height 60133...
Wallet: scanned to height 60564...
Wallet: scanned to height 60979...
Wallet: scanned to height 61414...
Wallet: scanned to height 61791...
Wallet: scanned to height 62125...
Wallet: scanned to height 62530...
Wallet: scanned to height 62939...
Wallet: scanned to height 63313...
Wallet: scanned to height 63674...
Wallet: scanned to height 64037...
Wallet: scanned to height 64413...
Wallet: scanned to height 64801...
Wallet: scanned to height 65171...
Wallet: scanned to height 65566...
Wallet: scanned to height 65849...
Wallet: scanned to height 66157...
Wallet: scanned to height 66496...
Wallet: scanned to height 66789...
Wallet: scanned to height 67197...
Wallet: scanned to height 67575...
Wallet: scanned to height 67955...
Wallet: scanned to height 68315...
Wallet: scanned to height 68670...
Wallet: scanned to height 69055...
Wallet: scanned to height 69447...
Wallet: scanned to height 69864...
Wallet: scanned to height 70205...
Wallet: scanned to height 70512...
Wallet: scanned to height 70825...
Wallet: scanned to height 71161...
Wallet: scanned to height 71488...
Wallet: scanned to height 71829...
Wallet: scanned to height 72170...
Wallet: scanned to height 72542...
Wallet: scanned to height 72892...
Wallet: scanned to height 73227...
Wallet: scanned to height 73577...
Wallet: scanned to height 73934...
Wallet: scanned to height 74294...
Wallet: scanned to height 74629...
Wallet: scanned to height 74977...
Wallet: scanned to height 75315...
Wallet: scanned to height 75637...
Wallet: scanned to height 75972...
Wallet: scanned to height 76278...
Wallet: scanned to height 76633...
Wallet: scanned to height 76986...
Wallet: scanned to height 77387...
Wallet: scanned to height 77834...
Wallet: scanned to height 78303...
Wallet: scanned to height 78699...
Wallet: scanned to height 79069...
Wallet: scanned to height 79429...
Wallet: scanned to height 79777...
Wallet: scanned to height 80177...
Wallet: scanned to height 80530...
Wallet: scanned to height 80632...
Wallet: scanned to height 80906...
Wallet: scanned to height 81221...
Wallet: scanned to height 81309...
Wallet: scanned to height 81564...
Wallet: scanned to height 81890...
Wallet: scanned to height 82227...
Wallet: scanned to height 82562...
Wallet: scanned to height 82907...
Wallet: scanned to height 83306...
Wallet: scanned to height 83715...
Wallet: scanned to height 84075...
Wallet: scanned to height 84445...
Wallet: scanned to height 84822...
Wallet: scanned to height 85209...
Wallet: scanned to height 85585...
Wallet: scanned to height 85944...
Wallet: scanned to height 86060...
Wallet: scanned to height 86197...
Wallet: scanned to height 86385...
Wallet: scanned to height 86540...
Wallet: scanned to height 86779...
Wallet: scanned to height 87075...
Wallet: scanned to height 87330...
Wallet: scanned to height 87698...
Wallet: scanned to height 87864...
Wallet: scanned to height 88044...
Wallet: scanned to height 88297...
Wallet: scanned to height 88686...
Wallet: scanned to height 89116...
Wallet: scanned to height 89462...
Wallet: scanned to height 89827...
Wallet: scanned to height 90289...
Wallet: scanned to height 90680...
Wallet: scanned to height 91109...
Wallet: scanned to height 91597...
Wallet: scanned to height 91980...
Wallet: scanned to height 92085...
Wallet: scanned to height 92302...
Wallet: scanned to height 92703...
Wallet: scanned to height 93124...
Wallet: scanned to height 93556...
Wallet: scanned to height 93967...
Wallet: scanned to height 94361...
Wallet: scanned to height 94811...
Wallet: scanned to height 95300...
Wallet: scanned to height 95711...
Wallet: scanned to height 96112...
Wallet: scanned to height 96536...
Wallet: scanned to height 96846...
Wallet: scanned to height 97211...
Wallet: scanned to height 97503...
Wallet: scanned to height 97558...
Wallet: scanned to height 97624...
Wallet: scanned to height 97718...
Wallet: scanned to height 97892...
Wallet: scanned to height 98121...
Wallet: scanned to height 98408...
Wallet: scanned to height 98578...
Wallet: scanned to height 98802...
Wallet: scanned to height 99069...
Wallet: scanned to height 99326...
Wallet: scanned to height 99550...
Wallet: scanned to height 99666...
Wallet: scanned to height 99790...
Wallet: scanned to height 99954...
Wallet: scanned to height 100062...
Wallet: scanned to height 100166...
Wallet: scanned to height 100259...
Wallet: scanned to height 100430...
Wallet: scanned to height 100628...
Wallet: scanned to height 100732...
Wallet: scanned to height 100809...
Wallet: scanned to height 100880...
Wallet: scanned to height 100953...
Wallet: scanned to height 101038...
Wallet: scanned to height 101138...
Wallet: scanned to height 101318...
Wallet: scanned to height 101564...
Wallet: scanned to height 101786...
Wallet: scanned to height 102008...
Wallet: scanned to height 102180...
Wallet: scanned to height 102342...
Wallet: scanned to height 102508...
Wallet: scanned to height 102685...
Wallet: scanned to height 102889...
Wallet: scanned to height 103103...
Wallet: scanned to height 103301...
Wallet: scanned to height 103504...
Wallet: scanned to height 103662...
Wallet: scanned to height 103809...
Wallet: scanned to height 103947...
Wallet: scanned to height 104116...
Wallet: scanned to height 104338...
Wallet: scanned to height 104567...
Wallet: scanned to height 104766...
Wallet: scanned to height 105103...
Wallet: scanned to height 105373...
Wallet: scanned to height 105638...
Wallet: scanned to height 105949...
Wallet: scanned to height 106265...
Wallet: scanned to height 106485...
Wallet: scanned to height 106701...
Wallet: scanned to height 106873...
Wallet: scanned to height 107062...
Wallet: scanned to height 107158...
Wallet: scanned to height 107269...
Wallet: scanned to height 107378...
Wallet: scanned to height 107578...
Wallet: scanned to height 107792...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc420fdf5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420fdf948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd54, 0xe, 0x7fff5fbffd80, 0x5, 0x7fff5fbffd6f, 0x5, 0x0, 0x7fff5fbffdd4, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420083200, 0xc420019310, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420083200, 0xc42000e0d0, 0x5, 0x5, 0xc420083200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420083200, 0x16c7c0f, 0x3b, 0xc420150960)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420083200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by droghio** [comment]
When did you download v1.2.2, right when it released? Also which OS are you running? Might be related to #1840

**Comment by tigerz7z** [comment]
I downloaded it just a 3 days ago, I'm using Mac OS X.

**Comment by tigerz7z** [comment]
Still can't see coins, please help to fix
