### ISSUE TITLE
Can't Install SiaWallet...Alternatives or Fix?

### ISSUE THREAD

**Issue by CryptoAddict** [NebulousLabs/Sia#1879]
Hi,

I'm currently mining siacoin.

I've been having trouble installing the wallet on 2 different computers.

One on my windows 10 laptop, and the 2nd on linux. Both have trouble syncing. One is stuck at 32% and the other is stuck at 99%.

Does anybody know a fix?

I'm willing to even go with an alternative wallet as I'm mining to a wallet address on Sia that can't even be opened.

Here's the log from the 99% sync:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.390938616 seconds

???

**Comment by droghio** [comment]
Could you run `gateway list` on one of your machines?

**Comment by CryptoAddict** [comment]
Hi droghio, how would I do that?

Soery, not very tech savvy.

**Comment by droghio** [comment]
If you are running the UI, go to the Terminal Plugin, type `gateway list` in the textbox on the bottom, and then hit enter.
