### ISSUE TITLE
Wallet mysteriously moves coins from auxillary seed to primary seed

### ISSUE THREAD

**Issue by JamesM424** [NebulousLabs/Sia#1880]
Hello Sia team.  

I'm finally reporting some odd wallet behaviour I've been having for two months as I finally tracked down the root cause last week.  And I just saw other users suggesting exactly what I did (possibly wrong?) that caused this, on reddit to other users (see here https://www.reddit.com/r/siacoin/comments/6f32h1/copying_wallet_to_another_machine/).

When I first started trying out Sia, I had one wallet [wallet A] and deposited some (~50K) coins into it.  I quickly screwed up and deleted, created a new wallet and did a force init of the seed.  As the hosting minimum was 20K, I was only expecting one host and one renter.  So with that wallet A, I added it as an Auxiliary seeds to Wallet B.  Times and needs changed and I needed a remote renter.  So without knowing much of the environment at the time, I started up Wallet C and added Wallet A and Wallet B as the Auxiliary seed.

Life was good.  Both new seeds could take from wallet A whenever they needed to put up collateral or issue a new contract.  

Until I started having some odd wallet activity.

I would have random (hash 1b284883679fe016e698f9dbe17fe59e02b141bd5e1fa79147961b0425b8c74f) withdrawals from the wallet that seemingly went stolen.

This happened a few times (2ec911aedfced9c06fdfce631a5f8b7f6465a56aadd7d632659a723913784515).  

Then the other day, I had a larger withdrawal of 20K coins.  (Hash d703d878317cfe0594659bfcf2b7bc0110923881f59106d24b5d4c1232e840bc)

A bit of investigation into the who, when and where on Sia Explorer I looked up the input and output coins as the value is increasing and getting more frequent it would be an issue with the corporate wallet.

As it turned out, the sender was Wallet B and the receiver was Wallet C.

It appears as if when you create a primary seed and init an auxiliary seed, that it doesn't move all funds over at once (sweep).  It also doesn't just take from the aux until it's empty or as needed.  It slowly siphons the aux into the primary with seemingly random reckless abandon. 

I can't say exactly what I would expect as "expected behaviour", but this wouldn't be it.  It could make sense to sweep a seed when it's init'd and monitor it for future deposits.  It could make sense to do nothing at all and just add the seed as a funding source and monitor it.  But - I would think - randomly moving coins around isn't expected.  Or necessary?

Edit - another user can confirm: https://www.reddit.com/r/siacoin/comments/6fg0va/siaui_unknown_transaction/

**Comment by JamesM424** [comment]
tagging another possible failure case for traceability:

https://www.reddit.com/r/siacoin/comments/6g3371/help_are_my_coins_lost/

**Comment by lukechampine** [comment]
My suspicion here is that the primary seed is receiving the "change outputs" when transactions are made that spend outputs from the auxiliary seed. For example:

1. Aux seed has an output worth 100 SC
2. User wants to send 70 SC to a friend
3. Wallet splits 100 SC output into 70 SC and 30 SC outputs
4. 70 SC is sent to friend, 30 SC is sent to primary seed

I can see why this would be surprising, but I'm not sure what the best solution is. You might simply say that the 30 SC should be sent back to the aux seed. But what if you want to spent 100 SC, and you have 4 auxiliary seeds, each with a single 27 SC output? Now we have 10 SC leftover -- do we send 2 SC back to each seed? That could bring us below the "dust threshold," so the outputs would be worthless individually, while a single 10 SC output would not be.

In general I think we perhaps have not done a great job of setting expectations for what an auxiliary seed is and is not. They are more of an "alternate funding source" than a full separate wallet.

**Comment by JamesM424** [comment]
Is it possible to remove the aux seed from wallet file?  I saw how it loaded them, but wasn't sure if there was anything else tied to the wallet, such as displayed balance.

**Comment by lukechampine** [comment]
Not currently. At present, the best you can do is create a new wallet (likely with `init-seed` so that you can retain the previous seed).

**Comment by JamesM424** [comment]
Thanks noss.  That's an interesting idea idea.

If I create a new wallet, do the renting and hosting contracts follow over?

**Comment by lukechampine** [comment]
The contracts reference an address created with the old wallet's seed, so they will "carry over" if the new wallet uses the same seed. The actual contract data lives in the `renter/` or `host/` subdirectories, so those need to be present if you want to keep functioning as a renter or host.

**Comment by JamesM424** [comment]
Perfect solution.  I wanted to wait for an answer because I would have delete the aux first.
