### ISSUE TITLE
Storage folder must be a factor of 64 sectors

### ISSUE THREAD

**Issue by MartijntenCaat** [NebulousLabs/Sia#1888]
Since I've installed SIA I get the following error when I try to add a storage folder.

![schermafdruk van 2017-06-05 19-01-58](https://cloud.githubusercontent.com/assets/29102397/26794406/ce18fa74-4a21-11e7-9323-0c22271c350f.png)

Sia UI version: v1.0.4
Sia version: 1.2.2

How can I solve this issue?

**Comment by johnathanhowell** [comment]
Upgrading to Sia-UI 1.2.2 will fix this.
