### ISSUE TITLE
Siad  Exited unexpectedly for Sia-UI-v1.2.2-win32-x64

### ISSUE THREAD

**Issue by jsha123** [NebulousLabs/Sia#1896]
I ran the Sia-UI-v1.2.2-win32-x64, it synced very slowly.
and in about 4X%， maybe my notebook entered a power saver mode.
the ui stoped. I ran the ui again.

it stoped sync and shows"Siad has exied unexpectedly. PLeaes submit a but report include the error log here"

here is the log:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 73.2251883 seconds

**Comment by jsha123** [comment]
I press the "start said" button , seems started sync.
Log is bellow. 
since the error msg still there, I'm not sure ok or not. (sync not finished)
--------------
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/netwo(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 19.5511183 seconds

**Comment by jsha123** [comment]
seems kill the process. then re start --> OK

**Comment by jcreyesb** [comment]
not work, allways 

 Exited unexpectedly
