### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by jcreyesb** [NebulousLabs/Sia#1899]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.7870451 seconds

Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Sólo se permite un uso de cada dirección de socket (protocolo/dirección de red/puerto)

**Comment by lukechampine** [comment]
Something else is listening on port 9980. Try stopping any existing Sia programs or restarting your computer.

**Comment by glad-zilla** [comment]
Same for me

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 145.319956769 seconds

Wallet: scanned to height 98344...
Wallet: scanned to height 98344...
Wallet: scanned to height 98363...
Wallet: scanned to height 98406...
Wallet: scanned to height 98446...
Wallet: scanned to height 98497...
Wallet: scanned to height 98548...
Wallet: scanned to height 98592...
Wallet: scanned to height 98639...
Wallet: scanned to height 98691...
Wallet: scanned to height 98710...
Wallet: scanned to height 98717...
Wallet: scanned to height 98723...
Wallet: scanned to height 98730...
Wallet: scanned to height 98739...
Wallet: scanned to height 98750...
Wallet: scanned to height 98762...
Wallet: scanned to height 98794...
Wallet: scanned to height 98812...
Wallet: scanned to height 98818...
Wallet: scanned to height 98820...
Wallet: scanned to height 98826...
Wallet: scanned to height 98828...
Wallet: scanned to height 98832...
Wallet: scanned to height 98843...
Wallet: scanned to height 98857...
Wallet: scanned to height 98871...
Wallet: scanned to height 98897...
Wallet: scanned to height 98935...
Wallet: scanned to height 98949...
Wallet: scanned to height 98957...
Wallet: scanned to height 98968...
Wallet: scanned to height 99010...
Wallet: scanned to height 99055...
Wallet: scanned to height 99111...
Wallet: scanned to height 99151...
Wallet: scanned to height 99175...
Wallet: scanned to height 99192...
Wallet: scanned to height 99219...
Wallet: scanned to height 99265...
Wallet: scanned to height 99291...
Wallet: scanned to height 99331...
Wallet: scanned to height 99374...
Wallet: scanned to height 99408...
Wallet: scanned to height 99445...
Wallet: scanned to height 99487...
Wallet: scanned to height 99537...
Wallet: scanned to height 99579...
Wallet: scanned to height 99631...
Wallet: scanned to height 99658...
Wallet: scanned to height 99691...
Wallet: scanned to height 99735...
Wallet: scanned to height 99789...
Wallet: scanned to height 99832...
Wallet: scanned to height 99882...
Wallet: scanned to height 99927...
Wallet: scanned to height 99969...
Wallet: scanned to height 100027...
Wallet: scanned to height 100081...
Wallet: scanned to height 100127...
Wallet: scanned to height 100156...
Wallet: scanned to height 100199...
Wallet: scanned to height 100229...
Wallet: scanned to height 100281...
Wallet: scanned to height 100320...
Wallet: scanned to height 100349...
Wallet: scanned to height 100409...
Wallet: scanned to height 100457...
Wallet: scanned to height 100513...
Wallet: scanned to height 100576...
Wallet: scanned to height 100611...
Wallet: scanned to height 100660...
Wallet: scanned to height 100686...
Wallet: scanned to height 100726...
Wallet: scanned to height 100756...
Wallet: scanned to height 100816...
Wallet: scanned to height 100846...
Wallet: scanned to height 100888...
Wallet: scanned to height 100942...
Wallet: scanned to height 101003...
Wallet: scanned to height 101045...
Wallet: scanned to height 101088...
Wallet: scanned to height 101121...
Wallet: scanned to height 101182...
Wallet: scanned to height 101227...
Wallet: scanned to height 101279...
Wallet: scanned to height 101330...
Wallet: scanned to height 101391...
Wallet: scanned to height 101459...
Wallet: scanned to height 101516...
Wallet: scanned to height 101563...
Wallet: scanned to height 101617...
Wallet: scanned to height 101658...
Wallet: scanned to height 101712...
Wallet: scanned to height 101769...
Wallet: scanned to height 101850...
Wallet: scanned to height 101899...
Wallet: scanned to height 101913...
Wallet: scanned to height 101948...
Wallet: scanned to height 102016...
Wallet: scanned to height 102079...
Wallet: scanned to height 102142...
Wallet: scanned to height 102208...
Wallet: scanned to height 102276...
Wallet: scanned to height 102336...
Wallet: scanned to height 102406...
Wallet: scanned to height 102474...
Wallet: scanned to height 102541...
Wallet: scanned to height 102603...
Wallet: scanned to height 102660...
Wallet: scanned to height 102725...
Wallet: scanned to height 102788...
Wallet: scanned to height 102873...
Wallet: scanned to height 102950...
Wallet: scanned to height 103023...
Wallet: scanned to height 103096...
Wallet: scanned to height 103161...
Wallet: scanned to height 103242...
Wallet: scanned to height 103312...
Wallet: scanned to height 103367...
Wallet: scanned to height 103427...
Wallet: scanned to height 103502...
Wallet: scanned to height 103571...
Wallet: scanned to height 103638...
Wallet: scanned to height 103711...
Wallet: scanned to height 103788...
Wallet: scanned to height 103858...
Wallet: scanned to height 103926...
Wallet: scanned to height 104006...
Wallet: scanned to height 104066...
Wallet: scanned to height 104127...
Wallet: scanned to height 104200...
Wallet: scanned to height 104260...
Wallet: scanned to height 104327...
Wallet: scanned to height 104401...
Wallet: scanned to height 104470...
Wallet: scanned to height 104528...
Wallet: scanned to height 104588...
Wallet: scanned to height 104646...
Wallet: scanned to height 104705...
Wallet: scanned to height 104772...
Wallet: scanned to height 104855...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Wallet: scanned to height 105122...
Done!
