### ISSUE TITLE
My coins are missing

### ISSUE THREAD

**Issue by Piradoxlanieve** [NebulousLabs/Sia#1903]
I'm new to mining A few days ago send 1023 nano pool coins to my wallet offline https://explore.sia.tech/hash.html?hash=d72ca6ebb8e11879ddcf1e7789d7367b4ec6f007a912abaa91913a6fa054b860
Arrived perfectly, but today I send 1023 to poloniex and I only got 1 coin but in the wallet I have discounted 1773 that I did not have https://explore.sia.tech/hash.html?hash=bb733b6889fd16835eb44a71bacdf43fb8a7eed4de24db20c6bf05e0d47ee8ba http://subefotos.com/ver/?56cacf5f96d959b8f45cc5366d6ede67o.jpg
Sorry my bad english

**Comment by tetreault** [comment]
poloniex is a nightmare, a lot of people are having issues with poloniex. while this doesn't resolve your current problem, give bittrex a try next time.
