### ISSUE TITLE
Cannot add folder: API call not recognized

### ISSUE THREAD

**Issue by hkparker** [NebulousLabs/Sia#1911]
Hopefully I'm just doing something wrong, but I don't seem to be able to add a folder.

```
root@cryptonode:~# siac host folder add /sia/ 6000GB
Could not add folder: API call not recognized: /host/storage/folders/add
```

Using a recent `go get` build (6197966279682bf898779cb40a344574f308b07d)

**Comment by lukechampine** [comment]
Are you running `siad` with the hosting module enabled? IIRC it is disabled by default. Run `siad modules` for info on how to enable/disable specific modules.

**Comment by hkparker** [comment]
Ah, good, it was a stupid error on my part.  I mixed up the 'host' and 'renter' modules and wasn't running it.  I guess there could have been a more helpful error message, but I'll leave that up to you guys to decide if its worth ticketing.  I'm all set now so I'll close this out.  Thanks for getting to me so fast!
