### ISSUE TITLE
siad critical error

### ISSUE THREAD

**Issue by nitronick600** [NebulousLabs/Sia#1916]
Hello,
I'm running siad locally on a Mac.  Here's a stacktrace it asked me to report:
goroutine 143 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc420c17c28)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420c17d80, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc420f77400, 0xc420c17d80, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc4209e8480, 0xc420c17f20)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320 +0x5be
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc4209e8480)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3ae
Critical error: ERROR: the renter is idle , but tracking active pieces: 13
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

Please let me know if there is anything else I can help with.

**Comment by johnathanhowell** [comment]
What version are you running?

**Comment by nitronick600** [comment]
Sia Daemon v1.2.2

**Comment by lukechampine** [comment]
should be fixed in v1.3.0
