### ISSUE TITLE
Add a /renter/file/__siapath__ endpoint

### ISSUE THREAD

**Issue by nitronick600** [NebulousLabs/Sia#1920]
It's inefficient to parse to the whole sia filesystem looking for a single file.  A singular endpoint would make sense.

**Comment by tbenz9** [comment]
recommendation to devs: tag "feature request" and "Programming task"

**Comment by MSevey** [comment]
@nitronick600 I just submitted a PR to add the endpoint, feel free to check it out #3003

**Comment by tbenz9** [comment]
Closed via #3003
