### ISSUE TITLE
Critical Error When Attempting to Download File From siad

### ISSUE THREAD

**Issue by nitronick600** [NebulousLabs/Sia#1926]
goroutine 139 [running]:
runtime/debug.Stack(0x445687, 0x0, 0xc4215abc28)
#011/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
#011/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4215abd80, 0x2, 0x2)
#011/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc420bfab80, 0xc4215abd80, 0x2, 0x2)
#011/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc4221018c0, 0xc4215abf20)
#011/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:320 +0x5be
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc4221018c0)
#011/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:585 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
#011/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3ae
Critical error: ERROR: the renter is idle , but tracking active pieces: 10
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

Siad Version 1.2.2

**Comment by lukechampine** [comment]
should be fixed in v1.3.0
