### ISSUE TITLE
Contract fees for allowance

### ISSUE THREAD

**Issue by Cinerar** [NebulousLabs/Sia#1930]
According to siahub.info stats Network utilization is only 2% 
Maybe contract fees for creating allowance should be somehow tied to overall network utilization rate? 
I believe they are quite high now.  And SIA definitelly need more renters.

**Comment by CtrlAltDefeat94** [comment]
I've been trying to rent my spare few TB's but apparently I need 2k Siacoins to start announcing that I have storage for rent. At current exchange rates that's $28.

I sure as hell won't be paying $28 to rent my storage

**Comment by johnathanhowell** [comment]
Note that you will get that amount back at the end of the contract duration, it's used to incentivize hosts to keep their files and stay on the network.

**Comment by Cinerar** [comment]
@johnathanhowell but in Sia-UI it states that it is unrefundable fee. To create allowance for ex 5ks 1600sc will be lost. I believe this stops a lot from renting.

**Comment by myfreeweb** [comment]
The minimum fee seems to be 1000 SC… even if I want to make an allowance for like 5 SC. That make Sia completely unusable for small storage. I don't need many terabytes, only a few GB!

**Comment by CodersBrothers** [comment]
Thats true! In Bitcoin you decide what do you want for the minners, and the miners say yer or not. Is the market who decide the fees. I think that the fixed params are allways a bad idea, must be as a variable. And must be possible offer small portions of size, like GBs for host or rent, but with the current fixed fees is imposible.

**Comment by Cinerar** [comment]
It is UI estimation? 
https://github.com/NebulousLabs/Sia-UI/blob/master/plugins/Files/js/components/allowancedialog.js#L16
