### ISSUE TITLE
Critical Error: ERROR: the renter is idle

### ISSUE THREAD

**Issue by nitronick600** [NebulousLabs/Sia#1932]
goroutine 175 [running]:
runtime/debug.Stack(0x445687, 0x0, 0xc43ba2bc28)
#011/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
#011/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc43ba2bd80, 0x2, 0x2)
#011/home/team/Go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc420fa6b80, 0xc43ba2bd80, 0x2, 0x2)
#011/home/team/Go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter.(*Renter).managedDownloadIteration(0xc420d56540, 0xc43ba2bf20)
#011/home/team/Go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:369 +0x5be
github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedDownloadLoop(0xc420d56540)
#011/home/team/Go/src/github.com/NebulousLabs/Sia/modules/renter/download.go:632 +0x37e
created by github.com/NebulousLabs/Sia/modules/renter.newRenter
#011/home/team/Go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:208 +0x3ae
Critical error: ERROR: the renter is idle , but tracking active pieces: 7
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues

I'm building from source against master.

**Comment by jestes11** [comment]
did you ever find out how to fix this? i am having the same problem

**Comment by nitronick600** [comment]
@jestes11 I did not figure out the root cause.  The best I could come up with is removing the renter/ directory.  You lose all contracts, but the value of those contracts will be refunded at the end of the contract period.

**Comment by vevarm** [comment]
This is a duplicat this issue already exists let me find it.

**Comment by vevarm** [comment]
https://github.com/NebulousLabs/Sia/issues/1591

I believe this is the same issue.

**Comment by lukechampine** [comment]
should be fixed in v1.3.0
