### ISSUE TITLE
Error with JavaScript when running Sia macOS v1.2.2 64-bit download

### ISSUE THREAD

**Issue by ltfschoen** [NebulousLabs/Sia#1936]
I tried to download and install Sia macOS v1.2.2 64-bit from http://sia.tech/apps/ to create a SiaCoin address but I encountered the below error: 

![screen shot 2017-06-15 at 10 16 39 am](https://user-images.githubusercontent.com/6226175/27160063-b2de2302-51b4-11e7-9d66-2e9e20efc7c8.png)

I am using macOS 10.11.5 El Capitan with 64-bit CPU

**Comment by lukechampine** [comment]
should be fixed in v1.3.0

**Comment by ltfschoen** [comment]
Thanks, yes it's fixed in v1.3.0
