### ISSUE TITLE
Downtime calculation bug

### ISSUE THREAD

**Issue by S-anasol** [NebulousLabs/Sia#1946]
Some hosts in hostdb have incorrect downtime.

For example: http://siahub.info/host/2044

hostdb.json scans history contains only success, zero failed scans.
But downtime keep growing every day.

Found indirect proof of bug.
uptimeadjustment: **0.05**9495223046291
Which is:
85%  uptime = 0.16
80%  uptime = 0.03
[source](https://github.com/NebulousLabs/Sia/blob/78d0e3f7c48597b0a79c6a4c82bd83916f127d51/modules/renter/hostdb/hostweight.go#L333-L334)
So real uptime between 80 and 85%
Same time other numbers shows 35% uptime (siahub/hostdb.json)

Only difference between sources is scan history sorting protection.

```
if recentTime.After(scan.Timestamp) {
	hdb.log.Critical("Host entry scan history not sorted.")
	// Ignore the unsorted scan entry.
	continue
}
```

[hostdbcmd.go](https://github.com/NebulousLabs/Sia/blob/9cfb1e895783534de23a785b8bac6cc0ea48a0a1/siac/hostdbcmd.go#L216-L229) - totally incorrect calculation.
[hostweight.go](https://github.com/NebulousLabs/Sia/blob/78d0e3f7c48597b0a79c6a4c82bd83916f127d51/modules/renter/hostdb/hostweight.go#L293-L297) - real or close to real uptime.

**Comment by lukechampine** [comment]
@DavidVorick thoughts?

**Comment by DavidVorick** [comment]
If the timestamps are unsorted for some reason, this is going to cause the uptime to return conflicting values. You can run into this issue if your system time is changing frequently, which could be happening from a bad clock + ntp corrections.

The hostdb also compresses historic scans. It'll only store a few of the most recent scans, and then other scans are compressed out but their historical values remain.

**Comment by tbenz9** [comment]
Recommendation to devs: close
