### ISSUE TITLE
Hosting on 1TB not receiving any funds

### ISSUE THREAD

**Issue by 3smat** [NebulousLabs/Sia#1947]
Hi 
I'm new at hosting with Siacoin - I have announced 1.7TB space for rent however, I'm not receiving any funds, I have included a screenshot below

 
<img width="741" alt="capture" src="https://user-images.githubusercontent.com/29495721/27249336-2d4f64f0-5356-11e7-9680-6886c51abbdb.PNG">

**Comment by S-anasol** [comment]
you need to wait until contracts with your host will be created.
Its not like announce and get instant money.
