### ISSUE TITLE
incoming RPCSettings failed

### ISSUE THREAD

**Issue by ams-123** [NebulousLabs/Sia#1948]
Hi, 
Trying to host on the sia network, host has been online for 24hrs plus, but no contracts. Looking at it, the network config may be wrong, as I see the following errors in host.log:

errors.go:151: connection error: error with aa.aaa.aaa.aaa:10154: incoming RPCSettings failed: failed WriteSignedObject during RPCSettings: write tcp bbb.bbb.b.bbb:9982->aa.aaa.aaa.aaa:10154: write: connection reset by peer 
aaa being the remote IP, bbb being the local.

host -v shows the following:
General Info:
	Connectability Status: Host appears to be working.

RPC Stats:
	Error Calls:        3
	Unrecognized Calls: 2
	Download Calls:     0
	Renew Calls:        0
	Revise Calls:       0
	Settings Calls:     10617
	FormContract Calls: 3

Is there an obvious issue in my setup?

**Comment by lukechampine** [comment]
It may take a while to get contracts. You only received 3 calls; they may have failed for benign reasons. You should only worry if you're seeing dozens of failed `FormContract` calls.
