### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by doctor2000** [NebulousLabs/Sia#1949]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus set...
Closing gateway...
panic: invalid page type: 627257: 10

goroutine 1 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x99239)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x81cf2000)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x1d02)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x826f5000)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x2705)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x8277c000)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x15d
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x278c)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1c2
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc04207c358, 0xc04207c3f8, 0x20, 0x20, 0x0, 0x0, 0x6d99ba, 0xc042058b78, 0xc04229cc90, 0x2, ...)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc04229a7c0, 0xc04207c3f8, 0x20, 0x20, 0xc04229a7c0, 0xa8416fa69dbcb61d, 0x491956724de7c972)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xf6
github.com/NebulousLabs/Sia/modules/consensus.getBlockMap(0xc042058b60, 0x2a05000000000000, 0x4e0b1805b3706e05, 0x26a69d570d22f8b2, 0xc2b5d6b84e2b3c01, 0x100c042015302, 0xc042360000, 0x157e418)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:153 +0x84
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc042129b80, 0xc042058b60, 0x0, 0x0, 0x0, 0xc04223fc60, 0x1, 0x1, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:53 +0x81f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc042058b60, 0xad5978, 0xc042058b60)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe7
github.com/NebulousLabs/bolt.(*DB).View(0xc0420f6780, 0xc04207d388, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/db.go:629 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc042129b80, 0xd90d80, 0xc042316120, 0xd8c753eea21e28b6, 0xdb8bb24948843e62, 0xbf1fc70ae0c02b19, 0x1da8f4a6eb195b6f, 0xc04223f960, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x256
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc042129b80, 0xd90d80, 0xc042316120, 0xd8c753eea21e28b6, 0xdb8bb24948843e62, 0xbf1fc70ae0c02b19, 0x1da8f4a6eb195b6f, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xf5
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc042316120, 0xc042316120, 0xc04229c630)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:152 +0x5b1
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xd9bca0, 0xc042129b80, 0xd9b100, 0xc04206ac60, 0xc04229a3c0, 0x38, 0x0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:107 +0x1d4
main.startDaemon(0x0, 0x0, 0xc04203e3eb, 0xe, 0xc04203e42b, 0x5, 0xc04203e40c, 0x5, 0x0, 0xc04203e44a, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:186 +0x169a
main.startDaemonCmd(0xc042071200, 0xc0420554a0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x74
github.com/spf13/cobra.(*Command).execute(0xc042071200, 0xc042036070, 0x5, 0x5, 0xc042071200, 0xc042036070)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x241
github.com/spf13/cobra.(*Command).ExecuteC(0xc042071200, 0xacaa11, 0x3b, 0xc042138a00)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc042071200, 0xea0cc0, 0xab35fb)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x32
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7a4

**Comment by netie** [comment]
Yeah, same problem here. Any fix please?

**Comment by doctor2000** [comment]
Foud the solution.
This is what I did:

   1) Go to cmd and run as administrator
   2) Cd into your Sia-UI-v1.2.2-win32-x64\resources\app\Sia directory
   3) Type siad.exe and hit enter
   6) After all 6/6 are loaded, you can open the Sia-UI.

It works for me, I hope this  will help others
