### ISSUE TITLE
Balance incorrect in Sia Wallet

### ISSUE THREAD

**Issue by freedomprivacy** [NebulousLabs/Sia#1950]
On June 14th 2017 I transferred some of my SC from BITTREX to my wallet. I had my SC wallet open, and saw in the wallet that the amount had hit the blockchain but was unconfirmed. At that point I closed the wallet as theres no point to wait to see it get confirmed....
Today I opened up the wallet, and saw that SC was confirmed in the wallet but 15 seconds later, a transaction to send the exact same amount out of the wallet has been confirmed. Hence my balance is not what I expected.
The TXN ID for the inbound wallet from Bittrex was: b2e879c58f2f6902869d1ecac253962f1116eece8bec2b2ff64728155625fa4a
The TXN ID for the outbound same amount from my wallet was: 38d10b3d3482be7788ce3c69ae291378b229cf617f13fe3a2e57f01266657f07

Please would you assist me in finding out what happened ?
thanks

**Comment by lukechampine** [comment]
try using the recover tool here: https://github.com/NebulousLabs/Sia-UI/issues/581#issuecomment-299747969
