### ISSUE TITLE
Race condition in Transaction Pool shutdown

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#1952]
The tpool calls `Commit` in an `AfterStop` function:
```go
tp.tg.AfterStop(func() {
	err := tp.dbTx.Commit()
	if err != nil {
		tp.log.Println("Unable to close transaction properly during shutdown:", err)
	}
})
```
but this races with `threadedRegularSync`, which calls `tp.syncDB` in a loop. I think this can be resolved by adding a lock around the call to `Commit` in the `AfterStop` function.

**Comment by DavidVorick** [comment]
The real issue here is that we have a goroutine (`threadedRegularSync`) which is operating outside the safety of the `Add()` and `Done()` calls, not that we need a lock.
