### ISSUE TITLE
Siad node priority suggest.

### ISSUE THREAD

**Issue by TimonPeng** [NebulousLabs/Sia#1967]
Sia can have a parameter that supports the preferred node json file?

Like go-ethereum's `static-nodes.json` file.

This makes it easy for sia's fans in different countries to run a fast sync network.

**Comment by S-anasol** [comment]
`siac gateway connect IP:PORT`

force add any peer and it will be saved into DB forever(probably, since nodes db not removing any peers)

**Comment by lukechampine** [comment]
As @S-anasol suggested, you can use `siac` to manually connect to a set of nodes. This is a bit awkward to do programmatically (would require a bash script or equivalent), but once you are connected, you should stay connected.

Still, I think a preferred node list is a good idea. We don't have much development bandwidth to spare on it right now, but it would be a good project for a contributor.

**Comment by TimonPeng** [comment]
Thanks! @S-anasol @lukechampine
