### ISSUE TITLE
Can't bind siad to interface/address

### ISSUE THREAD

**Issue by D4rk4** [NebulousLabs/Sia#1970]
siad -M cghrtw --rpc-addr 10.0.1.240:9981 --host-addr 10.0.1.240:9982

netstat -tapn | grep siad
tcp        0      0 127.0.0.1:9980          0.0.0.0:*               LISTEN      29987/siad
tcp        0      0 10.0.1.240:9981         0.0.0.0:*               LISTEN      29987/siad
tcp        0      0 10.0.1.240:9982         0.0.0.0:*               LISTEN      29987/siad
tcp        0      1 10.0.1.250:5864         24.27.103.185:9982      SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:24330        100.64.62.174:9982      SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:60610        68.118.232.232:9982     SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:61884        101.200.214.115:9981    SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:1676         192.222.228.186:9982    SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:5532         79.119.155.56:9982      SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:48356        99.91.195.81:9982       SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:26208        81.64.128.68:9982       SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:7238         90.87.224.114:9982      SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:20770        96.231.239.120:9982     SYN_SENT    29987/siad
tcp        0      0 10.0.1.250:3158         122.150.251.159:9982    ESTABLISHED 29987/siad
tcp        0      1 10.0.1.250:29888        79.172.204.10:9981      SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:4106         73.71.41.138:9982       SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:47304        95.86.33.52:9982        SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:28214        195.211.84.149:9982     SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:38482        94.123.92.8:9982        SYN_SENT    29987/siad
tcp        0     24 10.0.1.250:55518        99.27.120.250:9982      ESTABLISHED 29987/siad
tcp        0      0 10.0.1.250:4904         88.160.212.47:9981      ESTABLISHED 29987/siad
tcp        0      1 10.0.1.250:18510        87.88.3.76:9982         SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:27244        82.53.61.2:9982         SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:13942        60.35.187.4:9981        SYN_SENT    29987/siad
tcp        0     24 10.0.1.250:39058        213.204.241.185:9981    ESTABLISHED 29987/siad
tcp        0      1 10.0.1.250:11732        203.118.152.202:9982    SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:62486        88.201.148.216:9982     SYN_SENT    29987/siad
tcp        0      1 10.0.1.250:24666        79.179.95.237:9982      SYN_SENT    29987/siad
tcp        0      0 10.0.1.250:6532         178.32.220.148:9981     ESTABLISHED 29987/siad

**Comment by lukechampine** [comment]
I'm not sure I understand. What is the problem exactly?

**Comment by D4rk4** [comment]
I can't find way to bind siad to interface/IP.
If i set host-addr/rpc-addr, siad ignore it and try setup connection from default interface.

**Comment by D4rk4** [comment]
Can you simple add --bind-addr option on next release? I don't have golang env now, sorry.

**Comment by lukechampine** [comment]
I don't think we even need another flag, we can just use the address provided in the `--rpc-addr` flag. Unless there are more complicated networking setups that I'm ignorant of...

**Comment by D4rk4** [comment]
Okay,  can you build siad with net.Dialer defined LocalAddr flag for testing?

**Comment by tbenz9** [comment]
@D4rk4 have you been able to test https://github.com/NebulousLabs/Sia/pull/2255?

**Comment by lukechampine** [comment]
Closing for now. If anyone else has this problem, please leave a comment so that we can test whether #2255 fixes it.
