### ISSUE TITLE
Siad not syncing

### ISSUE THREAD

**Issue by alexyaoyang** [NebulousLabs/Sia#1972]
Hi all,

I wanted to utilize my VPS's extra disk space for Sia, so I installed a fresh install of Sia on my CentOS 7 64bit OS. After running siad with gctwh modules, it finished loading in less than 1 sec and when I check on siac, the progress is always 0% progress and Height 0. This has been going on for a few hours.

There are no error message so I can't even debug, and I double checked that my ports 9980, 9981, 9982 are open in my firewall.

I tried searching for Siad sync issues, but most of the issues were stuck at a certain block, but for me, it didn't even start syncing.

Anyone seen this before?

> ./siad -M gctwh                               
> Loading...
> (0/5) Loading siad...
> (1/5) Loading gateway...
> (2/5) Loading consensus...
> (3/5) Loading transaction pool...
> (4/5) Loading wallet...
> (5/5) Loading host...
> Finished loading in 0.132179701 seconds

> ./siac
> Synced: No
> Height: 0
> Progress (estimated): 0.0%

**Comment by lukechampine** [comment]
Is this one of our binary releases or did you compile it yourself? There may be useful information in `gateway/gateway.log`.

**Comment by DcyMatrix** [comment]
I don't think you should open port 9980 to the internet. But someone more
in the know hopefully will chip in on it. 😁

**Comment by alexyaoyang** [comment]
@lukechampine it was the linux binary release Sia-v1.2.1-linux-amd64.zip. 

In gateway logs, there is a warning message: WARN: could not automatically forward port 9981: no UPnP-enabled devices found: $. What plug n play device is used for Sia?

@DcyMatrix That's true, I opened all 3 of them because I don't know which one will be used to sync with the blockchain. Do you know which port should be left open?

**Comment by lukechampine** [comment]
>I don't think you should open port 9980 to the internet.

A peer-to-peer network cannot function if no one has open ports. Sia will automatically attempt to forward the necessary ports it needs to communicate. (Note that most BitTorrent clients do the same.)

**Comment by alexyaoyang** [comment]
@lukechampine Thanks, I've closed 9980. Consensus.log doesn't seem to have any errors.

> ...
> 2017/06/21 16:17:28.176288 persist.go:67: STARTUP: Logging has started.
> 2017/06/21 16:24:01.037799 persist.go:73: SHUTDOWN: Logging has terminated.
> 2017/06/21 16:24:05.973966 persist.go:67: STARTUP: Logging has started.
> 2017/06/21 16:35:08.569684 persist.go:73: SHUTDOWN: Logging has terminated.
> 2017/06/21 16:44:20.182090 persist.go:67: STARTUP: Logging has started.

**Comment by lukechampine** [comment]
Hmm. Do you have any peers? (`siac gateway list`). Try manually connecting to a known good peer with `siac gateway connect` and see if you get an error. Any of these IPs should work: https://github.com/NebulousLabs/Sia/blob/master/modules/gateway.go#L23. If they are still present in your peer list after a few minutes, you should start receiving blocks. If they disconnect, check the logs again for errors.

**Comment by alexyaoyang** [comment]
@lukechampine I finally figured out. I disabled my firewall temporarily and it started to sync. It must be one of the rules in my firewall that is the culprit. Thanks you your help and closing this issue.
