### ISSUE TITLE
Sia Wallet Crashed after successful start

### ISSUE THREAD

**Issue by sgjenks01** [NebulousLabs/Sia#1974]
I got the SIA blockchain synced up and then started the Sia Gui wallet. It started okay (first time that happened), bit now after an hour or two of running I went back to it to find this:
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus set...
Closing gateway...
invalid argument

**Comment by lukechampine** [comment]
this has been reported more than once. We need better context on these errors to have any hope of debugging them. We should figure out which call-chains could be responsible for this and wrap them in proper contexts.

**Comment by sgjenks01** [comment]
@lukechampine If you can tell me what further info you need to track this down, and how to capture it, I can probably reproduce it and capture whatever you want.

**Comment by lukechampine** [comment]
If it happens every time you run siad, we can track it down fairly quickly. Otherwise we need to take a more general approach.

Is this on v1.3.0?

**Comment by sgjenks01** [comment]
No, it was on v1.2.2, so I need to upgrade and see if it persists. If it does, I'll get back to you here. 

BTW, I was able to solve this problem by starting siad.exe first. If I waited for it to get caught up, I could then start the SIA-UI.exe. I read somewhere that you do run siad.exe first and then you can just run the wallet, but that wasn't true. Anyway, I'll upgrade, and If I can reproduce the problem, I will let you know.
