### ISSUE TITLE
Need FUSE client.

### ISSUE THREAD

**Issue by D4rk4** [NebulousLabs/Sia#1980]
Hey!
Any plans to release fuse client for sia? 
This will greatly increase the movement in the sia storage market. And maybe attract corporate customers.

**Comment by S-anasol** [comment]
https://bitbucket.org/siaextensions/siadrive

**Comment by D4rk4** [comment]
I think, need add this to documentation on site/wiki

**Comment by segator** [comment]
Exist an API Documentation to Upload/Download objects to sia network?
I am a developer and I  would like to implement Sia Protocol over S3QL :)
As same way I did the implementation for Gdrive.
Check S3QL Features: Full Posix FS based on object storage.
Dedup, compression,encryption, snapshotting, read/write cache

I think  sia have potential but client app is a mess.

**Comment by johnathanhowell** [comment]
@segator check out the Renter API docs here: https://github.com/NebulousLabs/Sia/blob/master/doc/api/Renter.md

**Comment by D4rk4** [comment]
@segator i wait for realisation, i already use s3fs for S3. It's realy powerful solution!
