### ISSUE TITLE
Upgrading from 1.0.4 to 1.2.2

### ISSUE THREAD

**Issue by daniel-lucio** [NebulousLabs/Sia#1984]
Hi

Maybe more a question than an issue. After I upgrade the binaries, I run
 ./siad --sia-directory /var/lib/sia/ 
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
    
And it hangs there. Almost 1 hr so far.

Then..
./siac
Could not get current consensus state: API call not recognized: /consensus

Do I need to wait or is it something wrong?

**Comment by S-anasol** [comment]
wow so old :D 

Yes host rebuilding uploaded files and preparing free space for upload.
So need wait long time.
Time depends on your host storage size.

So keep calm :)

**Comment by daniel-lucio** [comment]
I share 7TB, 5% rented

**Comment by S-anasol** [comment]
I dont remember approx. building time/storage ratio. :)
But at least few hours, maybe whole day.

**Comment by daniel-lucio** [comment]
Done, 27k seconds
