### ISSUE TITLE
explorer update failed: database not open

### ISSUE THREAD

**Issue by lishaobin1989** [NebulousLabs/Sia#1985]
When I stop siad, I get those below.
Caught stop signal, quitting...
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing explorer...
Closing consensus set...
goroutine 15 [running]:
runtime/debug.Stack(0x4456e7, 0x0, 0xc427a40d70)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc427a40e48, 0x2, 0x2)
	/root/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42017a6f0, 0x93740a3b502746db, 0xb32de48d878088f0, 0x4d6e8df8ebe2b569, 0x8b44d8384816d554, 0x0, 0x0, 0x0, 0xc420b083c0, 0x1, ...)
	/root/go/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0x15a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).readlockUpdateSubscribers(0xc42013bb80, 0x0, 0x0, 0x0, 0xc429add180, 0x1, 0x1)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:114 +0x173
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc42013bb80, 0x3804000000000000, 0xd0f3d1e10e3b49f0, 0xaa876168bab9bb44, 0x74b4681a87df446b, 0xf0f2000b00781d92, 0x585494f2, 0xc424ca56c0, 0x1, 0x1, ...)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:278 +0x1e9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc42013bb80, 0xdbe460, 0xc425461800, 0x0, 0x0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:194 +0x521
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdbe460, 0xc425461800, 0x0, 0x0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:411 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc420081340, 0xc420140df0, 0x10, 0xabc5ef, 0xa, 0xc4284c1d40, 0x0, 0x0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:59 +0x319
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc420081340, 0xc420140df0, 0x10, 0xabc5ef, 0xa, 0xc4284c1d40, 0x0, 0x0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:69 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc42013bb80, 0xc427a41ef0, 0xc427a41eb0, 0xc427a41eb8, 0x0, 0x0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:554 +0x12c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc42013bb80, 0x0, 0x0)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x307
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420200940, 0xc42013bb80, 0xdbe760, 0xc420081340)
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/root/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a
Critical error: explorer update failed: database not open

**Comment by tbenz9** [comment]
@lishaobin1989 This appears to be a pretty isolated bug, I haven't seen this error before in any open or closed bug report.  If you're still having issues after a reinstall of Sia we can take another look.  But I'm going to recommend we close this issue as unreproducible.  Feel free to reopen this issue if the problem persists.

Recommendation to devs: close (unreproducible)
