### ISSUE TITLE
error during sinchronizing

### ISSUE THREAD

**Issue by alexandr-krylov** [NebulousLabs/Sia#1986]
Error Log:
`Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 18.1888089 seconds
goroutine 30691 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc0423d9dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0423d9f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04285ba00, 0xc0423d9f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc042d8a920, 0xc042b860c8)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\ALMA\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\ALMA\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
goroutine 73894 [running]:
runtime/debug.Stack(0x4442be, 0x0, 0xc0431e7dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc0431e7f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc04285ba00, 0xc0431e7f20, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc043db3d30, 0xc042b860c8)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\ALMA\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\ALMA\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
panic: page 8922 already freed

goroutine 19 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc042146270, 0x6f4, 0x58ca000)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc0453181c0, 0xc047d26a40, 0xd97a00)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc045318150, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0428778f0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc0428775e0, 0xc043dce4e0, 0xc0484d9a30)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc044f3b680, 0xc043dce400, 0xc0484d9ca0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc042881358, 0x372eea3c, 0xea0a20)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc042881340, 0xc0421824e0, 0xc042157e88)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc0422ea000)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:58 +0x4b
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc0422ea000)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:48 +0x130
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3cf
`

**Comment by lukechampine** [comment]
looks like a permissions error
