### ISSUE TITLE
Proposed error conventions

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#199]
I propose the following changes:

I like the idea of creating an error convention:

```go
err = someFunc()
if err != nil {
    errorHandlingFunc()
    // control statement, IE break, continue, or return
}
// else code
```

If for some reason there is no control statement (this would happen if you are merely logging errors), then it needs to be documented inside of the if statement. If there is no `err != nil`, that needs to be documented directly above where error is created.

This is not okay:
```go
err = someFunc()
return
```
because errors should always be checked. If code gets moved around, the person moving the code will need to remember to add error checking, and that's a chance for making mistakes, especially if the person moving the code is not the person who originally wrote the code.

This is also not okay:
```go
err = someFunc()
if err != nil {
    // stuff1
    // stuff2
    /// control statement
}
```

Either stuff1 and stuff2 need to be combined into a single function, or documentation needs to be added explaining why the convention was broken and what the error handling should look like.

**Comment by lukechampine** [comment]
This seems reasonable enough that I'll try to follow it in the future, except for maybe the last point, which feels just a bit too rigid. I don't think it occurs much in practice anyway though.

**Comment by DavidVorick** [comment]
I mean, if you need 2 or 3 simple statements, then throw a comment in explaining it. But if you need like 12 lines of code inside of the `err != nil`, it really should be it's own function because you don't want readers to forget that they're doing error handling.

**Comment by DavidVorick** [comment]
Sometimes we get an error like "Failed to start daemon: could not unmarshal type []wallet.AddressKey" and we're not sure where the error is being called from. Is there some convention we can add that will allow us to more easily trace an error chain?
