### ISSUE TITLE
What is `/consensus/validate/transactionset`'s post data payload?

### ISSUE THREAD

**Issue by TimonPeng** [NebulousLabs/Sia#1996]
The [consensus-validate-transaction-api-document](https://github.com/NebulousLabs/Sia/blob/master/doc/API.md#consensusvalidatetransactionset-post) did not write the post payload.

Then I checked the [go test file](https://github.com/NebulousLabs/Sia/blob/d0d0ca09508781363b643ace050928e2cb43a3ca/api/consensus_test.go#L88), and found it from the `contract.LastTransaction` got the jsonTxns.

But I got a empty result `{"contracts":[]}` from the api `/renter/contracts`, and [api doc's lasttransaction demo is also empty](https://github.com/NebulousLabs/Sia/blob/master/doc/API.md#json-response-with-comments-12).

So I hope sia developers can provide an available lasttransaction data or `/consensus/validate/transactionset` post payload demo, that I can continue to develop API.

Thanks.

**Comment by lukechampine** [comment]
The test was merely using `LastTransaction` as an example. The correct type to use is `[]types.Transaction`, which can be found in `types/transactions.go`.

If you need an example transaction set for testing, one easy way is to call the `SendSiacoins` method on a wallet. This will return the transaction set that sends the coins.
