### ISSUE TITLE
Maximaxing the host weigh

### ISSUE THREAD

**Issue by daniel-lucio** [NebulousLabs/Sia#1998]
First of all, not a GO coder. I have been reading the hostweight.go, and I understand some functions.  However, as I have already said, I am not a Go coder. 

So, my question is, what file/fuction is the first one called to have the server weigh. And I can read from there.

**Comment by DavidVorick** [comment]
hostweight.go contains a bunch of values that get multiplied together to produce the host weight. In that sense, none of them are 'first', when a host gets added they all get called and mixed together.

I'm not sure if this answers your question.
