### ISSUE TITLE
/wallet/init/seed returns error on success

### ISSUE THREAD

**Issue by NickvanDyke** [NebulousLabs/Sia#1999]
I called `/wallet/init/seed` correctly, but it still responded with `Message: error when calling /wallet/init/seed: wallet has not been encrypted yet`. I know I sent the request correctly; a second request gave the response that a wallet scan is already in progress, and a while later when it was done, it'd created a wallet with the seed I specified. So the request worked, but still responded with an error. There was an existing wallet and I was calling with `force=true`, in case that matters.

**Comment by lukechampine** [comment]
Closing for now. Please reopen if this can be reproduced in v1.3.0
