### ISSUE TITLE
Renters ignore HostExternalSettings.SectorSize

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2006]
This field of host settings is [assigned](https://github.com/NebulousLabs/Sia/blob/1fa8c15578bba7bff09207a1d86bb280806d7343/api/host.go#L219) to modules.SectorSize. I guess there is a plan to let hosts to modify this value in future (currently there is no such a way so host uses modules.SectorSize). But renters also use `modules.SectorSize` instead of the value from HostExternalSettings:

```
$ git grep -w SectorSize modules/renter | grep -v modules.SectorSize
$
```

This means old renters will be incompatible with new hosts when hosts implement changing this value. Old renters will continue to use `modules.SectorSize` instead of the value provided by the host.

**Comment by lukechampine** [comment]
At this time we don't plan to support sector sizes other than 4MB, at least in the near future.
