### ISSUE TITLE
probably deadlock in transaction pool loading in 1.3.0rc1

### ISSUE THREAD

**Issue by rudibs** [NebulousLabs/Sia#2014]
i am just trying `siad 1.3.0rc1` on my host and it seems stuck on `loading transaction pool` for >20 minutes now..  is that normal?  
```Mon Jun 26 04:02:10 UTC 2017
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...```

then
```Mon Jun 26 04:28:42 UTC 2017
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 33.235905161 seconds
```
 (i guess)

**Comment by DavidVorick** [comment]
There are situations where it would get stuck for 20 minutes, specifically if you had just loaded a transaction pool where you didn't used to have one, or if you had recently upgraded a version.

But I noticed the same thing on my machine - one of the times it stopped startup at the transaction pool, even though I didn't do anything which should make it slow down.

I'm guessing there's a bug here, we've done a lot of work on the transaction pool recently, we probably introduced a deadlock somewhere during startup. We'll investigate.

**Comment by rudibs** [comment]
yes i was upgrading. here was the sequence.
1. shutdown 1.2.2
2. upgrade to 1.3.3rc1
3. start container -- booted fine in less than five minutes immediately after upgrade.
4. rebooted machine -- got stuck (surprising to me since i thought it would have already migrated from upgrade)
5. stopped container and restarted once or twice (i forget) -- fixed

**Comment by lukechampine** [comment]
Closing for now. Pleas reopen if this is reproducible on v1.3.0.

**Comment by OpenGrid** [comment]
Using v1.3.0. 
Stuck on:
(3/6) Loading transaction pool...

**Comment by DavidVorick** [comment]
If you have juggled around your consensus folder or if you deleted your transaction pool folder, or otherwise tampered with the internal files of Sia, it can take a while to reload and reset the transaction pool.
