### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by Primly** [NebulousLabs/Sia#2017]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus set...
Closing gateway...
panic: invalid page type: 19463: 4c08

goroutine 1 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0x54e9)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x40c
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0xc0420568c0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0x5544)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0xc0422e8540)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0x6fd9)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0xc0422e8380)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x12b
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0x81c4)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x17d
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc04207a110, 0xc04532bbe0, 0x20, 0x20, 0x0, 0x0, 0x9, 0xc04219e400, 0x120000, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc0422a6a80, 0xc04532bbe0, 0x20, 0x20, 0xebd580, 0x0, 0x0, 0x9ba3c0, 0xc04532bb80)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/bucket.go:300 +0x14d
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).addTransaction(0xc0422f2000, 0xc042292620, 0x9664dfc51b340f9e, 0xc2342cf2466af3dc, 0x852f77b3703845a5, 0x702cb0883b7f0763, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:208 +0xf3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc0422f2000, 0x3b7aa3a38dc98dce, 0x2da0a2f25ba0c157, 0x59d983ca244bbada, 0xaf27aaebe81115e7, 0x0, 0x0, 0x0, 0xc044d9a1e0, 0x1, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:32 +0x3fb
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc0422927e0, 0xad5978, 0xc0422927e0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:176 +0x160
github.com/NebulousLabs/bolt.(*DB).View(0xc0420f4780, 0xc04207b388, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/db.go:629 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc042127b80, 0xd90d80, 0xc0422f2000, 0xcd1b2039e3fbf884, 0x1c83d4b38be84226, 0x4013afb054284d28, 0x2b77a02afb1a8dd1, 0xc042288560, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x256
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc042127b80, 0xd90d80, 0xc0422f2000, 0xcd1b2039e3fbf884, 0x1c83d4b38be84226, 0x4013afb054284d28, 0x2b77a02afb1a8dd1, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xf5
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc0422f2000, 0xc0422f2000, 0xc04228a450)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:152 +0x5b1
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xd9bca0, 0xc042127b80, 0xd9b100, 0xc04206adc0, 0xc0422a6840, 0x36, 0x0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:107 +0x1d4
main.startDaemon(0x0, 0x0, 0xc04203c3eb, 0xe, 0xc04203c42b, 0x5, 0xc04203c40c, 0x5, 0x0, 0xc04203c44a, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:186 +0x169a
main.startDaemonCmd(0xc042071200, 0xc042053450, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x74
github.com/spf13/cobra.(*Command).execute(0xc042071200, 0xc042034070, 0x5, 0x5, 0xc042071200, 0xc042034070)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x241
github.com/spf13/cobra.(*Command).ExecuteC(0xc042071200, 0xacaa11, 0x3b, 0xc042134b40)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc042071200, 0xea0cc0, 0xab35fb)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x32
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7a4

**Comment by lukechampine** [comment]
Looks like an obscure bolt bug. Please reopen if this is reproducible on v1.3.0
