### ISSUE TITLE
host -v Locked Collateral value is higher than total SC existed on the wallet

### ISSUE THREAD

**Issue by Cinerar** [NebulousLabs/Sia#2027]
`./siac host -v  ` 
displays Locked Collateral value higher than existed on the wallet. 
I believe the place that should be checked is hosting while wallet is locked.

**Comment by lasat** [comment]
+1 I've seen this problem on my host too.

**Comment by tbenz9** [comment]
I believe this issue is adequately tracked between #2262 and #2144.

Recommendation to devs: Close
