### ISSUE TITLE
Download speeds starts fast then typically gets stuck at 80-100%   -- 1.3.0-RC

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#2028]
This is for 1.3.0-RC. 

Typical case download a 300MB file. 
Download starts at like 60mbps to around 80% , the rate counter decreases and the % counter moves slowly or not at all. After like 20minutes I conclude this is not working.

**Comment by lukechampine** [comment]
Does this still occur with v1.3.0?

**Comment by petabytestorage** [comment]
@tbenz9 seems like we should close this since we already know all public released siad renters are broken in this way. expect fix in 1.3.1

**Comment by vevarm** [comment]
@lukechampine It does not happen in 1.3.0 to my experience.
