### ISSUE TITLE
Bolt SegFault in Windows Linux Subsystem

### ISSUE THREAD

**Issue by S-anasol** [NebulousLabs/Sia#2034]
https://gist.github.com/S-anasol/735aaa47d03447ef8d974d396c175e59

Getting segfault on latest(commits) versions from github.
Trying to use for testing purposes(gateway and consensus only run), but got crash in 1-10 minutes after start.
But consensus still updating and work fine, but with random crashes 😢

**Comment by S-anasol** [comment]
Tried build for Windows, looks like no problem.

Possible problem in environment, crashed under Linux Subsystem for Windows.

**Comment by lukechampine** [comment]
hmm. I thought this was bug #1745, but your trace explicitly calls it a segfault, whereas #1745 does not. Is it possible that you don't have enough disk space? Maybe the subsystem runs on a small partition?

**Comment by S-anasol** [comment]
nope, it uses same disk as parent windows.
![image](https://user-images.githubusercontent.com/1709666/27608520-878f99b6-5b90-11e7-9154-d6fc4ce74de2.png)

Tested on 2 PC with Linux Subsystem. Same crash.

**Comment by tbenz9** [comment]
Are you still having problems?  Have you tried Sia 1.3.0?

Does Sia support an environment like this?  I haven't heard of other people reporting this bug when running on bare metal Linux or Windows.  I'd be inclined to say we close this as it's an unsupported environment.

**Comment by lukechampine** [comment]
it would be nice to support the Linux Subsystem, but we can't really devote much energy to debugging it right now. I'll close this for now; if there's sufficient demand, we can open a "Add support for Linux Subsystem" issue later.
