### ISSUE TITLE
Mac Sia Wallet Download Error

### ISSUE THREAD

**Issue by brucjones** [NebulousLabs/Sia#2037]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
Closing gateway...
panic: page 8858 already freed

goroutine 1 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc4200e1d40, 0x122b7, 0x5441000)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x29a
github.com/NebulousLabs/bolt.(*node).spill(0xc420148e70, 0xc42008cd88, 0x8)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e0
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc4200fe638, 0x28bc22b9, 0x1aa6220)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x17b
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc4200fe620, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x125
github.com/NebulousLabs/bolt.(*DB).Update(0xc420100780, 0xc42008d118, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/bolt/db.go:605 +0xf7
github.com/NebulousLabs/Sia/persist.(*BoltDatabase).checkMetadata(0xc4200e1da0, 0x16b217a, 0x16, 0x169b76d, 0x5, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/boltdb.go:41 +0x98
github.com/NebulousLabs/Sia/persist.OpenDatabase(0x16b217a, 0x16, 0x169b76d, 0x5, 0xc4200199f0, 0x4f, 0x4f, 0xc42008d258, 0x10daf4f)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/boltdb.go:82 +0x144
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).openDB(0xc420139b80, 0xc4200199f0, 0x4f, 0xc4200199f0, 0x4f)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/database.go:76 +0x6f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB(0xc420139b80, 0xc420287df0, 0xc420274f80)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:27 +0x9f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initPersist(0xc420139b80, 0xc420287dc0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:82 +0x18c
github.com/NebulousLabs/Sia/modules/consensus.New(0x19a0840, 0xc420070c60, 0x1, 0xc4200198b0, 0x42, 0x1b, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:139 +0x587
main.startDaemon(0x0, 0x0, 0x7fff5fbffccf, 0xe, 0x7fff5fbffcfb, 0x5, 0x7fff5fbffcea, 0x5, 0x0, 0x7fff5fbffd54, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:154 +0x1b25
main.startDaemonCmd(0xc420079200, 0xc4200194a0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420079200, 0xc42000e0d0, 0x5, 0x5, 0xc420079200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420079200, 0x16c7c0f, 0x3b, 0xc42014c8c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420079200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d

**Comment by lukechampine** [comment]
looks like an obscure bolt error. Unfortunately, not much we can do about these. Try resyncing with v1.3.0.
