### ISSUE TITLE
Ask for help get miner header.

### ISSUE THREAD

**Issue by MitsushimaHikari** [NebulousLabs/Sia#2038]
I use nodejs to requests miner header, but it's response looks wrong.

I think the correct result is the beginning of `0000000000000079b6a8fb9fd7f6b95d000f75a6c3f2f52b65d0c20ac3bcb5f6`.

But nodejs request response to hex is `0000000000000079efbfbdefbfbdefbfbdefbfbdefbfbdefbfbdefbfbd5d000f75efbfbdefbfbdefbfbdefbfbd2b65efbfbdefbfbd0ac3bcefbfbdefbfbd000000000000004a7a61efbfbd5befbfbd4cefbfbdefbfbd04efbfbd736f6d0870efbfbd55efbfbd57efbfbdefbfbd59efbfbd5800000000000000001148515900000000efbfbdefbfbdefbfbd07efbfbd22efbfbd724f6309efbfbd7b4aefbfbd59efbfbd2a2160efbfbd4b250b7c09efbfbd7235efbfbdefbfbdefbfbd`, it looks like a lot of dirty data.

How should i do it, please help me.

I tried using XHR2 by setting the `xhr.responseType = 'arraybuffer'` to request raw data, but it does [not support setting `User-Agent`](https://github.com/pwnall/node-xhr2/blob/master/src/001-xml_http_request.coffee#L382), so I gave up.

**Comment by MitsushimaHikari** [comment]
My code is:

```
var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
var request = new XMLHttpRequest();
request.open('GET', 'http://localhost:9980/miner/header', false);
request.setRequestHeader('User-Agent', 'Sia-Agent');
request.responseType = 'arraybuffer';
request.send();
var result = request.responseText;
```

Thanks, please help me.

**Comment by MitsushimaHikari** [comment]
I used the [Nodejs-Sia](https://github.com/NebulousLabs/Nodejs-Sia), and there seemed to be something wrong too.

Code:

```
import { connect } from 'sia.js'
var fs = require('fs');
var path = require('path');

connect('localhost:9980')
  .then((siad) => {
    siad.call('/miner/header')
      .then((header) => (
        fs.writeFile(path.resolve(__dirname,'hash'), header, function(err) {
          if(err) {
            return console.log(err);
            process.exit();
          }
        })
      ))
  })
  .catch((err) => {
    console.error(err)
  })
```

Hash raw file:

![hash-raw-file](http://imgur.com/a/Z2mfe)

**Comment by tbenz9** [comment]
This question would be more appropriate on the NebulousLabs/Nodejs-Sia repo here: https://github.com/NebulousLabs/Nodejs-Sia

recommendation to devs: close
