### ISSUE TITLE
Loading siad fails : 127.0.1.1:53: no such host

### ISSUE THREAD

**Issue by martinbs** [NebulousLabs/Sia#2039]
>Loading... 
(0/6) Loading siad... 
listen tcp: lookup localhost on 127.0.1.1:53: no such host

port 53 is open on my machine : _netstat -anp | grep 127.0.1.1:53_
>tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -   
udp       0      0 127.0.1.1:53            0.0.0.0:*                                  -  

_cat /etc/hosts_
>127.0.0.1	local.martin.com
127.0.1.1	ldlc

I followed the steps in that article:
https://blog.sia.tech/how-to-run-a-host-on-sia-2159ebc4725

Please help me getting started as a host.

Thank you

**Comment by rudibs** [comment]
hi Martin,

I am not a core-dev but i have set up the sia host server a few times. can you let me know what the output is of the following three commands to help us diagnose the problem?

```siac host -v```

```ifconfig```

```cat /etc/resolv.conf```

these are all to look at your network status because it looks like you have a network configuration problem

**Comment by lukechampine** [comment]
does `localhost` resolve to the correct address?

What arguments are you supplying to `siad`?

**Comment by martinbs** [comment]
siac host -v 
> Could not fetch host settings: no response from daemon

**Comment by rudibs** [comment]
the top line of my `/etc/hosts` is always this for my `sia host servers` ```127.0.0.1       localhost
```  i believe that is always correct

**Comment by rudibs** [comment]
top line of `/etc/hosts` that always works for me with regards to `localhost` name resolution:

```127.0.0.1       localhost```

**Comment by martinbs** [comment]
Ok that's what i thought, it works now thanks!

**Comment by rudibs** [comment]
you're welcome @martinbs
