### ISSUE TITLE
public key & hashes ??

### ISSUE THREAD

**Issue by 2SI3NX** [NebulousLabs/Sia#2049]
Apologies if i might have missed something but i cannot seem to find the public key, signatures and hashes of each file that is generated on http://sia.tech/apps/ ?
For the basic user who wants to verify, it would be easier if you had all this readily available, even in the wiki.

I see a .sig file in https://github.com/NebulousLabs/Sia-UI/releases  for the UI, but its unreadable.

Please help.

**Comment by lukechampine** [comment]
Instructions for verifying can be found here: https://github.com/NebulousLabs/Sia/releases/tag/v1.0.1
