### ISSUE TITLE
Sia Exited Unexpectedly on OSX 10.12 with Sia v1.2.2

### ISSUE THREAD

**Issue by siatrial** [NebulousLabs/Sia#2052]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.985420701 seconds

Wallet: scanned to height 111983...
Wallet: scanned to height 111983...
Wallet: scanned to height 111983...
Wallet: scanned to height 111983...
Wallet: scanned to height 111991...
Wallet: scanned to height 111993...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc420a9b5f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420a9b948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd17, 0xe, 0x7fff5fbffd43, 0x5, 0x7fff5fbffd32, 0x5, 0x0, 0x7fff5fbffd96, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc42007b200, 0xc420019220, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc42007b200, 0xc42000e0d0, 0x5, 0x5, 0xc42007b200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc42007b200, 0x16c7c0f, 0x3b, 0xc420148a00)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42007b200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by aa2on** [comment]
Pretty much the exact same error for me as well

**Comment by lukechampine** [comment]
dup of https://github.com/NebulousLabs/Sia/issues/1840

**Comment by siatrial** [comment]
Yes maybe same problem but this is my machine making the error.
If you need me to shed more light, its fresh install of OSX 10.12 with no other apps running except Sia.
I have one external USB drive connected and one NAS drive connected on the host.
Can work for around 12 hours then crash
Application has to force quit and then reboot computer so Sia can start again
