### ISSUE TITLE
When you have lots of files, it tries to upload ALL of them at once

### ISSUE THREAD

**Issue by Zelex** [NebulousLabs/Sia#2053]
or so it seems. If so, its *very* inefficient and really you should limit the number of simultaneous uploads. 

Taking days/weeks over here to upload a few GB

**Comment by lukechampine** [comment]
The number of simultaneous uploads is inherently limited by the number of hosts you're uploading to. The main reason why uploading many files is slow is that they are being padded to consume a full sector. See #1921
