### ISSUE TITLE
Option to disable fsync from command line

### ISSUE THREAD

**Issue by kobalicek** [NebulousLabs/Sia#2063]
I think an ability to disable this would help a lot of people with initial sync and prevent SSD destruction at that stage as well.

**Comment by DavidVorick** [comment]
That is a bad idea, you'd almost certain end up with corruption that would cost you your files, you consensus database, and your hosting contracts.

**Comment by kobalicek** [comment]
Can you elaborate? If I understand it correctly then data corruption can only happen on power failure. I don't have this problem here so I would like to use caching instead. And I asked for a command line option, for advanced users.

**Comment by kobalicek** [comment]
Just to add something to this topic. I temporarily solved this by creating a ramdisk and linking ~./config/Sia-UI to it. This way I was able to do the initial sync from 33% to 100% in less than 2 hours, while 0..33% took more than 12 hours (without the ramdisk).

**Comment by lukechampine** [comment]
disabling fsync during IBD is something that we can consider. There are clear benefits to doing so, and the risk is small compared to disabling fsync globally.

**Comment by DavidVorick** [comment]
Going to close this, disabling fsync is a really bad idea. If we want to reduce the fsync burden on disks, we should do it by reducing the number of calls to fsync that we make (something that we're already working towards)

**Comment by kobalicek** [comment]
It's your project guys, I just thought that minimizing the time of the initial sync is something many people would find useful, myself included. I no longer use SIA, though, I wish you good luck with the project.
