### ISSUE TITLE
Problem stopping daemon.

### ISSUE THREAD

**Issue by keithlovett** [NebulousLabs/Sia#2071]
I can't seem to shutdown app cleanly. When I try to stop daemon via terminal I'm informed SIAD has exited unexpectedly and I should submit bug report along with error log:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.8700533 seconds
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus set...
Closing gateway...
Shutdown complete.

Although terminal acknowledges daemon has stopped I am unable to restart SAID and receive another error log:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.8800019 seconds.

Only way to shut app down is by quitting via hidden icon, losing latest synchronisation. Normal icon has no effect. App is unusable until until then.

How do I shutdown app properly?

Thanks,
Keith

**Comment by lukechampine** [comment]
Sia-UI expects to be shutdown by closing Sia-UI. siad expects to be shutdown by closing siad. This is more of a UI bug than a siad bug.
