### ISSUE TITLE
What's the relationship between block,  transaction and Siacoin input/output etc?

### ISSUE THREAD

**Issue by TimonPeng** [NebulousLabs/Sia#2079]
There are so many descriptions that make me a bit confusing.

Input/output ∈ transaction ∈ block, is this right?

And which of the file contract belonged to?

Thanks.

**Comment by S-anasol** [comment]
Block => Transactions => Outputs/Inputs/FileContracts

Block contains Transcactions(many)
Transaction(one/each) contains many SC Output/Input, SF Output/Input, File contracts etc...

**Comment by S-anasol** [comment]
Almost Full tree here:

block
- miner payouts
- transactions
- - sc inputs
- - sc outputs
- - sf inputs
- - sf outputs
- - Storage Proofs
- - file contracts
- - - valid storage proofs
- - - missed storage proofs
- - file contracts revisions
- - - valid storage proofs
- - - missed storage proofs

**Comment by TimonPeng** [comment]
Oh, thank you so much! Thank you.

**Comment by S-anasol** [comment]
https://github.com/SiaHub
😆 🤣

https://github.com/S-anasol/siahub

**Comment by TimonPeng** [comment]
LOL. The same organization name. 😂

We can consider merging our organization in the future...

My sia daemon api is not bad, you can try it.
