### ISSUE TITLE
siad and siac 

### ISSUE THREAD

**Issue by goldkey0070** [NebulousLabs/Sia#2088]
Not compatible with UI Windows 64 wallet using windows 10 if siad and siac  started first in CMD .

**Comment by chadillac81** [comment]
Since you're already running siad from CLI (most likely on the default port), when you launch the UI you're getting a second instance of siad.  The second instance of siad is also trying to run on the default port.  The CLI wins this fight because it's already running an instance of siad on the same port the UI is trying to get the second siad instance to utilize.  Basically, you'll need to run CLI siad on a different port, then you can use the UI at the same time.

May I ask why you want to do this?

**Comment by johnathanhowell** [comment]
Sia-UI should connect to `siad` if it's running on the default `api-addr` (localhost:9980) and is fully loaded and connectable (we have automated testing for this specific case here: https://github.com/NebulousLabs/Sia-UI/blob/master/test/app.js#L184). What does 'Not compatible' mean specifically here, does an error get thrown?

**Comment by goldkey0070** [comment]
yes the error says cant find package,json file in sia resources but its there when i lookOn Friday, July 7, 2017, 12:54:35 AM CDT, Johnathan Howell <notifications@github.com> wrote:


Sia-UI should connect to siad if it's running on the default api-addr (localhost:9980) and is fully loaded and connectable (we have automated testing for this specific case here: https://github.com/NebulousLabs/Sia-UI/blob/master/test/app.js#L184). What does 'Not compatible' mean specifically here, does an error get thrown?

**Comment by goldkey0070** [comment]
When i used the wallet before thesiad dint work so i used the siad from other file and it worked but the ui siad wouldnt from then on and i would get error about no json file
On Thursday, July 6, 2017, 10:40:11 PM CDT, chadillac81 <notifications@github.com> wrote:


Since you're already running siad from CLI (most likely on the default port), when you launch the UI you're getting a second instance of siad. The second instance of siad is also trying to run on the default port. The CLI wins this fight because it's already running an instance of siad on the same port the UI is trying to get the second siad instance to utilize. Basically, you'll need to run CLI siad on a different port, then you can use the UI at the same time.

May I ask why you want to do this?

**Comment by lukechampine** [comment]
The json error should be fixed in v1.3.0
