### ISSUE TITLE
Error Adding Folder

### ISSUE THREAD

**Issue by Odoardo** [NebulousLabs/Sia#2093]
The message below has just appeared on my iMac. What does it mean? More importantly, how do I fix it? Thank you.

**Error Adding Folder**
could not allocate sector data file: truncate /Users/leveson3051/Documents/G&S Sia/siahostdata.dat: no space left on device

**Comment by lukechampine** [comment]
It means your drive is full. You need to delete some files if you want to free up space for Sia hosting.
