### ISSUE TITLE
some online hosts do not get updated by scan.go

### ISSUE THREAD

**Issue by chargr** [NebulousLabs/Sia#2094]
_assuming i understand this correctly..._

hostTree.All() returns a list of hosts sorted by weight
threadedScan() cuts off after 200 online hosts

now that the list is sorted by weight and the host list is well over 200, low ranked hosts never have their configuration updated by a scan - it seems only an announce can do so at this point.

**Comment by DavidVorick** [comment]
It also randomly queries ones outside of the top 200, so eventually you will get updated. But if you want to be certain that you are rescanned by the network quickly, the only way to do so is to re-announce.
