### ISSUE TITLE
Can I encode/decode between public key and unlock hash?

### ISSUE THREAD

**Issue by TimonPeng** [NebulousLabs/Sia#2097]
Thanks.

**Comment by lukechampine** [comment]
To create an unlock hash you need a set of [`UnlockConditions`](https://github.com/NebulousLabs/Sia/blob/master/types/signatures.go#L95).

For the vast majority of addresses, the unlock conditions are simple: they do not have a timelock and only require one signature. So if you have a pubkey, you can create the typical unlock conditions like so:
```go
uc := types.UnlockConditions{
	PublicKeys:         []types.SiaPublicKey{pubkey},
	SignaturesRequired: 1,
}
```
The `UnlockHash` is then calculated via the appropriate method on `uc`:
```go
addr := uc.UnlockHash()
```
The hash is the Merkle root of a tree that has the timelock, public keys, and number of signatures as leaves.
