### ISSUE TITLE
Storage proof revenue is incorrect in host.log

### ISSUE THREAD

**Issue by nielscastien** [NebulousLabs/Sia#2110]
The value that is shown with a successfull or failed storage proof is the Potential revenue of the host.

Line 558 in storageobligation.go should be changed to:

`h.log.Printf("Successfully submitted a storage proof. Revenue is %v.\n", so.financialMetrics.PotentialContractCompensation.Add(so.financialMetrics.PotentialStorageRevenue).Add(so.financialMetrics.PotentialDownloadBandwidthRevenue).Add(so.financialMetrics.PotentialUploadBandwidthRevenue))`

The same holds for line 574

**Comment by nielscastien** [comment]
I believe this issue is linked with #1862

**Comment by tbenz9** [comment]
Fixed in PR #2347 

Recommendation to devs: close
