### ISSUE TITLE
Siad panics if stopped while setallowance is in progress

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2115]
Commit: ec3fbc0dd35bc2ad0b476ab0c96d6e4ec3317045 + https://github.com/NebulousLabs/Sia/pull/2068
Log: https://gist.github.com/49ef9536d05809062e87bde1fdb3e5c9
(I typed Ctrl+C in the terminal running siad)

**Comment by lukechampine** [comment]
This bug is fairly old so I'd like to confirm whether or not it can be reproduced first. I don't like letting open issues fester in the backlog, so I'll close this proactively and we can reopen it if it's reproducible on the current master branch.
