### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by vanylis** [NebulousLabs/Sia#2135]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.615323769 seconds

**Comment by Cinerar** [comment]
Can't see anything wrong here.
What version do you use. Post full log.
