### ISSUE TITLE
Issues organization.

### ISSUE THREAD

**Issue by Cinerar** [NebulousLabs/Sia#2150]
I believe there should be some organization involved into issues, right now it have very bad representation of project and could eat a lot of developers time to answer and get critical information from them.
Maybe Nebulus/SIA should consider volonteers for some basic issue organization and make an issue template.  
I find this one quite informative template and it can be taken as a base for SIA issue template.
https://github.com/mholt/caddy/issues/new 

IMHO Bad issue organization produce bad feeling for developers that can join SIA development for free, and even can stop them from doing this.

@DavidVorick what do you think about it?

**Comment by lukechampine** [comment]
I think the primary problem right now is issue duplication. We have a large number of duplicate issues in the tracker, mostly the `too many files` error and the `unexpected fault address` panic. These are probably so numerous because the error messages are confusing. We're working on both of them, but in the long run we'd like to have a better way to deal with duplicate bug reports. Perhaps in the issue template we could list the most common errors or link to the troubleshooting page of the wiki.

**Comment by Cinerar** [comment]
@lukechampine Volonteers or developers  should mark and close duplicate issues and link them to original. 
The way issues go now not the way to go .

**Comment by DavidVorick** [comment]
I am strongly in favor of more active moderation of our issue tracker, including closing issues within 7 days if clear direction for how to fix them is not determined. This keeps the clutter low, and makes it easier for developers to focus on the issues. 

Is there anyone that wants to volunteer to help moderate issues on our repo? Preferably you have at least 3 merged pull requests into the Sia repo if you are volunteering to help keep the issues clean, though it's not a hard requirement.

**Comment by Cinerar** [comment]
I would like to help. But i'm quite sure that me will not be enough, as my knoweledge of SIA code and expirience is quite limited.  At least we can try some basic labeling organization, issues templates and other things that you developers do not have enough time to spend on.
So i would be very pleased if there will be more volunteers to help with issues.

**Comment by S-anasol** [comment]
@S-anasol ready to do some labeling/sorting in case of someone will prepare guidelines for it.

i.e. need some support leader i think. Like @Cinerar as author of this idea.
To avoid mess of course.

**Comment by petabytestorage** [comment]
I am volunteering to help keep the issues clean. I am the brandname of rudibs and I have 3 merged PR. I am happy to work with S-anasol and Cinerar in particular.  I am happy to work with others as well if they are interested.

**Comment by starius** [comment]
@starius ready to join!

**Comment by petabytestorage** [comment]
created slack channel #ticketgrooming

**Comment by eddiewang** [comment]
Bumping this issue. I understand the Nebulous team has closed hundreds of issues, but we need a better way to manage and give visibility to issues on Github rather than just on Discord channels.

**Comment by eddiewang** [comment]
I would be willing to volunteer my time to help manage the issues. We would need some guidelines on how the format to submit new issues, different issue tags, and a basic primer to determine if an issue is relevant or should be closed.

**Comment by Cinerar** [comment]
We have developed a suggestion for issue template  
https://docs.google.com/document/d/1Sk3s3fVIclbqBHiXC-voZYQrkeBOQEHowR-yoVH17i4/edit

Most recent version 



### 1. What version of Sia are you using (`siac version`)

### 2. What is your environment (Linux, Windows, Mac, etc...) ?

### 3. What are you trying to do? 

### 4. What did you expect to see?

### 5. What did you see instead?

### 6. Include logs.  
Cut and paste full error messages.
If you are using specific module include log file from that module (see `modules/.../....log` or `Sia-UI/sia/siad-output.log` when using Sia-UI )

### 7. How can a developer who is starting from scratch reproduce the bug as simply as possible?

**Comment by tbenz9** [comment]
Bump.  I am willing/able to help as well.  I propose we do something a little more drastic to get us through our massive backlog though.  I propose any "siad has exited unexpectedly" issue older than 7 days with no comments from a developer be closed.

Going forward let's get a #ticketgrooming room in Discord going.  And follow up with @cinerar suggestion for the issue template (I'll create a Pull Request that implements the [template](https://github.com/NebulousLabs/Sia/blob/d0d0ca09508781363b643ace050928e2cb43a3ca/build/critical.go)).

**Comment by petabytestorage** [comment]
@tbenz9 I spoke with Cinerar privately a couple times in the last few weeks and he ran out of time to help.

**Comment by tbenz9** [comment]
I've been asked by the Dev Team to try to get a handle on some of the GitHub issues.

@petabytestorage, @starius, @eddiewang, @S-anasol, If you're still willing to help; our first task is to clean up the issues we already have.  

**Tasks to do now:**
Look for duplicates, issues that have been resolved but not closed, and issues that can be closed (insufficient information, trolls, etc).  Simply comment on them with what action you think the core team should take and I'll make sure they consider your suggestion.  Be patient though, it could be a bit before they have time to review everything.

**Labels:**
For now we're going to keep the existing labels, this could change in the future but I want to sort through the backlog before we go creating/deleting labels.
If you think a label should be applied, please leave a comment saying what label(s) should be applied.  

**Template:**
I'll be working with the dev team on improving the template, I'll try to submit a PR this weekend where we can continue the discussion.  Keep an eye out for that if you want to participate or help in it's design.


Remember that the dev team will get notified whenever you comment on an issue, there is no need to @mention them unless you think a specific member should take a close look.  Thanks for your willingness to help and let's get this Issue backlog cleaned up!

**Comment by tbenz9** [comment]
@petabytestorage are you on Discord?  What's your Discord handle?  I'd love to discuss what to do with some specific issues with you if you're interested.

**Comment by lukechampine** [comment]
@petabytestorage is @rudi on Discord :)

**Comment by tbenz9** [comment]
Lets close this issue.  I'm thinking we'll be able to stay on top of future issues without changing anything in the code for now.
