### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by altcoin725** [NebulousLabs/Sia#2164]
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by altcoin725** [comment]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.7592634 seconds

**Comment by S-anasol** [comment]
kill all siad(s) and try again

**Comment by didaw** [comment]
did you find a way to fix this? i have the same problem and i cant seem to find a solution

**Comment by lukechampine** [comment]
it means another program is listening on port 9980. Try killing any other running instances of siad. If there aren't any, try running siad on a different port: `siad --api-addr :9970`
