### ISSUE TITLE
1.2.2 OSX Gui disappears from dock even when locked

### ISSUE THREAD

**Issue by BigslimVdub** [NebulousLabs/Sia#2173]
The gui will disappear from the dock and be left with a " ? " where it was that will be labeled "SIA-ui" after a few days of not syncing with the blockchain. 

On fresh install this installs to ~/Library/application support (hidden folder)

If I move the entire installed folder with my wallet and everything to a non hidden folder (ex: documents folder), I lose everything and when I open the GUI it requests a new wallet to be made and starts downloading the blockchain again even though the folder the GUI is in has the wallet and chain files. If I move the folder back to its original location everything works as it did before, wallet and everything.

suggestions on this issue?

**Comment by lukechampine** [comment]
This is an issue for Sia-UI, not Sia
