### ISSUE TITLE
fatal error: fault

### ISSUE THREAD

**Issue by patrickjam3s** [NebulousLabs/Sia#2174]
sia is syncing up at about 53.3% and it keeps doing this now, I have relaunched it several times.

Siad has exited unexpectedly.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.9030517 seconds
unexpected fault address 0x7fff1040
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x7fff1040 pc=0x72a568]

**Comment by lukechampine** [comment]
this is an out-of-disk-space error. See #1745. In the upcoming release (v1.3.0), siad will print a more helpful error message when this happens.

**Comment by patrickjam3s** [comment]
oh I thought it was syncing the wallet to the directory I installed sia to... Is there a way to set the directory, the drive I want it on has 2TB free on it.

**Comment by lukechampine** [comment]
yep, use the `-d` flag
