### ISSUE TITLE
Possible BIG Problem

### ISSUE THREAD

**Issue by DcyMatrix** [NebulousLabs/Sia#2180]
Siad 1.2.2 on Ubuntu Server 16.04LTS
Possible BIG problem, **I am writing you just to make sure I am wrong hopefully.**
Yesterday these two transactions was sent from my wallet (I am hosting NOT renting at all) 
Amount = 388,586.44 SC
Here is the link: https://explorer.siahub.info/hash/4407381eda8f00147d937dd6a46f980ba150bc988b9029b71af09d57c49c19ff5ccf5d848323
Those Sia was sent without my knowledge, and for no apparent reason I have been able to find.
After some digging I got a hunch, and went to take a look at my Poloniex.com withdraw history, this is the transaction I am suspicious about: https://explorer.siahub.info/hash/714e6a8fefc7b66d616d77a0a9ef3720b78c7b94b93559f919eca5febeab3de8 that was a withdraw for 389,682.98 SC very very close to the exact amount now suddently missing from my wallet.
My fear is that the fix, that was made some time back for all the exchanges might be to blame for this sudden transaction (reversal?).
My withdraw from Poloniex.com was made on 2017-04-05.

**Comment by lukechampine** [comment]
I'm not sure I understand your situation, but if the coins showed up in your local wallet (not on Poloniex), there is nothing Poloniex can do to force your wallet to send them. Try using the recovery tool posted [here](https://github.com/NebulousLabs/Sia-UI/issues/581#issuecomment-299747969). If it reports that the highest seed index seen in the blockchain is higher than the one in your wallet, there's a good chance that your coins can be recovered.

**Comment by DcyMatrix** [comment]
@lukechampine My wallet made 2 transactions by itself, amount in total was 388,586.44 SC
Some months back I withdraw that amount from Poloniex.com, so it was in my account for a long time until yesterday when they were suddenly transferred out from my account.

**Comment by DcyMatrix** [comment]
@lukechampine I will take a look at the recovery tool :-)

**Comment by DcyMatrix** [comment]
I will close this issue till I get a result from the recovery tool, so I don't freak people out ;-P

**Comment by lukechampine** [comment]
The most likely explanation is that your wallet needed to spend a small as number of coins, so it spent the large outputs in order to split them into smaller outputs. If you're hosting, this could happen when you put up collateral for a file contact.

**Comment by DcyMatrix** [comment]
@lukechampine I am so happy I was wrong! :-D
The recovery utility worked great! Everything seems to be back now. Thank you!
And thank you for the explanation as well, my heart probably skipped more than one beat when I saw the (to me) huge amount leaving and not coming back.

**Comment by lukechampine** [comment]
I'm always glad to hear that. But this is clearly bad UX on our part. Fortunately, the next release (v1.3.0) solves this problem. It will maintain a "lookahead" of the next few thousand addresses the wallet plans to use. That way, if you're using Sia on multiple computers, it won't get confused. So hopefully this is one of the last reports we'll see of someone "losing" coins in this way. :)
