### ISSUE TITLE
multiple files stuck at Boosting Redundancy  and new files upload pop esockettimedout

### ISSUE THREAD

**Issue by hklkf200553** [NebulousLabs/Sia#2196]
i got multiple files stuck at Boosting Redundancy and never ending ,  also new files upload pop esockettimedout warning , restart , reinstall another copy of sia wont work 

remove and generate new consensus.db wont work 
restart computer and network wont work 
adding extra budget to the storage prevent bandwidth / hosting space full wont work 

need some help

**Comment by DanielKerkmann** [comment]
Hey hklkf200553,

me and one friend of me have the same situation.
I have 50 active contracts but i think many contracts are not online.
If i ping the ip from the contracts, so many hosts are not online and sia are not closing the contracts and getting new contracts.

Im stucking at 20% on every file (0.6x).

**Comment by tbenz9** [comment]
My understanding is this is a known bug and they are working on it.  There are several discussions on Discord and in GH Issues.  Without any logs the dev team is unlikely to be able to help in your specific situation.  If you're still having problems try asking for help at https://discord.gg/sia

Recommendation to devs: Close
