### ISSUE TITLE
Cannot get transactions from API

### ISSUE THREAD

**Issue by egogo-nl** [NebulousLabs/Sia#2197]
I try to get transactions with the API, but it always returns `null`.

I've installed Sia on Ubuntu 16.04.
When I start the Sia deamon I get the following result:
```
$ ./siad -M gctwrhe &
Loading...
(0/7) Loading siad...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading explorer...
(4/7) Loading transaction pool...
(5/7) Loading wallet...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.616628007 seconds
```

When I check consensus, I see consensus is synced:
```
$ ./siac consensus
Synced: Yes
Block:      000000000000001bcd16066bf2536b413fb153368cc3e3993e1025f4c4801611
Height:     116233
Target:     [0 0 0 0 0 0 0 93 210 35 186 12 69 126 113 122 7 109 203 128 155 37 131 21 15 223 222 45 151 172 75 164]
Difficulty: 196616664314958276
```

But when I try to look up a transaction with the API, I always get the same result:
```
$ curl -s -X GET http://localhost:9980/wallet/transactions/e0e00caf28477a4ac57125ee94055991a9f2d10e57073034b1de2b70a6b370063c099ab9d861 -A "Sia-Agent"
{"confirmedtransactions":null,"unconfirmedtransactions":null}
```

I've already re-installed Sia and synced again, but still the same result.

**Comment by S-anasol** [comment]
this is your address?

e0e00caf28477a4ac57125ee94055991a9f2d10e57073034b1de2b70a6b370063c099ab9d861

**Comment by egogo-nl** [comment]
No, I want to view transactions from other wallets. Like the Sia Explorer.

**Comment by S-anasol** [comment]
this api show only your transactions.

Wallet doesnt have global api to explore blockchain. Except explorer module that doesnt work properly :(

You can use explore.sia.tech api calls
or
https://siahub.readme.io/v1.0/reference#hash
