### ISSUE TITLE
Collateral changes in 1.3.0?

### ISSUE THREAD

**Issue by JamesM424** [NebulousLabs/Sia#2201]
Hello Sia guys.

Did you change collateral handling in Capricorn?  I noticed some different wallet activity related to collateral in the update.  So to test, I upped my Collateral per TB to 500 for the last 12 hours.

I previously had 1200SC in this wallet, and sent it an additional 400.  So I should have 1600 - collateral taken for contracts formed.

In the last 12 hours, I went from 583 contracts to 759 (+176).  Locked collateral went from 20.98K to 25.21K (+4,230) and risked went from 4.001k to 5.262K (+1261)

In that time, the only wallet activity I have is a 62SC transaction and a whole lot of .04 (which I would imagine are related to a different bug opened).  My wallet balance is still ~1500SC.

**Comment by Cinerar** [comment]
https://github.com/NebulousLabs/Sia/issues/2144

**Comment by tbenz9** [comment]
Recommendation to devs: Close as this bug is tracked in #2144
