### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Wlinc** [NebulousLabs/Sia#2202]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 159.248571429 seconds

Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114557...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Wallet: scanned to height 114573...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc4208275f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420827948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffca7, 0xe, 0x7fff5fbffcd3, 0x5, 0x7fff5fbffcc2, 0x5, 0x0, 0x7fff5fbffd2e, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420079200, 0xc420015400, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420079200, 0xc42000e0d0, 0x5, 0x5, 0xc420079200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420079200, 0x16c7c0f, 0x3b, 0xc420148be0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420079200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

**Comment by Wlinc** [comment]
General related feedback: I'm on MacOS 10.12.5 and have found that crashes like this prevent me from providing good uptime as a host.

**Comment by lukechampine** [comment]
Is this on v1.3.0?

**Comment by mindjuice** [comment]
I'm seeing this too on MacOS 10.12.5.  Running v1.3.0 of sia.

**Comment by zachherbert** [comment]
Same here. Are you guys on fusion drives by any chance?

**Comment by mindjuice** [comment]
I'm on an SSD MacBook Pro.

**Comment by petabytestorage** [comment]
suggest @tbenz9 : open one issue that is "keep less files open" and close all the issues related to "too many open files" but link them in the combining issue.

**Comment by tbenz9** [comment]
@petabytestorage Excellent Idea, want to take point on this?  Create the new issue, link all the others to it.  (I don't have permission to close issue yet so I'm in the same boat as you).

**Comment by Wlinc** [comment]
I'll go ahead and close the issue, but I don't think it was truly resolved. I just ran out of time to keep working with hosting and realized that my setup doesn't offer enough uptime to meet the SLAs.

**Comment by Wlinc** [comment]
If it helps @petabytestorage and @tbenz9 I tried hosting most recently on wallet version 1.3.9
