### ISSUE TITLE
103.33% upload progress with 3.10x redundancy

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2205]
I uploaded two files in Sia and they've somehow reached > 100% upload:

```
PS C:\sia-nextcloud> docker exec -it sianextcloud_sia_1 ./siac renter -v
Renter info:
        Storage Spending:  476.9 mS
        Upload Spending:   21.3 mS
        Download Spending: 3.887 mS
        Unspent Funds:     218.7 SC
        Total Allocated:   219.2 SC

Tracking 2 files:
File size  Available  Progress  Redundancy  Renewing  Sia path
198.61 MB  Yes         101.33%        3.00  Yes       Futurama - s04e05 - A Taste of Freedom.mp4
167.82 MB  Yes         103.33%        3.10  Yes       Futurama - s04e11 - Where No Fan Has Gone Before.mp4

PS C:\sia-nextcloud> docker exec -it sianextcloud_sia_1 ./siac version
Sia Client v1.3.0
Sia Daemon v1.3.0
```

Is this expected behavior?

**Comment by eddiewang** [comment]
@mtlynch I believe so. It tries it's best to maintain a 3x redundancy. As your contracted hosts go offline or disappear, the progress will extend pass 100% to try and get back to 3x redundancy. However, sometimes the host will come back online, which is why redundancy won't hover exactly at 3x.

**Comment by DavidVorick** [comment]
Yes. The 101% is totalDataUploaded/totalFileSizeAfterRedundancy. If your hosts go offline and then you repair, the 100% will go above 100%.

The 3.10 happens if you have a host go offline, and then you repair that file, and then the host comes back online.

**Comment by mtlynch** [comment]
I can understand 3.10x redundancy, but 103.33% is nonsensical in this context. A process can't be more than 100% complete. Suggest capping progress indicator to 100% because from the user's perspective, it is 100% complete.

**Comment by lukechampine** [comment]
duplicate of #1557
