### ISSUE TITLE
Bug: Sia UI crashes when trying to unlock wallet

### ISSUE THREAD

**Issue by TheDujin** [NebulousLabs/Sia#2207]
As stated in the title, Sia UI crashes when I try to unlock my wallet. After I enter in my wallet password, Sia UI tells me "Scanning the blockchain", but crashes after a few minutes. This has happened three times out of three times trying to unlock my wallet.

There is a really long error report, but I can't copy it in because of how long it is (exceeds the character limit). I'll just attach a .txt file containing it then.
[temp.txt](https://github.com/NebulousLabs/Sia/files/1191414/temp.txt)

**Comment by lukechampine** [comment]
Are you using v1.3.0? Is there enough space left on your drive? Are you using a network drive or other unconventional drive setup? What version of Windows are you using?

**Comment by TheDujin** [comment]
I see Product Version: 1.6.4, and I have 1 TB on my hard drive and am only using 1/3 of it. I don't think I have any unconventional setup; it's an unmodified Dell Inspiron (15 5000 series). I have Windows 10.

Synchronization took a long time, and while it was still synchronizing, I was able to unlock my wallet, but now that synchronization is complete, it crashes.

**Comment by lukechampine** [comment]
You can check the version in the `About` view. v1.3.0 is the most recent release.
I know it sucks, but other users have reported that redownloading the blockchain sometimes fixes these strange boltdb errors.

**Comment by TheDujin** [comment]
Oops, I looked under Windows -> Properties and saw 1.6.4. I have 1.2.2; how should I update to 1.3.0 without losing my wallet (I am mostly clueless as to how this all works)? Thanks.

**Comment by lukechampine** [comment]
you should be able to delete your Sia-UI folder and replace it with the new release. The blockchain and your wallet are stored in a separate location. Make a backup if you want to be sure. You can always recover your wallet using your seed phrase. Also make sure to completely shutdown the old version before starting the new version.

**Comment by TheDujin** [comment]
I deleted my Sia UI folder and downloaded and unzipped version 1.3.0, but when I try to run Sia-UI, it crashes. The error log is attached.
[temp.txt](https://github.com/NebulousLabs/Sia/files/1201035/temp.txt)

I am fairly certain I completely shut down the old Sia-UI version; right click on Sia's icon, then click "Quit Sia", right?

**Comment by lukechampine** [comment]
Ok. At this point you'll have to try deleting the blockchain and redownloading it. Quit Sia, delete the folder `%APPDATA%\Sia-UI\sia\consensus`, and restart Sia. It should automatically begin redownloading.

**Comment by TheDujin** [comment]
Deleted that folder and it still crashes on startup.

**Comment by tbenz9** [comment]
@TheDujin Please try the latest Sia version 1.3.1 You can also follow the instructions below to completely reinstall Sia.

https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

I'm going to close this issue due to inactivity, age, and a new version of Sia being released since it was last updated.  If you still need help you can re-open this issue.
