### ISSUE TITLE
Bug: Renter Info showing 0 H

### ISSUE THREAD

**Issue by kpr2011** [NebulousLabs/Sia#2208]
I set up allowance and formed contracts. After uploading for a few minutes the renter info reset all the values to 0 H

![image](https://user-images.githubusercontent.com/12262015/28843903-a4fb85fe-76b7-11e7-9223-41d33aed5dc6.png)

**Comment by eddiewang** [comment]
I can confirm that this issue is happening to me as well. Strangely, uploading and downloading still works as intended, and running `watch siac renter contracts` will show the contracts functioning as normal.

**Comment by eddiewang** [comment]
@kpr2011 do you have any files that have stopped uploading?

**Comment by kpr2011** [comment]
@eddiewang Nope, uploading without any problems. It's just i have no idea of knowing how much i have left and when to stop or add more funds.

**Comment by tbenz9** [comment]
without more information the devs are unlikely to be able to do anything with this information.  I would recommend uninstalling and reinstalling Sia (make sure you backup your renter folder).  If you're still having problems try asking for help at https://discord.gg/sia

Recommendation to devs: close
