### ISSUE TITLE
[feature] siac renter download allow to queue download async

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#2209]
Add a paramater to siac download to allow it to trigger the download to siad and then return without waiting for the file to be downloaded. There already is support to view status with siac renter downloads.

**Comment by lukechampine** [comment]
This should be fairly easy to add. In the meantime, you can use `siac renter download [file] [path] &`.

**Comment by tbenz9** [comment]
Recommendation to Devs: "Feature Request"
