### ISSUE TITLE
Error Removing Folder

### ISSUE THREAD

**Issue by Vaenoxis** [NebulousLabs/Sia#2212]
Hi and sorry for my english. 

I have a big problem on my SIA UI, i can't manage to delete some old folders that do not exist anymore. I Always get the same error message: "Error Removing Folder, no storage folder exists at that index". 
Even if the folder exists, i got the same message.. 
![capture d ecran 2017-08-02 a 21 50 46](https://user-images.githubusercontent.com/30668737/28892248-9970cb2e-77cd-11e7-881a-fa0971706bf4.png)

So now i've got only one folder wich is working (Sia Host 3) and 6-7 ghost folders (some of them do not exists, but the UI think they are working with some used and free space but no, i delete those folder.. I can't remove them to re add new one in order to have much space to offer to my renters.. 
Another dude in reddit has the same issue: " Can't remove storage folder self.siacoin
soumis il y a 28 jours par iissmarter
I'm trying to remove a storage folder with the command 'siac host folder remove /path/to/folder/' but I'm getting the error: "Could not remove folder: no storage folder exists at that index". I can add/remove additional folders at different paths perfectly fine, but there is one folder that can't be removed. The folder is currently empty so I was trying to recreate it. Any ideas on how to clear out this storage folder so I can re-add it? 
The 'host folder add' command says the folder is already in use as a storage folder. 'host folder resize' and 'host folder remove' both say no storage folder exists at that index."

I don't know what to do. I try something that Taek suggested in an old post saying i could remove the folder via the console, but it didn't worked. :/ 

Here is my computer in Siahub: https://siahub.info/host/3055 
Siahub think i've got more than 2 TB of free space, but currently i only have the folder Sia Host 3 wich is a folder in my mac desktop of 298 Gb wich is working great, and the folder "Fast Siadude" wich is an external SSD of 249 GB that i add as a folder, thinking it could be good to have an SSD (renters could download and upload faster no ?). But Fast Siadude doesn't seem to fulfill with some contract, and i can't remove it (error removing folder). 

Long post, i love SIA, i've managed to do a lot of thing in order to get it working, l've learned a lot, but now i'm kind of stucked. 
Any help please ? 

Vaenoxis

**Comment by Vaenoxis** [comment]
Up

**Comment by Vaenoxis** [comment]
Pleaaaaaase guys. There is absolutely no one to help me. I can't erase those folders. 

Could someone answer me and not walk away. We are a community we try to help each other with SIA, there is an actual problems, other people have this problem. 
Why nobody answer in Slack or here, what can i do to have my SIA folders working ? 
It drive me crazy.. 

Taek, someone. 

please help me :'(..... !!!

**Comment by Vaenoxis** [comment]
Should i delete everything and reinstall SIA ? 
Could i get my contract back if i reinstall SIA and add new folders ? 

Maybe it is a solution ?

**Comment by Vaenoxis** [comment]
Ok, i am calm now. 
My question is. 
How can I reinstall sia without losing my contracts, but without any folders added in the UI (this is my problems, all those ghost folders). 
I would love to reinstall a clean sia, copy the wallet folders in it. Have my contracts back, add my ONLY folder wich is working, and that’s it.. 
taek said somewhere that if an host folders is deleted, the renters will automatically reupload their content in the new host folder. So maybe if I could reinstall sia, keeping my contract but not all those bugged folders, and add new clean folders it will work no ? 

I am sorry but it is not so easy to be understood in English, of someone is using sia and speak french 😢.. 

Good night everyone.

**Comment by lukechampine** [comment]
Sorry for the slow response.

On OS X, your Sia data is stored in `$HOME/Library/Application Support/Sia-UI/sia`. To do a clean reinstall, delete the `host` folder and restart Sia. You will lose all your current contracts, but renters will eventually form new ones with you.

**Comment by Vaenoxis** [comment]
Thank you 🙏🏻 very very much lukechampine. I will do that.
Have a good day !

**Comment by Vaenoxis** [comment]
I did what you say. I delete the host folder (so no host folder anymore in /applicaion support/sia-ui/sia. 
I restarted SIA, and now sia said: loading can take a while after upgrading to a  new version. For about 30 minutes now :/. 

do you think Sia will re create the host folder and launch ?

**Comment by tbenz9** [comment]
Recommendation to devs: close
