### ISSUE TITLE
siad is constantly writing ~200 KiB to disk when 'host' module is enabled

### ISSUE THREAD

**Issue by Flowdalic** [NebulousLabs/Sia#2215]
I've setup siad and already host ~5GiB. I noticed that siad is constantly performing write operations.

```
Total DISK READ :     904.36 K/s | Total DISK WRITE :     239.43 K/s
Actual DISK READ:     904.36 K/s | Actual DISK WRITE:     344.83 K/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                  
  287 be/4 sia       208.20 K/s   39.04 K/s  0.00 %  9.93 % siad -d /var/lib/sia
 1272 be/4 sia        19.52 K/s   23.42 K/s  0.00 %  5.81 % siad -d /var/lib/sia
  274 be/4 sia        42.94 K/s   46.84 K/s  0.00 %  4.88 % siad -d /var/lib/sia
  383 be/4 sia         0.00 B/s   65.06 K/s  0.00 %  4.25 % siad -d /var/lib/sia
 1274 be/4 sia         0.00 B/s   52.05 K/s  0.00 %  4.02 % siad -d /var/lib/sia
  296 be/4 bitcoin   633.70 K/s    0.00 B/s  0.97 %  2.01 % bitcoind -daemon -con~.pid [bitcoin-msghand]
  343 be/4 sia         0.00 B/s   13.01 K/s  0.00 %  0.00 % siad -d /var/lib/sia
    1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % systemd --system --deserialize 20
    2 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.
```

The blockchain is fully synced. While it would be great, I doubt that there are constants file uploads going on, as my storage's folder used space does not grow.

Compare this to bitcoind running on the same system, which mostly performs reads and occasional writes (e.g. when a new block is found).

**Why does siad constantly write ~200 KiB/s to disk**?

<sup>[Original sia forum post](https://forum.sia.tech/topic/1537/siad-is-constantly-writing-to-disk)</sup>

**Comment by lukechampine** [comment]
from the thread:
>I set up disk monitoring for siad process and found out what it is constantly (every second!) rewrite all files in \sia\host\contractmanager\ folder.

Would be good if we could confirm this, perhaps using `strace` or a similar tool. It's definitely true that some modules are saving their state to disk on a regular basis. It's also true that modules log nearly all incoming events. If you're hosting, my guess is that incoming RPCs are resulting in disk writes, even if they don't result in new data being stored.

**Comment by lf94** [comment]
Is there a somewhat easy way to turn off logging?

**Comment by lukechampine** [comment]
Not currently, but #2085 may make it easy to disable, depending on how we implement it.

No idea if this will work, but you could try replacing the default log files with symlinks to `/dev/null`?

**Comment by DavidVorick** [comment]
The 200KB/s I think comes from the host continually writing the sector metadata to disk once per second. We have plans to fix this by moving the sector metadata (should have been designed that way in the first place, oops), and also by changing it from writing once per second to only writing when there's actual activity.

**Comment by pablos91** [comment]
I can this issue. My NAS is quiet enough to hear disk reads and writes and it sounds like heart beating when I start the sia host. Running without issue when starting w/o host module

**Comment by KopfKrieg** [comment]
This is a serious issue, most harddrives are not designed to write data 24/7 to the disk. The disk should be able to put itself into idle/sleep mode if there's no new data.

**Comment by avahowell** [comment]
#2362 should fix this.
