### ISSUE TITLE
new BigNumber() not a number

### ISSUE THREAD

**Issue by uclnj** [NebulousLabs/Sia#2219]
Trying to send some SIA over to bittrex using their generated address and getting the error new BigNumber() not a number

![screenshot 2017-08-07 09 14 45](https://user-images.githubusercontent.com/835685/29028072-235000fe-7b51-11e7-9546-74dd2bc3fc57.png)

**Comment by lukechampine** [comment]
Perhaps you mixed up the amount and the address?

Regardless, we should throw a better error here

**Comment by uclnj** [comment]
Copied it directly from the bittrex site, many times just to be safe.  Same result.

**Comment by lukechampine** [comment]
It's not that the address is wrong, it's that it's being pasted into the wrong field (at least, that's my guess)

As a workaround, go to the Terminal and enter `wallet send siacoins <amount> <address>`

**Comment by tlightsky** [comment]
paste address to amount? lol

**Comment by DavidVorick** [comment]
This is actually a Sia-UI problem. Closing this issue and opening a corresponding issue for Sia-UI.
