### ISSUE TITLE
Source build failure: unrecognized import path "runtime/trace"

### ISSUE THREAD

**Issue by madsmao** [NebulousLabs/Sia#2221]
I'm trying to build from source following the instructions in the Readme. I'm on Debian Jessie. I run this command:

`go get -u github.com/NebulousLabs/Sia/...`

And get this output on the final line:

`imports runtime/trace: unrecognized import path "runtime/trace"`

Subsequently when trying to run `make release-std`, I get the following error:

```
profile/profile.go:10:2: cannot find package "runtime/trace" in any of:
	/usr/lib/go/src/pkg/runtime/trace (from $GOROOT)
	/root/go/src/runtime/trace (from $GOPATH)
```

Here is the output of `go env` for reference:

```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by Fornax96** [comment]
Maybe your gcc is outdated? https://github.com/golang/go/issues/15544

**Comment by madsmao** [comment]
Yeah, that must have been the case because upgrading from Jessie to Stretch solved the issue.
