### ISSUE TITLE
Cant upload files, many contracts offline

### ISSUE THREAD

**Issue by DanielKerkmann** [NebulousLabs/Sia#2222]
Hey, i cant upload any files with siac or Sia-UI,

if i upload a new file, 6 contracts working fine and receiving my files but the other 44 contracts are not pingable and not accepting my files.
All of my files are stucking on 20% uploading and i dont now what to do.
One of my friend have the same issue with 60% and on another friend it works fine.

I uploaded my contracts list: https://pastebin.com/J3J2EdpV

Sorry for my bad english. :D

**Comment by lukechampine** [comment]
If only 6 contacts are working, you will not be able to recover your file. You could wait and hope that enough of the hosts come back online for you to download files. Or you could give up and form new contacts. Either way, the unused coins in those contracts will still be returned to you when the contract ends.

What version did you upload the files on? New versions do a better job of migrating data off of offline hosts. Have you been actively running Sia since you uploaded, or did you only run it rarely? Sia must be running in order to migrate data.

**Comment by DanielKerkmann** [comment]
Sia is running 24/7 since 7 days. I uploaded the files 3 days ago and have only 7 contracts working fromn 57.

How can i form new contracts? sia is building automatically contracts.

**Comment by lukechampine** [comment]
I am able to manually ping most of the contracts listed. Are there errors in your `renter.log` or `contractor.log`? It seems more likely that the hosts are online, but the revision process is failing.

The contracts end at height 130756, which will occur around November.

**Comment by DanielKerkmann** [comment]
I dont use sia since November, i have installed Sia-UI last month and build it completely from the blockchain with Sia-UI.

The log files are not showing any weird errors.

[contractor.log.txt](https://github.com/NebulousLabs/Sia/files/1212504/contractor.log.txt)
[renter.log.txt](https://github.com/NebulousLabs/Sia/files/1212505/renter.log.txt)
[contracts.txt](https://github.com/NebulousLabs/Sia/files/1212512/contracts.txt)

**Comment by DanielKerkmann** [comment]
Okay, strange.

I have found one weird thing, if i close Sia-UI and reopen it, the blockchain must resync after 99.2% and after 5 Minutes it have 100% and is complete.

But if i close and reopen it, it is the same situation with 99.2%...

**Comment by lukechampine** [comment]
Hmm. This warrants more investigation.

The resync thing is normal, it's because Sia is paranoid about whether it is truly synced or not. It won't mark you as 100% synced until it has connected to some peers with the same blockheight.

**Comment by DanielKerkmann** [comment]
Thats realy weird, im living in germany and the problem is very often.

One server in Frankfurt am Main have the problem, im living in 36381 Schlüchtern and have the problem, one friend lieving in 36391 Sinntal Altengronau and have the problem.

Another friend living also in Schlüchtern and have no problems.

Okay i have package alle files excluding my wallet.db, consensus.db, transactionpool.db and uploaded it.

If you need it, i can upload it for you, except the wallet.db. xD

[sia.zip](https://github.com/NebulousLabs/Sia/files/1212849/sia.zip)

**Comment by DanielKerkmann** [comment]
Okay, they have 62 contracts but still not going to upload, its on %23.33.

Renter info:
	Storage Spending:  19.22 mS
	Upload Spending:   655.6 uS
	Download Spending: 0 H
	Unspent Funds:     1.289 KS
	Total Allocated:   1.289 KS

Tracking 1 files:
  42.8 KB  testbild.jpg (uploading, 23.33%)

**Comment by DanielKerkmann** [comment]
@lukechampine oh thank, nice to know, i dont know what works with the contracts.
Yes i can compile it, i have a compiled version from git repo, how can i run it with debugging?

**Comment by lukechampine** [comment]
perfect, just run `make release` and it will install `siad` to your PATH as usual. Then restart `siad` and examine the output of `renter.log` for a while (15-20 minutes should be enough to catch something interesting). If nothing suspicious happens, try uploading another file.

**Comment by DanielKerkmann** [comment]
Okay thank, i started it after building it with go.

I upload another file and see what is happening.
"I hope", the error with the commandline and compiled version is the same as Sia-UI to reproduce the error and find a fix. ;)

See you in 20 Minutes back. ;)

**Comment by DanielKerkmann** [comment]
@lukechampine okay it took a little bit more time that i excpected, now im getting realy good logfiles.
I have started now uploading new files, the logfile are very fresh, i upload new logfile in 20 minutes. ;)

[renter.log.txt](https://github.com/NebulousLabs/Sia/files/1213246/renter.log.txt)

**Comment by DanielKerkmann** [comment]
Okay the issue is here:
[modules/host/negotiaterevisecontract.go#L298](https://github.com/NebulousLabs/Sia/blob/master/modules/host/negotiaterevisecontract.go#L298)

I dont know why, but from that line there comes the error message.

**Comment by lukechampine** [comment]
hmm. That's a strange error, but there's an easy fix. In `modules/renter/proto/editor.go`, apply this change:
```diff
 var hostPriceLeeway = build.Select(build.Var{
        Dev:      0.05,
-       Standard: 0.002,
+       Standard: 0.01,
        Testing:  0.002,
 }).(float64)
```
this should add enough leeway to the collateral math for hosts to start accepting your revisions again. Recompile (again with `make release`) and see if the uploads resume.

**Comment by DanielKerkmann** [comment]
Ouh man, that works so good, after a few seconds all contracts are downloading my files..
Thank you very much.

**Comment by lukechampine** [comment]
you can cross-compile using `GOOS=windows go build -o siad.exe ./siad`. There may be some missing dependencies though, in which case you would also need to do `GOOS=windows make dependencies`. After that, copy the `siad.exe` binary to `Sia-UI/resources/app/Sia/siad.exe` on the windows machine.

I'll make a separate issue for this so that we can have it permanently fixed in the next release.
