### ISSUE TITLE
HttpPOST  

### ISSUE THREAD

**Issue by Jackluren** [NebulousLabs/Sia#2224]
When I call this resp, err := api.HttpPOSTAuthenticated(url, "", password)

resp.Status is 400 Bad request,what is the reseason for this ?

**Comment by lukechampine** [comment]
what URL are you using? There are lots of routes that return 400. The body of the response should contain the specific error message; try printing it with:
```go
io.Copy(os.Stdout, resp.Body)
```

**Comment by DavidVorick** [comment]
Closing until further information is provided
