### ISSUE TITLE
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system

### ISSUE THREAD

**Issue by agarustovich** [NebulousLabs/Sia#2228]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.011216364 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc4201cd5c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4201cd930, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffcbc, 0xe, 0x7fff5fbffce8, 0x5, 0x7fff5fbffcd7, 0x5, 0x0, 0x7fff5fbffd3f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:311 +0xaa9
main.startDaemonCmd(0xc420081200, 0xc4200194f0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420081200, 0xc42000e0d0, 0x5, 0x5, 0xc420081200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420081200, 0x16fce88, 0x3b, 0xc420150a00)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420081200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
Shutdown complete.

**Comment by S-anasol** [comment]
too many open files, https://stackoverflow.com/a/923369

**Comment by Wlinc** [comment]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.750097829 seconds

Wallet: scanned to height 118238...
Wallet: scanned to height 118748...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1043857, 0x0, 0xc420a195f8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420a19948, 0x1, 0x1)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffca7, 0xe, 0x7fff5fbffcd3, 0x5, 0x7fff5fbffcc2, 0x5, 0x0, 0x7fff5fbffd2e, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:295 +0xaa9
main.startDaemonCmd(0xc420079200, 0xc4200153b0, 0x0, 0x5)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:309 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc420079200, 0xc42000e0d0, 0x5, 0x5, 0xc420079200, 0xc42000e0d0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc420079200, 0x16c7c0f, 0x3b, 0xc420148b40)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420079200, 0x1aa6520, 0x16b10c0)
	/home/jrh/go/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/home/jrh/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x79d
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...

**Comment by avahowell** [comment]
Please try the latest release, v1.3.0, which addresses this issue along with a few others: https://github.com/NebulousLabs/Sia-UI/releases/tag/v1.3.0

**Comment by Wlinc** [comment]
@avahowell Thank you. I will update and attempt to host again.

**Comment by tbenz9** [comment]
@Wlinc Any update?  Can you close this issue if it's resolved?  You might also try asking for help on the Sia Discord https://discord.gg/sia

**Comment by Wlinc** [comment]
@tbenz9 I don't recall if it was resolved by updating or not. I realized that I am short on time to play around with hosting and that I can't offer the uptime needed, so I gave up essentially.
