### ISSUE TITLE
Memory Pool for Renter Uploader and Downloader

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#2233]
We need to add a memory pool for the uploader and downloader. When you upload and download files, you need to store all of the data in memory at once. There are ways to improve upon this, but the fact remains that upload and download jobs both require a bunch of memory, and we want a global manager that will prevent each of them from allocating too much.

The memory pool should have some configurable amount of memory, and then a function for requesting memory, and a function for returning memory. You should be able to request memory with a priority. The request will block until there is enough memory in the pool to provide all of the memory at once. An error should be returned if too much memory is requested. If multiple requests for memory are active, they should be fed memory in order of priority.

The uploader and downloader should be able to release partial amounts of data at a time. This is most relevant to uploading, where data can be released as soon as the sector upload finishes.

To prevent deadlocks, we need to be certain that no process will ever request memory twice in a row. Once memory has been requested, that needs to be enough memory to complete the full operation.

There is one major complication, which is online file repair, where the uploader uses the downloader before beginning a repair operation. The uploader will need to specify to the downloader the amount of memory that it needs, and then the downloader should make the memory request based on `max(downloader needs, uploader needs)`. When it returns memory, it should return enough memory so that only `uploader needs` memory remains, and then expect that the uploader will return the rest.

We will configure the uploader and downloader to request memory from the pool once this piece of code exists. We should make sure to cleanly segment this code from the other code, and perhaps it should even be a subpackage.

**Comment by lukechampine** [comment]
Would probably simplify the code a lot if all requests/returns were 1 sector. If the requests are arbitrary, I worry that you'd need to do a lot of bookkeeping + defragging.

**Comment by DavidVorick** [comment]
Dynamic growth might be good, including releasing memory if it's not used for a while. Also good would be to allow the user to adjust this memory volume on-the-fly in the API (later of course, not in the first pass).

We probably don't want to limit this library to feeding memory in the size of one sector. One thing we can do to really help memory usage is to only erasure code things like 4kb at a time, instead of 4mb at a time. During repair, we end up throwing away most of the memory when we are done. So instead of taking a full 50 sectors (for 20-of-50), we take the 10 we plan on uploading, plus some 200kb scratch space so we can encode 4kb fragments at a time.

When I made this issue, I wasn't planning on re-using the memory, just on allocating new memory each time memory was requested and making sure only a limited amount was allocated at any given time. Re-using memory is certainly an extra step of complexity, though it may be worthwhile.

**Comment by lukechampine** [comment]
hmm, so more like a rate limiter than a `sync.Pool`. That'd probably be even easier to implement. Would this work?

```go
type memLimiter struct {
	inuse int64
	limit int64
	cond  *sync.Cond
}

func (m *memLimiter) Get(n int) []byte {
	m.cond.L.Lock()
	for m.inuse+int64(n) > m.limit {
		m.cond.Wait()
	}
	m.inuse += int64(n)
	m.cond.L.Unlock()
	return make([]byte, n)
}

func (m *memLimiter) Put(n int) {
	m.cond.L.Lock()
	m.inuse -= int64(n)
	if m.inuse < 0 {
		panic("memory in use cannot be < 0")
	}
	m.cond.L.Unlock()
	m.cond.Broadcast()
}

func newMemLimiter(limit int64) *memLimiter {
	return &memLimiter{
		limit: limit,
		cond:  sync.NewCond(new(sync.Mutex)),
	}
}
```
