### ISSUE TITLE
Windows 7 - Initial blockchain synchronisation failed

### ISSUE THREAD

**Issue by chrisr1256** [NebulousLabs/Sia#2240]
Initial installation and run of Sia UX on 64 bit Windows 7 platform

Synchronizing blockchain, got to 27.2% 

Software was installed on Drive E: with plenty of free space, Drive C: had 275MB free when it crashed 

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.210012 seconds
goroutine 121853 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04242ddc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04242df20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0422295e0, 0xc04242df20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04467b140, 0xc042075988)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\Chris\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\Chris\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
panic: bolt.DB.meta(): invalid meta pages
	panic: bolt.DB.meta(): invalid meta pages

goroutine 27 [running]:
github.com/NebulousLabs/bolt.(*DB).meta(0xc0420fa780, 0xcc3)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xed
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc042cdac40)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*DB).Update.func1(0xc042cdac40)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:595 +0x45
panic(0x9f3160, 0xc044ddb960)
	/usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/NebulousLabs/bolt.(*DB).meta(0xc0420fa780, 0xcc3)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xed
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc042cdac40)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc042cdac40, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:164 +0x8a0
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420fa780, 0xc043baf2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xfe
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042160280, 0xc0446dbc00, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x520
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042160280, 0xde41c0, 0xc043725cc0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5be
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde41c0, 0xc043725cc0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc04206cdc0, 0xc0424de900, 0x13, 0xaddb78, 0xa, 0xc0494e1aa0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x339
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc04206cdc0, 0xc0424de900, 0x13, 0xaddb78, 0xa, 0xc0494e1aa0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042160280, 0xc04202def0, 0xc04202deb0, 0xc04202deb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x133
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042160280, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x30e
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421bcc50, 0xc042160280, 0xde4440, 0xc04206cdc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x404
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x641

**Comment by chrisr1256** [comment]
It looks increaqsingly likely that the problem was due to lack of space on drive C: though it would be useful if the app said so!

**Comment by lukechampine** [comment]
in most cases it should fail with a readable "out of disk space" error, but it looks like we aren't catching all the places where running out of space can cause a weird error message.

Another point of confusion is that Sia-UI always stores the blockchain in `%APPDATA%` which (IIRC) is always on `C:`, so it can be surprising to see "out of disk space" errors when you believe you installed Sia-UI on a large, empty drive.

**Comment by tlightsky** [comment]
@lukechampine many people don't have a large C: drive, quite a problem

@chrisr1256 you can start `siad` under some folder in `E:\` drive, 
then start `Sia-UI` after load finished (everytime)

**Comment by tbenz9** [comment]
This bug is being tracked in #2407 and #2318 

Using the Sia command line you can specify what directory Sia uses for storing its configurations, blockchain, and files.

Recommendation to devs: Close
