### ISSUE TITLE
Siad has exited unexpectedly - error log

### ISSUE THREAD

**Issue by Tibika** [NebulousLabs/Sia#2243]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.038756218 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc42021f5c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42021f930, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffd4c, 0xe, 0x7fff5fbffd78, 0x5, 0x7fff5fbffd67, 0x5, 0x0, 0x7fff5fbffdcd, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:311 +0xaa9
main.startDaemonCmd(0xc420083200, 0xc420019310, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420083200, 0xc42000e0d0, 0x5, 0x5, 0xc420083200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420083200, 0x16fce88, 0x3b, 0xc420150960)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420083200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
Shutdown complete.

**Comment by DanielKerkmann** [comment]
Same here. ;)

Running with debugging enabled
Loading...
(0/6) Loading siad...
mkdir profiles: permission denied
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1688.847625039 seconds
panic: Contract Merkle roots mismatch: 12 10

goroutine 116409 [running]:
github.com/NebulousLabs/Sia/modules/renter/contractor.(*journal).checkpoint(0xc42696ee20, 0x0, 0xc422c283c0, 0x2, 0x5, 0x32, 0x32a0, 0x1950, 0x1d198, 0xc4203604b0, ...)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/journal.go:82 +0x9e4
github.com/NebulousLabs/Sia/modules/renter/contractor.(*stdPersist).save(0xc426cc8020, 0x0, 0xc422c283c0, 0x2, 0x5, 0x32, 0x32a0, 0x1950, 0x1d198, 0xc4203604b0, ...)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/dependencies.go:88 +0x141
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).save(0xc424646000, 0xc42394c030, 0xc42742ea48)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/persist.go:124 +0xc2
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).ProcessConsensusChange(0xc424646000, 0xdad3b0a16e077c56, 0xf8598446b8ca217d, 0xf4d38419f920d11f, 0x7a385040cacab54e, 0x0, 0x0, 0x0, 0xc421d1ca80, 0x1, ...)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/update.go:55 +0x7b6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc42029c000, 0x0, 0x0, 0x0, 0xc425a021e0, 0x1, 0x1)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:115 +0x173
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc42029c000, 0xc42450dd18, 0x1, 0x1, 0x1e8400, 0x0, 0x0)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:338 +0x75a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlock.func1(0xe33a60, 0xc429c706c0, 0x0, 0x0)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:529 +0x209
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4201e0000, 0xc42022aa40, 0x12, 0xb03973, 0x7, 0xc4227f16e0, 0x0, 0x0)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x332
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4201e0000, 0xc42022aa40, 0x12, 0xb03973, 0x7, 0xc4227f16e0, 0x0, 0x0)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader.func5(0xc427fc55c0, 0xc427fc55a0, 0xc42029c000, 0xe33a60, 0xc42164ad60, 0xc42074afa0)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:459 +0x14a
created by github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedRPCRelayHeader
	/home/daniel/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:463 +0x47a

**Comment by tbenz9** [comment]
Tracked in #2406 

Recommendation to Devs: Close this issue
