### ISSUE TITLE
sia quit unexpectedly

### ISSUE THREAD

**Issue by owain82220** [NebulousLabs/Sia#2249]
This is actually the 2nd time its happened.

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 58.494324 seconds

Has stopped syncing at 97%

**Comment by Tinkymon** [comment]
did you resolve this?

**Comment by owain82220** [comment]
Not yet no. I'm not sure what else I can do except start all over again

**Comment by jaaayy** [comment]
i have the same.. what to do?

**Comment by DavidVorick** [comment]
Siad just closes? Is it possibly running out of memory?

**Comment by owain82220** [comment]
I still haven't solved the issue. 

I tried downloading again, but the same thing happens:

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 120.4616258 seconds

I read in another post there is a way to fix this in CMD. I tried that too, but failed.
https://forum.sia.tech/topic/1093/a-critical-error-loading-sia-has-occured-siad-unexpectedly-exited

If there are any Sia programmers reading this, please help. It looks like its a common problem, especially for people like myself who are new to crypto. 

If mass adoption is the aim here, this wallet really needs to have the simple outcome of you download it and it works. A faster way for it to sync also.

**Comment by petabytestorage** [comment]
@tbenz9  suggest close non-actionable - not enough info, stable release coming in 1.3.1

**Comment by tbenz9** [comment]
Recommendation to devs: Close (see comment above)
