### ISSUE TITLE
HTTP API /file/status returning bad json

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia#225]
This needs to be verified, but the user interface seems to be having a display problem.

When we don't have files, we get something like this...
`{"Files":null}`
When we do have files, we get something like this...
`{"Files":[""]}

We should be getting `{"Files":[]}` and `{"Files":["filename.txt"]}` respectively

More testing needed to verify it's an actual issue

**Comment by seveibar** [comment]
Thanks to @lukechampine we have sourced the error.

Slices need to be instantiated before they're sent to json.Marshal. So sometimes you shouldn't use named return arguments.

This commit fixed it for `/peer/status`
https://github.com/seveibar/Sia/commit/5436e308857cb904ae8d53dcf26b287065f5732e

We'll have to enforce this convention on info structs or change how we output JSON.

relevant go
```go
 // AddressBook returns the server's address book as a slice.
-func (tcps *TCPServer) AddressBook() (book []Address) {
+func (tcps *TCPServer) AddressBook() []Address {
 	tcps.RLock()
 	defer tcps.RUnlock()
+	book := []Address{}
 	for address := range tcps.addressbook {
 		book = append(book, address)
 	}
-	return
+	return book
 }
```

**Comment by DavidVorick** [comment]
is this
