### ISSUE TITLE
Siad has exited unexpectedly. Not Syncing

### ISSUE THREAD

**Issue by Tinkymon** [NebulousLabs/Sia#2257]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.0304612 seconds

**Comment by tbenz9** [comment]
Are you still having an issue? Can you upload your log files? Try asking for help at https://discord.gg/sia
