### ISSUE TITLE
SiaFund import into wallet error

### ISSUE THREAD

**Issue by goin2mars** [NebulousLabs/Sia#2258]
The error it's giving is that the slice is too large. Please see the linked threadpost with more relevant information.

https://forum.sia.tech/topic/1682/siafund-from-2015-may

**Comment by lukechampine** [comment]
`load 033x` is for loading old `wallet.dat` files. To load a siag key, you need to use the command `siac load siag [keyfile]`.

**Comment by tbenz9** [comment]
No response from OP.  

Recommendation to Devs: Close
