### ISSUE TITLE
Sia crashes on start.

### ISSUE THREAD

**Issue by Niall2L** [NebulousLabs/Sia#2259]
It was working yesterday but still hasn't finished syncing my wallet. It's stuck at 99.1%

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.962055 seconds

**Comment by tbenz9** [comment]
Are you still having an issue?  Can you upload your log files?  Try asking for help at https://discord.gg/sia
