### ISSUE TITLE
rankings.sia.tech: all supplied contracts were invalid

### ISSUE THREAD

**Issue by Fornax96** [NebulousLabs/Sia#2265]
For the last two hours I've been getting this message from my cron job that automatically pushes my contracts to rankings.sia.tech every hour: `could not add or update user: all supplied contracts were invalid`.

Is this a server side problem? My client is still uploading to these contracts just fine. I don't know if they're downloadable, because none of the files have reached 1x redundancy yet.

Here's my full contracts.json file: https://pixeldra.in/u/GMZV1s

**Comment by lukechampine** [comment]
I'm reasonably sure it's server-side. The server ran out of disk space and its `siad` crashed. I freed up some space and restarted `siad`, and based on the logs it looks like your last job went through successfully.

**Comment by Fornax96** [comment]
Cool, thanks.

**Comment by Fornax96** [comment]
Hey @lukechampine, fyi: the command on the contract submit page is incorrect. It says `renter export contracts contracts.json`, but it should be `renter export contract-txns contracts.json`.
