### ISSUE TITLE
incomming RPCSettings

### ISSUE THREAD

**Issue by bbspike** [NebulousLabs/Sia#2276]
I have a host up for 2 weeks now but keep getting:

 incoming RPCSettings failed: failed WriteSignedObject during RPCSettings: write tcp 

with dozens of different ip adresses. Something wrong with my setup or maybe iptables.

Have it on Centos 7:

RPC Stats:
        Error Calls:        120
        Unrecognized Calls: 2351
        Download Calls:     0
        Renew Calls:        0
        Revise Calls:       0
        Settings Calls:     44784
        FormContract Calls: 112

**Comment by tbenz9** [comment]
Without any logs or more information the Devs probably can't do anything with this information.  If you're still having problems I would recommend asking for help on the Sia Discord.  https://discord.gg/sia

Recommendation to Devs: Close
