### ISSUE TITLE
siad doesn't close file properly after download

### ISSUE THREAD

**Issue by fuffenz** [NebulousLabs/Sia#2279]
Using Sia-UI 1.3 on Windows 10.

After downloading a file, it is still held open by siad after it's fully downloaded.

Can reproduce by just downloading a file with Sia-UI or curl and then use Process explorer to view open files (or just try to open the file in another process (read only is fine, but no write access)).

**Comment by tlightsky** [comment]
i can confirm this, 
i can't delete the file after download compete
