### ISSUE TITLE
Sia is crashing after a few time.

### ISSUE THREAD

**Issue by DanielKerkmann** [NebulousLabs/Sia#2283]
Heyho,

sia is crashing every time after a few minutes/hours.
If i unlock the wallet and don't unlock the wallet, sia is crashing.

Error:

Running with debugging enabled
Loading...
(0/6) Loading siad...
mkdir profiles: permission denied
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.663437053 seconds

Wallet: scanned to height 119772...
Wallet: scanned to height 119772...

AFTER LONG TIME.

Wallet: scanned to height 119772...
Wallet: scanned to height 119772...goroutine 607 [running]:
runtime/debug.Stack(0x446247, 0x0, 0xc421485688)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc421485720, 0x2, 0x2)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc421b6cf60, 0xc420d32100)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1b3
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/daniel/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x182
Severe error: api call is taking more than 60 minutes to return: /consensus
panic: Severe error: api call is taking more than 60 minutes to return: /consensus

goroutine 607 [running]:
github.com/NebulousLabs/Sia/build.Severe(0xc421485720, 0x2, 0x2)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/build/critical.go:36 +0xfc
github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1.2(0xc421b6cf60, 0xc420d32100)
	/home/daniel/go/src/github.com/NebulousLabs/Sia/api/api.go:146 +0x1b3
created by github.com/NebulousLabs/Sia/api.cleanCloseHandler.func1
	/home/daniel/go/src/github.com/NebulousLabs/Sia/api/api.go:148 +0x182

**Comment by DavidVorick** [comment]
It looks like there's a deadlock somewhere while the wallet is doing a rescan. Did you run any commands, like loading a seed?

**Comment by DanielKerkmann** [comment]
Nope, i have just started it and then it crashes after 60 Minutes.

**Comment by petabytestorage** [comment]
@tbenz9 without more info we should close this as there's not much that can be done yet imo .. new write ahead log (WAL) wallet should fix this kind of problem in 1-3 months i think.

**Comment by tbenz9** [comment]
Recommendation to devs: Close.  New WAL is likely to fix this issue.
