### ISSUE TITLE
Issue setting up GPU Mining

### ISSUE THREAD

**Issue by blancl** [NebulousLabs/Sia#2289]
I have been trying to set Sia up again to GPU mine (I have done it before on the beta version).  I have Sia UI version 1.3.0 and 1.1 of the miner (Windows 8.1, 64 bit).  I am kind of ignorant when it comes to setting up the folders properly, so I just copied and pasted the extracted Sia miner files into a "Miner" folder in "E:\Programs\Sia\Sia-UI-v1.3.0-win32-x64\resources\app\plugins" (note that E is _not_ my primary operating system drive).

When I run the UI, it loads my wallet and synchronizes the block chain fine.  I cannot find a miner tab like I did before and when I try "miner run" I get the "Could not start miner: API call not recognized: /miner/start" error.  I've tried following [this fix post](https://forum.sia.tech/topic/1141/fixing-the-http-404-miner-error/2), but when I run the "miner start" command in the Sia terminal again in step 4, I get the same "Could not start miner: API call not recognized: /miner/start" error.  Although I probably should not expect it to work, I've tried step 5 after that, and the resulting command prompt window seems stuck at "initializing..."

What can I change to make the Sia GPU miner work?  Thank you for your attention with this issue.

**Comment by lukechampine** [comment]
You need to run `siad` with the miner module enabled. In previous versions it was enabled by default, but now you must specify `siad -M cgtwm` to run the miner. Refer to `siad modules` for more info.

**Comment by blancl** [comment]
My bad, I overlooked the options in the command in the instructions; it works.  Although I had originally thought it would be a one time fix to set the UI up for mining, but it seems I will need to directly start Siad according to the instructions each time I intend to start Sia again for mining.  Is it possible to have the Sia UI remember that it has a miner plugin?  Thank you for your quick response.

**Comment by lukechampine** [comment]
It should be possible to configure that, but there's an [open issue](https://github.com/NebulousLabs/Sia-UI/issues/709) that suggests otherwise. We're looking into it.

**Comment by blancl** [comment]
Ah, OK.  Since I'm able to run the GPU miner now I will close this issue, but I'm interested to see if it is possible to make it built-in like before.  Thanks again for your help.
