### ISSUE TITLE
Documentation of FileContract: sum(ValidProofOutputs) = Payout + siafund fee

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2297]
https://godoc.org/github.com/NebulousLabs/Sia/types#FileContract 

> The sum of 'MissedProofOutputs' must equal 'Payout', and the sum of 'ValidProofOutputs' must equal 'Payout' **plus** the siafund fee.

Is it a typo? (s/+/-/)
Otherwise a contract creates new siacoins in case a storage proof has been submitted.

**Comment by tbenz9** [comment]
Recommendation to devs: tag as 'Documentation'

**Comment by lukechampine** [comment]
It is a typo, or perhaps a protocol change that was made long ago. Both the Valid and Missed outputs must sum to (payout - siafund fee).
