### ISSUE TITLE
Issue with synchronizing Sia

### ISSUE THREAD

**Issue by ChefCCC** [NebulousLabs/Sia#2299]
Hi all,

While trying to sync Sia when starting the Sia-UI program I receive the following error code:

Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: address already in use

Tips to resolve this problem are highly appreciated.

**Comment by lukechampine** [comment]
This means that another instance of siad is running (or possibly another program that listens on port 9980, but that's unlikely). You can confirm this by running the `siac` program included with the UI; it should be able to communicate with the siad running on port 9980 and display some information. If not, it may be another program.

Try killing other instances of siad, or simply rebooting.

**Comment by ChefCCC** [comment]
Hi Lukechampine,

Thank you for your reply.
At the moment I receive the following notice:
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.472175223 seconds
Could you tell me where I can find the siac program?

**Comment by tbenz9** [comment]
You can find the siac program in /resources/app/Sia/siac of the Sia download.
If you're still having issues try asking for help at https://discord.gg/sia

Recommendation to devs: close this issue.
