### ISSUE TITLE
Siad has exited unexpectedly. I transfered coins and since its not syncing will i loose them?

### ISSUE THREAD

**Issue by saitejagaddipati** [NebulousLabs/Sia#2302]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.560034 seconds

**Comment by DIOHz0r** [comment]
Here is another log...
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.9560547 seconds
panic: page 12431 already freed

goroutine 28 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc0421e0c90, 0x62c, 0x60bf000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*node).spill(0xc0420f6310, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e7
github.com/NebulousLabs/bolt.(*node).spill(0xc042056380, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*node).spill(0xc042138150, 0xc0421e0f90, 0xc042393a28)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbb
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0423105c0, 0xc042393b00, 0x15)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x182
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc0420f09b8, 0xdb89900, 0xee9fe0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8ff
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0420f09a0, 0xc042216340, 0xc042393e80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x12c
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc042069080)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc042069080)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

**Comment by tbenz9** [comment]
You will not lose your coins as long as you have your Seed.  If you're still having trouble I would recommend asking for Help on Discord (https://discord.gg/sia) or try deleting Sia and reinstalling.  After Sia has synced you can "Recover Wallet from Seed" and your coins should be there.

This error looks like it's probably related to Bolt.

Recommendation to Devs: Close due to age, and issue likely involving BoltDB.
