### ISSUE TITLE
Align Contractor's Contracts into a Budget Cycle

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#2308]
Currently contracts will more or less arbitrarily align their end heights. This is no longer necessary for compatibility with the hosts (as of v1.2.1 iirc), and it does cause a lot of confusing transactions and a steady drain on the user's wallet instead of monthly deductions.

To more effectively match user expectations, we would like to align the end heights of the contracts with a billing cycle. The field `contractor.currentPeriod` indicates when the most recent contract period started. The end height of all contracts that get formed should become `contractor.currentPeriod + contractor.allowance.Period`, which means that all contracts should always end at the same height, unless the period is decreased in the middle.

The naming is not great here. 'Period' actually means 'contract duration', the user is going to be billed more frequently than the period, because a renew cycle happens every `allowance.Period - allowance.RenewWindow` blocks. So the billing cycle actually has a length/period of `allowance.Period - allowance.RenewWindow`.

When we hit the renew block height, we want to start a new billing period at height `contractor.currentPeriod + allowance.Period - allowance.RenewWindow`. Even if the current height is already a few weeks ahead of that (due to user machine being offline), we should still keep the alignment perfect and start the billing cycle at the time that it would have originally started. There is an edge case where the billing cycle is less than half of the period, which means we could potentially skip full billing cycles. So really, the equation for the new block height is `contractor.currentPeriod + ((allowance.Period - allowance.RenewWindow)*n)`, where `n` is the number of billing cycles that have elapsed. Usually `n` will equal 1, but if the user left the computer off for a long time or has funky allowance settings, it could be 2+.

**Comment by tbenz9** [comment]
Was this fixed with #2369?

If yes, close.

**Comment by MSevey** [comment]
I believe #3087  should resolve this as it is address #3077  which seems like a similar issue.
