### ISSUE TITLE
Adjust Contract Formation and Renew Monetary Allocation

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#2309]
Some hosts are going to be used more than others. This is going to be especially prominent once the renter has an awareness of bandwidth saturation and can stop using the expensive hosts for uploading + downloading, instead favoring the cheaper hosts without sacrificing throughput (because the cheaper hosts are able to saturate fully anyway).

There's no easy way to pre-predict how much each host is going to be used, so instead of allocating money according to how expensive the host is (what we currently do), we want to start the host with a percentage of our total allowance, and then renew the host with an amount that is based on the amount spent on that host in the previous billing cycle.

The plan is to start contracts with `c.allowance.Funds / c.allowance.Hosts / 3` amount of money. This means approx. 1/3 of the allowance gets spent initially forming contracts.

If any of the contracts runs out partway through, the renewed contract should have 2x the funds of the previous contract. This means throughout a billing cycle, you increase your per-host spending exponentially as you spend heavily on one host, limiting the total number of contracts you might have to make. This also plays out well if the user dramatically increases their allowance halfway through. They may need to renew the contracts several times over, but at least it's bounded very hard by the exponential growth.

At the end of the billing cycle, all contracts get renewed with new funds. We can track how much money that contract line (the contract, plus any contract predecessors that were renewed for running out of money) spent in the last billing cycle, and so we can renew putting an equivalent amount of money in the contract. We'll add up all the money spent on that contract line in the previous period (amount spent, not amount allocated), and then we'll multiply that by 1.33 to get the new amount of money to put into the contract.

Doing the final step will require adding some state so that we can be certain how much money a contract spent across all renewals.

**Comment by eddiewang** [comment]
Just to clarify, I had two different interpretations of this PR. Are we expecting each contract to initially have the same amount of funds allocated, with the sum of all the contracts equal to 1/3 of the allowance? Or do we follow the current allocation method (based on how expensive the host is), but limit the entire set of contracts to 1/3 of the allowance.

**Comment by DavidVorick** [comment]
Code is updated now. We are starting all hosts with the same amount of money, assuming more or less homogeneous prices among your hosts (as you are picking the top 50 out of 700), and also assuming (though it's not implemented yet) that cheaper hosts are going to be prioritized.
