### ISSUE TITLE
siac wallet balance not equal to sum(transactions' net siacoins)

### ISSUE THREAD

**Issue by wincss** [NebulousLabs/Sia#2314]
$ siac version
Sia Client v1.2.2
Sia Daemon v1.2.2

$ siac
Synced: Yes
Block: 000000000000000e446a671851bcdde18eaf8fefc64c35e39233b0a48eed95b5
Height: 123070
Target: [0 0 0 0 0 0 0 72 146 22 90 143 235 70 227 89 151 224 152 100 177 96 244 36 227 213 63 115 24 240 24 120]
Difficulty: 254190132799417438

$ siac wallet balance
Wallet status:
Encrypted, Unlocked
Confirmed Balance: 73.11 KS
Unconfirmed Delta: +0 H
Exact: 73114261535831251257159865839 H
Siafunds: 0 SF
Siafund Claims: 0 H

$ siac wallet transactions
[height] [transaction id] [net siacoins] [net siafunds]
... many trx here ...

"net siafunds" is all zero
run a simple awk script to sum "net siacoins"

$ siac wallet transactions|awk 'BEGIN{A=0} {A+=$3} END{print A}'
248154

248154 SC is not equal to 73.11KS

is it a bug or I misunderstand something?

**Comment by nielscastien** [comment]
If you are a host it could be the locked collateral returned to the wallet after a contract expires. This is not visible in the trx list of the wallet.

**Comment by creativelytek** [comment]
Sorry, I'm here




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wincss** [comment]
@nielscastien i'm not a host, and there is no contract.

**Comment by avahowell** [comment]
@wincss Did you set an allowance, and are you uploading/downloading files?

**Comment by wincss** [comment]
sorry, it's my fault.

the award of mined block will be include in 'siac wallet balance' after 144 blocks.
