### ISSUE TITLE
Unknown confirmations height

### ISSUE THREAD

**Issue by khelle** [NebulousLabs/Sia#2336]
Hi, I am developing app which is using Siad node. Everything was working as expected for about month, but today the application started failing when calling to `/wallet/transactions` with error `error when calling /wallet/transactions: requesting transactions at unknown confirmation heights`.

The call being sent to node is: `/wallet/transactions?startheight=123783&endheight=123791`
Wallet is unlocked
Consesus shows me that node current height is 123791.

I tried restarting the siad node, but it does not help.

What is the reason of this and how can it be fixed?

**Comment by tbenz9** [comment]
@khelle you might try asking for help on the Discord channel https://discord.gg/sia.  The community tends to be much more active there than on GitHub issues.  Please comment back on this issue if you find a solution to your problem.

recommendation to devs: tag as 'bug'

**Comment by tbenz9** [comment]
I'm going to go ahead and close this.  It hasn't had any action in 6 months and I believe the issue can be resolved by deleting the transactionpool.db file.  Steps to do that can be found here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
