### ISSUE TITLE
4GB memory leak

### ISSUE THREAD

**Issue by mythrill** [NebulousLabs/Sia#2339]
On Windows - loading the wallet consumes 4GB of ram - which is not returned on exit - during synchronization it peaked at 10GB - the 4GB is not assigned to Sia-UI in Task Manager, but testing shows it is using/allocating it and not releasing - maybe a caching issue - either way I can't run the wallet yet.

**Comment by avahowell** [comment]
What version of Sia-UI and `siad` are you using?

**Comment by avahowell** [comment]
https://github.com/NebulousLabs/Sia/pull/2322 should help with this

**Comment by mythrill** [comment]
trying again and again with the same version helped - it no longer does this - I now think it was because of downloading and replacing the consensus.db - catching up caused this, but the problem goes away.
