### ISSUE TITLE
Enhancement: Siacoin Wallet Sync Times

### ISSUE THREAD

**Issue by ayumihamsaki** [NebulousLabs/Sia#2340]
Hello,

I have been testing out Siacoin system for a few days.

Simply put it took me 3 days to sync a siacoin wallet so I could use it to confirm a transaction. Let's put this issue into perspective:

```
Amazon Cloud = Takes less than 1 hour to setup.
Google Cloud = Again takes less than 1 hour to setup.

Siacoin = Takes 3 days to setup (depending on type of hard drive).
```

In the modern world we live in, it's all about speed. Bitcoin is very slow for example taking 1 hour for some transactions and other cyrpto's like Ripple for example take 3-5 seconds. The world is moving across to Mobile and this is why Google is changing it's whole search engine from Desktop over to Mobile with what they call "Mobile First Indexing". Let's try to imagine trying to setup a Siacoin on a Mobile Smart Phone would it take 3 weeks to setup the wallet syncing?!

Solution and some common sense:

```
There are two types of users:

1. People that want to use Siacoin and don't care about hard drive hosting. These people should be able to open a Siacoin wallet and use it in a few seconds and NOT have to worry about syncing at all.

2. People that want to use Siacoin and host or use the hosting features. These people should be the ones that wait for the syncing.
```

You really need to update your wallet to work like this! With Mobile payments in the coming years being the biggest form of payments over Desktop payments, Siacoin needs to address these issues and change it's UI-Siacoin Wallet.

Lastly, sorry if this topic has been covered before, but I have only been testing out your system for around 7-10 days now. I feel it's a good project but the syncing is crazy and pure madness enough to make this project totally fail if not addresses asap.

Who is going to say let's use Siacoin over Amazon cloud to host their website files and have to wait 3 days to set it up. Right now the block chain says around 123,000 blocks so it's still very small, for example burst coins are around 300,000. Does this mean next year people are going to wait 6-7 days to sync their wallet?

I look forward to the replies and hope this issue is going to get addressed properly.

**Comment by lukechampine** [comment]
We never expected the average user to sync the full blockchain -- you are absolutely correct that it is impractical for them to do so, at least with today's blockchain tech.

Sia is a backend, not a user-facing app. Our current user interface exists only to bootstrap the network. Long-term, the average user of Sia will not even know they are using Sia. They'll use a service like Dropbox, and Dropbox will transparently store their data on Sia. In this scenario, only a few thousand large entities (and a few crypto enthusiasts) need to deal with the blockchain directly. That's better anyway, since blockchains run into significant scaling issues past that point.

Hope this clears things up a little. And thanks for being an early adopter :)

**Comment by ayumihamsaki** [comment]
@lukechampine Thanks for your reply, I see this project having a 'possible' big future, when I read that you guys want to add Video Streaming features later on. I can almost compare Sia to Megaupload doing the same thing. But my downside to the project is just thinking when a user opens a bitcoin wallet it takes them less than an hour, whereas Siacoin takes 72 hours (3 days). So it's really NOT energy saving as your video promo advert let's you believe coz users have to use 71 hours more computing power just to open a wallet.

I think this project is good, however because it's 'pegged' to a currency called Siacoin, steps must be made to make Siacoin strong in order for the project hosting to succeed. If Siacoin value was to drop to 0.0000001 BTC would you really want to continue building it?

So I hope the developers will try to fix this issue as it's a big one I feel and this is the only thing from stopping Sia becoming as big or bigger than Google and Amazon for cloud hosting. Long term goals should be to beat them and then you guys will have Google, Facebook or Amazon knocking at your door wanting to buy your project and paying you millions of dollars from their Venture Capital departments.

I would like to know where I can keep in the loop with this project and hope the developers try to fix this issue with the syncing. As for the wallet design, actually the design is quite good, it's the syncing which is the only problem and has the power to kill off this project and other projects like Burst coin, File coin etc.

**Comment by lukechampine** [comment]
>I think this project is good, however because it's 'pegged' to a currency called Siacoin, steps must be made to make Siacoin strong in order for the project hosting to succeed. If Siacoin value was to drop to 0.0000001 BTC would you really want to continue building it?

If the value drops, then it will become very cheap to store data on the Sia network. The increase in demand then allows hosts to raise their prices. In the long term, the supply/demand relationship between renters and hosts causes the value of the Siacoin to stabilize around the value of storage on the network.

The best way to stay in the loop is to [join our Discord server](https://discord.gg/sFCT3Ar). We also have a [newsletter](https://sia.tech/) (bottom of the page) if you just want infrequent updates.
