### ISSUE TITLE
Lost contractmanager.json file contents during crash, no native backups available.

### ISSUE THREAD

**Issue by 4Dolio** [NebulousLabs/Sia#2343]
A crash of my windows host running siad resulted in the total lost of the contents of my crontractmanager.json file and thus all information regarding the data my host was storing for contracts.  It retained the knowledge of the existence of the contracts, but expect it to fail to be able to deliver old data to renters.

**Comment by 4Dolio** [comment]
Both my solarcoin and Sia-UI had crashed, only noticed around 20170912~0900
* The AppData\Roaming\Sia-UI\sia\host\contractmanager.json and _temp files were 1KB and contained only the header line.
* Windows rollback checkpoint from 20170912~04?? was also empty
* No other backups are available, My Bad.
* Closes backup are: A:\Trash\Sia-UI-OldBackups Dated 20170906
* Unable to start Sia due to invalid contractmanager.json file which contains only the opening header line.
* Deleted all contractmanager.json{,_temp} files and started over, and started up new Sia-UI, created empty contractmanager data.
* Created snapshot of old SiaStore\HostStore as SiaStore\HostStore-Lost
* Created 24 new storages at same paths as last S:\HostStore\SiaData??? of size 256GB
* Uncertain if this overwrote or re-used the existing sparse siahostdata.dat and siahostmetadata.dat files.
* Sia-UI Still shows that we have 45 active contracts and 70.3SC expected, many of the other stats also seem to be unchanged.
* A short time later SiaData003 shows 4.16MB Used...
* Locked Collateral: 3.315 KS
* Risked Collateral: 627.7 mS
* Lost Collateral: 0 H so far...
* At last check SiaData000 Was not used.. could perhaps migrate all new data there and then try restoring the old HostStore(s) to see if it can find the data within?
* @other_host:/etc/fstab added cifs mount of the windows host
* Tue Sep 12 22:40:53 root@other_host:~# mkdir /host_mount ; mount /host_mount
S=/host_mount/Users/UserName/AppData/Roaming/Sia-UI ; T=/SiaStore/host_Sia-UI/ ; Exclude="--exclude=consensus.db --exclude=transactionpool.db"
* d=`date +%Y%m%d.%H%M` ; rsync -aP --stats --delete-after -b --backup-dir=$T/$d.SyncBack $S $T/Sia-UI $Exclude
** # -c use checksum not mod and size.
* d=`date +%Y%m%d.%H%M` ; find $S -name \*log -exec echo mv -v "{}" "{}.$d" \; # Consider not echoing in order to rotate .log files # not using this yet.

**Comment by 4Dolio** [comment]
I have now heard of a second user experiencing corruption of their contractmanager.json
* Also head mention of two other older issues which may be related.

I recommend at minimum solution to enable recovery from this problem:
* Begin keeping daily/hourly contractmanager.json.YYYYMMDD.HHMM backup files natively.
** Perhaps also a sane cleanup older than 30 days
** Perhaps also do the same for other contract data and renter data files..

**Comment by tbenz9** [comment]
I don't think it's unreasonable to request that Sia keep some kind of backup file, but I also think this would be better implemented in a 3rd party tool.  If you would like a hourly backup of your Sia config files then there are a number of solutions that will do that for you (backblaze, crashplan, carbonite, etc).

If you have log files that would be useful.  But as I understand it right now I don't think the Dev team has anything actionable on this issue.  I would recommend using a backup utility to protect your individual configs, and read up on how to Migrate a Sia Host in the event you have another corruption issue.

Recommendation to devs: close

**Comment by 4Dolio** [comment]
Yup, have my own hourly now. But even a simple .last(clean_start) copy would have been priceless.

**Comment by tbenz9** [comment]
I would recommend creating a new issue (that links to this one) that clearly requests that feature.  There is no need to include all the history of what happened and what you did to try to solve it.  Simply saying something like "Sia should create a backup of critical files on startup/shutdown/whenever" and a list of the files you think are necessary should be sufficient for the Devs to understand and decide if they will do anything about it.

**Comment by lukechampine** [comment]
regular backups shouldn't be necessary; our intention is to make updates atomic, such that at least one of `contractmanager.json` and `contractmanager.json_temp` are valid at any given time.

**Comment by tbenz9** [comment]
My understanding is this will be fixed with the new writeaheadlog.  If this is true I recommend we close this issue.

**Comment by tbenz9** [comment]
With 1.3.1 the contract management has been overhauled.  I believe the fundamental issues you ran into are solved with the 1.3.1 release.  If you continue to have issues please reopen this issue.
