### ISSUE TITLE
Feature request - Hosting UI to include IPaddress:port field

### ISSUE THREAD

**Issue by songproducer** [NebulousLabs/Sia#2355]
Would make it much easier for those who have dynamic IPs.

**Comment by tbenz9** [comment]
Recommendation to devs: tag as "feature request".

**Comment by lukechampine** [comment]
IIUC this is a UI feature request, so it should be closed and re-filed on the Sia-UI issue tracker

@tbenz9 one of the problems we run into a lot is that people file UI bugs on the Sia repo, and Sia bugs on the UI repo. We can probably do a better job of guiding users to the correct tracker for their issue.
