### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by valerij101** [NebulousLabs/Sia#2356]
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
st...
panic: bolt.DB.meta(): invalid meta pages

goroutine 11 [running]:
github.com/NebulousLabs/bolt.(*DB).meta(0xc042396000, 0x5cc)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xed
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc042322540)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc042322540, 0xc042019520, 0xc04238fe80)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:164 +0x8a0
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc042382b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x4e
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc042382b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0x17e
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3f6

**Comment by tbenz9** [comment]
This usually happens when you have another process listening on port 9980.  Check to make sure you don't already have a siad process running or that no other processes are using port 9980.  You can also try changing the port that siad uses via the commandline.
