### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2359]
History of [appveyor](https://ci.appveyor.com/project/lukechampine/sia/history) and [travis](https://travis-ci.org/NebulousLabs/Sia/builds) demonstrates that the tests fail from time to time. Some tests fail locally as well. This impedes further development because if something fails, it is not clear if it happened because of the changes or because the test is broken (or flaky).

Can we identify all such tests and then either fix or remove/silent them, please?

Examples:
https://travis-ci.org/NebulousLabs/Sia/builds/277995657#L700
https://ci.appveyor.com/project/lukechampine/sia/build/221#L282

Some errors are not considered failures but look not healthy:
https://travis-ci.org/NebulousLabs/Sia/builds/279245604#L1984
https://ci.appveyor.com/project/lukechampine/sia/build/221#L140

**Comment by tbenz9** [comment]
Recommendation to devs: tag as "bug".

**Comment by lukechampine** [comment]
We've recently taken steps to reduce these failures (which we call NDFs -- nondeterministic failures). Specifically, we have a CI bot that runs the test suite once a day and emails a handful of devs if any NDFs are spotted. Contact one of the devs on our discord if you want to be added to the list of people who receive these daily emails.

I'm going to close this and recommend that we instead file issues for each NDF individually, and tag them as such.
