### ISSUE TITLE
Siad has exited unexpectedly    Loading... (0/6) Loading siad... listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by kelemenf** [NebulousLabs/Sia#2370]
Loading...
(0/6) Loading siad...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by lukechampine** [comment]
This means you're running another program on that port -- most likely another instance of `siad`. Kill those other instances and try again.

**Comment by tbenz9** [comment]
Recommendation to devs: Close
