### ISSUE TITLE
Siad has exited unexpectedly. Won't pass 96.6% synchronized for first time

### ISSUE THREAD

**Issue by tstansbury1013** [NebulousLabs/Sia#2379]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.8949106000000002 seconds

**Comment by tbenz9** [comment]
The output you included is not enough to help debug the problem.  Do you have a stack trace?  If you're still having problems you might consider asking for help in the #help Discord channel.

**Comment by tstansbury1013** [comment]
Unfortunately, I'm not to much of a computer expert.  How do I find a stack trace?  Bottom line, it seems stuck at 96.6% synchronizing on my initial time trying to download the AIA UI.  I am concerned that I did try to transfer coin into this wallet and, if I recall correctly, if the sia UI doesn't load correctly, I could lose that coin.  (it has already been sent).  Any recommendations on how to proceed?

**Comment by lukechampine** [comment]
As long as you saved your seed phrase, you can always recover any coins that were sent to you.

I recommend the following:
1. Make sure Sia-UI is fully shutdown
2. Start `siad` on the command line
3. Wait for `siad` to finish synchronizing
4. Reopen Sia-UI

For step 2, open Command Prompt if you're on Windows or Terminal if you're on Mac, then navigate to the place where you unzipped Sia-UI. Then open the folder `resources\app\Sia` (or `Contents/Resources/app/Sia` on Mac). Inside, you should see two binaries, `siad` and `siac`.
Now you want to run `siad` and tell it to use the blockchain you previously downloaded. Enter the following command:
```bash
# Windows
siad.exe -d %APPDATA%\Sia-UI\sia

# Mac
siad -d $HOME/Library/Application Support/Sia-UI/sia
```
You should see the `Loading...` statements like before. Once it finishes loading, it will begin syncing. If it crashes or prints out an error, post it here.

For step 3, you can monitor the syncing progress by using `siac`. Open another Command Prompt/Terminal in the same location, but this time run `siac.exe` (or `./siac` on Mac). Each time you run it, it will print the highest block that `siad` has synchronized to. It will also print a percentage.

Once the percentage reaches 100%, launch Sia-UI as usual. It will connect to `siad` and should report that it is 100% synced. If Sia-UI crashes again, we'll have to do more work to investigate why, but you'll still be able to use your wallet via the `siac` command.

**Comment by tbenz9** [comment]
@tstansbury1013 If you're still having trouble I would recommend asking for help on the Sia Discord:  https://discord.gg/sia

Recommendation to Devs: Close issue due to lack of actionable data
