### ISSUE TITLE
Hosts can upload to themselves

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#239]
This probably shouldn't happen. A simple IP comparison would prevent it, it's just a question of where and how.

**Comment by DavidVorick** [comment]
I'm going to add to this problem: multiple pieces of the same file can end up on the same host, and it's actually likely given that we're planning on keeping the active pool from which we draw hosts relatively small. We need some way to avoid this.

Additionally, I might argue that it's not a bad thing to upload at least 1 piece to yourself. The idea is to put the file in the cloud, and if you are a host then you are part of the cloud.  Supposedly you are doing more than just backing up your data and are planning on recovering it from anywhere.

**Comment by lukechampine** [comment]
That logic seems mostly sound to me. I think it's worth adding a config setting though.
