### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by hero1012** [NebulousLabs/Sia#2390]
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 4.8779402 seconds

**Comment by hero1012** [comment]
synchronizing 45.1%

**Comment by hero1012** [comment]
siad not found. sia-ui couldn't locate siad.please navigate to siad

**Comment by tbenz9** [comment]
Please attach the Sia logs.  Otherwise this is insufficient information to troubleshoot your issue.

Recommendation to devs: Close issue (reopen if logs are attached)

**Comment by lukechampine** [comment]
Not being able to locate siad is an uncommon error. Try reinstalling Sia-UI.
