### ISSUE TITLE
[rpc] Will Sia support "getblocktemplate"?

### ISSUE THREAD

**Issue by bitkevin** [NebulousLabs/Sia#2400]
The Nonce in block header is only 8 bytes, it's far from enough in the near future. Some mining pools already support stratum mining protocol like bitcoin, if using stratum protocol to mining Sia, the rpc should support GetBlockTemplate.

https://en.bitcoin.it/wiki/Stratum_mining_protocol
https://en.bitcoin.it/wiki/Getblocktemplate

**Comment by tbenz9** [comment]
Recommendation to devs: tag "feature request" and "Programming Task"

**Comment by DavidVorick** [comment]
I'm not sure what the feature request is here. Getblocktemplate is something that would need to be implemented by the mining pool, not by the sia daemon.

8 bytes is more than enough nonce space, you need 2^64 operations to grind through it, and world class theoretical ASICs would still take days to grind through the full nonce space.

Closing, feel free to re-open if you can clarify the feature being requested.
