### ISSUE TITLE
omnibus "too many open files" all-inclusive ticket

### ISSUE THREAD

**Issue by petabytestorage** [NebulousLabs/Sia#2406]
The following tickets are all related to "too many open files"
and can all be solved with smarter open fd management.

fd's can be leaked by open files or network sockets

https://github.com/NebulousLabs/Sia/issues/2202
https://github.com/NebulousLabs/Sia/issues/2236
https://github.com/NebulousLabs/Sia/issues/2243
https://github.com/NebulousLabs/Sia/issues/2272
https://github.com/NebulousLabs/Sia/issues/2288
https://github.com/NebulousLabs/Sia/issues/2307
https://github.com/NebulousLabs/Sia/issues/2326
https://github.com/NebulousLabs/Sia/issues/2363

@tbenz9 suggest the above linked open issues should be closed.

**Comment by tbenz9** [comment]
Excellent, thanks for making this.

Devs: Can we label this 'bug'

**Comment by Wlinc** [comment]
Still happening. Running Sia 1.3 on macOS Sierra (unable to get version information). When this error happens, I have to reboot my system to regain basic functionality. And each time this happens, I'm not running an excess number of applications. Typically my Ram and CPU usage, even with wallets running, is around 70% Ram and 50% CPU


Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 19.198039287 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc421eef5c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc421eef930, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
main.startDaemon(0x0, 0x0, 0x7fff5fbffca7, 0xe, 0x7fff5fbffcd3, 0x5, 0x7fff5fbffcc2, 0x5, 0x0, 0x7fff5fbffd2e, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:311 +0xaa9
main.startDaemonCmd(0xc420093200, 0xc4200952c0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420093200, 0xc42006c070, 0x5, 0x5, 0xc420093200, 0xc42006c070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420093200, 0x16fce88, 0x3b, 0xc420166aa0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420093200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing renter...

**Comment by edendekker** [comment]
I have the same issue as @Wlinc 
Same os, sia version, & error

**Comment by mckelvin** [comment]
@Wlinc @edendekker Would you please confirm if you're running Sia-UI when the issue occurs?

**Comment by DavidVorick** [comment]
Indeed. Biggest question for us is whether the culprit is Sia-UI or siad. Historically, the problems have been Sia-UI not properly managing file descriptors as it opens connections to the API. But it's possible that siad is causing problems as well.

**Comment by mckelvin** [comment]
Hey @DavidVorick do you have any idea on https://github.com/NebulousLabs/Sia-UI/issues/752 , which is a place where fd leak happens for sure.

**Comment by petabytestorage** [comment]
If that's the question it seems setting a lower limit than the system hard limit using ```ulimit -n``` may solve the problem.  You can for example limit each of `siad` and `Sia-UI` to half the file descriptors each and then you will (more likely) know which one is broken because it will not (immediately due to fd exhaustion) crash the other. @DavidVorick  @mckelvin

**Comment by Wlinc** [comment]
@mckelvin I am running Sia UI.

**Comment by tbenz9** [comment]
I haven't seen this pop up in nearly 3 months.  I'm going to close it due to inactivity.  We can re-open it if the error comes back.

**Comment by taiwil** [comment]
This Problem KEEPS occuring.  You are closing a subject without resolving the probelm.  
My Sia closes down once or twice a DAY ..>EVERYDAY!!!
This is wrecking my Uptime and my rating....Im losing Contracts.  
If no Developer can resolve this problem, then Sia is DONE.

**Comment by tbenz9** [comment]
@taiwil I'm sorry you're having issues.  Can you provide more information about Sia is doing that is causing it to crash?  We believe this is an issue with the User Interface (UI), have you tried running Sia without the UI?

Lastly, the reason this issue is closed is that it's being tracked in https://github.com/NebulousLabs/Sia-UI/issues/752

**Comment by taiwil** [comment]
@tbenz9 

I am running IOS 10.11.6 
I had followed created a file via the instructions here(which i think you may have linked me):
https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

I don't know if that file is effected when I repair my Disk permisssions.  
In the terminal, I am increasing the Max number of open files.   

 I am still getting THIS Error:
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 20.749124299 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1045ec7, 0x0, 0xc420041948)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc420041ac8, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7fff5fbffd53, 0xe, 0x7fff5fbffd7f, 0x5, 0x7fff5fbffd6e, 0x5, 0x0, 0x7fff5fbffdd3, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x588
main.startDaemonCmd(0xc4200acfc0, 0xc42007e550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200acfc0, 0xc42000e0d0, 0x5, 0x5, 0xc4200acfc0, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200acfc0, 0x16e1b17, 0x3b, 0xc420099a40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200acfc0, 0x1b0a200, 0x16ca346)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.

I hope you know a solution. 
Thank you for your reply,
Wil

**Comment by taiwil** [comment]
@tbenz9 
I don't know how to run Sia Without IU.   I host many files and contracts.

**Comment by teja42** [comment]
This issue is closed but I just got this error on Sia v1.3.3 on Linux. I think I found the culprit. I ran `ulimit` and got back `unlimited`. If someone is having this trouble then try setting `ulimit` to some reasonable value.
