### ISSUE TITLE
omnibus disk full / out of disk space

### ISSUE THREAD

**Issue by petabytestorage** [NebulousLabs/Sia#2407]
The following issues seem possibly, likely, or certainly related to
out-of-disk-space issues:

https://github.com/NebulousLabs/Sia/issues/2189
https://github.com/NebulousLabs/Sia/issues/2237
https://github.com/NebulousLabs/Sia/issues/2238
https://github.com/NebulousLabs/Sia/issues/2240
https://github.com/NebulousLabs/Sia/issues/2250
https://github.com/NebulousLabs/Sia/issues/2337
https://github.com/NebulousLabs/Sia/issues/2366

A two part solution is proposed below:

1. auto restartability
2. free disk space check on startup using portable file write-close-read.

One common and time-tested solution for this kind of failure mode is
from the Erlang OTP community called Supervisor Trees. These seem to
be available in Golang in the `suture` package:

http://www.jerf.org/iri/post/2930

`Supervisor trees` are one way to provide auto-restart for crashes in the long running
`Actor model`.

If we add restartability using supervisor trees as above or another Golang package such as https://github.com/ochinchina/supervisord

and we add a brief check during startup of `siad` to ensure that it
can create a one-megabyte file, close it and then read it back before
deleting it

this would let us detect all uncaptured `disk full` errors during startup
quickly and thereby provide missing error messages. One simple approach
is to allow for only 1 restart attempt. This can add fault tolerance, visibility, and robustness.

@tbenz9

**Comment by lukechampine** [comment]
Supervisor trees are cool but I don't think we should graft them onto a mature project. I would consider them if starting over from scratch. Even then, if I were starting over from scratch and really wanted supervisor trees, I'd probably write it in Erlang. Reminds me of my own [stm](https://github.com/lukechampine/stm) repo, which, while cool, is clearly at odds with Go's concurrency model.

My inclination is to handle these errors on a case-by-case basis. We've already done so for bolt; we just need to extend that to other files. I imagine that in most or all cases, we should crash the program (while shutting down cleanly) and display the out-of-space error in the clearest possible terms.

**Comment by petabytestorage** [comment]
I use this supervisor a lot. If you added it to sia and added the check I
suggested on startup, it would catch everything that you haven't gotten yet
and still wouldn't prevent you from going around to each cause specifically
and handling it a specific way as well. Think of it as a catch all.
```
#!/bin/bash
while true ; do
  siad
  sleep 1
done
```
(a production one will be better but this is just for illustration of how simple can still be useful)

In real fault tolerant distributed systems I find there are usually mutliple
failure modes and multiple recovery modes. So it is not odd to me to have
both at once. But if you know there are only a few places left to cover then
that sounds good to fix. But then the maintainability is at question as well
if you leave out the catch all.  Since future deps or sia core code changes
can introduce new ways to write to disk there may be a burden without the
extra coverage.

I think the only reason I have known not to do some sort of simple top level
restart for any server that is supposed to be long running but isn't is if it
is harmful or destructive to restart. One example might be if log files are
truncated.  But as far as I know I haven't seen Sia to be harmful to try
restarting a few times after it crashed.

I love Erlang and Elixir. I don't think you need all of Erlang to benefit from
restartable actors or fail fast (with restart at least once) because you can
concentrate expensive checks just once up front on boot and thereby detect
unexpected failures. Might be disk full or network connectivity loss.
It's the simplest way to provide the information we developers and users need
automatically to close these issues in a timely manner.

**Comment by tbenz9** [comment]
@petabytestorage Thanks for creating this!

Recommendation to devs: tag "Bug"

**Comment by tbenz9** [comment]
@petabytestorage I'm thinking it's time we close this issue.
1: The new writeaheadlog in 1.3.1 will resolve most of the issues linked
2: It sounds like the devs aren't very interested in implementing Supervisor trees

Let me know if you think otherwise and we can re-open this issue.
