### ISSUE TITLE
error - not enough storage remaining to accept sector?

### ISSUE THREAD

**Issue by uclnj** [NebulousLabs/Sia#2427]
I started a [Sia Host](https://siahub.info/host/6938) and have been fine tuning some of the hosting variables and noticed these in the host.log.  This is hosted on an Ubuntu VM (at office) with 8TB of NFS mapped storage.

2017/10/14 07:03:31.363233 errors.go:151: internal error: error with [ip]:53207: incoming RPCReviseContract failed: revision iteration failed: could not modify storage obligation: not enough storage remaining to accept sector
2017/10/14 08:39:02.580352 errors.go:151: internal error: error with [ip]:56710: incoming RPCReviseContract failed: revision iteration failed: could not modify storage obligation: not enough storage remaining to accept sector

The NFS store has the two files
```
-rw-r--r-- 1 root root 7999913459712 Oct  4 16:56 siahostdata.dat
-rw-r--r-- 1 root root      26702592 Oct  4 16:56 siahostmetadata.dat
```

and su'ed as siad I can make/delete test folders/files so it doesn't look like a permission issue.

**Comment by DavidVorick** [comment]
Permission issue would give you a different error. Are you sure that the host is aware of those folders? What happens if you run `siac host -v`?

**Comment by tbenz9** [comment]
Recommendation to Devs: Close as no response has been made.

Feel free to reopen this issue if you want to continue the troubleshooting.
