### ISSUE TITLE
Provide local path of renter files in API

### ISSUE THREAD

**Issue by KaiRo-at** [NebulousLabs/Sia#2428]
In our usage of Sia in the Minebox backup procedure, we'd like to find out the local path for files uploaded with the Sia renter, esp. to make sure we don't delete local copies of files that aren't fully uploaded yet.
Unfortunately, while renter.json has those references to local files ("RepairPath"), the siad API does not expose them. It would be great if that field would be added to the info we can get for renter files via the API.

**Comment by tbenz9** [comment]
Recommendation to devs: "Feature Request" "Programming Task"

**Comment by tbenz9** [comment]
This can be closed.
