### ISSUE TITLE
Updating requires restart

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#244]
Some updates won't require a restart (such as interface tweaks), but most probably will. In cases where both the backend and frontend are updated, it would be dangerous to allow siad to continue running. This is because the (un-updated) binary continues to run in memory, while the (updated) resources have changed.

For now, we should just automatically stop siad after each update, and ask the user to restart it. siac can do a little better because it can automatically restart siad, but I don't think siad can restart itself.

**Comment by seveibar** [comment]
Couldn't you have another daemon that strictly takes care of running/restarting siad? You could call it siadd!

**Comment by lukechampine** [comment]
![no](http://www.myttonwilliams.co.uk/media/files/179/News_No.jpg)

**Comment by DavidVorick** [comment]
You could implement a system-wide lock or something? The issue is with the data? Or is the issue with the program running?

If stuff just froze/deadlocked during the update, would that be good enough?

**Comment by lukechampine** [comment]
The issue is that you have an old binary trying to interact with new resources. It could break things in a bad way.
Best scenario would be if we could restart siad from siad. Then you could just click "restart" in the web interface and things would freeze for 0.2 seconds until the API came back online.

**Comment by DavidVorick** [comment]
what's the block with doing that?

**Comment by lukechampine** [comment]
here's a library for self-restarting go programs: https://github.com/rcrowley/goagain/
