### ISSUE TITLE
 how to build merkle_branch

### ISSUE THREAD

**Issue by sunysen** [NebulousLabs/Sia#2441]
now I need to do a siacoin mine pool,need to use (`/transactionpool/transactions`) api build merkle_branch，the latest version of the api did not provide, view the historical version(0.6.0) is yes, then the latest version of what should I do

**Comment by tbenz9** [comment]
Sorry, I am not sure what you are asking.  Maybe you can see if there is a Sia Discord channel in your native language and if they can answer your questions.

Recommendation to devs: try to interpret; else "close"
