### ISSUE TITLE
Siacoin wallet syncing from last two days and my Siacoins are not visible

### ISSUE THREAD

**Issue by paragasraj** [NebulousLabs/Sia#2448]
Hi Team,

I have installed Siacoin UI wallet and from last two days it is syncing. Till now it has completed only 49.3%. I have core i5 with 8 GB RAM with 100 Mbps speed.

Also, After installing wallet, I have transferred my Siacoin from Bittrex but till now it is not visible. I am hoping once wallet sync completed 100% it will show up.

Regards,
Parag

**Comment by lukechampine** [comment]
You will not see the transferred coins until your wallet finishes syncing.

More precisely: when you sent the coins, they were included in a block, which was added to the blockchain. You haven't downloaded the full blockchain yet, so you don't have the block with your transaction in it. Once you download that block, your wallet will see the transaction and update its balance accordingly.
