### ISSUE TITLE
Started with 1.3.0, ran 1.3.1, back to 1.3.0 for renter contract renewal. Go fault.

### ISSUE THREAD

**Issue by 4Dolio** [NebulousLabs/Sia#2452]
On my renter laptop..
Started with 1.3.0, ran 1.3.1, back to 1.3.0 for renter contract renewal. Go fault.

Due to the 1.3.1RC contract renal bugs? and my contracts eventually needing renewals...

I went back to running the original 1.3.0, hope that is safe to have done...

On startup siad crashed twice, perhaps due to malwarebytes interceptions, which I attempted to exclude.
I disabled the malwarebytes active checks entirely, not sure if this had anything to do with these first two crashes.  I did not record the error output from these two events.  The third run appears to have kept running enough to finish syncing.  I am not entirely sure how to determine if/when my contracts actually expire and/or if they have been renewed.

After a sleep or hibernation event siad crashed again with the following output:
.oO( Oh snap, it appears that I am running 1.3.0 of Sia-UI but still 1.3.1 of siad, anyway )

```
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.9163637 seconds
panic: division by zero

goroutine 65138 [running]:
math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0430ed080, 0x2, 0x6, 0x0, ...)
	/usr/local/go/src/math/big/nat.go:516 +0x457
math/big.(*Int).QuoRem(0xc0455d5eb0, 0xc0455d5e70, 0xc0455d5e90, 0xc0455d5e10, 0xc0455d5e60, 0x6e334e)
	/usr/local/go/src/math/big/int.go:227 +0xc6
math/big.(*Int).Div(0xc0455d5eb0, 0xc0455d5e70, 0xc0455d5e90, 0x1)
	/usr/local/go/src/math/big/int.go:238 +0x7b
github.com/NebulousLabs/Sia/types.Currency.Div(0xc0420aa000, 0xc0430ed080, 0x2, 0x6, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:85 +0x6c
github.com/NebulousLabs/Sia/modules/renter/proto.Renew(0x0, 0x0, 0x0, 0x0, 0x0, 0x20552, 0x205e2, 0x0, 0xc042989a70, 0x2, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/proto/renew.go:40 +0x540
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).managedRenew(0xc042051860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20552, 0x205e2, 0x0, 0xc042989a70, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contracts.go:280 +0x6b7
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).threadedContractMaintenance.func2(0xc042051860, 0xf0ec8a81a3e2fa30, 0xb78cbf6335b10705, 0x57b7a7c9d97310a0, 0xd5bb087aabc7fde8, 0x0, 0xc0435d1c80, 0x2, 0x7, 0xc0556d5e08, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contracts.go:546 +0x3b1
github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).threadedContractMaintenance(0xc042051860)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/contracts.go:591 +0x417
created by github.com/NebulousLabs/Sia/modules/renter/contractor.(*Contractor).ProcessConsensusChange
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/contractor/update.go:66 +0x870
```

Will attempt to revert back to 1.3.0 siad for real next time (if I do not hear back that doing so is not safe) and append any new issues and/or the results of the contract renewals.  Any help with accurately determining the state of my renter contracts, expiration and renewals, would be appreciated. Anxiously awaiting 1.3.2RC! cheers

**Comment by 4Dolio** [comment]
Used a bat/cmd to launch 1.3.0 siad without the host module (wish I could set this when Sia-UI spawns siad).  Confirmed running both at 1.3.0 now, seems fine so far.  I think I found I can use renter contract view UUID to see details, will try and keep track of how renewals go...
`call siad.exe -d C:\Users\username\AppData\Roaming\Sia-UI\sia -Mgctwr`

**Comment by DavidVorick** [comment]
We may have some upgrade code from v130 to v131 that means you can't go back to running v130 once you upgrade.

**Comment by lukechampine** [comment]
I believe this was fixed in https://github.com/NebulousLabs/Sia/pull/2320.
btw, you can configure Sia-UI to not launch the host module by modifying this line: https://github.com/NebulousLabs/Sia-UI/blob/93100af935d6ace93642f096e84c12bf8071edaa/js/rendererjs/loadingScreen.js#L128
I thought we had config support for that, but apparently not.
