### ISSUE TITLE
Reopening the question asked in request #2448

### ISSUE THREAD

**Issue by paragasraj** [NebulousLabs/Sia#2457]
Siacoin wallet syncing from last two days and my Siacoins are not visible.

Hi, My siacoin-ui wallet is synchronized completely, but still I am not able to see my transferred siacoin from bittrex. Bittrex showing transaction complete but Siacoin wallet has 0 confirmed/unconfirmed balance. Below is the transaction Id.

TxId: 66aff607d5c7812e8f6ef870cb8f46d57cb3529755aacbf68cebf4cf88ca9007

**Comment by tbenz9** [comment]
Please read through this issue and try to solutions provided: https://github.com/NebulousLabs/Sia-UI/issues/581

**Comment by tbenz9** [comment]
This is likely a duplicate of https://github.com/NebulousLabs/Sia-UI/issues/691
