### ISSUE TITLE
structured documentation

### ISSUE THREAD

**Issue by tkphd** [NebulousLabs/Sia#2460]
The useful information in [doc](https://github.com/NebulousLabs/Sia/tree/master/doc) is difficult to navigate, since it's just a bunch of files. Please tie this into modern documentation tools such as [readthedocs][rtd]. This should be trivial to accomplish with a simple `index.rst` and automatic conversion of the `md` files into `html` on the doco platform you choose, and will produce a beautifully formatted version with easy navigation and clear structure.

If GitHub is the focal point for Sia development, it would also help to make use of the platform's tools for making contributing guidelines, easily discoverable, as well as providing templates for new issues and
pull requests to help guide the iterative process of accepting community input. Details are in the Insights
tab under Community.

[rtd]: https://readthedocs.io

**Comment by tbenz9** [comment]
I think this is a great idea and would be willing to help.  Lets let the core devs weigh in on any opinions they have about documentation structuring.  I'm not too fond of hosting documentation on other sites but I definitely think we could improve the in-repo docs for our users.

I also like the idea of utilizing some of the GitHub platform tools, I'll work on a PR that implements some of those ideas.

Recommendation to devs: Label "Feature Request" and comment with opinions about structured documentation.

**Comment by tkphd** [comment]
Good point re. hosting docs yourself, although at the moment, GitHub is hosting them.
But self-hosting is not a big deal: readthedocs, for example, is just a build server running Sphinx on the backend. Tools and services better targeted for Go are probably out there, possibly with docstrings-like support for deep documentation of the code.

Beautifying the docs may seem like a distraction, but if the API is Sia's core product, then it's worth the effort of making clear, complete documentation.

**Comment by tbenz9** [comment]
Godoc already documents the code based on docstrings.  For example: https://godoc.org/github.com/NebulousLabs/Sia/api

I think we could improve the documentation for the community though, things like contributing guidelines, FAQs, known issues, etc.

**Comment by tkphd** [comment]
Oh, cool! I totally missed that on the main README. Oops.
