### ISSUE TITLE
Unable to upload:79 Contracts (now 84)

### ISSUE THREAD

**Issue by mannp** [NebulousLabs/Sia#2461]
I am unable to upload any files as they just remain at 0.1 or 0.2% indefinitely.

I have 10 files uploaded from a couple of months ago taking up a couple of 100 meg.

Allowance:
	Amount: 260 SC
	Period: 12096 blocks

Renter info:
	Storage Spending:  4.743 mS
	Upload Spending:   33.62 uS
	Download Spending: 716.7 mS
	Unspent Funds:     239.8 SC
	Total Allocated:   240.5 SC

Logs with DEBUG enabled attached below.

renter.log http://safe.dsh.re/download/06d9d68c-f105-477d-9bb7-50972618ceab
hostdb.log http://safe.dsh.re/download/f2ddb304-e52c-4f65-8e99-72183802ee3b
contractor.log http://safe.dsh.re/download/79604957-7ad9-49f7-b5dd-44cf88a99781

Any instructions on how to solve would be greatly appreciated.

Thanks

**Comment by mannp** [comment]
Thanks @lukechampine for marking my issue as a bug.

Is a resolution likely for the 1.3.1 by any chance as I have been unable to upload now for a few weeks thinking it was me doing something wrong.

**Comment by tbenz9** [comment]
Please update to 1.3.1 and reopen this issue if the problem remains.
