### ISSUE TITLE
/renter/files API should expose upload progress in bytes

### ISSUE THREAD

**Issue by huetsch** [NebulousLabs/Sia#2467]
I recently wrote a download speed monitor for the Sia UI. I wanted to extend the code to display upload speed as well, but the "uploadprogress" field returned by the API tripped me up. It wasn't immediately obvious to me if a value of 100% included the parity bytes or not. Looking at the code, 100% does include parity. I realize I could figure out the file size inclusive of parity before I make my API call and then multiply that by the upload progress percentage to figure out how many bytes have been uploaded, but this makes using the API really painful.

How about a bytesUploaded() function in modules/renter/files.go? Then we could return a "bytesuploaded" field alongside the "uploadprogress" field in the /renter/files API.

I'll go ahead and write the code for a PR if you guys approve.

**Comment by DavidVorick** [comment]
Basically you want to add a field to the API so that you do not have to do a calculation based on filesize + progress?

@lukechampine what do you think?

**Comment by lukechampine** [comment]
I'm ok with `bytesUploaded` as long as we're clear about what it means. Namely, `bytesUploaded` won't progress to exactly `filesize` and then stop; it can grow pretty much unbounded, depending on the redundancy of the file and how much repair work is needed. As a consequence, you can't use `bytesUploaded` to infer when uploading will stop. It should only be used to estimate upload speed and to see how many total bytes have been uploaded over the lifetime of the file.
