### ISSUE TITLE
After update from 1.2.0: A critical error loading Sia has occured

### ISSUE THREAD

**Issue by vitlav** [NebulousLabs/Sia#2468]
log after run Sia-Ui:
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
Closing gateway...
panic: division by zero

goroutine 1 [running]:
math/big.(*Rat).Inv(0xc420f67500, 0xc420f67540, 0x0)
	/usr/local/go/src/math/big/rat.go:361 +0x2e1
github.com/NebulousLabs/Sia/types.Target.Inverse(0x0, 0x0, 0x0, 0x0, 0xc420f673c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/types/target.go:79 +0x6f
github.com/NebulousLabs/Sia/types.Target.AddDifficulties(0x600000000000000, 0x62f220eac0cb9bb9, 0x2e6fa8ba2693f4b8, 0x127ae7b6a568bac3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/types/target.go:32 +0xcd
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).storeBlockTotals(0xc420145b80, 0xc42030a0e0, 0x13935, 0xfc04000000000000, 0x827e1c933c2a103d, 0x9cdd36333724d23, 0x757a0de7f1edd467, 0x20094, 0x583c507f, 0x583c5523, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/difficulty.go:137 +0x19a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initOak(0xc420145b80, 0xc42030a0e0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/difficulty.go:198 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB.func1(0xc42030a0e0, 0xb036c8, 0xc42030a0e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:45 +0xc1
github.com/NebulousLabs/bolt.(*DB).Update(0xc42010e780, 0xc4200a1250, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0x9f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).loadDB(0xc420145b80, 0xc420460110, 0xc42038b900)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:60 +0x12c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).initPersist(0xc420145b80, 0xc4204600f0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/persist.go:88 +0x18c
github.com/NebulousLabs/Sia/modules/consensus.New(0xde29a0, 0xc420086c60, 0x1, 0xc420304d50, 0x26, 0x1b, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:139 +0x587
main.startDaemon(0x0, 0x0, 0x7ffd6ab807de, 0xe, 0x7ffd6ab8080a, 0x5, 0x7ffd6ab807f9, 0x5, 0x0, 0x7ffd6ab80847, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:170 +0x1b25
main.startDaemonCmd(0xc42008cfc0, 0xc4200192c0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc42008cfc0, 0xc4200100d0, 0x5, 0x5, 0xc42008cfc0, 0xc4200100d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008cfc0, 0xaf832c, 0x3b, 0xc420154a00)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42008cfc0, 0xee9020, 0xae0d0e)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa

**Environment**
* Sia version: 1.3.0
* OS: ALT Linux p8

**Comment by tbenz9** [comment]
`division by zero` errors have occurred in #2452 and #2190.  It is generally related to an incompatible change when upgrading or rolling back Sia versions.  I would recommend backing up your Sia config directory and completely reinstalling.  It's also noteworthy that you're running a less common version of Linux.  It's possible that ALT Linux p8 has never been fully tested or verified to work.  If that's the case the devs are unlikely to be able to solve your problem as they may not want to support your OS.

**Comment by vitlav** [comment]
> I would recommend backing up your Sia config directory and completely reinstalling. 
A good idea.
I just did it and I have no more access to a files I sent to before.
