### ISSUE TITLE
In the latest version (1.3.0), how to build coinbase1 coinbase2 merkle_branch

### ISSUE THREAD

**Issue by sunysen** [NebulousLabs/Sia#2471]
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

**Environment**
* Sia version:1.3.0
* OS:

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by lukechampine** [comment]
I assume this question relates to Sia stratum mining. Please direct your question there.
