### ISSUE TITLE
contractor.journal identified as virus

### ISSUE THREAD

**Issue by gitmalong** [NebulousLabs/Sia#2472]
Bug Report
==========

Avira identified '/Users/myusername/Library/Application Support/Sia-UI/sia/renter/contractor.journal' as Virus and provides the link: https://www.avira.com/de/support-virus-lab-product?vdl%5Bsq%5D=HTML%2FRedirMEinf&noLog=1

Seems other users had similar issues: https://www.reddit.com/r/siacoin/comments/6i2ooq/avira_antivir_sia_false_positive/

Is my installation broke since my file is in quarantine or what I am supposed to do now?

**Environment**
* Sia version: 1.3
* OS: Mac OS High Sierra

**Comment by lukechampine** [comment]
Not much we can do about this. However, `contractor.journal` will be removed in the next version, so (hopefully) anti-virus won't complain anymore.
