### ISSUE TITLE
Issue when restarting SIA UI

### ISSUE THREAD

**Issue by deccap** [NebulousLabs/Sia#2486]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
error while loading contract manager atomic data: error loading the contract manager settings file: unable to read persisted json object from disk: unable to read header from persisted json object file: EOF

Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

**Environment**
* Sia version:
* OS:

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by lukechampine** [comment]
Looks like `contractmanager.json` is corrupted. There may be a `contractmanager.json_temp` file in the same folder. If so, you can try replacing `contractmanager.json` with `contractmanager.json_temp`. If that also fails, you will need to delete the `contractmanager` folder entirely.
