### ISSUE TITLE
explore show nothing after hard fork

### ISSUE THREAD

**Issue by tsai1993** [NebulousLabs/Sia#2510]
<https://explore.sia.tech/>

show nothing

**Comment by tbenz9** [comment]
Devs are aware of the issue, It has been discussed in the Sia Discord.  Should be fixed soon.

**Comment by lukechampine** [comment]
To clear up any confusion, this is not an issue caused by the hardfork. You can enter any block in the search bar and it will display normally. It's a separate issue that affects only the front page.

Closing this since it's not relevant to this repo.
