### ISSUE TITLE
Consensus getting stuck after block 135,000

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2517]
Bug Report
==========

I checked my 1.3.0 node a day or so after the hardfork and noticed it was stuck at block 135,088 (block height was ~135,300 at the time). Following the SiaStats-posted workaround helps it along, but it doesn't seem to fix it entirely, as it keeps getting stuck.

We're getting more reports of this on reddit:

* https://www.reddit.com/r/siacoin/comments/7ijo5u/are_not_all_wallet_addresses_working_anymore/dqzw68p/?st=jazmghjz&sh=84dffc11
* https://www.reddit.com/r/siacoin/comments/7immb8/36_hours_later_i_still_havent_received_any_payout/?st=jazmgwxw&sh=72e5e35a
* https://www.reddit.com/r/siacoin/comments/7in5xy/not_getting_payouts_or_transactions_check_your/?st=jazmhuq4&sh=dc8df77d
* https://www.reddit.com/r/siacoin/comments/7ind0m/sia_ui_isnt_fully_synchrozing/?st=jazmhq9l&sh=5268dafc
* **Megathread**: https://www.reddit.com/r/siacoin/comments/7iocnu/troubleshooting_thread_20171209_wallet_not/?st=jazo13sk&sh=6c41994a

I also had a node running from a recent master build (47514b4). That seems to be running fine.

So 1.3.1 appears to work, but will 1.3.1 have the same issue on the next hardfork?

**Comment by i3bitcoin** [comment]
The same here. Even after deleting consensus.db and adding nodes it doesn't start syncing.
Also I have warning in gateway.log
WARN: could not automatically forward port 9981: no UPnP-enabled devices found: no UPnP-enabled gateway found

**Comment by tbenz9** [comment]
For any users who find this issue looking for a fix, try following the steps in this blog post: https://blog.sia.tech/troubleshooting-the-recent-hardfork-ca77e0b17f0f

**Comment by DavidVorick** [comment]
To answer the question, v1.3.1 will not have the same connection issues after the hardfork. The connection issues are separate, and were not a problem for 130 before the hardfork because the 122 nodes were keeping everyone connected. But now, 122 nodes are obsolete, which removed the safety net that was protecting 130 nodes. 131 fixes the issues, and will be released soon

**Comment by tbenz9** [comment]
With 1.3.1 now released I'm closing this issue.
