### ISSUE TITLE
Faulty disk results in SIGBUS/SIGSEGV panics

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#2518]
Previously we thought that all cryptic boltdb errors were caused by low disk space. However, it appears that `mmap`'d files (like our consensus.db) can cause SIGBUS/SIGSEGV panics if the program accesses part of the file that resides on a faulty disk block. As such, I am reclassifying the following issues as "faulty disk" errors:
#2231
#2220
#1819
And for Sia-UI:
https://github.com/NebulousLabs/Sia-UI/issues/738
https://github.com/NebulousLabs/Sia-UI/issues/708
https://github.com/NebulousLabs/Sia-UI/issues/700
https://github.com/NebulousLabs/Sia-UI/issues/690

These issues all mention SIGBUS, but an IO error may also cause SIGSEGV (at least, according to Wikipedia). I didn't mark those issues because SIGSEGV can also be caused by bolt failing to mmap enough space. We can clean up those issues later.

We should add signal handling to catch such errors and report them in a more actionable (and less scary) way. This shouldn't require much code.

**Comment by joycegarcia1** [comment]
Noob terms for me please. LOL! Is there a fix?

**Comment by lukechampine** [comment]
Follow these instructions to check your disk for errors:

- [Windows](http://www.thewindowsclub.com/disk-error-checking-windows-8)
- [Mac](https://support.apple.com/en-us/HT201639)
- [Linux](https://www.tecmint.com/check-linux-hard-disk-bad-sectors-bad-blocks/)

In most cases, you can repair the errors, but in some, you may need to replace the disk.

**Comment by joycegarcia1** [comment]
Sorry for the late response. I ran the Disk Utility first aid and it came back saying:
File System check exit code is 0.
Operation Successful.

Sia-UI still giving me the same errors. What next?

**Comment by joycegarcia1** [comment]
I should've done my research before transferring my SC to this wallet. It worked the first day then died on me. Apparently (according to thousands of posts on the internet) this is the worse wallet ever. 

Can someone explain to me if and how I can move my SC from this wallet to the paper wallet?

**Comment by dNetGuru** [comment]
Just write down your recovery seed on a piece of paper @joycegarcia1! That'll be your paper wallet.
