### ISSUE TITLE
RC2: Not enough workers to finish download: insufficient hosts to recover file

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2524]
Bug Report
==========

I uploaded a bunch of files on a build of master about 3 weeks ago (I built from 47514b4). Tonight I upgraded to the latest master branch (561a85d9cde1772ab3b84dae76c13e19c1809ed3) and rebuilt, but I'm seeing tons of lines in `renter.log` like this:

```
2017/12/12 01:34:41.711043 download.go:501: Not enough workers to finish download: insufficient hosts to recover file
```

And less frequently, lines like this:

```
2017/12/12 01:10:07.596194 download.go:374: CRITICAL: ERROR: the renter is idle, but tracking 16 active pieces; resetting to zero
```

Note that I'm simultaneously trying to upload 6 files, each between 1-4 GB, but they're all stuck (likely due to #2492). Not sure if that's related.

**Environment**
* Sia version: 561a85d9cde1772ab3b84dae76c13e19c1809ed3 (Roughly RC2)
* OS: Ubuntu 16.04

**Any useful logs**

https://gist.github.com/mtlynch/98b0e46935ff930725066c915ffbb8d7

**Comment by tbenz9** [comment]
FYI `renter is idle...` error is duplicated in #2395 This bug has been around for a while.

**Comment by Virtix21** [comment]
Yes, I'm stuck below 20 contracts too, I can't upload or download at all.

**Comment by tbenz9** [comment]
Is this still an issue with 1.3.1?

**Comment by mtlynch** [comment]
Yep still seeing this:

```
2018/01/02 13:36:02.537225 repairscanner.go:330: Repairing 4332 chunks
2018/01/02 13:36:02.590603 download.go:502: Not enough workers to finish download: insufficient hosts to recover file
```

No longer seeing any `CRITICAL ERROR` lines, though.

**Comment by tbenz9** [comment]
I'm going to close this. With the release of Sia v1.3.2 the download code has been overhauled.  If you can reproduce this with 1.3.2 I encourage you to re-open this issue.
