### ISSUE TITLE
siad not syncing to reach consensus

### ISSUE THREAD

**Issue by dymurray** [NebulousLabs/Sia#2544]
Bug Report
==========

**Stack Trace or error message**
```
curl -i -A “Sia-Agent” localhost:9980/consensus                           │
HTTP/1.1 200 OK                                                                                          │
Content-Type: application/json; charset=utf-8                                                            │
Date: Thu, 14 Dec 2017 21:52:19 GMT                                                                      │
Content-Length: 213                                                                                      │
                                                                                                         │
{"synced":false,"height":0,"currentblock":"25f6e3b9295a61f69fcb956aca9f0076234ecf2e02d399db5448b6e22f26e8│
1c","target":[0,0,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"difficulty":"34359738367│
"}  
```
**Environment**
Fedora 25, golang 1.9.2. Installed Sia from source

* Sia version: 1.3.1

* OS: Fedora

**Any useful logs**
I have left siad running for almost 5 hours at this point and I still see a height of 0 and failure to even change the `currentblock`. 

Is there anything I need to do to trigger the daemon to start syncing? Thanks.

**Comment by ChrisSchinnerl** [comment]
Can you post the output of `siac gateway list` ?

**Comment by dymurray** [comment]
```
$ siac gateway list`
No peers to show
```

That looks like a problem... Am I missing something?

**Comment by tbenz9** [comment]
@dymurray this is a known bug recently introduced (and fixed in the next release).  Follow these instructions as a workaround.

https://siastats.info/nodes.html

**Comment by dymurray** [comment]
Thanks a lot @tbenz9 !
