### ISSUE TITLE
1.3.1: cannot refresh empty contract due to low allowance

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2549]
Bug Report
==========

I'm seeing lots of errors like this in my `contractor.log` even though I have 500 SC unspent allowance:

```
2017/12/15 16:20:08.559323 contracts.go:573: WARN: need to form new contracts, but unable to because of a low allowance
2017/12/15 17:00:20.302081 contracts.go:419: WARN: cannot refresh empty contract due to low allowance.
```

```
$ $GOPATH/bin/siac renter -v
Renter info:
        Storage Spending:  146.6 SC
        Upload Spending:   4.797 SC
        Download Spending: 391.9 mS
        Unspent Funds:     500 SC
        Total Allocated:   503.3 SC

$ $GOPATH/bin/siac wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   763.7 SC
Unconfirmed Delta:  +0 H
Exact:               763717463077504375291841288 H
Siafunds:            0 SF
Siafund Claims:      0 H

Estimated Fee:       30 mS / KB
```

**Environment**
* Sia version: 789adc13d8d7ac7397128ef695e550649fb15ccf
* OS: Ubuntu 16.04 LTS

**Any useful logs**

https://gist.github.com/mtlynch/0cd9b2f9649809f013d70c0182e029f8

**Comment by DavidVorick** [comment]
Hmm. Do you remember what you set your allowance to? I think there's a discrepancy between the backend and the frontend here.

On the backend, you set an allowance and then it's carved into 2 parts: unallocated, and allocated. Unallocated is money that's never been put into a contract, and can be used for new contracts or for renewals. Allocated is money that's been locked into a contract.

Then, 'unspent' refers to the amount of money that remains in the contract. But it's already allocated.

My guess is that you've run out of unallocated allowance, and you have a bunch of contracts which have unspent money, but you also have contracts which are full.

Especially at 146 SC in storage spending, I could imagine that some of your hosts have used up most of their allocated allowance. Seems like we still need to clean up the reporting a bit for the allowance.

**Comment by mtlynch** [comment]
>Do you remember what you set your allowance to? I think there's a discrepancy between the backend and the frontend here.

I set it to 500SC for 12w.

After watching it stuck for a few days, I changed it to 700SC. It managed to upload 1 more GB of data, then got to the same state. Here's where it is now:

```
Renter info:
        Storage Spending:  77.64 SC
        Upload Spending:   2.407 SC
        Download Spending: 408.8 mS
        Unspent Funds:     0 H
        Total Allocated:   692.3 SC

Wallet status:
Encrypted, Unlocked
Confirmed Balance:   431.5 SC
Unconfirmed Delta:  +0 H
Exact:               431450796410837708625174656 H
Siafunds:            0 SF
Siafund Claims:      0 H

Estimated Fee:       30 mS / KB
```

**Comment by mtlynch** [comment]
Here's what my Sia-UI looks like:

![image](https://user-images.githubusercontent.com/7783288/34454786-a8e6e3de-ed40-11e7-9128-858e58513bdb.png)

**Comment by arnili** [comment]
Check your contracts, I just found one in my own contracts with massively overpaying fees:

https://explore.sia.tech/hashes/a25b4795177228ce2ab8d8b0f9c9282d8aeacf42481fd08046170e3e897e4e08
104.4 SC fees alone

If you have several of these its no wonder you're out of allowance.

**Comment by mtlynch** [comment]
@arnili I checked my contracts, but it doesn't seem like any of them have anything egregious in terms of fees:

https://gist.github.com/mtlynch/ebd2b0c8a09d76e3702ddd7bde572c3c

**Comment by mtlynch** [comment]
Oh wait, if I look on the blockchain explorer, it shows wildly different numbers. 

In siac output:

```
Host                                      Remaining Funds  Spent Funds  Spent Fees  Data       End Height  ID
sia.eters.lv:9982                         39.38 SC         1.891 SC     12.06 SC    28.710 GB  149134      248c0f80215dff7270b2af324e2e2ea66e9faf41278a58e86e458766f187d05b
```

On explore.sia.tech:

https://explore.sia.tech/hashes/248c0f80215dff7270b2af324e2e2ea66e9faf41278a58e86e458766f187d05b

![image](https://user-images.githubusercontent.com/7783288/34459355-2ec74a72-edbc-11e7-8194-f31a3e51764d.png)

**Comment by arnili** [comment]
Ok, not sure if this should get it's own bug report then - because I actually have the same problem (low allowance), but for me the reason is clear (overspent on fees):

```
Host                                      Remaining Funds  Spent Funds  Spent Fees  Data       End Height  ID
siaais.dynu.net:9982                      256.4 mS          23.2 mS     104.4 SC    1.078 GB   150305      a25b4795177228ce2ab8d8b0f9c9282d8aeacf42481fd08046170e3e897e4e08
```
(Contract created with 1.3.1)

**Comment by heiko1234** [comment]
may I ask a question beside this discussion. 
I got an problem while setting up the sia host. I do not get the siad in the $GOPATH/bin directory. The folder is not build and there is no SIAD or SIAC program. 
I downloaded from go get - u github.com/NebulousLabs/SIA/...   and i guess it works so far but i cannot find the folder for SIAD and SIAC. May you can give me som advice or help.

**Comment by MSevey** [comment]
@heiko1234 if you have another question on a different topic I would first try the help channel in discord or create a separate issue, otherwise people won't find this question.

@mtlynch have you checked on this bug with v1.3.3?  We made a small improvement to the reported spending as we noticed that it was not aligning with what the wallet balance was. Additionally, #3087 should help this as well when it is merged.

**Comment by mtlynch** [comment]
I don't have any tests running on v1.3.3 but @Fornax96 might be able to check since he's currently testing it.

@Fornax96: Do you see the string "low allowance" anywhere in your `contractor.log`?

**Comment by Fornax96** [comment]
@mtlynch Nope, my contractor log does not talk about allowance. In the end my uploads stopped due to "insufficient balance", which occurs 4242 times in my contractor.log

**Comment by MSevey** [comment]
I think this was address in v1.3.3 then and we are working on additional reporting updates which there are a couple other issues already  for so I'm going to close this one.
