### ISSUE TITLE
SIa UI wont get past loading screen

### ISSUE THREAD

**Issue by Patricio16** [NebulousLabs/Sia#2551]
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus...
Closing gateway...
panic: assertion failed: read: zero-length inode key

goroutine 1 [running]:
github.com/NebulousLabs/bolt._assert(0xa76800, 0xaed7cf, 0x1b, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:1034 +0xfd
github.com/NebulousLabs/bolt.(*node).read(0xc047f34850, 0x24eb0000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:178 +0x1e2
github.com/NebulousLabs/bolt.(*Bucket).node(0xc042158440, 0x21ee0, 0xc044157d50, 0xc044157d50)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:666 +0x15f
github.com/NebulousLabs/bolt.(*node).childAt(0xc044157d50, 0x27, 0x14)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:77 +0x66
github.com/NebulousLabs/bolt.(*Cursor).node(0xc04216f308, 0xc04ab928e0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:373 +0x152
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc042158440, 0xc04ab928e0, 0x20, 0x20, 0xf06bb0, 0x0, 0x0, 0xc048256600, 0xde2420)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:309 +0x233
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).putTransaction(0xc042072840, 0xc0421641c0, 0xb6461a5650800eb6, 0xe6bb241fb948cc6b, 0x2ebcd39de103401, 0x35a41d88058e756a, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/database.go:123 +0xf3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc042072840, 0xa4d7384b1be2c8b4, 0x3f359925ecafc16a, 0x9a81c64bb7331e6c, 0xd5d4f6c84d315fff, 0x0, 0x0, 0x0, 0xc05278ef60, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:200 +0x49e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc04e94aa80, 0xb0b578, 0xc04e94aa80)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:176 +0x160
github.com/NebulousLabs/bolt.(*DB).View(0xc042100780, 0xc042171248, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0xa6
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc042133b80, 0xdd9de0, 0xc042072840, 0xc962f1176450a7b1, 0xd91ae5f7bf44c352, 0xa772cd2c20e736dc, 0xde64e58b1161e423, 0x8d6e2e, 0x2a2f7115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x256
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc042133b80, 0xdd9de0, 0xc042072840, 0xc962f1176450a7b1, 0xd91ae5f7bf44c352, 0xa772cd2c20e736dc, 0xde64e58b1161e423, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xf5
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc042072840, 0xc042072840, 0xc042071a70)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x94b
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xde5060, 0xc042133b80, 0xde4440, 0xc042072f20, 0xc042046240, 0x38, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x27d
main.startDaemon(0x0, 0x0, 0xc0420443eb, 0xe, 0xc04204442b, 0x5, 0xc04204440c, 0x5, 0x0, 0xc04204444a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x169a
main.startDaemonCmd(0xc042079200, 0xc04205b4a0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x169
github.com/spf13/cobra.(*Command).execute(0xc042079200, 0xc04203c070, 0x5, 0x5, 0xc042079200, 0xc04203c070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x2a0
github.com/spf13/cobra.(*Command).ExecuteC(0xc042079200, 0xb002aa, 0x3b, 0xc042142aa0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc042079200, 0xeea320, 0xae8452)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7b1

**Environment**
* Sia version: 1.3.0
* OS: Windows 10 x64

**Any useful logs**

**Comment by tbenz9** [comment]
We've seen this error once before in #2349.  It's a Bolt error related (i think) to https://github.com/boltdb/bolt/issues/456.

As a possible workaround try deleting the consensus.db file and restarting Sia. It is located in:
- Windows: Users\<user>\appdata\roaming\Sia-UI\sia\consensus\consensus.db
- OS X: $HOME/Library/Application Support/Sia-UI/sia/consensus/consensus.db
- Linux: $HOME/.config/Sia-UI/sia/consensus/consensus.db

**Comment by Patricio16** [comment]
I did your suggestion but I got this error.  Also before the error, it says that I have updated to a new version and to look at the release notes to see what has changed even though I have been using 1.3 since the beginning 

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
Closing consensus...
Closing gateway...
panic: page 138945 already freed

goroutine 1 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc04223ae10, 0xc0, 0x24be1000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x2a1
github.com/NebulousLabs/bolt.(*Bucket).free.func1(0x24be1000, 0x0, 0x3)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:684 +0x58
github.com/NebulousLabs/bolt.(*Bucket)._forEachPageNode(0xc04200a480, 0x21ee1, 0x3, 0xc0424771e8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:506 +0x8e
github.com/NebulousLabs/bolt.(*Bucket)._forEachPageNode(0xc04200a480, 0x21ef1, 0x2, 0xc0424771e8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:513 +0xfd
github.com/NebulousLabs/bolt.(*Bucket)._forEachPageNode(0xc04200a480, 0x21ffa, 0x1, 0xc0424771e8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:513 +0xfd
github.com/NebulousLabs/bolt.(*Bucket)._forEachPageNode(0xc04200a480, 0x27326, 0x0, 0xc0424771e8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:513 +0xfd
github.com/NebulousLabs/bolt.(*Bucket).forEachPageNode(0xc04200a480, 0xc0424771e8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:499 +0x83
github.com/NebulousLabs/bolt.(*Bucket).free(0xc04200a480)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:688 +0x6f
github.com/NebulousLabs/bolt.(*Bucket).DeleteBucket(0xc04214a1d8, 0xdd81e0, 0x15, 0x15, 0xee9fe0, 0xdcc6b4)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:255 +0x2d8
github.com/NebulousLabs/bolt.(*Tx).DeleteBucket(0xc04214a1c0, 0xdd81e0, 0x15, 0x15, 0xc04220a140, 0x43)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:121 +0x56
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).resetDB(0xc04205b1e0, 0xc04214a1c0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:67 +0x5a
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc04205b1e0, 0xc04205b1e0, 0xc04223ad20)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:188 +0xb44
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xde5060, 0xc042113b80, 0xde4440, 0xc04205ac60, 0xc042151080, 0x38, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x27d
main.startDaemon(0x0, 0x0, 0xc04200268b, 0xe, 0xc0420026cb, 0x5, 0xc0420026ac, 0x5, 0x0, 0xc0420026ea, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x169a
main.startDaemonCmd(0xc042061200, 0xc04200d770, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x169
github.com/spf13/cobra.(*Command).execute(0xc042061200, 0xc0420100d0, 0x5, 0x5, 0xc042061200, 0xc0420100d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x2a0
github.com/spf13/cobra.(*Command).ExecuteC(0xc042061200, 0xb002aa, 0x3b, 0xc042122aa0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x340
github.com/spf13/cobra.(*Command).Execute(0xc042061200, 0xeea320, 0xae8452)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7b1

**Comment by tbenz9** [comment]
The "updated to a new version" message is normal.  You deleted some of the config files and Sia detected it as an upgrade and was rebuilding the configurations.

For your new error: delete the transactionpool.db file:
- Windows: Users\<user>\appdata\roaming\Sia-UI\sia\transactionpool\transactionpool.db
- OS X: $HOME/Library/Application Support/Sia-UI/sia/transactionpool/transactionpool.db
- Linux: $HOME/.config/Sia-UI/sia/transactionpool/transactionpool.db

You will probably see the same "new version" message again.

**Comment by Patricio16** [comment]
I ended up deleting the folder in the appdata directory and it started syncing again and finally completed this morning

**Comment by ryanchappell85** [comment]
I had the same basic problem. GUI would get to 28% synced then would throw an error message and would stop syncing. I deleted the file (Windows: Users<user>\appdata\roaming\Sia-UI\sia\consensus\consensus.db) and restarted the GUI. It started to resync at 0 and appears to be working properly.
