### ISSUE TITLE
change password lacks confirmation

### ISSUE THREAD

**Issue by jfcg** [NebulousLabs/Sia#2552]
Feature Request:  Siac should ask to confirm the password when changing it.
./siac wallet change-password
Current Password: 
New Password: 
Password changed sucessfully.

It did not ask a second time to confirm if I really entered new password correctly..

**Environment**
* Sia version: v1.3.0
* OS: Manjaro Linux 64-bit

**Comment by tbenz9** [comment]
I think this is a great idea, I edited this issue to make it a little more clear.  I hope that's okay.

**Comment by lukechampine** [comment]
This would be a good task for first-time contributors.
