### ISSUE TITLE
Readme.md possible typo

### ISSUE THREAD

**Issue by ordtrogen** [NebulousLabs/Sia#2554]
Bug Report
==========
Readme.md on https://github.com/NebulousLabs/Sia needs review:

![clip](https://user-images.githubusercontent.com/15184875/34095159-aae904d8-e3d0-11e7-93bf-cab9053b2582.png)

The three dots at the end have me confused. Maybe a stupid question, but should it read:

' go get -u https://github.com/NebulousLabs/Sia.git '

?

**Comment by Fornax96** [comment]
That's intentional.

The three dots mean that all the packages that Sia depends on should also be updated. It's not a unix convention, but a custom syntax which is interpreted by `go get`.

https://stackoverflow.com/questions/28031603/what-do-three-dots-mean-in-go-command-line-invocations

**Comment by ordtrogen** [comment]
Great. I had actually tried the ... syntax on my machine but nothing seemed to happen (now I understand wasn't patient enough)

But surely, this merits at least a comment in Readme.md that it's a Go thing and not a typo?
Especially since it's so similiar to the olde

' git clone https://github.com/ProjHome/proj.git '

**Comment by lukechampine** [comment]
go get will install the siad/siac binaries, whereas git clone just fetches the source.

This is common enough in Go repos that I don't think it warrants additional explanation, although I can see why `...` could be misleading to people who haven't used Go before
