### ISSUE TITLE
launch the daemon as a background process:

### ISSUE THREAD

**Issue by sunysen** [NebulousLabs/Sia#2567]
Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

**Environment**
* Sia version:1.3.1
* OS:ubuntu16.04

**Any useful logs**
run commad
`echo "test" | siad --api-addr 192.168.1.1:9980 --disable-api-security --authenticate-api --modules cgmhrtw -d /test/siacoindata`
There is nothing wrong, it can not start

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by chargr** [comment]
I am not sure what you are trying to do, but the command provided is wrong.
```
echo "test" > siad
```
That will create a file with name 'siad' with the contents of 'test'.

Consider using screen to run the sia in the background:
```
screen -dmS sia /opt/sia/bin/siad -M cghrtw -d /data/sia/siad
```

**Comment by sunysen** [comment]
@chargr  commond write wrong，`echo "test" | siad`

**Comment by lukechampine** [comment]
you can also run it in the background with `&`, or by suspending via `^Z`.

**Comment by tbenz9** [comment]
As far as I know `siad` does not accept any data from stdin.  I would recommend reading about the siad api and using the suggestions above for running siad in the background.
