### ISSUE TITLE
mac osx icon is wrong on Sia-UI-v1.3.1-osx-x64

### ISSUE THREAD

**Issue by gilemon** [NebulousLabs/Sia#2569]
* Sia version: 1.3.1
* OS: 10.11.6

Looks like a packaging issue, see the print-screen here:
http://www.utyp.net/thumbs/s/screen-shot-2017-12-21-at-11.png

**Comment by JoshMountain** [comment]
Possibly related, I also see an icon that is way too large in my status bar:

![status-bar](https://user-images.githubusercontent.com/3465855/34309465-46283e8c-e70f-11e7-808f-5815d350da19.png)

**Comment by martinbehrens** [comment]
I can confirm the latter for OS X 10.13.3 (17D47) and Sia v1.3.1.

**Comment by SpectralKH** [comment]
Appears in the get info window as well
![screen shot 2018-03-05 at 10 15 06 pm](https://user-images.githubusercontent.com/11315492/37000139-b62be52a-20c2-11e8-93ce-69d1c29f3e59.png)

**Comment by tbenz9** [comment]
Can anyone confirm if this is still a bug with the 1.3.2 release?

**Comment by SpectralKH** [comment]
@tbenz9 Still there
![screen shot 2018-03-14 at 10 38 09 pm](https://user-images.githubusercontent.com/11315492/37432365-68f57d6c-27d8-11e8-85a6-53255cf5bb58.png)
![screen shot 2018-03-14 at 10 38 14 pm](https://user-images.githubusercontent.com/11315492/37432366-690f2884-27d8-11e8-9e4e-d284b9fe8be3.png)

**Comment by martinbehrens** [comment]
@SpectralKH Not for me.

@tbenz9 For OSX 10.13.3 and Sia-UI 1.3.2 the get info issue seems fixed:

<img width="399" alt="screen shot 2018-03-20 at 22 09 16" src="https://user-images.githubusercontent.com/2241794/37683061-a6faaaf8-2c8b-11e8-91f0-68316d700e94.png">

@tbenz9 @JoshMountain For OSX 10.13.3 and Sia-UI 1.3.2 the status bar issue is still reproducible:

<img width="608" alt="screen shot 2018-03-20 at 22 08 21" src="https://user-images.githubusercontent.com/2241794/37683180-02c83a62-2c8c-11e8-8af7-8a13c3a5d453.png">

**Comment by turnkit** [comment]
Still an issue for OSX 10.12.6 ad Sia-UI 1.3.1 and 1.3.2.

![screen shot 2018-03-27 at 9 18 09 pm](https://user-images.githubusercontent.com/4126167/38005156-32d6a6fc-3205-11e8-8588-cc35f85cf5fe.png)

**Comment by MSevey** [comment]
@eddiewang

**Comment by ChrisSchinnerl** [comment]
I think this was fixed by @eddiewang yesterday. If it still persists on the master branch of Sia-UI we should reopen this issue in the Sia-UI [repository](https://github.com/NebulousLabs/Sia-UI).
