### ISSUE TITLE
Sia issue

### ISSUE THREAD

**Issue by adammsafi** [NebulousLabs/Sia#2570]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
difficulty adjustment hardfork incompatibility detected

**Stack Trace or error message**

**Environment**
* Sia version: 1.3.1
* OS:10.13.2

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment]
Please follow these instructions to fix: https://blog.sia.tech/troubleshooting-the-recent-hardfork-ca77e0b17f0f
