### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by ghasrfakhri** [NebulousLabs/Sia#2573]
Bug Report
==========
During synchronizing I get *Siad has exited unexpectedly.*

**Environment**
* Sia version: 1.3.1
* OS: Fedora 27 (4.14.4-200.fc26.x86_64)

**Stack Trace or error message**
[siad-output.log](https://github.com/NebulousLabs/Sia/files/1580624/siad-output.log)

**Comment by dlsso** [comment]
I'm getting the same error on Windows 10.

```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
```

**Comment by tbenz9** [comment]
@ghasrfakhri this looks like a very low-level system error.  Perhaps you have some bad RAM, or a bad sector on your HDD.  If you are still running into problems getting Sia to sync, I would recommend following the instructions below to "Delete the consensus.db file".  I don't think this is a Sia problem but rather a computer problem.  I'm going to close this issue, and you can re-open it if still need additional help.

https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by tbenz9** [comment]
@dlsso You need to include the error message, the output you included is all normal Sia output.  See this link for finding your logs.  https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by dlsso** [comment]
Downloaded 1.3.1 and haven't got it since. Thanks for the troubleshooting link though. Will use in future if needed.
