### ISSUE TITLE
Critical Error Loading Sia and Syncing Wallet (Siad) 

### ISSUE THREAD

**Issue by Alexanders78** [NebulousLabs/Sia#2582]
I received the following error message while transferring coins to wallet; 

Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.84217434 seconds

Wallet: scanned to height 119790...
Wallet: scanned to height 119850...
Wallet: scanned to height 119900...
Wallet: scanned to height 119936...
Wallet: scanned to height 119985...
Wallet: scanned to height 120053...
Wallet: scanned to height 120122...
Wallet: scanned to height 120196...
Wallet: scanned to height 120252...
Wallet: scanned to height 120310...
Wallet: scanned to height 120356...
Wallet: scanned to height 120416...
Wallet: scanned to height 120467...
Wallet: scanned to height 120500...
Wallet: scanned to height 120571...
Wallet: scanned to height 120631...
Wallet: scanned to height 120701...
Wallet: scanned to height 120777...
Wallet: scanned to height 120854...
Wallet: scanned to height 120931...
Wallet: scanned to height 121007...
Wallet: scanned to height 121082...
Wallet: scanned to height 121138...
Wallet: scanned to height 121193...
Wallet: scanned to height 121277...
Wallet: scanned to height 121356...
Wallet: scanned to height 121435...
Wallet: scanned to height 121515...
Wallet: scanned to height 121598...
Wallet: scanned to height 121691...
Wallet: scanned to height 121724...
Wallet: scanned to height 121758...
Wallet: scanned to height 121823...
Wallet: scanned to height 121891...
Wallet: scanned to height 121978...
Wallet: scanned to height 122057...
Wallet: scanned to height 122150...
Wallet: scanned to height 122227...
Wallet: scanned to height 122319...
Wallet: scanned to height 122413...
Wallet: scanned to height 122498...
Wallet: scanned to height 122589...
Wallet: scanned to height 122665...
Wallet: scanned to height 122745...
Wallet: scanned to height 122825...
Wallet: scanned to height 122916...
Wallet: scanned to height 123000...
Wallet: scanned to height 123085...
Wallet: scanned to height 123164...
Wallet: scanned to height 123245...
Wallet: scanned to height 123322...
Wallet: scanned to height 123386...
Wallet: scanned to height 123419...
Wallet: scanned to height 123471...
Wallet: scanned to height 123523...
Wallet: scanned to height 123567...
Wallet: scanned to height 123616...
Wallet: scanned to height 123679...
Wallet: scanned to height 123735...
Wallet: scanned to height 123803...
Wallet: scanned to height 123851...
Wallet: scanned to height 123907...
Wallet: scanned to height 123960...
Wallet: scanned to height 124031...
Wallet: scanned to height 124093...
Wallet: scanned to height 124158...
Wallet: scanned to height 124227...
Wallet: scanned to height 124296...
Wallet: scanned to height 124357...
Wallet: scanned to height 124420...
Wallet: scanned to height 124479...
Wallet: scanned to height 124536...
Wallet: scanned to height 124592...
Wallet: scanned to height 124644...
Wallet: scanned to height 124706...
Wallet: scanned to height 124766...
Wallet: scanned to height 124827...
Wallet: scanned to height 124895...
Wallet: scanned to height 124960...
Wallet: scanned to height 125022...
Wallet: scanned to height 125090...
Wallet: scanned to height 125155...
Wallet: scanned to height 125207...
Wallet: scanned to height 125268...
Wallet: scanned to height 125337...
Wallet: scanned to height 125405...
Wallet: scanned to height 125480...
Wallet: scanned to height 125551...
Wallet: scanned to height 125617...
Wallet: scanned to height 125683...
Wallet: scanned to height 125750...
Wallet: scanned to height 125822...
Wallet: scanned to height 125881...
Wallet: scanned to height 125953...
Wallet: scanned to height 126024...
Wallet: scanned to height 126092...
Wallet: scanned to height 126145...
Wallet: scanned to height 126207...
Wallet: scanned to height 126278...
Wallet: scanned to height 126341...
Wallet: scanned to height 126404...
Wallet: scanned to height 126462...
Wallet: scanned to height 126513...
Wallet: scanned to height 126576...
Wallet: scanned to height 126628...
Wallet: scanned to height 126680...
Wallet: scanned to height 126730...
Wallet: scanned to height 126790...
Wallet: scanned to height 126855...
Wallet: scanned to height 126923...
Wallet: scanned to height 126985...
Wallet: scanned to height 127059...
Wallet: scanned to height 127121...
Wallet: scanned to height 127200...
Wallet: scanned to height 127268...
Wallet: scanned to height 127327...
Wallet: scanned to height 127387...
Wallet: scanned to height 127421...
Wallet: scanned to height 127466...
Wallet: scanned to height 127533...
Wallet: scanned to height 127585...
Wallet: scanned to height 127650...
Wallet: scanned to height 127682...
Wallet: scanned to height 127741...
Wallet: scanned to height 127809...
Wallet: scanned to height 127873...
Wallet: scanned to height 127941...
Wallet: scanned to height 128009...
Wallet: scanned to height 128080...
Wallet: scanned to height 128147...
Wallet: scanned to height 128218...
Wallet: scanned to height 128274...
Wallet: scanned to height 128316...
Wallet: scanned to height 128373...
Wallet: scanned to height 128430...
Wallet: scanned to height 128488...
Wallet: scanned to height 128539...
Wallet: scanned to height 128578...
Wallet: scanned to height 128631...
Wallet: scanned to height 128687...
Wallet: scanned to height 128745...
Wallet: scanned to height 128802...
Wallet: scanned to height 128840...
Wallet: scanned to height 128881...
Wallet: scanned to height 128920...
Wallet: scanned to height 128977...
Wallet: scanned to height 129030...
Wallet: scanned to height 129084...
Wallet: scanned to height 129141...
Wallet: scanned to height 129198...
Wallet: scanned to height 129241...
Wallet: scanned to height 129294...
Wallet: scanned to height 129324...
Wallet: scanned to height 129373...
Wallet: scanned to height 129431...
Wallet: scanned to height 129486...
Wallet: scanned to height 129536...
Wallet: scanned to height 129588...
Wallet: scanned to height 129646...
Wallet: scanned to height 129711...
Wallet: scanned to height 129773...
Wallet: scanned to height 129830...
Wallet: scanned to height 129874...
Wallet: scanned to height 129928...
Wallet: scanned to height 129983...
Wallet: scanned to height 130034...
Wallet: scanned to height 130090...
Wallet: scanned to height 130147...
Wallet: scanned to height 130205...
Wallet: scanned to height 130266...
Wallet: scanned to height 130308...
Wallet: scanned to height 130360...
Wallet: scanned to height 130409...
Wallet: scanned to height 130462...
Wallet: scanned to height 130521...
Wallet: scanned to height 130556...
Wallet: scanned to height 130612...
Wallet: scanned to height 130643...
Wallet: scanned to height 130689...
Wallet: scanned to height 130743...
Wallet: scanned to height 130786...
Wallet: scanned to height 130836...
Wallet: scanned to height 130872...
Wallet: scanned to height 130915...
Wallet: scanned to height 130966...
Wallet: scanned to height 131010...
Wallet: scanned to height 131061...
Wallet: scanned to height 131099...
Wallet: scanned to height 131124...
Wallet: scanned to height 131185...
Wallet: scanned to height 131240...
Wallet: scanned to height 131288...
Wallet: scanned to height 131319...
Wallet: scanned to height 131346...
Wallet: scanned to height 131396...
Wallet: scanned to height 131459...
Wallet: scanned to height 131511...
Wallet: scanned to height 131581...
Wallet: scanned to height 131639...
Wallet: scanned to height 131695...
Wallet: scanned to height 131753...
Wallet: scanned to height 131818...
Wallet: scanned to height 131861...
Wallet: scanned to height 131920...
Wallet: scanned to height 131980...
Wallet: scanned to height 132046...
Wallet: scanned to height 132103...
Wallet: scanned to height 132157...
Wallet: scanned to height 132220...
Wallet: scanned to height 132278...
Wallet: scanned to height 132336...
Wallet: scanned to height 132401...
Wallet: scanned to height 132453...
Wallet: scanned to height 132513...
Wallet: scanned to height 132569...
Wallet: scanned to height 132626...
Wallet: scanned to height 132682...
Wallet: scanned to height 132730...
Wallet: scanned to height 132775...
Wallet: scanned to height 132832...
Wallet: scanned to height 132887...
Wallet: scanned to height 132942...
Wallet: scanned to height 132989...
Wallet: scanned to height 133036...
Wallet: scanned to height 133094...
Wallet: scanned to height 133153...
Wallet: scanned to height 133215...
Wallet: scanned to height 133275...
Wallet: scanned to height 133329...
Wallet: scanned to height 133386...
Wallet: scanned to height 133448...
Wallet: scanned to height 133510...
Wallet: scanned to height 133555...
Wallet: scanned to height 133616...
Wallet: scanned to height 133661...
Wallet: scanned to height 133716...
Wallet: scanned to height 133775...
Wallet: scanned to height 133827...
Wallet: scanned to height 133884...
Wallet: scanned to height 133944...
Wallet: scanned to height 133991...
Wallet: scanned to height 134040...
Wallet: scanned to height 134074...
Wallet: scanned to height 134129...
Wallet: scanned to height 134171...
Wallet: scanned to height 134234...
Wallet: scanned to height 134288...
Wallet: scanned to height 134350...
Wallet: scanned to height 134398...
Wallet: scanned to height 134455...
Wallet: scanned to height 134516...
Wallet: scanned to height 134574...
Wallet: scanned to height 134615...
Wallet: scanned to height 134670...
Wallet: scanned to height 134725...
Wallet: scanned to height 134775...
Wallet: scanned to height 134829...
Wallet: scanned to height 134884...
Wallet: scanned to height 134929...
Wallet: scanned to height 134986...
Wallet: scanned to height 135035...
Wallet: scanned to height 135098...
Wallet: scanned to height 135137...
Wallet: scanned to height 135202...
Wallet: scanned to height 135264...
Wallet: scanned to height 135321...
Wallet: scanned to height 135382...
Wallet: scanned to height 135452...
Wallet: scanned to height 135508...
Wallet: scanned to height 135568...
Wallet: scanned to height 135638...
Wallet: scanned to height 135715...
Wallet: scanned to height 135773...
Wallet: scanned to height 135846...
Wallet: scanned to height 135934...
Wallet: scanned to height 136018...
Wallet: scanned to height 136114...
Wallet: scanned to height 136205...
Wallet: scanned to height 136277...
Wallet: scanned to height 136345...
Wallet: scanned to height 136407...
Wallet: scanned to height 136473...
Wallet: scanned to height 136527...
Wallet: scanned to height 136589...
Wallet: scanned to height 136645...
Wallet: scanned to height 136713...
Wallet: scanned to height 136774...
Wallet: scanned to height 136832...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Wallet: scanned to height 136852...
Done!

Bug Report
==========
Check to see if a bug report already exists.  If you still want to create a new issue please include the information below.

**Stack Trace or error message**

**Environment**
* Sia version:
* OS:

**Any useful logs**

Feature Request
===============
Check to see if the feature is on the roadmap.  If it is not on the roadmap then clearly describe your feature request and why it would benefit Sia.

[Sia roadmap](https://trello.com/b/Io1dDyuI/sia-public-roadmap)

**Comment by tbenz9** [comment]
All the the attached output is normal output.  If you have additional logs or information please reopen this issue and attache the additional information.

Read this document to find your logs: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
