### ISSUE TITLE
password/seed input prompt in siac 1.3.1 broken on Windows

### ISSUE THREAD

**Issue by Fiktik** [NebulousLabs/Sia#2587]
Bug Report
==========
It appears that when a password/seed input prompt is invoked in siac, an error is triggered giving the output below. There is no actual input accepted, the command exits immediately.

Issue is reproducible in both 'cmd' and 'powershell'. Tried executing "Get-Content seed.txt | .\siac wallet init-seed" in powershell, but doesn't help.

**Stack Trace or error message**
> .\siac wallet unlock
Wallet password:
Reading password failed: The handle is invalid.

> .\siac wallet init-seed
Seed:
Reading seed failed: The handle is invalid.

**Environment**
* Sia version: 1.3.1 binaries downloaded from https://sia.tech/apps/ on 27. Dec
* OS: Windows 10

**Comment by tbenz9** [comment]
I would recommend using the SIA_WALLET_PASSWORD env variable instead of trying to pass it in via stdin.  This feature is not well documented (yet) but the PR below outlines how it works.

https://github.com/NebulousLabs/Sia/pull/2351

**Comment by betaboot** [comment]
Same here. Win10 with v1.3.1 does not work in the cmd window. I backtracked and found that v1.3.1RC1 was still working, RC2 not anymore.

**Comment by tbenz9** [comment]
Possibly related to #2593

**Comment by hackneyb** [comment]
// passwordPrompt securely reads a password from stdin.
func passwordPrompt(prompt string) (string, error) {
    fmt.Print(prompt)
    pw, err := terminal.ReadPassword(0)
    fmt.Println()
    return string(pw), err
}

I think this is a documented Go bug
https://github.com/golang/go/issues/11914
GitHub
x/crypto/ssh/terminal: ReadPassword broken on windows · Issue #11914 · golang/go
On go1.4.2 windows/amd64 with golang.org/x/crypto/ssh/terminal revision 56474dfd625f18739b46f075b138fd0133717491. ReadPassword seems to be broken. Reproduction Case: package main import ( "fmt" ...

Quoted from link above: Does it work if you use terminal.ReadPassword(syscall.Stdin) ?

Quoted from link above: The fact that 0 == syscall.Stdin on Unix system does not mean that that holds true on Windows.(edited)
Quoted from link above: You're correct, I made the mistake of assuming that syscall.Stdin was 0 on windows. I never considered that it would be different on windows (silly windows), and the docs on stdin were a little misleading. Thank you for the clarification!(edited)

**Comment by radegeddon** [comment]
Not working, even with the SIA_WALLET_PASSWORD env variable set, siad.exe reports Auto-unlock failed.
