### ISSUE TITLE
Problem reading in db tranasction

### ISSUE THREAD

**Issue by Archie1978** [NebulousLabs/Sia#2597]
SIA: 1.3.0
OS: Unbuntu 16:04 (docker)

Since i stop my siad my transaction pool is on error. For corrected error, I resync but it is very long time. Can you make everthing ?

(0/4) Loading siad...
(1/4) Loading gateway...
(2/4) Loading consensus...
(3/4) Loading transaction pool...
Closing consensus...
Closing gateway...
panic: assertion failed: tx closed

goroutine 1 [running]:
github.com/NebulousLabs/bolt._assert(0xc4200a5200, 0xabc082, 0x9, 0x0, 0x0, 0x0)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/bolt/db.go:1029 +0xf6
github.com/NebulousLabs/bolt.(*Cursor).Next(0xc4200a5260, 0x20, 0x20, 0x7f83c9e35360, 0x0, 0x0, 0x0)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/bolt/cursor.go:74 +0x6f
github.com/NebulousLabs/bolt.(*Bucket).ForEach(0xc420068640, 0xc4200a5318, 0x15, 0x15)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/bolt/bucket.go:389 +0x11c
github.com/NebulousLabs/bolt.(*Bucket).DeleteBucket(0xc4201181d8, 0xdb4320, 0x15, 0x15, 0xdb5be0, 0xc420017650)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/bolt/bucket.go:244 +0x1fe
github.com/NebulousLabs/bolt.(*Tx).DeleteBucket(0xc4201181c0, 0xdb4320, 0x15, 0x15, 0x0, 0x41)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/bolt/tx.go:121 +0x4f
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).resetDB(0xc420088840, 0xc4201181c0, 0xdb5be0, 0xc420017650)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:67 +0x53
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc420088840, 0xc420088840, 0xc420013d70)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:185 +0x95c
github.com/NebulousLabs/Sia/modules/transactionpool.New(0xdc13a0, 0xc42014fb80, 0xdc0800, 0xc420088c60, 0xc4200d2620, 0x1a, 0x0, 0x0, 0x0)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x276
main.startDaemon(0x0, 0x0, 0x7ffccb55ef5b, 0x5, 0xab282a, 0x5, 0xab282f, 0x5, 0x1, 0x7ffccb55ef0e, ...)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/Sia/siad/daemon.go:205 +0x1683
main.startDaemonCmd(0xc42008efc0, 0xc4200ee120, 0x0, 0x9)
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/Sia/siad/daemon.go:338 +0x162
github.com/spf13/cobra.(*Command).execute(0xc42008efc0, 0xc4200100b0, 0x9, 0x9, 0xc42008efc0, 0xc4200100b0)
	/opt/docker/sia/pkg-src/src/github.com/spf13/cobra/command.go:651 +0x23a
github.com/spf13/cobra.(*Command).ExecuteC(0xc42008efc0, 0xadf518, 0x3b, 0xc42015eaa0)
	/opt/docker/sia/pkg-src/src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc42008efc0, 0xec6c60, 0xac8348)
	/opt/docker/sia/pkg-src/src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/opt/docker/sia/pkg-src/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Loading...
(0/4) Loading siad...
(1/4) Loading gateway...

**Comment by tbenz9** [comment]
This error shows up in #2239.

Try following the "Delete the transactionpool.db file" section of the document below.  It will take a long time to load at first, then it should load quickly in the future.
https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
