### ISSUE TITLE
Transaction problem 

### ISSUE THREAD

**Issue by tgeorgiop** [NebulousLabs/Sia#2604]
# BUG REPORT

Hello. I made a withdrawal from bittrex to the address: 57368ea7ab9b74306f1751d2e878ab14df799ae322776557aa2543540a07da0503c8c2156266 and txId: a97e59a0974dce3496e2a5755c04b785c596195e8ae5bb222b087db851c876b7 . In https://explore.sia.tech it shows "Hash not found" but in https://explorer.siahub.info I can see the transaction. What is going on?

**Comment by eddiewang** [comment]
cc @nitronick600

**Comment by nairyl** [comment]
hi  i ve the same here 
on this address -> 9be93fb1a3d0028489b2ae2f868b920202c031ef8887cfedf0b5cea7b42059a875c417600d8b
and txid -> 1ab68539eaa37f7c67f6c9061501aa777e00b9076aa56df264e955d812d6bba3
the tx is from poloniex 
i saw @nitronick600 but i don't found any contact ..
Thanks for the help and wish the best @ all team

**Comment by nairyl** [comment]
i don't know if some body did something but now it's ok thank you all  and see you later ;-)

**Comment by nitronick600** [comment]
Hi @nairyl I think this is fixed. Can you take a look and close it out please/

**Comment by nitronick600** [comment]
@tbenz9 @DavidVorick this can be closed.
