### ISSUE TITLE
Wallet requested I file this bug

### ISSUE THREAD

**Issue by victorengel** [NebulousLabs/Sia#2606]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS: OSX

Log requested to be attached:

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.018180844 seconds

Wallet: scanned to height 999...
Wallet: scanned to height 6099...
Wallet: scanned to height 13399...
Wallet: scanned to height 18799...
Wallet: scanned to height 23499...
Done!

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by victorengel** [comment]
Interesting. I just installed the wallet, and it's doing its first scan. After reporting the ticket by following the instructions (why would it ask me to create a ticket if there were no problem?) I quit the app and started it up again. I'm guessing this means the message is gone now.

**Comment by victorengel** [comment]
Looking through the various log files, the only thing that looked like an error to me was this:

2018/01/03 23:50:47.339047 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
2018/01/04 00:56:08.863324 update.go:84: Unable to save while processing a consensus change: unable to open temp file: open /Users/########/Library/Application Support/Sia-UI/sia/renter/contractor.json_temp: too many open files in system
2018/01/04 01:03:09.604800 contractor.go:194: STARTUP: Logging has started. Siad Version 1.3.1
