### ISSUE TITLE
The fucking SIA Wallet ERROR please help !

### ISSUE THREAD

**Issue by Aldafx** [NebulousLabs/Sia#2609]
Hello there, has anybody solved this shit with the SIA wallet while syncing ? I cannot solve it by myself and there is no SIA support ,
thany a lot

Siad has exited unexpectedly. Please submit a bug report including the error log here.

Error Log:
<Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.7931597999999997 seconds

**Comment by tbenz9** [comment]
Please be respectful when asking for help.

The log you attached does not show an error, all the text you've included is expected.  If you would like help the best place to ask is on the #Help channel of the Sia Discord.  https://discord.gg/sia

To view your logs (and fix issues) you can check out this tutorial: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by Aldafx** [comment]
I sorry for such language, but i have been fighting the wallet sync process fro a week now! that is too long and I have cons sent to me, anyway thank you for your help
