### ISSUE TITLE
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1 Loading... (0/6) Loading siad... (1/6) Loading gateway... listen tcp :9981: bind: address already in use

### ISSUE THREAD

**Issue by thedrunkencrane** [NebulousLabs/Sia#2616]
# BUG REPORT

**Stack Trace or error message**

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
listen tcp :9981: bind: address already in use

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

open sia and only get this error message

**Environment**
* Sia version: v1.3.1 (Capricorn)
* OS: OSX 10.12.6

**Comment by tbenz9** [comment]
This means that a process is already using port 9981.  make sure you are not running more than one process of siad at once, or that another program already has that port reserved.

There is no action for the Sia team, so I'm closing this issue.
