### ISSUE TITLE
SIA 1.3.1 fails to upload on new insstallation (logs included)

### ISSUE THREAD

**Issue by chrsch** [NebulousLabs/Sia#2618]
# BUG REPORT

**Stack Trace or error message**
Sia doesn't upload 5 MB file. After 1 hour siad uploaded 500 mb, but upload progress of the file is 0%.

**Expected Behavior**
Sia uploads 5 MB file in reasonable time. on a 2 mbit upload connection (maybe some minutes).

**How to reproduce it (as minimally and precisely as possible)**
1. Create a new SIA installation
2. Add some SC to the new wallet
3. Create 1000 SC allowance, wait for contracts (> 60 contracts available)
4. Add new upload via SIA UI and wait

**Environment**
* Sia version: 1.3.1 official
* Sia UI version: 1.3.1 official
* OS: Windows 10

![sia-uploads-issue](https://user-images.githubusercontent.com/198256/34640502-2aa36b3c-f2f4-11e7-8dec-be0088853ab1.jpg)
[consensus.log](https://github.com/NebulousLabs/Sia/files/1608846/consensus.log)
[contractmanager.log](https://github.com/NebulousLabs/Sia/files/1608847/contractmanager.log)
[contractor.log](https://github.com/NebulousLabs/Sia/files/1608848/contractor.log)
[gateway.log](https://github.com/NebulousLabs/Sia/files/1608849/gateway.log)
[host.log](https://github.com/NebulousLabs/Sia/files/1608850/host.log)
[hostdb.log](https://github.com/NebulousLabs/Sia/files/1608851/hostdb.log)
[renter.log](https://github.com/NebulousLabs/Sia/files/1608852/renter.log)
[transactionpool.log](https://github.com/NebulousLabs/Sia/files/1608853/transactionpool.log)
[wallet.log](https://github.com/NebulousLabs/Sia/files/1608854/wallet.log)

**Comment by chrsch** [comment]
Ok it turns out sia will run perfect on a remote linux server. Uploads succeed as expected. So I think this is related to my local internet connection or to Windows.

**Comment by tbenz9** [comment]
I'm going to guess this is either related to something on your end, or insufficient Allowance.  If you have new information feel free to re-open this issue.  But as it stands right now I don't think there is any action for the devs to take so I'm closing the issue.
