### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by mhaebig** [NebulousLabs/Sia#2621]
# Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.650106503 seconds

I hoped to use Sia online storage, but my first experience is a crash.

**Environment**
* Sia version: 1.3.1
* OS: MacOS HighSierra

**Comment by tbenz9** [comment]
This issue doesn't include any errors, all the text shown is normal output for Sia.  Check out this document to find your logs, and re-open this issue if you still need help.
https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
