### ISSUE TITLE
Sia Unexpectedly crashes After starting to synchronize v1.3.1

### ISSUE THREAD

**Issue by Daz56** [NebulousLabs/Sia#2622]
# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.9570548 seconds
panic: invalid page type: 4307697279208140556: c200

goroutine 65 [running]:
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0xb0ce5)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:256 +0x413
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0x11dfa7000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x161
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0x9dfb7)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1a9
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0xc04363f0a0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x127
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0x9e080)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x164
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0xc042eafb90)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x127
github.com/NebulousLabs/bolt.(*Cursor).search(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0xc117c)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x164
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc0445484d0, 0xc044548698, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc042dabac0, 0xc044548698, 0x20, 0x20, 0xc042dabac0, 0x587b6c, 0xc044548738)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xed
github.com/NebulousLabs/Sia/modules/consensus.validSiacoins(0xc042096000, 0xc044f8f9f0, 0x1, 0x1, 0xc045207180, 0x2, 0x2, 0xf1c8d8, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:37 +0x23a
github.com/NebulousLabs/Sia/modules/consensus.validTransaction(0xc042096000, 0xc044f8f9f0, 0x1, 0x1, 0xc045207180, 0x2, 0x2, 0xf1c8d8, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/validtransaction.go:297 +0xcc
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc042096000, 0xc0420ad080, 0xc042160ad0, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:220 +0x1a0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc0420b9b80, 0xc042096000, 0xc0420ad080, 0x0, 0x0, 0x0, 0x7101000000000000, 0xbcb392f096d0cfb)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x228
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc0420b9b80, 0xc042096000, 0xc0420ad080, 0x1000000000000000, 0xab83d524bd1621cc, 0x7b03eea718760e4f, 0x22c058fb0e84e299, 0x3b92005700410f5c, 0x59a12e67, 0xc044033a80, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc0420b9b80, 0xc042096000, 0x1000000000000000, 0xab83d524bd1621cc, 0x7b03eea718760e4f, 0x22c058fb0e84e299, 0x3b92005700410f5c, 0x59a12e67, 0xc044033a80, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x10d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc042096000, 0xaf16f8, 0xc042096000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x2b0
github.com/NebulousLabs/bolt.(*DB).Update(0xc0420632c0, 0xc04230b2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420b9b80, 0xc04420c400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420b9b80, 0xdee020, 0xc0447d0fa0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc0447d0fa0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420ac9a0, 0xc04223d840, 0x13, 0xac0d00, 0xa, 0xc0421608d0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420ac9a0, 0xc04223d840, 0x13, 0xac0d00, 0xa, 0xc0421608d0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420b9b80, 0xc044549ef0, 0xc044549e98, 0xc044549ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420b9b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421444a0, 0xc0420b9b80, 0xdee820, 0xc0420ac9a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Expected Behavior**
No crashes

**How to reproduce it (as minimally and precisely as possible)**
I restarted my pc and was prompted that there was an update for SIA, after upgrading, Sia always crashes..

Load/reload Sia v1.31 and start to sync with network

* OS:
Windows 7 x64bit home premium

**Comment by tbenz9** [comment]
This can occur if Sia wasn't shut down properly or the computer went to sleep during a database operation.

Follow the instructions to delete your consensus.db file.  Note, it'll take a while to load, and a while to sync the blockchain.
https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
