### ISSUE TITLE
Not Synchronising

### ISSUE THREAD

**Issue by CryptoToni** [NebulousLabs/Sia#2625]
Not Synchronising

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.1542779 seconds

Sia Daemon v1.3.1
Loading...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Finished loading in 0.1592881 seconds 

https://www.dropbox.com/s/e83vcjyh64s0stj/Screenshot%202018-01-07%2021.05.25.png?dl=0

Syncing and fully functional

WIndows 64
Version 1.3.1

**Comment by tbenz9** [comment]
This happens when you have more than one program trying to use 127.0.0.1:9980.  Make sure you only have 1 instance of Siad running at a time.

More info: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by CryptoToni** [comment]
Thanks
