### ISSUE TITLE
[Idea] Plugin - Sia as "GNOME online accounts"

### ISSUE THREAD

**Issue by michaldev** [NebulousLabs/Sia#2627]
I have an idea for creating a plugin to support sia in gnome. Like that:
![7dl6s](https://user-images.githubusercontent.com/5132385/34664645-2ffe5be0-f45d-11e7-8b94-e5dfb01ae0da.png)

**Comment by Fornax96** [comment]
I'd love to see this as well. But this is not related to this repository. I think https://github.com/NebulousLabs/Sia-UI would be closer, but maybe it's best as a separate project. Sia-UI does no desktop integration whatsoever and it seems like the developers are not planning to add any either.

**Comment by lukechampine** [comment]
Indeed, we are happy to provide developer resources for anyone who wants to build something like this, but currently we don't have the time/energy to implement it ourselves. I suggest asking around on our Discord to see if other developers are interested.

**Comment by S-anasol** [comment]
https://github.com/pmknutsen/gnome-shell-sia

**Comment by Fornax96** [comment]
I've tried installing that one, but I don't think it works on modern gnome versions.

Gnome has a tendency of breaking their APIs every new release.
