### ISSUE TITLE
How to use node-open-mining-portal or open-ethereum-pool to build mining pool of sia?

### ISSUE THREAD

**Issue by 625001850** [NebulousLabs/Sia#2629]
How to use node-open-mining-portal or open-ethereum-pool to build mining pool of sia?

**Comment by tbenz9** [comment]
GitHub Issues are for reporting Bugs, Feature Requests, or changes to Sia Core.  For questions, help, and mining discussion please join the Sia Discord Server.

https://discord.gg/sia
