### ISSUE TITLE
Loading can take a while after upgrading to a new version

### ISSUE THREAD

**Issue by vivsur** [NebulousLabs/Sia#2632]
# BUG REPORT
I installed Sia-UI 1.3.0 on 12/2/2017 and it was taking lot of time to synchronize. Meanwhile i bought and sent siacoins to my wallet address. I was waiting for the wallet to synchronize 100% so I can see my coins. Before it was fully synchronized(last i remember, it synced up about 75%), I had to restart my machine for some reason and when I opened siacoin wallet, it keeps saying "Loading can take up a while after upgrading to new version". I have my seed words saved safely. Would installing again the newer version of sia(1.3.1) and supplying my old seed words to that, resolve this issue? Could you guys please help me out?
![sia](https://user-images.githubusercontent.com/35263342/34723769-5aa5840e-f511-11e7-8814-d0804ebf8ffa.JPG)

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment** 
* Sia version: 1.3.0
* OS: Windows 10 64-bit

**Comment by tbenz9** [comment]
Most likely letting it sit at "Loading can take a while" will fix the issue.  If it sits for 24+ hours and hasn't moved you can re-install Sia and restore your wallet using the seed.

**Comment by vivsur** [comment]
Thanks for the response. Will try that. While re-installing sia, is it okay to install the newer version(1.3.1) as opposed to the 1.3.0 version I have now?

**Comment by tbenz9** [comment]
Yes.  It's recommended

**Comment by vivsur** [comment]
I let it sit at "loading can take a while" and it finally reported this

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
goroutine 350653 [running]:
runtime/debug.Stack(0x44439e, 0x0, 0xc04b099dc8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04b099f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042002660, 0xc04b099f20, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources.func1(0xc04a1023e0, 0xc042070308)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:50 +0x4f1
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:52 +0x9a
Severe error: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\vivek\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\vivek\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
invalid argument
 
Kindly help me out
