### ISSUE TITLE
Exchange Wallets Down

### ISSUE THREAD

**Issue by dcorn24** [NebulousLabs/Sia#2633]
Can you please give us an update on when the Exchange wallets will be back up and running? I'd like to safely store my coins in a hard wallet. 

Thank you

# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
Please follow the conversation below for updates on the exchange issues.

https://www.reddit.com/r/siacoin/comments/7ld1ic/siacoin_exchange_issues_megathread/
