### ISSUE TITLE
Sia-UI Wallet won't load! Can't get to my coins

### ISSUE THREAD

**Issue by teepoe** [NebulousLabs/Sia#2643]
I pasted the message that's been on there below:

# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: UI
* OS: Macbook

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.596560937 seconds

**Comment by tbenz9** [comment]
The log you attached does not show an error, all the text you've included is expected. If you would like help the best place to ask is on the #Help channel of the Sia Discord. https://discord.gg/sia

To view your logs (and fix issues) you can check out this tutorial: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
