### ISSUE TITLE
# Bug report. Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by xfperez** [NebulousLabs/Sia#2651]
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.9461113 seconds
panic: page 439547 already freed

goroutine 19 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc042188240, 0x2c21, 0xeb4eb000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x308
github.com/NebulousLabs/bolt.(*node).spill(0xc04c21a700, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x217
github.com/NebulousLabs/bolt.(*node).spill(0xc04da10310, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*node).spill(0xc04becfe30, 0xc04bec3170, 0xc045b1ec50)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xc6
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04a7f3b00, 0xc045b1ed00, 0xd)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x4da
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc04cc46b78, 0x944c219a4, 0xefca20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x41e
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc04cc46b60, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x130
github.com/NebulousLabs/bolt.(*DB).Update(0xc04205d2c0, 0xc045b1f260, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0421b2000, 0xc044a13c00, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:301 +0x884
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0421b2000, 0xdee020, 0xc04e81b7e0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc04e81b7e0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420a6840, 0xc0421918a0, 0x13, 0xac0d00, 0xa, 0xc0421ede00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420a6840, 0xc0421918a0, 0x13, 0xac0d00, 0xa, 0xc0421ede00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0421b2000, 0xc045b1fef0, 0xc045b1fe98, 0xc045b1fea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0421b2000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421444a0, 0xc0421b2000, 0xdee820, 0xc0420a6840)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by tbenz9** [comment]
Duplicate #2413
