### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by dm123345** [NebulousLabs/Sia#2653]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.6241333 seconds
panic: bolt.DB.meta(): invalid meta pages
	panic: bolt.DB.meta(): invalid meta pages

goroutine 4 [running]:
github.com/NebulousLabs/bolt.(*DB).meta(0xc04227c000, 0xcf1)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xc9
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc0422ae1c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*DB).Update.func1(0xc0422ae1c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:595 +0x45
panic(0x9d7b80, 0xb58940)
	/usr/local/go/src/runtime/panic.go:491 +0x291
github.com/NebulousLabs/bolt.(*DB).meta(0xc04227c000, 0xcf1)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:830 +0xc9
github.com/NebulousLabs/bolt.(*Tx).rollback(0xc0422ae1c0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:255 +0x88
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc0422ae1c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:164 +0x7bf
github.com/NebulousLabs/bolt.(*DB).Update(0xc04227c000, 0xc0423852e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420cbb80, 0xc0423ae000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420cbb80, 0xdee020, 0xc042370420, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc042370420, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420be840, 0xc04220eb60, 0x12, 0xac0d00, 0xa, 0xc042159650, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420be840, 0xc04220eb60, 0x12, 0xac0d00, 0xa, 0xc042159650, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420cbb80, 0xc043ff7ef0, 0xc043ff7e98, 0xc043ff7ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420cbb80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042158490, 0xc0420cbb80, 0xdee820, 0xc0420be840)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by tbenz9** [comment]
Duplicate #2318
