### ISSUE TITLE
new idea for sia

### ISSUE THREAD

**Issue by inits** [NebulousLabs/Sia#2656]
why user storage file must pay siacoin ?  we need encourage normal user to provide there own storage  to expand the sia network ,  and the "siacoin network" pay siacoin to normal user who provide there own storage, other can upload 100gb for free to storage on sia network forever,  then the sia network will be the bigest  share platform , then siacoin will be more price ,thanks

**Comment by lukechampine** [comment]
Sia is a low-level storage interface. "100 GB of free storage" and similar tiered plans are always layered on top of low-level storage by subsidizing the free storage with paid plans. This is what Dropbox, Google, Microsoft, etc. all do. We are happy to support anyone who wants to build a similar service on top of Sia, but this is not something that we plan to add to the protocol or provide by default.
