### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by mehranbln** [NebulousLabs/Sia#2666]
# BUG REPORT

**Siad has exited unexpectedly. Please submit a bug report including the error log here.**

**Siad should open normally, but all the functions are disabled**

log:
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
listen tcp :9981: bind: address already in use

**Environment**
* Sia version: Sia Daemon v1.3.1
* OS: macOS High Sierra 10.13.2

**Comment by tbenz9** [comment]
This issue happens if you already have sia running and try to open a second instance.  Please make sure you only have one running at a time.
