### ISSUE TITLE
siad has exicted unexpectedly.  Please submit a report, including the error log.

### ISSUE THREAD

**Issue by globeswift** [NebulousLabs/Sia#2667]
# BUG REPORT

**Stack Trace or error message** Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.2341666 seconds
panic: runtime error: slice bounds out of range

goroutine 49 [running]:
github.com/NebulousLabs/Sia/modules/consensus.removeFileContract(0xc0424ee000, 0x535e5aadfb9b0f1f, 0x5f7c4277b5271e70, 0x126318b874993a6b, 0x44102aa8e749a1b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:396 +0x251
github.com/NebulousLabs/Sia/modules/consensus.commitFileContractDiff(0xc0424ee000, 0x5e5aadfb9b0f1f00, 0x7c4277b5271e7053, 0x6318b874993a6b5f, 0x102aa8e749a1b012, 0x44, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:69 +0xd7
github.com/NebulousLabs/Sia/modules/consensus.applyFileContractMaintenance(0xc0424ee000, 0xc04272a2c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:178 +0x4b7
github.com/NebulousLabs/Sia/modules/consensus.applyMaintenance(0xc0424ee000, 0xc04272a2c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/maintenance.go:192 +0x6c
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc0424ee000, 0xc04272a2c0, 0xc042270370, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:231 +0x1ef
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc0421ee000, 0xc0424ee000, 0xc04272a2c0, 0x0, 0x0, 0x0, 0xaa5c030000000000, 0x4e8d3cda4d98c67a)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x228
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc0421ee000, 0xc0424ee000, 0xc04272a2c0, 0x5d67000000000000, 0x40035d28fa6696e5, 0x349acdf5c6524e8c, 0x13fdfeab6045b384, 0x278dea7e, 0x571d1521, 0xc042031fc0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc0421ee000, 0xc0424ee000, 0x5d67000000000000, 0x40035d28fa6696e5, 0x349acdf5c6524e8c, 0x13fdfeab6045b384, 0x278dea7e, 0x571d1521, 0xc042031fc0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x10d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0424ee000, 0xaf16f8, 0xc0424ee000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x2b0
github.com/NebulousLabs/bolt.(*DB).Update(0xc0422621e0, 0xc0420572e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0421ee000, 0xc0422ce800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0421ee000, 0xdee020, 0xc04226e780, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc04226e780, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420a8840, 0xc0421ab760, 0x12, 0xac0d00, 0xa, 0xc04215c0c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420a8840, 0xc0421ab760, 0x12, 0xac0d00, 0xa, 0xc04215c0c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0421ee000, 0xc042181ef0, 0xc042181e98, 0xc042181ea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0421ee000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421444a0, 0xc0421ee000, 0xdee820, 0xc0420a8840)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: v1.3.1
* OS:windows 10

**Comment by tbenz9** [comment]
Duplicate #2644
