### ISSUE TITLE
Safe shutdown

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#267]
siad should listen for signals and handle them properly. Specifically, it should catch a `^C` and initiate a graceful shutdown. This is crucial to prevent corruption of things like the wallet file.

Speaking of which, there's another step I think we should take to protect the wallet file. When the file is saved, it should be saved to a different file, like `__wallet.new`, and then we should call `os.Rename` to overwrite the old file. We can rely on the move operation to be atomic, so if siad gets interrupted it won't corrupt the old file.

**Comment by DavidVorick** [comment]
Both sound good. Might actually want to make an alternate SecureSave helper function or something. We're going to have a lot of files that will be overwritten:

the host has state that needs to be saved
the hostdb has state that needs to be saved
wallet, of course
the peerlist needs to be saved

Each should go into it's own file. A general utility for save overwriting would be great to have.

**Comment by lukechampine** [comment]
The signal handling side of things is now implemented, so I'm renaming this issue.

**Comment by lukechampine** [comment]
Components should probably have a `Shutdown` method. Right now we have no way to, e.g., call `wallet.Save` because `Save` isn't actually part of the `Wallet` interface.
