### ISSUE TITLE
Where are my siacoins?

### ISSUE THREAD

**Issue by Pele51** [NebulousLabs/Sia#2670]
Hello, i downloaded my sicaoin wallet for win7 few weeks ago, since i can send them from bittrex to my wallet i just send my coins to my wallet and they were showing unconfirmed for 2hours in my wallet, so i closed my wallet and reopen it again, now i see i have 0 coins in my wallet, no transaction history nothing..... how is that possible i backup my wallet when i installed it but i didnt backup after i receive the coins... and when i click to backup it shows me the same seed i allready have written down, please help me guys!

**Comment by Pele51** [comment]
2018/01/19 11:14:46.355568 update.go:116: Wallet has gained a spendable siacoin output: 147334896250961f0f438c3db640a9dc15d0411cf163a0694e5291aabdb24516 :: 1.9 SC
2018/01/19 11:14:46.355568 update.go:116: Wallet has gained a spendable siacoin output: 86459903d9fce10f3f7c6e1547ee8182f71b023dfeb9c7488a4e0250059d9b7a :: 15 KS
2018/01/19 11:14:46.371168 update.go:285: A transaction has been confirmed on the blockchain: 8c2bbad7104ab6d389c1367c8fc6efe4da8e0bf759e40cd284a9ec1683ab45e2
2018/01/19 11:14:46.371168 update.go:323: 	Siacoin Output: 147334896250961f0f438c3db640a9dc15d0411cf163a0694e5291aabdb24516 :: 1.9 SC
2018/01/19 11:14:46.371168 update.go:285: A transaction has been confirmed on the blockchain: 3bf06ba7bc2b0652a2d73ece2f5b900827784597f13c5ca730d36f4bb0341ed0
2018/01/19 11:14:46.371168 update.go:323: 	Siacoin Output: 86459903d9fce10f3f7c6e1547ee8182f71b023dfeb9c7488a4e0250059d9b7a :: 15 KS

**Comment by tbenz9** [comment]
Your coins will only appear if your wallet is fully synchronized.  If it is fully synced and they are still not there.  I would recommend removing Sia, re-installing Sia, then recovering your wallet with your password and seed.

**Comment by tbenz9** [comment]
I've closed this issue because there is no action for the core developers to take.  If you still need help please ask for help on the Sia Discord: https://discord.gg/sia
