### ISSUE TITLE
weird SC outputs listed in explorer

### ISSUE THREAD

**Issue by rmcdaniel** [NebulousLabs/Sia#2671]
I keep finding weird SC outputs like this -> https://explorer.siahub.info/hash/568062673b6f2607256d3c22653dc57b9622f1aa19e21c03e3545964bf7e4d49

it should look like this -> https://explorer.siahub.info/hash/16a811b0308bbe9c64a298eba026b6d8c10b6e773f0a0dd83e66f5aa17102d48 with an input and output listed

am I just misunderstanding things or is it a bug?

**Comment by rmcdaniel** [comment]
Also, just to make it clear, this isn't a bug I'm reporting with siahub but rather the blockchain itself. I'm not convinced that these outputs should be possible according to the design but I am very new to this codebase.

These same issues happen when I try to parse the blockchain starting at block 0. It hits these `568062673b6f2607256d3c22653dc57b9622f1aa19e21c03e3545964bf7e4d49` ouput id's to be used as inputs but I can't find them anywhere. Maybe it's some kind of collision?

**Comment by tbenz9** [comment]
I'm going to close this as it was discussed in Discord chat and determined that 0SC outputs are actually allowed in contracts, and used to be allowed in any transaction.
