### ISSUE TITLE
Sia-UI will not epen 

### ISSUE THREAD

**Issue by ktmine** [NebulousLabs/Sia#2675]
1. open Sia-UI. 
2. window appears saying loading sia
3. after a bit window now says "loading can take a while after upgrading....."
4. then "siad has stopped unexpectedly" this error report comes up and it tells me to post it here. 

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.6595058 seconds

5. then click "restart Siad" button and it changes to this error message

Sia Daemon v1.3.1
Loading...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Then I quit sia and restart. the same thing happens each time.

______________________________________

when I initially started the program the ui did come up and I was able to create a wallet. As it was syncing was when I first got the error message. It was shortly after I originally opened it. it has never opened the interface since. only "loading" messages, and the error messages.

I have tried to exit sia and restart it. did not help.
I deleted the all of the app data and files and used new unzip to start fresh.  It still goes directly to the loading, then loading will take a while, then the errors I posted above.

I would like to do a fresh start, or repair this one.  I sent coins to the wallet after it initially gave me the address, then it crashed.  I have the seed to restore at least, but I need to get the UI to open.  Please help... 

**Environment**
* Sia version: 1.13
* OS: Win10. 64 bit

**Comment by tbenz9** [comment]
I'd recommend asking for help in the Sia Discord server.  https://discord.gg/sia

The error you mentioned happens when you have more than one copy of Sia running at a time, or if another program is using port 9980 on your computer.  Most likely a computer reboot would make the problem go away.  If you need to do additional troubleshooting please check out this document.
https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by ktmine** [comment]
the computer has been rebooted multiple times
