### ISSUE TITLE
Add clear error message when siad cannot bind to a port.

### ISSUE THREAD

**Issue by tbenz9** [NebulousLabs/Sia#2676]
# Feature Request
Add a clear error message if the gateway fails to start because of `address already in use`.  This would require a small amount of error parsing in the gateway module, and an additional message to the user if that particular error is found.

**For example:**
I think `bind address already in use; are you running another instance of siad?` would be clear enough.

## Background information:
tbenz9: I've seen a lot of GitHub issues and support requests come through lately with the "bind: address already in use" error.  How hard would it be to add a check into Sia that fails gracefully with a clear error message if a siad process is already running?
Nemo: In theory that shouldn't be too difficult. Just need to check for that specific error and then print a more helpful error instead of just forwarding it to the user

**Comment by Dynamikey** [comment]
Looks interesting!

**Comment by lukechampine** [comment]
For contributors looking to implement this:

Don't do this:
```go
func isAddrInUseErr(err error) bool {
	return strings.Contains(err.Error(), "address already in use")
}
```
Instead do this:
```go
func isAddrInUseErr(err error) bool {
	if opErr, ok := err.(*net.OpError); ok {
		if syscallErr, ok := opErr.Err.(*os.SyscallError); ok {
			return syscallErr.Err == syscall.EADDRINUSE
		}
	}
	return false
}
```
