### ISSUE TITLE
ERROR SIA

### ISSUE THREAD

**Issue by TecNickle** [NebulousLabs/Sia#2678]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
goroutine 1 [running]:
runtime/debug.Stack(0x446237, 0xc42011edd8, 0xc42011eda0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc42011eed0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x85
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4202860c0, 0xc42011eed0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xcc
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).createWALTmp(0xc4200a89c8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:206 +0x1fd
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).load(0xc4200a89c8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:259 +0x43
github.com/NebulousLabs/Sia/modules/host/contractmanager.newContractManager(0xdd64e0, 0xc420286080, 0xc420268340, 0x33, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:163 +0x4a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.New(0xc420268340, 0x33, 0x2, 0xc420268340, 0x33)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:226 +0x51
github.com/NebulousLabs/Sia/modules/host.newHost(0xdd6560, 0xf04bd8, 0xdd6f80, 0xc4200c7b80, 0xdd62e0, 0xc4200be9a0, 0xdd9c80, 0xc42026e2c0, 0x7ffc99effb52, 0x5, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:269 +0x47d
github.com/NebulousLabs/Sia/modules/host.New(0xdd6f80, 0xc4200c7b80, 0xdd62e0, 0xc4200be9a0, 0xdd9c80, 0xc42026e2c0, 0x7ffc99effb52, 0x5, 0xc42001a390, 0x23, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:305 +0xc2
main.(*Server).loadModules(0xc42009a4b0, 0xad8488, 0xc42009a4b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:525 +0xce9
main.startDaemon(0x0, 0x0, 0x7ffc99effb37, 0xe, 0x7ffc99effb63, 0x5, 0x7ffc99effb52, 0x5, 0x0, 0x7ffc99effba2, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1a7
main.startDaemonCmd(0xc420011200, 0xc42007c550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420011200, 0xc42000e0d0, 0x5, 0x5, 0xc420011200, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc420011200, 0xac967f, 0x3b, 0xc420099900)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc420011200, 0xee5060, 0xab23bc)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Severe error: Unable to write WAL metadata: unable to write WAL metadata: write /home/ethos/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
panic: unable to create WAL temporary file, crashing to prevent corruption

goroutine 1 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).createWALTmp(0xc4200a89c8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:207 +0x219
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).load(0xc4200a89c8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:259 +0x43
github.com/NebulousLabs/Sia/modules/host/contractmanager.newContractManager(0xdd64e0, 0xc420286080, 0xc420268340, 0x33, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:163 +0x4a5
github.com/NebulousLabs/Sia/modules/host/contractmanager.New(0xc420268340, 0x33, 0x2, 0xc420268340,

**Comment by ktmine** [comment]
what do I know, but it looks like you have run out of space on your HD.

Severe error: Unable to write WAL metadata: unable to write WAL metadata: write /home/ethos/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: no space left on device
panic: unable to create WAL temporary file, crashing to prevent corruption

Are you installing this on ethOs?

**Comment by tbenz9** [comment]
Looks like you ran out of disk space. Make sure you have enough free space for the Sia configurations.

Tracked in #2407
