### ISSUE TITLE
can't send sc, but I have total confirmed balance

### ISSUE THREAD

**Issue by AlanGuo** [NebulousLabs/Sia#2680]
![image](https://user-images.githubusercontent.com/727863/35275297-3a9aca06-007a-11e8-8843-72a9448c4ca4.png)
![image](https://user-images.githubusercontent.com/727863/35275337-5d3ffaf4-007a-11e8-9bb6-49683eac6d6f.png)

**Comment by tbenz9** [comment]
This error typically resolves itself after a few blocks.  If you're still having issues please reopen this issue.

Explanation: #2443
