### ISSUE TITLE
siad.exe Critical error: Host entry scan history not sorted.

### ISSUE THREAD

**Issue by random12345678** [NebulousLabs/Sia#2681]
Hey!

Can not start Sia-UI.
A couple days earlier I started to update it and it synced in around 70% or something like that, but I had to close it meanwhile and now I can't start it no matter what. I have seen a lot of forum posts about it and didn't find any solution. 
This is the first time I am getting a "bug report" in cmd after starting siad.exe there and it says I should open a ticked here, so here I go.

**BUG REPORT:**
_Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
goroutine 92 [running]:
runtime/debug.Stack(0x44441e, 0x0, 0xc04435a6d8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc04435a850, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xae
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc04214f280, 0xc04435a850, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe7
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc042032280, 0x0, 0x0, 0x0, 0x0, 0xc0512001c0, 0x12, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:318 +0x27f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc042032280, 0x0, 0x0, 0x0, 0x0, 0xc0512001c0, 0x12, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:374 +0x216
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x0, 0x0, 0x0, 0x0, 0xc0512001c0, 0x12, 0x0, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x73
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Modify(0xc04214f2a0, 0x0, 0x0, 0x0, 0x0, 0xc0512001c0, 0x12, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:257 +0x13d
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).updateEntry(0xc042032280, 0x0, 0x0, 0x0, 0x0, 0xc0512001c0, 0x12, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:185 +0x4b6
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).managedScanHost(0xc042032280, 0x0, 0x0, 0x0, 0x0, 0xc0512001c0, 0x12, 0x0, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:254 +0x454
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedProbeHosts(0xc042032280)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:291 +0x36c
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:173 +0x6f2
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues_

**SIA-UI Error message:**
_A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
invalid argument_

Every time I start Sia-UI I get this message and have to manually start siad.exe in cmd but it still doesn't work.

Sia version: Sia-UI-v1.3.0
OS: Win10

**Comment by tbenz9** [comment]
Please update to 1.3.1 and follow the instructions here: https://blog.sia.tech/troubleshooting-the-recent-hardfork-ca77e0b17f0f
