### ISSUE TITLE
Can not unlock the wallet with the correct password after stopping with error

### ISSUE THREAD

**Issue by reincarnated** [NebulousLabs/Sia#2683]
# BUG REPORT
1. It took 2 days to sync to 100% and I had changed the default password from the seed to my own and noted down.
2. After syncing, it showed the balance that was transferred.
3. After that I stopped the daemon but it gave an error and got stuck.
4. Had to stop the windows process "electron"
5. Started the Sia-UI.exe again and it showed syncing 95.4% again.
6. It prompted for the password when I clicked wallet but when I entered the CORRECT PASSWORD it said "error when calling /wallet/unlock: provided encryption key is incorrect" for "Wallet Locked" screen.

**Stack Trace or error message**

Siad has exited unexpectedly. Please submit a bug report including the error log here.

Error Log:
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.9193964000000001 seconds

After showing the above, no response to clicks on the menu on the left side.

**Expected Behavior**
When I entered the password correctly, should unlock and show my balances.

**How to reproduce it (as minimally and precisely as possible)**
Follow the steps illustrated above.

**Environment**
* Sia version: Sia-UI-v1.3.1
* OS: Windows 10 Pro 64 bit
core i3/8GB

**Comment by mauro6592** [comment]
I am having the same issue, have u been able to fix it?

**Comment by reincarnated** [comment]
Unfortunately not. I have given up trying to unlock it.

Now I am going to restore the wallet using the seed in two other computers but waiting for the synchronization to complete before I attempt anything. It has already been 1 day and only synced 25%!

The problem is that in the computer where the wallet is locked, even if I create a fresh copy from a new download to a different folder and try to open, it gives the same errors :(

Will let you know how it goes.

**Comment by S-anasol** [comment]
Firstly, 
> It has already been 1 day and only synced 25%!
https://consensus.siahub.info/

Secondly,
you cant just remove wallet(and probably transactionpool) folder from sia data folder and re-init again from your old seed.
Then in about 20-30 minutes(with ssd) it will be ready.

**Comment by reincarnated** [comment]
Hi Alex,

Thanks for the reply.

Now it is 29% something for over 2 days on a 100 mbps connection. Normally
a few GBs can be downloaded in minutes. Guess your the servers for the db
are overloaded?

You mean "..CAN just remove wallet..."? I don't have the folders you
mentioned about?

What I have is as below:
C:\Wallets\Sia-UI-v1.3.1
  -locales
  -resources
    -app
      -assets
      -css
      -dist
      -js
      -plugins
      -Sia
        -doc

Would be great if can restore the wallet without wasting time again to sync
the whole thing.

Thanks!

**Comment by S-anasol** [comment]
https://siawiki.tech/client/transferring_the_client_to_a_different_computer?s[]=data&s[]=folder

**Comment by tbenz9** [comment]
Thanks to everyone for your help and reports.  If you're still having trouble accessing your Siacoin I highly recommend you join the Sia Discord #help channel.  You'll get live help from people who have a lot of Sia experience.  Support staff does not monitor the GitHub issues.

As for your initial bug report: Most likely the password change was unsuccessful or you have a typo in the new password.  Have you tried your old password?
Some relevant issues around this topic: 
#2447 
#2587 
#2646 

We try to keep support requests out of GitHub.  I'm going to close this issue as there is no action for the Sia devs to take (as it's written right now), please direct support requests to Discord or support@sia.tech.  If you think this is prematurely closed feel free to open it again and comment why you think that.

**Comment by reincarnated** [comment]
Hi,

I only changed the password from the default password which is the same as
the seed to my own password.

I doubt copy paste will have any typos :)

I am still having the same issue and can not even sync other wallets for
over 4 days to try to restore wallet from the seed.

**Comment by ggoldenb** [comment]
same issue :-(

**Comment by radegeddon** [comment]
same issue :-(
Not working, even with the env. var. set, siad.exe reports Auto-unlock failed.
