### ISSUE TITLE
Feature Request: Send Transaction with Arbitraty Data Api Endpoint

### ISSUE THREAD

**Issue by geo-gs** [NebulousLabs/Sia#2686]
As titled; I'd like to be able to leverage the API to send transactions with arbitrary data in the following way:

```
// Number of hastings being sent. A hasting is the smallest unit in Sia. There
// are 10^24 hastings in a siacoin.
amount      // hastings

// Address that is receiving the coins.
destination // address

// data should be a Base64 representation of a byte[]. First 6 bytes must decode to 'NonSia'
// note: is optional
arbitrarydata // data

// JSON array of outputs. The structure of each output is:
// {"unlockhash": "<destination>", "value": "<amount>", "arbitrarydata":"<data>"}
outputs
```

**Comment by lukechampine** [comment]
hmm. Can I ask what the intended use is? If you want to use arbitrarydata purely to get certain data on the blockchain, the `/wallet/siacoins` endpoint isn't a great fit, because you don't really need to be sending coins to anyone in order to get arbitrarydata into a transaction; you just need to pay the transaction fee.

**Comment by geo-gs** [comment]
@lukechampine 
I'm writing a program called [sawwit](https://github.com/geo-gs/sawwit) which is basically a way for people to communicate with each other on top of a block-chain.

The use case is that I want people to use small amounts of sia coins when interacting with the program to:
* Bring in revenue
* Prevent spam and self-voting
* Allow users to profit-share

Specifically, I could really use this endpoint in my code here: https://github.com/geo-gs/sawwit/blob/master/src/main/java/com/sawwit/siad/WalletHelper.java#L50

Additionally, NghtRppr (Discord handle) already wrote a patch that looks functional: https://gist.github.com/rmcdaniel/acddb741377f408165806069e64aa7c4

**Comment by DavidVorick** [comment]
I'm going to reject this idea. Communicating on top of a blockchain is very wasteful of the resources of everyone on the network. And while there's nothing in the official protocol that we can do to stop you, I would really ask that you don't do it. The Sia blockchain is already bloated enough, if storage transactions have to start competing in a fee market with chat apps, it might start to cost $5 or $10 just to get started on Sia.

**Comment by DavidVorick** [comment]
*wrong button, will leave open for discussion

**Comment by tbenz9** [comment]
I agree with DavidVorick, I think this is an interesting idea, but doesn't fit in with the goal and purpose of Sia itself.  Storing this type of data on the blockchain is going to cause issues long term and unneeded growth of the blockchain itself.

**Comment by geo-gs** [comment]
That is understandable but disappointing. Is there some limit to the amount of arbitrary data attached to a transaction that you would feel comfortable with? For instance, what if the arbitrary data was limited to 300 bytes?

If there is no limit that you feel comfortable with then I think the [arbitrary-data-usage](https://github.com/NebulousLabs/Sia/blob/b3ef0cc99d070ba4ce3aa357f793c64b59d01336/doc/Standard.md#arbitrary-data-usage) documentation could use a large revision. In its current form it implies that it is acceptable to use arbitrary data to build third party protocol rules with the only restrictions being that the arbitrary data be prefixed with `NonSia` and that the transaction fees be paid. Note that this was also the general consensus that I received from the developer Discord channels when enquiring about arbitrary data usage so I'm guessing that there are many people that are under this same assumption.

**Comment by lukechampine** [comment]
Regardless of how much arbitrary data you use, the end result is that you're using space on the Sia blockchain for a purpose that isn't aligned with the goals of the system.
Currently, `siad` stores hosts announcements in the arbitrary data. This is an example of usage that is aligned with the goals of the system.

As David said, we can't stop you from doing it, but we don't want to encourage it either. So I'm okay with it being a little difficult. We may use the arbitrary data for other purposes in the future, but I doubt we'll ever expose it via the API.
