### ISSUE TITLE
Siad has exited unexpectedly - Wallet Not Syncing 

### ISSUE THREAD

**Issue by bhouse03** [NebulousLabs/Sia#2687]
# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.1047462 seconds
**Expected Behavior**
I'm unable to start the Daemon as it keeps exiting. When I click Start Siad, it starts up and then Exits with the following error message "Siad has exited unexpectedly. Please submit a bug report including the error log here."
**How to reproduce it (as minimally and precisely as possible)**

**Environment** Desktop Wallet Windows 10
* Sia version: 1.2.1
* OS: Windows 64 bit

**Comment by tbenz9** [comment]
Please use the instructions below to attach your error message (the text you included is all normal) and reopen this issue when you have the additional information.

https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by bhouse03** [comment]
Thanks! I'll take a look and let you know if I need additional help.
