### ISSUE TITLE
HTTP Accept Error

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#269]
After running siad for a while, it started logging the following error about once a second:
`http: Accept error: accept tcp 127.0.0.1:9980: too many open files`
Cause is unknown, but it's likely due to connection that isn't being closed. If it happens again I'll try to identify who is opening so many files.

**Comment by DavidVorick** [comment]
is this an os.Open problem or a conn.Open problem?

A linter might be able to help with this

**Comment by lukechampine** [comment]
I've examined all the `net.Dial`s and `http.Get`s and I don't think it's any of them. That just leaves `os.Open`

**Comment by DavidVorick** [comment]
is this still a problem?

**Comment by lukechampine** [comment]
I haven't reproduced it with the new frontend, so I'll close this for now.
