### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by spacemanjim** [NebulousLabs/Sia#2690]
# BUG REPORT
Siad has exited unexpectedly.

**Stack Trace or error message**
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.9813214000000001 seconds

**Expected Behavior**
restart siad

**How to reproduce it (as minimally and precisely as possible)**
I used stop command and sync will not restart after.  Clicking "Start Siad" will result in a red synchronizing indicator 9/10 times, and a yellow 1/10, but even when yellow, no synchronization progress.  stalled at 94.4%

**Environment**
* Sia version: 1.3.1
* OS: Windows 10 64 bit

**Comment by tbenz9** [comment]
Please use the instructions below to attach your error message (the text you included is all normal) and reopen this issue when you have the additional information.

https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by spacemanjim** [comment]
Thanks for links to troubleshooting.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
