### ISSUE TITLE
when run new version but have old version installed

### ISSUE THREAD

**Issue by hooshbanmodir** [NebulousLabs/Sia#2698]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
goroutine 1 [running]:
runtime/debug.Stack(0x446dde, 0x0, 0xc042062a00)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Critical(0xc042062b48, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x9a
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc04216af00, 0xc042062b48, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xd3
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commitStorageFolderExtension(0xc0421b6548, 0x2e8000008a3b)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/storagefoldergrow.go:92 +0xe8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commitChange(0xc0421b6548, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:175 +0x192
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).recoverWAL(0xc0421b6548, 0xdedde0, 0xc04215e100, 0x1, 0x180)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:236 +0x200
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).load(0xc0421b6548, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:286 +0x799
github.com/NebulousLabs/Sia/modules/host/contractmanager.newContractManager(0xdee2a0, 0xc04216aec0, 0xc0421b33c0, 0x3c, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:163 +0x4ac
github.com/NebulousLabs/Sia/modules/host/contractmanager.New(0xc0421b33c0, 0x3c, 0x2, 0xc0421b33c0, 0x3c)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/contractmanager.go:226 +0x58
github.com/NebulousLabs/Sia/modules/host.newHost(0xdee320, 0xf1c8d8, 0xdeed40, 0xc042192000, 0xdee0a0, 0xc04223e000, 0xdf1940, 0xc04223e160, 0xc04200c2cc, 0x5, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:269 +0x484
github.com/NebulousLabs/Sia/modules/host.New(0xdeed40, 0xc042192000, 0xdee0a0, 0xc04223e000, 0xdf1940, 0xc04223e160, 0xc04200c2cc, 0x5, 0xc042228120, 0x2c, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/host.go:305 +0xc9
main.(*Server).loadModules(0xc04208a4b0, 0xaf1aa0, 0xc04208a4b0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/server.go:525 +0xcf0
main.startDaemon(0x0, 0x0, 0xc04200c28b, 0xe, 0xc04200e12b, 0x5, 0xc04200c2cc, 0x5, 0x0, 0xc04200e16a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:164 +0x1ae
main.startDaemonCmd(0xc0420b8d80, 0xc04208e410, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:209 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0420b8d80, 0xc04206c010, 0x5, 0x7, 0xc0420b8d80, 0xc04206c010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0420b8d80, 0xae2c79, 0x3b, 0xc042049ae0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x315
github.com/spf13/cobra.(*Command).Execute(0xc0420b8d80, 0xefcd80, 0xacaf03)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x32
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x797
Critical error: ERROR: storage folder extension provided for storage folder that does not exist

**Comment by hooshbanmodir** [comment]
please email me

**Comment by sososoapy** [comment]
I' having the same issue.  sorry, didn't mean to make a duplicate thread. We posted about the same time.

**Comment by tbenz9** [comment]
I don't quite understand what you are trying to do.  If you have installed a new version of Sia you cannot go back to an older version.  We recommend you always run the latest version of Sia.

I have not seen this particular error before, can you tell me what version of Sia you are using and provide steps to reproduce the error?

**Comment by tbenz9** [comment]
Closing due to no response from reporter.  Please re-open if you continue to need help.
