### ISSUE TITLE
Issues trying to update

### ISSUE THREAD

**Issue by sososoapy** [NebulousLabs/Sia#2699]
Hi,
I was running sia UI v1.2.0 win32 x64 for a long time with no issues. Recently I tried to send some siacoins to another wallet but the transaction never confirmed. So I decided to upgrade to the latest version. I downloaded and installed sia UI v1.3.1 win32 x64.  But now the UI won't load. The message I get is, "a critical error loading sia has occurred. Said unexpectedly exited. Error log: sia daemon v1.3.1
Loading...
(0/6)loading said...
(1/6) loading gateway...
(2/6) loading consensus...
Difficulty adjustment hardfork incompatibility dectected."

What am I doing wrong?

# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by stanley98745** [comment]
I have the same problem!!!!

**Comment by tbenz9** [comment]
When updating Sia you typically cannot skip releases.  Each release has code to upgrade the previous release, when you try to jump from 1.2.0 to 1.3.1 it cannot handle such a large release jump.  We recommend you always run the latest version of Sia.

Steps to fix that error can be found here: https://blog.sia.tech/troubleshooting-the-recent-hardfork-ca77e0b17f0f
