### ISSUE TITLE
Understanding merkle_root calculation

### ISSUE THREAD

**Issue by ocminer** [NebulousLabs/Sia#2700]
I'm having a hard time getting merkle_root calculation to work, despite having the information from siamining's stratum page, it's missing some bits.

Here'a a valid (private testnet) block:

000000eda4d0a08911b8a402c63fff9732294dd246c512b82d0b6287c8684740361f0000000000004b086d5a0000000001000000000000000d0000000000000003c95115b416737929f500000075a9abfbb906572eb4af355ee1021e348314f26c98c525602c220bed309acb11010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000020000000000000004e6f6e5369610000000000000000000037b284cf7309b11894faa53b938895a30000000000000000

Chopping this block into pieces:

Prevhash: 000000eda4d0a08911b8a402c63fff9732294dd246c512b82d0b6287c8684740

Nonce: 361f000000000000

Ntime: 4b086d5a00000000

Minerpayout: 01000000000000000d0000000000000003c95115b416737929f500000075a9abfbb906572eb4af355ee1021e348314f26c98c525602c220bed309acb11

No idea what this is: 0100000000000000

The so called "arbitrary" transaction: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000020000000000000004e6f6e5369610000000000000000000037b284cf7309b11894faa53b938895a30000000000000000

According to my information, i'd hash the arbitrary transaction using blake2b and adding a null byte in front which gives me the arbtx_hash hex of 5130943a55d9ca19c274e3bf6a77f48a50fe5853a15cb8b306b196dae25c267f

Now comes the question:
What now ? I do simply hash the Minerpayout which is stated above and use the resulting hash for hashing again using blake2b like this:

"01" + hash_of_minerpayout + arbtx_hash_hex  

This doesn't seem to be right, as my blocks on testnet are rejected.

I'd appreciate some info on this

**Comment by S-anasol** [comment]
https://github.com/darval/Sia/compare/NebulousLabs:master...master
check this mining pool code.

As far as i understand it fully working, at least on ant farm(testnet).

**Comment by tbenz9** [comment]
If you're still looking for help I'd recommend joining the Sia Discord server.  The GitHub issues are generally meant for Bug reports and feature requests.

**Comment by ocminer** [comment]
I tried already but nobody replied.. who will be the one I'd talking to ?

**Comment by tbenz9** [comment]
@nemo#4926 will definitely be able to answer your question but he can be hard to reach sometimes.  You might try @darval#2130 who wrote the code that S-anasol linked above.
