### ISSUE TITLE
Clean up lint errors

### ISSUE THREAD

**Issue by tbenz9** [NebulousLabs/Sia#2702]
If anyone is looking to contribute, some easy, beginner level tasks would involve adding more packages (one at a time please) to our $lintpkgs in our Makefile and cleaning up all of the linting errors
That's a good way to learn go if you aren't familiar, and it's something that would benefit the project.

Makefile: https://github.com/NebulousLabs/Sia/blob/master/Makefile

**Comment by tbenz9** [comment]
Great work @mharkus & @mikkeljuhl!! 
Looks like these are all that are left:
- ./modules/host/contractmanager
- ./modules/miner
- ./node/api
- ./sync
- ./types

It'd be awesome to finish this up before 1.3.2 drops.

**Comment by tbenz9** [comment]
@mikkeljuhl thanks!  v1.3.2 is arriving this week, think you could get the last 2 packages Lint'ed in the next day or two?

**Comment by mharkus** [comment]
Sorry missed the message 4 days ago. Will try to to wrap it up tonight if @mikkeljuhl isn't working on it yet.

**Comment by mikkeljuhl** [comment]
@mharkus good job, didn't see this until now!

**Comment by mharkus** [comment]
I guess we can close this issue now that the last remaining lint-cleanup tasked has been merged. 
#2786
