### ISSUE TITLE
error running Sia-UI-v1.3.1-win32-x64

### ISSUE THREAD

**Issue by hooshbanmodir** [NebulousLabs/Sia#2711]
# BUG REPORT
Siad unexpectedly exited. Error log: Sia Daemon v1.3.1
storage folder extension provided for storage folder that does not exist
**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:Sia-UI-v1.3.1-win32-x64
* OS:

**Comment by tbenz9** [comment]
Duplicate of your previous issue #2698 Please do not open multiple issues with the same error.
