### ISSUE TITLE
Wallet transactions incorrect height?

### ISSUE THREAD

**Issue by uclnj** [NebulousLabs/Sia#2714]
# BUG REPORT

./siac wallet transactions output shows:

`126157   779ad383b1f9a74ae3c85cc677bda0a67f9086bbcd7ffff721030948a3a4f762        9000.90`
`127168   eb58df2d5a8f562d611e06c43d3b00b321c37c9d7826dbe2721f611df3838bdc       25099.90`

yet Sia Explorer shows eb58df2d5[..] belonging to a different block height of [127178](https://explore.sia.tech/hashes/eb58df2d5a8f562d611e06c43d3b00b321c37c9d7826dbe2721f611df3838bdc) and 779ad383[...] belongs to [126167](https://explore.sia.tech/hashes/779ad383b1f9a74ae3c85cc677bda0a67f9086bbcd7ffff721030948a3a4f762) yet mine shows 126157.

It seems all transactions in my list have a height ten less than what Sia Explorer is showing.

**Comment by ChrisSchinnerl** [comment]
What version of Sia-UI are you running? What's the current blockheight of your node?

**Comment by uclnj** [comment]
Yeap, forgot to post all of that.  It's Sia Client v1.3.1, Sia Daemon v1.3.1 on an Ubuntu 17 host.  Current height 139935.  This is a full node/host with an up-time of around 4 months.

**Comment by ChrisSchinnerl** [comment]
This might be related to an issue we have seen a few months ago where the wallet would go out of sync with the consensus set and show a different height for some long running nodes. I think there is no fix in 1.3.1 for that, but you can probably rescan the wallet as a workaround for now.

**Comment by uclnj** [comment]
Is there a process to init-seed on a host?  My wallet shows 2011 addresses and after backing it up and trying to reseed I get a 

```
Seed:
Could not initialize wallet from seed: error when calling /wallet/init/seed: wallet is already encrypted, cannot encrypt again
```

**Comment by ChrisSchinnerl** [comment]
You can do `siac wallet init-seed --force`. That overwrites the existing wallet.

**Comment by uclnj** [comment]
init finished in a few minutes, unlock is taking 2+ hours.  is this from the sheer number of addresses this host has created?

**Comment by uclnj** [comment]
init did the trick - all heights now match what Sia Explorer shows.

**Comment by ChrisSchinnerl** [comment]
The wallet won't start rescanning the blockchain until you unlock it. That's why unlocking takes longer.
