### ISSUE TITLE
Lost my wallet due to computer shut off

### ISSUE THREAD

**Issue by hadi77h** [NebulousLabs/Sia#2716]
The computer shut off while the account was syncing, and now when I try to get in my wallet, it says error. How do I recover my wallet?

**Comment by DavidVorick** [comment]
What error does it report?

**Comment by hadi77h** [comment]
Enviado desde mi iPhone

**Comment by tbenz9** [comment]
This issue doesn't include any errors or logs. Check out this document to find your logs, and re-open this issue if you still need help.
https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
