### ISSUE TITLE
Feature Request: Process to test host for storage access.

### ISSUE THREAD

**Issue by uclnj** [NebulousLabs/Sia#2718]
Sia Client/Daemon 1.3.1 on Ubuntu 17 server, NFS storage on Synology.

I sporadically get these messages in the contractmanager.log

`2018/02/01 19:11:53.585622 sectorupdate.go:394: ERROR: Unable to add sector: not enough storage remaining to accept sector`

The mount point is accessible and transfers data throughout the day.  There should be a tool that would allow the host to "test" access to the siahostdata.dat file and verify connectivity from the hosts end, something akin to nfswatch.  Having the ability to trigger an alert if the storage suddenly goes away would be a huge help.

**Comment by DavidVorick** [comment]
That means the remote host doesn't have enough space remaining. It's a normal enough message, and doesn't affect the reliability of your files - they are redundant enough to tolerate occasional errors from the host.

**Comment by uclnj** [comment]
I am the host.  host -v shows 1.5TB out of 8TB available.  nfswatch showed a stream of reads/writes and lsof shows activity to the host file but I still see these messages in the event log.

**Comment by tbenz9** [comment]
I think this is a reasonable request, but unlikely to be built directly into Sia.  To use your example, nfswatch is not built into the nfs server but rather, is its own utility, in much the same way, Sia is probably not going to add this type of monitoring into its core product.

I'm going to close this issue as I don't think the devs are interested in implementing it as described.  If you can provide a clear reproducer of a bug or feel this was unjustly closed please re-open the issue and say why.

**Comment by tbenz9** [comment]
I'll just add, that I am in favor of adding additional testing and support tools around Sia.  If you want to discuss what these might look like I'd recommend starting a conversation on Discord, I'd certainly be interested in discussing it there.
