### ISSUE TITLE
Feature request: Allow the gateway to connect to resolvable addresses instead of ip-addresses only

### ISSUE THREAD

**Issue by robvanmieghem** [NebulousLabs/Sia#2720]
This would also make docker test setups easier.

**Comment by DavidVorick** [comment]
The reason that we only allow IP addresses when connecting to the gateway is that IP addresses are much more difficult to come by, and increase the difficulty of eclipse attacks.

I guess it's not an issue if we allow the user to issue an outbound command to connect to a node via a dns name, I'm not sure how difficult that would be to code. But we definitely can't accept inbound requests unless they are ip addresses.
