### ISSUE TITLE
An issue about totalSuppl

### ISSUE THREAD

**Issue by lehuyit275** [NebulousLabs/Sia#2726]
A problem that I think you need to pay attention and update the fixes immediately.
I do not know if you really understand me. I will present it in the most detailed way I can. Hope you will understand my mind.

This problem is in the total supply of a token.

When a token is generated, it will have a TotalSupply. Based on TotalSupply, the investor will decide what to invest in at a reasonable price. Nothing if totalSupply does not change. But now, many fraudsters take advantage of everyone's trust, generating a much larger amount than TotalSupply to sell.

I do not know the reason why you allow this to happen. But it's not fair. It only benefits scammers. Consequently, a lot of people lose their money.

I think you need to fix it, you should create a trigger to bind it. Do not allow to create a greater number of tokens than totalSupply. Or at least before allowing totalSupply change it needs to be temporarily locked out in a timely manner so that investors have time to review.

I hope you know what I mean and fix it soon.

**Comment by Fornax96** [comment]
I'm not sure what you're trying to accomplish. 

You can view the coinbase calculation here: https://github.com/NebulousLabs/Sia/blob/9cc9cc78f25b4f36df35548a870d5b0c7f9f9cfc/types/block.go#L54
InitialCoinbase is 300000 SC as defined here: https://github.com/NebulousLabs/Sia/blob/561a85d9cde1772ab3b84dae76c13e19c1809ed3/types/constants.go#L28 MinimumCoinbase is defined in the same file on line 203.

The coin generation rules have been known from the beginning, it was mentioned in the bitcointalk announcement, and pretty much any cryptocurrency tracker has this information. I don't see how this is relevant to people losing money.

**Comment by lehuyit275** [comment]
Sorry. I'm talking about ETH tokens. I have mistakenly commented on the project. so sorry. Please allow it to be closed
