### ISSUE TITLE
My password isnt working Ive been using the same on for a long time and now I cant even use my seed to recover my funds?

### ISSUE THREAD

**Issue by Altcoinbroker** [NebulousLabs/Sia#2727]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
I highly recommend you ask for help on the Sia Discord.  Without more information there is no action the devs can take on this issue.  If you have an error message or log feel free to attach it to this issue and reopen the ticket.

Make sure you don't have any extra spaces before/after/in-between the words.  Ensure your seed has the correct number of words, and they are spelled correctly.

You can try following these instruction to re-install Sia and then recover your wallet: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
