### ISSUE TITLE
Question/Feature Request: bandwidth throttling

### ISSUE THREAD

**Issue by dhensen** [NebulousLabs/Sia#2728]
Last week I noticed `siad` occupy all of my upload bandwidth multiple times per hour. I only have 2.2GB in use on my host. And that has been so since august 2017. What generates this large amount of upload? I am talking about 50GB over the course of 2 days. 

Is anybody else running into this issue? How do you handle it? I don't just want to pull the plug, but my internet connection is now useless for me and my family.

(Data usage is 99% traffic that goes over port 9981).

Is there bandwidth throttling in siad behind some obscure flag? Can it be implemented? Please shed some light on this.

**Environment**
* Sia version: 
```
$ siad version  
Sia Daemon v1.3.1
```
* OS:
```
$ uname -a
Linux my_host_name_was_here 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
```

**Comment by hackneyb** [comment]
I solved the same problem by using a bandwidth throttling / optimization software so that it does not use the entire pipe.  This would be an advanced, but great feature to add in for home users who lack hardware features to control bandwidth utilization.

**Comment by dhensen** [comment]
@hackneyb nice solution! An hour after I posted I found `trickle`. I currently modified my systemd to use trickle in standalone. I will monitor my bandwidth this week and report back and post how to set this up.

**Comment by dhensen** [comment]
I can already report back this soon because I was just staring at `bmon` and I see that block of data pumpin' and I see the `siad` cpu usage rising, the same pattern I have been observing for the last days.

I have used trickle, a userspace bandwidth shaping tool, in standalone mode like this:
```
[Unit]
Description=Sia Daemon

[Service]
User=sia
Group=sia
ExecStart=/usr/bin/trickle -s -d 1000 -u 1000 /usr/local/bin/siad
WorkingDirectory=/path/to/my/siad/working/dir
Restart=always
EnvironmentFile=/path/to/my/siad/environment/file

[Install]
WantedBy=multi-user.target
Alias=siad.service
```

On arch linux installing `trickle` is as simple as running `pacman -S trickle`.

Then my bandwidth usage stays within the bounds I defined:
![2018-02-04-211614_1500x509_scrot](https://user-images.githubusercontent.com/2786295/35781934-b333e1d0-09f0-11e8-9fc4-1fe26b4460f8.png)

On the image you can see the graph in the upper right corner in red color: upload capped at 1000 KB/s
Htop shows siad is currently one of the most cpu intensive programs (my computer was pretty much idling apart from running chromium.) 

I'm very happy. With this I can continue being a sia host for now... Only thing I need to fix now is the fact that since august my occupied space has not increased by even 1 MB.... feels like a bug.

**Comment by dhensen** [comment]
Previous message was incorrect. I've just noticed siad using my full upload bandwidth again.

I've read that trickle does not work if the process forks... going to read the siad source code to see if it forks.

@hackneyb what traffic shaping software do you use?

**Comment by dhensen** [comment]
Trickle also does not work with statically linked libraries. I've checked this repo for `CGO_ENABLED=0` and could not find it. Can anybody confirm that `siad` is not statically linked?

**Comment by lukechampine** [comment]
@dhensen Go binaries are statically linked. Cgo was used in versions of Go <=1.5 for DNS resolution, but not anymore (at least on Unix).

**Comment by hackneyb** [comment]
I used cFosSpeed .. I don't know if there is a Linux version.  On Windows here

**Comment by tbenz9** [comment]
A bandwidth limiter/throttling for Sia is tracked in #1554.
