### ISSUE TITLE
siad does not work right in IPv4 IPv6 dual stack 

### ISSUE THREAD

**Issue by Teesla** [NebulousLabs/Sia#2735]
# BUG REPORT
On the Linux where there is IPv6 support `siad` does not bind to `0.0.0.0:9981` and `0.0.0.0:9982` when run with default settings.
```
tesla@AMS64:~$ netstat -tupnl | grep siad
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:9980          0.0.0.0:*               LISTEN      1955/./siad
tcp6       0      0 :::9982                 :::*                    LISTEN      1955/./siad
tcp6       0      0 :::9981                 :::*                    LISTEN      1955/./siad
```

`siac gateway` shows only an IPv6 address 

As a result incoming connections over IPv4 are not accepted even if port is forwarded.

**Expected Behavior**
`siad` should accept incoming connections both on IPv4 and IPv6 addresses.

**How to reproduce it (as minimally and precisely as possible)**
Run `siad` with default setting on IPv6 enabled Linux

**Environment**
* Sia version:
```
tesla@AMS64:~/Sia$ ./siac version
Sia Client v1.3.1
Sia Daemon v1.3.1
```
* OS:
```
tesla@AMS64:~/Sia$ uname -a
Linux AMS64 4.9.23-std-1 #1 SMP Mon Apr 24 13:18:14 UTC 2017 aarch64 GNU/Linux
tesla@AMS64:~/Sia$ cat /etc/issue
Debian GNU/Linux buster/sid \n \l
```

**Comment by ChrisSchinnerl** [comment]
@Teesla have you tried connecting to it? Works fine on my server. 
I think golang uses ipv4-mapped-ipv6 if the protocol is not specified explicitly.  which is only shown by netstat as `tcp6` even though the port is reachable via ipv4.

**Comment by Teesla** [comment]
Okay, I have tried connecting to it with `telnet` and it worked. The problem now is that IPv4 is not advertised to peers so even after a full day I do not get any incoming connections over IPv4:
```
tesla@AMS64:~/Sia$ netstat -tupn | grep siad
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 10.9.163.143:43802      91.121.86.100:9981      ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:48526      173.178.176.128:9981    ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:56602      85.27.163.135:9981      ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:44660      91.231.94.22:9981       ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:34328      86.12.187.141:9981      ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:54092      45.56.21.129:9981       ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:56814      73.50.51.48:9981        ESTABLISHED 1955/./siad         
tcp        0      0 10.9.163.143:51612      188.244.40.69:9997      ESTABLISHED 1955/./siad         
tcp6       0      0 2001:bc8:4700:2500:9981 2601:642:4100:433:33922 ESTABLISHED 1955/./siad   
```
As a consequence the node is not helping the network.

**Comment by Teesla** [comment]
Additional info:
```
tesla@AMS64:~/Sia$ ./siac gateway
Address: [2001:bc8:4700:2500::238f]:9981
Active peers: 9
```

**Comment by Bojak4616** [comment]
@Teesla Have you tried re announcing with your ipv4 address?

**Comment by Teesla** [comment]
@Bojak4616 
If I do `./siad --rpc-addr 51.15.85.168:9981 --host-addr 51.15.85.168:9982` the `siac gateway` still reports IPv6 only, `siad` does listen on the specified IPv4 addr buy I do not get incoming IPv4 connections after about 20 minutes (being fully synced)

If I pass it two times `./siad --rpc-addr 51.15.85.168:9981 --host-addr 51.15.85.168:9982 --rpc-addr [2001:bc8:4700:2500::238f]:9981 --host-addr [2001:bc8:4700:2500::238f]:9982` the `siac gateway` still reports IPv6 only, does not listen on IPv4 but IPv6 only (first one is ignored?). I still do not get incoming connection over IPv4.

The other way around `./siad --rpc-addr [2001:bc8:4700:2500::238f]:9981 --host-addr [2001:bc8:4700:2500::238f]:9982 --rpc-addr 51.15.85.168:9981 --host-addr 51.15.85.168:9982` the `siac gateway` reports IPv6 only, `siad` does not listen on it. No incoming connections after about 10 minutes.

**Comment by ChrisSchinnerl** [comment]
@Teesla thanks for reporting this. I think I found an issue in the code that might lead to that behavior. I opened a [PR](https://github.com/NebulousLabs/Sia/pull/2739) for that.

**Comment by lukechampine** [comment]
This was auto-closed by the merge of #2739, but I'd like more assurance that the bug was actually fixed. @Teesla, can you build from master and confirm that the behavior is correct?

**Comment by Teesla** [comment]
@lukechampine I'v rebuilt from master and ran with default settings. `siac gateway` still reports IPv6 only. `siad` listens on both IPv4 and IPv6 and i can confirm that with `telnet` but I do not get incoming IPv4 connections after an hour or so.

**Comment by Teesla** [comment]
Still no incoming connections neither on IPv4 or IPv6 after 10 more hours.

**Comment by ChrisSchinnerl** [comment]
@lukechampine even after building the master branch @Teesla won't notice a difference. The fix causes the receiving end (the peer that you are connecting to) to store your IPv4 address instead of your IPv6 address. This causes your IPv4 address to be propagated through the network by other peers.
That means that the peers Teesla is connecting to would need to upgrade.

**Comment by tbenz9** [comment]
I'm going to close this. With the release of Sia v1.3.2 the fix is being rolled out and there is no additional work the devs need to take at this time.
