### ISSUE TITLE
Make Travis Build Fail if code is not go fmt'd

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#274]

**Comment by DavidVorick** [comment]
I don't know how we'd approach making this happen

**Comment by lukechampine** [comment]
Well, `go fmt` outputs a list of files it changed, so we can run `go fmt` during the `install` key and check for output. I think this should do it:
```bash
install:
    $(exit $(go fmt ./... | wc -l))
    make dependencies
    make # is this necessary?
```
