### ISSUE TITLE
Critical error on loading wallet - Host entry scan history not sorted.

### ISSUE THREAD

**Issue by MichelSakr** [NebulousLabs/Sia#2742]
# BUG REPORT

**Stack Trace or error message**
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc423f18418)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc454d5cd60, 0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc464631a40, 0x0, 0x0, 0x0, 0x0, 0xc45f201da0, 0x13, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:318 +0x278
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc464631a40, 0x0, 0x0, 0x0, 0x0, 0xc45f201da0, 0x13, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:374 +0x20f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x0, 0x0, 0x0, 0x0, 0xc45f201da0, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x6c
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Insert(0xc454d5cd80, 0x0, 0x0, 0x0, 0x0, 0xc45f201da0, 0x13, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:214 +0xdd
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).load(0xc464631a40, 0xc46462c4b0, 0xc46462a9c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:69 +0x28b
github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0x19e83c0, 0x1b0c470, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:111 +0x44a
github.com/NebulousLabs/Sia/modules/renter/hostdb.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0xc464623000, 0x3f, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:69 +0xb4
github.com/NebulousLabs/Sia/modules/renter.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0x19ed080, 0xc43fd3edc0, 0x19e99a0, 0xc42008a840, 0xc464623000, 0x3f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:168 +0x81
main.startDaemon(0x0, 0x0, 0x7ffeefbffc84, 0xe, 0x7ffeefbffcb0, 0x5, 0x7ffeefbffc9f, 0x5, 0x0, 0x7ffeefbffd09, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:266 +0xcb5
main.startDaemonCmd(0xc420093200, 0xc42006b310, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420093200, 0xc42006c070, 0x5, 0x5, 0xc420093200, 0xc42006c070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420093200, 0x16fce88, 0x3b, 0xc420160960)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420093200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc423f18418)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc454d5cd60, 0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc464631a40, 0x0, 0x0, 0x0, 0x0, 0xc444be0700, 0x12, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:318 +0x278
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc464631a40, 0x0, 0x0, 0x0, 0x0, 0xc444be0700, 0x12, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:374 +0x20f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x0, 0x0, 0x0, 0x0, 0xc444be0700, 0x12, 0x0, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x6c
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Insert(0xc454d5cd80, 0x0, 0x0, 0x0, 0x0, 0xc444be0700, 0x12, 0x0, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:214 +0xdd
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).load(0xc464631a40, 0xc46462c4b0, 0xc46462a9c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:69 +0x28b
github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0x19e83c0, 0x1b0c470, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:111 +0x44a
github.com/NebulousLabs/Sia/modules/renter/hostdb.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0xc464623000, 0x3f, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:69 +0xb4
github.com/NebulousLabs/Sia/modules/renter.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0x19ed080, 0xc43fd3edc0, 0x19e99a0, 0xc42008a840, 0xc464623000, 0x3f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:168 +0x81
main.startDaemon(0x0, 0x0, 0x7ffeefbffc84, 0xe, 0x7ffeefbffcb0, 0x5, 0x7ffeefbffc9f, 0x5, 0x0, 0x7ffeefbffd09, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:266 +0xcb5
main.startDaemonCmd(0xc420093200, 0xc42006b310, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420093200, 0xc42006c070, 0x5, 0x5, 0xc420093200, 0xc42006c070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420093200, 0x16fce88, 0x3b, 0xc420160960)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420093200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc423f18418)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc454d5cd60, 0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc464631a40, 0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:318 +0x278
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc464631a40, 0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:374 +0x20f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, 0xb4a94564ed7a6317, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x6c
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Insert(0xc454d5cd80, 0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:214 +0xdd
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).load(0xc464631a40, 0xc46462c4b0, 0xc46462a9c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:69 +0x28b
github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0x19e83c0, 0x1b0c470, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:111 +0x44a
github.com/NebulousLabs/Sia/modules/renter/hostdb.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0xc464623000, 0x3f, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:69 +0xb4
github.com/NebulousLabs/Sia/modules/renter.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0x19ed080, 0xc43fd3edc0, 0x19e99a0, 0xc42008a840, 0xc464623000, 0x3f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:168 +0x81
main.startDaemon(0x0, 0x0, 0x7ffeefbffc84, 0xe, 0x7ffeefbffcb0, 0x5, 0x7ffeefbffc9f, 0x5, 0x0, 0x7ffeefbffd09, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:266 +0xcb5
main.startDaemonCmd(0xc420093200, 0xc42006b310, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420093200, 0xc42006c070, 0x5, 0x5, 0xc420093200, 0xc42006c070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420093200, 0x16fce88, 0x3b, 0xc420160960)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420093200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 1 [running]:
runtime/debug.Stack(0x1043947, 0x0, 0xc423f18418)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0xa7
github.com/NebulousLabs/Sia/persist.(*Logger).Critical(0xc454d5cd60, 0xc423f18590, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:37 +0xe0
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).uptimeAdjustments(0xc464631a40, 0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:318 +0x278
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).calculateHostWeight(0xc464631a40, 0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostweight.go:374 +0x20f
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).(github.com/NebulousLabs/Sia/modules/renter/hostdb.calculateHostWeight)-fm(0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, 0xb4a94564ed7a6317, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:107 +0x6c
github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree.(*HostTree).Insert(0xc454d5cd80, 0x1, 0x1100000, 0xbd00, 0x1100000, 0xc44849e220, 0x13, 0x280000000, 0x400000, 0x280000000, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hosttree/hosttree.go:214 +0xdd
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).load(0xc464631a40, 0xc46462c4b0, 0xc46462a9c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/persist.go:69 +0x28b
github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0x19e83c0, 0x1b0c470, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:111 +0x44a
github.com/NebulousLabs/Sia/modules/renter/hostdb.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0xc464623000, 0x3f, 0xc464623000, 0x3f, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:69 +0xb4
github.com/NebulousLabs/Sia/modules/renter.New(0x19e9ba0, 0xc42008ac60, 0x19ea7c0, 0xc420151b80, 0x19ed080, 0xc43fd3edc0, 0x19e99a0, 0xc42008a840, 0xc464623000, 0x3f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/renter.go:168 +0x81
main.startDaemon(0x0, 0x0, 0x7ffeefbffc84, 0xe, 0x7ffeefbffcb0, 0x5, 0x7ffeefbffc9f, 0x5, 0x0, 0x7ffeefbffd09, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:266 +0xcb5
main.startDaemonCmd(0xc420093200, 0xc42006b310, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162
github.com/spf13/cobra.(*Command).execute(0xc420093200, 0xc42006c070, 0x5, 0x5, 0xc420093200, 0xc42006c070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0xc420093200, 0x16fce88, 0x3b, 0xc420160960)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc420093200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa
Critical error: Host entry scan history not sorted.
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
incompatible version
**Expected Behavior**
Wallet needs to load
**How to reproduce it (as minimally and precisely as possible)**
Loading wallet produces this error
**Environment**
* Sia version: 1.3.0 and 1.3.1
* OS: OSX 10.13.3

**Comment by tbenz9** [comment]
Duplicate #1799

**Comment by MichelSakr** [comment]
Deleted Consensus DB and transactionpool.db and still I get an error
