### ISSUE TITLE
Feature request: Wallet project recommendations

### ISSUE THREAD

**Issue by MichelSakr** [NebulousLabs/Sia#2750]
Hi

I like the Sia project and with Asic mining the project adoption and coin is falling behind, primarily it is due to its wallet.
It is becoming really difficult to store Sia or transact with the coins, It is clear that the wallet is a part of the project, however market trends and dynamics will drive the project adoption in parallel, and the more you make the wallet and sia accessible for Hodlers and traders who are a large driving force in projects adoption, you will onboard more supporters and users to the main cause, you might want to make the below part of your strategic plan, especially if you want corporate adoption, the layers and processes need to be clear and separate as much as applications need to be resilient:

- Separate the wallet from the SIA-UI  and hosting node and make it lightweight, i.e to connect to the BC node instead of being part of one / downloading it, this one will make the wallet accessible to hodlers and traders and with the scale as said will add to your core users.
- Reach and Agree with hardware wallet vendors to incorporate Sia, after all the you are in the top 50 in market cap, Ledger supports more than 40 coins and you should be supported.
- Work with 3rd party to endorse a wallet creation.
- Project awareness, with market being crowded with similar projects, being the first in the market helps and you should set a team to market and promote Sia further.

The above mid 2 points will offload you from the wallet issues and let focus on the core apps..

My 2 cents..

**Comment by tbenz9** [comment]
Thanks for the input.  The devs have addressed all points you mention in previous reddit and Discord posts.  They are well aware of Sia's limits and are working towards many of the goals you mentioned.
