### ISSUE TITLE
lost my wallet please help ASAP

### ISSUE THREAD

**Issue by ggoldenb** [NebulousLabs/Sia#2752]
Hi , I did restart of my laptop , now the wallet is lock , i'm sure i didn't enter any password for lock it 
please let me know how to unlock it

# BUG REPORT

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
listen tcp :9981: bind: address already in use

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
This means that more than 1 instance of Sia is running.  If you stop all Sia instances, and only start 1 you should be able to log in and access your coins.

**Comment by ggoldenb** [comment]
Hi Thomas
after i restarted a laptop the wallet is lock and ask me a password but i didn’t put any password when i created it
what can i do ?
