### ISSUE TITLE
Unconfirmed balance not showing

### ISSUE THREAD

**Issue by Piewo74** [NebulousLabs/Sia#2754]
# BUG REPORT
Hello, I firstly stopped to mine due to another cause on the miners during circa 2 weeks. I then changed my email adress because I thought it would maybe change something and can't see nothing as unconfirmed balance. Only my past balance.

**Stack Trace or error message**

No error mesage

**Expected Behavior**

To see the pool mining some uncofirmed balance

**How to reproduce it (as minimally and precisely as possible)**

Get a key via nanoppol to mine SIA
Mine 205 SIA
Wait for one weeks without mining
Re connect your Wallet on the pool
Nothing happen and hasrate cuurent is 1032

**Environment** : I don't know what you need as information for this item.

* Sia version: SIA v1.3.1

* OS: Windows 7 64 bit

Thanks for your time and answer and have a good day,*

Pierre

**Comment by tbenz9** [comment]
Double check that Sia has the correct pool information.  This sounds like an issue with nanopool and not Sia.  You might try opening an support ticket with them.  You may also be able to get more support in the Sia Discord server.

I'm going to close this issue as there is not action the Sia devs need to take.  If you think it was prematurely closed feel free to reopen it and mention why.
