### ISSUE TITLE
Problem with SIA-UI on Mac OS 10.10.5

### ISSUE THREAD

**Issue by ocochar** [NebulousLabs/Sia#2766]
I am experiencing problems to finish the 1st sync with SIA-UI on Mac OS 10.10.5.

The first launch of SIA-UI synced ok until 93.4% and exited with similar error. I restarted several times and got the same crash again and again so I decided to report it here.

Thanks for your help

-- OC

# BUG REPORT

Siad has exited unexpectedly. Sync status at 93.4% it is my first sync on this system never reached the full sync status.

ERROR LOG :

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.644765049 seconds
panic: page 102213 already freed

goroutine 67 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0x421f246f0, 0x3e5, 0x867aded000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x301
github.com/NebulousLabs/bolt.(*node).spill(0x421d3c700, 0x429650f80, 0x19ef040)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x210
github.com/NebulousLabs/bolt.(*node).spill(0x421d3c690, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbf
github.com/NebulousLabs/bolt.(*node).spill(0x421d3c620, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbf
github.com/NebulousLabs/bolt.(*node).spill(0x421cb67e0, 0x421f24390, 0x421c5ea18)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xbf
github.com/NebulousLabs/bolt.(*Bucket).spill(0x421e5a3c0, 0x421c5eb00, 0x15)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x4d3
github.com/NebulousLabs/bolt.(*Bucket).spill(0x421c6c0f8, 0x1bf30ad30a, 0x1b00c40)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x417
github.com/NebulousLabs/bolt.(*Tx).Commit(0x421c6c0e0, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x129
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0x421cd8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:54 +0x47
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0x421cd8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:44 +0xb6
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:132 +0x3a7

**Expected Behavior**
Finish 1st sync so I can load my wallet

**How to reproduce it (as minimally and precisely as possible)**
Just launching the SIA-UI application will run for 2 minutes and crash

**Environment**
* Sia version: V1.3.1 (Capricorn)
* OS: Mac OS 10.10.5 Yosemite

**Comment by ocochar** [comment]
Moving it to SIA-UI

**Comment by tbenz9** [comment]
Duplicate of #2413  

The devs are aware of this and working on a fix this week.  Steps for workaround: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
