### ISSUE TITLE
Cheating bug when Sia runs in virtual machine hosting free disk space can set to any level without having the physical hard drive space

### ISSUE THREAD

**Issue by jensamberg** [NebulousLabs/Sia#2773]
# BUG REPORT

I found maybe a cheating bug. When Sia is running on a qnap virtual machine you can set host space for example to 100 TB  and on Sia hub 100 TB is presented and score goes up.
But in reality the virtual disk image is only so big how big is the actual disk space consumption.

**Stack Trace or error message**

**Expected Behavior**
I think it shall only be possible to host space what really physical is present. But mybe 
in virtual machines it is not possible. I dont know. When it is not possible it is easy to cheat as a hoster
with free space which not exist 

**How to reproduce it (as minimally and precisely as possible)**
Install Sia in a virtual machine on a qnap nas drive.
Hist 100 TB without having the physical drive space. Now you are able to hist 100 TB and also SiaHub tells you hist 100 TB but the virtual disk image is only so big hiw much data is realy used.

**Environment**

Qnap TVS 463 with virtual station 3 

* Sia version:
1.3.1

* OS:
Ubuntu 16.04 in the virtual station on the qnap drive

**Comment by lukechampine** [comment]
It has always been possible for hosts to lie about how much storage they have. Renters should not assume that the storage reported by hosts is accurate. Unfortunately there is little we can do about this unless someone develops an efficient "proof of capacity." In the meantime, the security model is not affected.
