### ISSUE TITLE
Quit Unexpectedly 

### ISSUE THREAD

**Issue by Amybabyyyyyy** [NebulousLabs/Sia#2795]
# BUG REPORT

Sia Daemon v1.3.1
Loading...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

to finish synchronizing/updating

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
Make sure you only have 1 instance of Sia running at a time.

See: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
