### ISSUE TITLE
Get submodule/subtree working with Sia-UI

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia#280]
The Sia-UI repo has history and is ready to go, but is not yet linked to the main Sia repo.

Git subtrees seem to be a good approach, although I'd like to defer this to the great git grand maester @lukechampine

**Comment by lukechampine** [comment]
I actually just had a thought... instead of Sia importing Sia-UI, why not the other way around?

After all, it makes sense for Sia to just be library. It might even simplify the design, because the `sia` package could then live in the top-level. No more `NebulousLabs/Sia/sia`.

**Comment by seveibar** [comment]
Hmmm, that does make a lot of sense. Because the UI is basically going to be a desktop application, all the startup/shutdown logic will actually be in it instead of Sia.

I think that's probably the best approach at this point.

**Comment by DavidVorick** [comment]
I'm with Luke we were being silly before

**Comment by seveibar** [comment]
I think some structural changes might be helpful then, if Sia is a library that the UI calls then should it really be the style/web folder within Sia?

Maybe siad could take an optional parameter to the style/web folder?

**Comment by seveibar** [comment]
Actually, it's not necessary for Sia to host the files anymore- it would all be done through atom-shell/node-webkit. So siad could just handle the API and not worry about the style folder

**Comment by DavidVorick** [comment]
Sounds good to me, I don't think golang is really a great tool for serving pages anyway.
