### ISSUE TITLE
API REQUEST - get total calculated fee for transaction before sending

### ISSUE THREAD

**Issue by subseven** [NebulousLabs/Sia#2800]
# FEATURE REQUEST

I would like to have an api endpoint where I am able to pass the amount to send, and the target address, and to get the response with the calculated total fee. At the moment I can only get per api the min and the max fee (per kb). But there is no simple solution to fetch the total est. fee. building this on my own would have the disadvantages, that it would take a lot of code to build it to calculate it, and when you make changes in your maths, that persons like me (or whoever does it similar), has to recognize the change, and has to rewrite then the function accordingly to the new math.

So it would be much easier, if you were able to implement an API endpoint which returns the accumulated total fee. Because I think you already have all functions / methods in your core, that it would be just some few lines of new code to make this available.

**Comment by lukechampine** [comment]
Calculating the fee is pretty simple, and we don't want to increase the "surface" of our API if we can avoid it. The fee calculation is simply `maxFee * 750`, where `maxFee` is the `maximum` field returned by the `/tpool/fee` call.

We can revisit this if the fee calculation changes.

**Comment by subseven** [comment]
You are sure we are talking about the same thing ?

the max fee comes from the tpool/fee call, thats clear. And your 750 (whereever this value comes from) is the the maximum, not depending on how many kb the transfer has ?

Lets say I send 1SC , I have not more than maxfee + 750 ?

Similar as I want to send 1 mio SC ?


I am not sure, but I think you are talking about the fee per kb ? And not about the total calculated fee

**Comment by lukechampine** [comment]
Yes, fee per kb. The fee is always the same, regardless of the number of coins you're sending; 750 bytes is the estimated size of the encoded transaction.
The relevant code is here: https://github.com/NebulousLabs/Sia/blob/master/modules/wallet/money.go#L101
