### ISSUE TITLE
Web socket support

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia#281]
Web sockets will allow for pushing notifications to the client, which is a lot nicer than the client constantly polling for updates.

Support will also need to be added in the UI NebulousLabs/Sia-UI#1

**Comment by seveibar** [comment]
There also needs to be some kind of signaling, where if something that happens that changes the balance it's able to propagate to the daemon so it can send an update to any client.

**Comment by DavidVorick** [comment]
changes the balance?

**Comment by seveibar** [comment]
Basically any event that happens e.g. incoming siacoin (that's what I was talking about), a miner shutting off etc. needs to be pushed by the daemon- unless we want to continue using polling but over a Websocket instead of with GET/POST requests.

It might be a good place to start by having polling over the Websocket and worrying about the signaling later.

**Comment by DavidVorick** [comment]
we can worry about this more when the time comes.
