### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by fuadukak** [NebulousLabs/Sia#2811]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**
Siad has exited unexpectedly.

**How to reproduce it (as minimally and precisely as possible)**
Panic: invalid page type: 0:0

**Environment**
* Sia version: 1.3.1
* OS: ethOS 1.2.7

**Comment by tbenz9** [comment]
Duplicate of #2247
