### ISSUE TITLE
Not Synchronizing on 1.3.1 MacOS - Need a permanent fix

### ISSUE THREAD

**Issue by MichelSakr** [NebulousLabs/Sia#2817]
Guys, the stuck synchronization workaround by downloading the latest consensus db (10GB+)  is not a solution for the wallet, a root cause analysis is required and permanent fix issued.. the wallet is the Store front of the Sia project and it should be properly addressed in terms of quality :( otherwise the perception of the whole project will be linked to it.

# BUG REPORT

**Stack Trace or error message**
None
**Expected Behavior**
SIA-UI should synchronize by downloading the latest blockchain data, currently it gets stuck on a block then it displays synchronized, while the block is lower than the last mined one.
The only workaround is to delete the BC consensus db file and download a new one or let it synchronize anew .. which takes 5 to 48 hours depending on internet connection and client hardware.
**How to reproduce it (as minimally and precisely as possible)**
Random on various OSs
**Environment**
MAC OS high sierra 10.13.3
* Sia version:
1.3.1
* OS:
MAC OS high sierra 10.13.3

**Comment by tbenz9** [comment]
The root cause analysis has been completed and a permanent fix implemented in version 1.3.2.  The workaround was never meant to be a permanent fix.  If you're frustrated with the initial sync time, you can bootstrap the sync.

**Comment by MichelSakr** [comment]
Thanks, we'll wait for the 1.3.2 release then
