### ISSUE TITLE
CatchUp fails

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#283]
CatchUp seems to have some base failure rate, so the more times you call it, the greater the chance of failure. It also seems that once you stop catching up, no further attempts to catch up will succeed. This becomes a serious problem when the blockchain grows larger than a few thousand blocks.

**Comment by lukechampine** [comment]
`CatchUp` calls itself in a loop, but it recurses before the state has finished processing all the blocks from the previous `CatchUp`. This causes `knownBlocks` to reflect an outdated view of the state, and consequently, `SendBlocks` will send blocks that the receiver has already received, but hasn't yet processed.

This explains why I was seeing so many `KnownBlockErr`s, but I'm not sure that it explains why `CatchUp` is failing.

**Comment by lukechampine** [comment]
okay, I think I've traced it. The code is freezing during `AcceptBlock`. This would indicate a deadlock somewhere in the state. A deadlock would explain why subsequent calls to `CatchUp` failed as well.

**Comment by DavidVorick** [comment]
I imagine it will. I think the problem originated from ConsensusSubscribe()
