### ISSUE TITLE
Feature Request: Allow password to be chosen at wallet creation

### ISSUE THREAD

**Issue by pyskell** [NebulousLabs/Sia#2834]
Just as the title says, simple and sweet.

**Comment by lukechampine** [comment]
This should already be possible with `siac wallet init -p`

**Comment by pyskell** [comment]
Sorry, I intended this for Sia-UI

**Comment by tbenz9** [comment]
Please open this issue in Sia-UI.  There is no way for us to transfer the issue over, and it is not relevant in this repo as Luke mentioned.
