### ISSUE TITLE
Feature Request: Not enough contracts to upload should specify the minimum # of 12 contracts

### ISSUE THREAD

**Issue by pyskell** [NebulousLabs/Sia#2838]
Same for the UI, it should say "10/12 contracts minimum" here or something to that effect. Maybe a status bar.

![image](https://user-images.githubusercontent.com/9665963/37180434-f6ebb9b0-22f6-11e8-8a97-2163c6f624ad.png)

**Comment by tbenz9** [comment]
I'm going to close this as duplicate since you opened a more relevant issue in Sia-UI repo.
