### ISSUE TITLE
Contractor attempts to renew contracts when there is zero wallet balance

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2847]
# BUG REPORT

**How to reproduce it (as minimally and precisely as possible)**

1. Set renter allowance
1. Exhaust full amount of renter allowance on renter spending

**Expected Behavior**

Contractor does not attempt to renew contracts when allowance has insufficient funds.

**Actual Behavior**

Contractor never stops attempting to renew contracts, filling the `contractor.log` with repetitive log warnings like the following:

```
2018/03/11 16:31:25.062784 contracts.go:479: WARN: failed to renew contract 2a49afa77dd37e59e5ab1c8c22de307e7eef517ed36d4b9218af842ea058abed: insufficient balance
```

**Environment**
* Sia version: 1.3.1
* OS: Win10 x64

Logs: https://gist.github.com/mtlynch/7726468eca7ffef0ff6ac9370b05024e

**Comment by DavidVorick** [comment]
I don't think this is a bug. If you don't have enough money to renew your contracts, your data is at risk. It should be filling your log with messages and if possible giving you some bright flashy warnings in the ui or cli.

**Comment by MSevey** [comment]
I agree that there should be some sort of warning to the user in the UI that warns when contractrs are over spending and the renter is running out of funds.  We can close this issue and submit a feature request for the UI.
