### ISSUE TITLE
Renter uploads files with >3x redundancy

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2848]
# BUG REPORT

**How to reproduce it (as minimally and precisely as possible)**

1. Set 5000 SC renter allowance
1. Upload ~48,000 1-byte files

**Expected Behavior**

`/renter/files` shows that uploaded files have redundancy of ~3.0x

**Actual Behavior**

`/renter/files` shows that uploaded files have the following redundancy:

* Mean: 5.2x
* Median: 5.3x
* Min: 3.0x
* Max: 11.3x

![image](https://user-images.githubusercontent.com/7783288/37257050-faa11092-2539-11e8-996b-77ad36f8c2ca.png)

* [As Spreadsheet](https://docs.google.com/spreadsheets/d/1-Qe2OfwouFSMTo6nDrSnPOT9SjBgXnZl1m4zlknZfdk/edit?usp=sharing)
* [Logs](https://gist.github.com/mtlynch/db57294cc66c235ad9fc791796200abb)

**Environment**
* Sia version: 1.3.1
* OS: Win10

**Comment by tbenz9** [comment]
Possibly a duplicate or related to #2813

**Comment by mtlynch** [comment]
Thanks, merged it with that one.
