### ISSUE TITLE
siac wallet init-seed fails on Win10

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2849]
# BUG REPORT

**How to reproduce it (as minimally and precisely as possible)**

1. Open Windows Command Prompt
1. Type `siac wallet init-seed`

**Expected Behavior**

siac prompts user for wallet seed passphrase

**Actual Behavior**

siac fails with `The handle is invalid.` before the user can type a seed in:

```
c:\Sia-v1.3.1-windows-amd64>siac wallet init-seed
Seed:
Reading seed failed: The handle is invalid.
```

**Workaround**

Creating a wallet via Sia-UI works.

**Environment**
* Sia version: 1.3.1
* OS: Win10

**Comment by tbenz9** [comment]
I think this is a duplicate of #2587.  Have you tried this with a version newer than 1.3.1?

**Comment by mtlynch** [comment]
Yep looks like a dupe. I haven't tried with any of the 1.3.2 release candidates.
