### ISSUE TITLE
siad will crash when upload more then 64 files by siac

### ISSUE THREAD

**Issue by princ1** [NebulousLabs/Sia#2850]
# BUG REPORT

**Stack Trace or error message**
fatal error: runtime: out of memory
**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
1. create one file in 1mb;
    dd if=/dev/zero of=./1m.txt bs=1M count=1
2. siac to upload this file 64 times at the same time
   siac renter upload ./1m.txt 1m_001.txt
   ......
   siac renter upload ./1m.txt 1m_0063.txt
3. a few hours later, siad will crash.
    please refer to attached logs
[siad.txt](https://github.com/NebulousLabs/Sia/files/1801186/siad.txt)

**Environment**
ubuntu 16.04
mem: 4g
* Sia version:1.3.2
* OS: ubuntu 16.04

**Comment by tbenz9** [comment]
Sia does not handle small files very well, each of your 1MB files is being padded to 40MB before being uploaded.  I would think Sia should be able to handle more than 64 files at 1MB but Sia is also fairly RAM intensive.  With only 4GB of RAM it looks like you're running out of usable memory.  

I'm going to close this issue for a couple reasons.  
1: You've run out of RAM, unless you can demonstrate a memory leak there is no action for the Sia devs to take.

2: The devs are very aware that Sia performs suboptimally with files smaller than 40MB.  Smaller file support is on the feature roadmap, and the devs are actively working on improving this limitation.
