### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by NUEH7hdOSA** [NebulousLabs/Sia#2851]
# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 20.9186399 seconds

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
Launch sia ui

**Environment**
* Sia version:v1.3.1
* OS:Windows10

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
