### ISSUE TITLE
Feature Request: Ability for hosts without contracts to have intentional downtime without uptimeAdjustments penalty

### ISSUE THREAD

**Issue by davidlcassidy** [NebulousLabs/Sia#2853]
There may be good reasons why a good host may need to intentionally go offline for an extended period of time (ie. moving). If the hosts stops allowing new contracts and allows their current contracts to finish, then being offline has no effect on the network, right? Is so, their scores shouldn't reflect that.

This should be a really easy fix. I think in scan.go before line 350, add a check to skip lines 350-355 if the host has no contracts and no longer allowing new contracts. Probably also want to adjust the hostCheckupQuantity to reduce the frequency that the host is scanned.

https://github.com/NebulousLabs/Sia/blob/2ef11d0737b12878f9ae5f7399a325513d548531/modules/renter/hostdb/scan.go#L348-L355

**Comment by lukechampine** [comment]
>skip lines 350-355 if the host has no contracts

Do you mean *any* contracts, or contracts formed with the local renter? Both are possible, but the former would require more work. Actually, I think both would take a fair amount of work. Currently, the hostdb doesn't store any information about how many contracts a host has.

**Comment by davidlcassidy** [comment]
Yeah, the renter would have to check if the host has any contracts, not just the local ones. So it's a bit more complicated because hostdb would also have to be modified.

**Comment by davidlcassidy** [comment]
Yeah, the renter would have to check if the host has any contracts, not just local ones. So it's a bit more complicated than I initially though because hostdb would also have to be modified like you said.

If someone were to get deployed or join the Peace Corps, I imagine with the current setup that this extended offline time would cripple the host's score. Maybe there may be another solution, like make host's ScanHistory forgiving and drop scans after a year. Or maybe provide hosts the ability to announce as a new host, reseting their FirstSeen to the current block height and clearing their ScanHistory entirely.

**Comment by lukechampine** [comment]
>provide hosts the ability to announce as a new host, reseting their FirstSeen to the current block height and clearing their ScanHistory entirely.

Yes, that's the approach I'd recommend, and it's doable now -- just delete your `host` folder, and the next time you start `siad` you'll get a new keypair and thus a new identity.

I'm going to close this for now because I'm not convinced that it's a good thing to do. Our incentive structure has always basically been: "hosts should be incentivized to provide maximum quality of service (including uptime) at minimal cost." This feels at odds with that. Thanks for your input though -- it's always good to have people thinking about these problems.
