### ISSUE TITLE
API /renter/upload/*siapath [POST] Returned: 301 Moved Permanently

### ISSUE THREAD

**Issue by princ1** [NebulousLabs/Sia#2857]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**
curl -i -A "Sia-Agent" -X POST localhost:9980/renter/upload//apps/sia_up_down_files/1k_1.txt
HTTP/1.1 301 Moved Permanently
Location: /renter/upload/apps/sia_up_down_files/1k_1.txt

it works fine using siac command:
siac renter upload /apps/sia_up_down_files/1k.txt 1k.txt
**Environment**
* Sia version:1.3.2
* OS: macOS

**Comment by mtlynch** [comment]
I think it's due to the double forward slash. Sia paths can't start with a slash or path traversal characters.

```bash
curl -i -A "Sia-Agent" -X POST localhost:9980/renter/upload//apps/sia_up_down_files/1k_1.txt
                                                           ^^
```

**Comment by tbenz9** [comment]
I don't use the API much, is there a way to upload a file with an absolute path?

**Comment by mtlynch** [comment]
>I don't use the API much, is there a way to upload a file with an absolute path?

Yeah, the source file (i.e. the file on your filesystem) can have an absolute path. It's just that the siapath (the name of the file represented within Sia) can't start with a slash or path traversal characters. The path in the URL is the siapath. The source path is passed as a POST parameter.

https://github.com/NebulousLabs/Sia/blob/master/doc/api/Renter.md#path-parameters-4

**Comment by tbenz9** [comment]
Thanks, makes sense.
