### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by SIAX1** [NebulousLabs/Sia#2862]
Can you help me with that issue?

Sia Daemon v1.3.1
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 7.9994575999999995 seconds
panic: runtime error: index out of range

goroutine 30 [running]:
github.com/NebulousLabs/bolt.(*leafPageElement).key(...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/page.go:120
github.com/NebulousLabs/bolt.(*Cursor).nsearch.func2(0x6431, 0xc04516f600)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:334 +0xb2
sort.Search(0x6ade, 0xc045349dc0, 0xc045349df8)
	/usr/local/go/src/sort/search.go:66 +0x5f
github.com/NebulousLabs/bolt.(*Cursor).nsearch(0xc04534a388, 0xc0465cab20, 0x20, 0x20)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:333 +0x109
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0x4b680)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:263 +0x1e9
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0xc046d7a850)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x127
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0x6d674)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x164
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0xc0433c77a0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x127
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0x6f854)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x164
github.com/NebulousLabs/bolt.(*Cursor).searchNode(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0xc0433c6700)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:291 +0x127
github.com/NebulousLabs/bolt.(*Cursor).search(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0xb0abe)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:268 +0x164
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc04534a388, 0xc0465cab20, 0x20, 0x20, 0x0, 0x0, 0xc0465f6300, 0x99, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb8
github.com/NebulousLabs/bolt.(*Bucket).Put(0xc0445970c0, 0xc0465cab20, 0x20, 0x20, 0xc0465f4648, 0x34, 0x40, 0x0, 0xf1c8d8)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:300 +0x141
github.com/NebulousLabs/Sia/modules/consensus.addSiacoinOutput(0xc0454702a0, 0xf831d2361d08fe98, 0x29540664ea5ab654, 0xe325df2ec33a5a53, 0xb4c730a40e7a418f, 0x0, 0xc043b4ed20, 0x2, 0x6, 0xf19f6c60149d693a, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:314 +0x14b
github.com/NebulousLabs/Sia/modules/consensus.commitSiacoinOutputDiff(0xc0454702a0, 0x31d2361d08fe9801, 0x540664ea5ab654f8, 0x25df2ec33a5a5329, 0xc730a40e7a418fe3, 0xb4, 0x0, 0xc043b4ed20, 0x2, 0x6, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:58 +0x8a
github.com/NebulousLabs/Sia/modules/consensus.applySiacoinOutputs(0xc0454702a0, 0xc0420c18c0, 0xc04516f680, 0x1, 0x1, 0xc04592a000, 0x32, 0x32, 0xf1c8d8, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/applytransaction.go:45 +0xa8
github.com/NebulousLabs/Sia/modules/consensus.applyTransaction(0xc0454702a0, 0xc0420c18c0, 0xc04516f680, 0x1, 0x1, 0xc04592a000, 0x32, 0x32, 0xf1c8d8, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/applytransaction.go:208 +0xc0
github.com/NebulousLabs/Sia/modules/consensus.generateAndApplyDiff(0xc0454702a0, 0xc0420c18c0, 0xc0421726f0, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/diffs.go:224 +0xdc
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).applyUntilBlock(0xc0420cdb80, 0xc0454702a0, 0xc0420c18c0, 0x0, 0x0, 0x0, 0xde01000000000000, 0x61874f2927df7fc5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:84 +0x228
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).forkBlockchain(0xc0420cdb80, 0xc0454702a0, 0xc0420c18c0, 0x2200000000000000, 0x4f4e0b2be8fec1f9, 0x776f0d788934eb8c, 0x9edb152a31574228, 0xdb1100c5034c11f5, 0x5977af08, 0xc042c58d00, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/fork.go:111 +0xb3
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).addBlockToTree(0xc0420cdb80, 0xc0454702a0, 0x2200000000000000, 0x4f4e0b2be8fec1f9, 0x776f0d788934eb8c, 0x9edb152a31574228, 0xdb1100c5034c11f5, 0x5977af08, 0xc042c58d00, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:164 +0x10d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks.func1(0xc0454702a0, 0xaf16f8, 0xc0454702a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:262 +0x2b0
github.com/NebulousLabs/bolt.(*DB).Update(0xc04206b2c0, 0xc043e4d2e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:603 +0xa1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420cdb80, 0xc0423a2400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:245 +0x4f9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420cdb80, 0xdee020, 0xc044354a00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdee020, 0xc044354a00, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420c0b00, 0xc0421fa9a0, 0x1b, 0xac0d00, 0xa, 0xc042172fc0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420c0b00, 0xc0421fa9a0, 0x1b, 0xac0d00, 0xa, 0xc042172fc0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420cdb80, 0xc04534bef0, 0xc04534be98, 0xc04534bea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420cdb80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04215c480, 0xc0420cdb80, 0xdee820, 0xc0420c0b00)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by Bojak4616** [comment]
v1.3.2 was just released. Try upgrading and see if the issue persists.

**Comment by tbenz9** [comment]
I think this is actually an issue with the consensus.db.  If upgrading doesn't fix your problem try deleting your consensus.db file and resyncing the blockchain on the new version.

Instructions: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by tbenz9** [comment]
Looking a little closer at the error, a simple sia restart may fix it.  Please report back if you were able to fix your problem and what the workaround was.

**Comment by SIAX1** [comment]
I have installed the new version and startet from scratch. Thanks for your support.
