### ISSUE TITLE
Bug: contractmanager.json wiped?

### ISSUE THREAD

**Issue by misternils** [NebulousLabs/Sia#2883]
# BUG REPORT

**Stack Trace or error message**
My storage folders  _IN SIA_ were removed. 

contractmanager.json no longer was connecting my data to my HDDs, All the data is still on the HDDs

**Expected Behavior**
For it to still be there.

**How to reproduce it (as minimally and precisely as possible)**
Possibly happened after a restart, not sure. 

**Environment**
GUI

* Sia version:
1.3.1

* OS:
Windows 7

____

Is there no way to reconnect my HDD which still has all the data from contracts that are still intact?  Lost thousands of SIA because of this bug.

**Comment by tbenz9** [comment]
A 12GB log file is certainly not normal.  I rotate my logs (via logrotate on Linux), but I've never had my logs get close to that size.  What is in there?

Side note:  here's my section from my logrotate script.
```
tbenz9@spartan1:~/go/src/github.com/NebulousLabs/Sia$ cat /etc/logrotate.d/sia                                                                                
/home/tbenz9/Documents/Sia/consensus/consensus.log {
        size 10M
        copytruncate
        create 660 tbenz9 tbenz9
        rotate 10
        compress
}
```

**Comment by misternils** [comment]
I tried to open it but none of my note programs would open a file that big

**Comment by Fornax96** [comment]
`less` can handle huge files: https://linux.die.net/man/1/less

**Comment by tbenz9** [comment]
So would `head` or `tail` but alas, OP is on Windows.  :)

**Comment by misternils** [comment]
When i get a chance I will do a little research and find a way.

**Comment by tbenz9** [comment]
Based on the information you've provided there is no action for the dev team to take.  I'm going to close this issue, feel free to reopen it if you are able to access your log files or have additional information.
