### ISSUE TITLE
Feature Request: Sia-UI- Add advanced settings section to settings

### ISSUE THREAD

**Issue by schranklabs** [NebulousLabs/Sia#2887]
Add an advanced settings section to settings in UI.
collateral
collateralbudget
maxcollateral
minuploadbandwidthprice
mincontractprice

**Environment** 
* Sia version: 1.3.2
* OS: Ubuntu 16.04

**Comment by tbenz9** [comment]
This feature request belongs in the https://github.com/NebulousLabs/Sia-UI repo.  Please move the feature request there.
