### ISSUE TITLE
while restoring from seed : Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by psychameleon** [NebulousLabs/Sia#2893]
Tried to restore from key 10 times alst night.

# BUG REPORT

**Stack Trace or error message**
Siad has exited unexpectedly. Please submit a bug report including the error log here.
**Expected Behavior**
restore wallet from key successfully
**How to reproduce it (as minimally and precisely as possible)**
download sia coin, sync, hit restore from seed.
When i kill the process and open it again, it appears as it is not synced ( at 94.9 ) and then it jumps to 146578 block height directly.
**Environment**
linux, opensuse
* Sia version:
1.3.2
* OS:
opensuse 42.3

**Comment by Bojak4616** [comment]
Do you have a stack trace?

> When i kill the process and open it again, it appears as it is not synced ( at 94.9 ) and then it jumps to 146578 block height directly.

This is normal and is fine.

**Comment by tbenz9** [comment]
Use this document to find your logs and error message.  Once you've found them post the output here.
https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
