### ISSUE TITLE
When Updating Transaction Pool, panic: page xxx already freed

### ISSUE THREAD

**Issue by tsangsir** [NebulousLabs/Sia#2898]
# When Updating Transaction Pool, panic: page xxx already freed

I am a hoster. Recently, I faced several crash issue with both Sia 1.3.1 & 1.3.2.

In Sia 1.3.1, I got error "panic: Consensus change series appears to be inconsistent - we are applying the wrong block.". `siad`basically died immediately after start up. Guess it is same as bug #2867 . 

Then I upgraded to 1.3.2 ( https://github.com/NebulousLabs/Sia/releases/download/v1.3.2/Sia-v1.3.2-windows-amd64.zip ). It still got the same error. So I replace `consensus.db` by downloading https://consensus.siahub.info/consensus.db.gz and also cleared `transactionpool` . 

When starting, `siad` worked a bit on transaction pool and died. Re-starting `siad`, it re-did some previously done work (seen from the height in `transactionpool.log`... I assume the worked wasn't committed) and sometimes went further before crashing again. 

Since restarting seems to bring progress, I repeated the processes again and again. Eventually, it reached height 136xxx, but it never succeeded to pass 139000. When re-ran `siad`, it restart at 136xxx again and made no progress for many hours. 

Since Sia is down for several days already, should I assume all my locked collateral burnt? Anything remedy?

**Stack Trace or error message**
I don't have the message on hand... will provide actual message later
```
D:\Sia-v1.3.2-windows-amd64> siad -M gctwh -d E:\sia
(0/5) Loading siad...
(1/5) Loading gateway...
(2/5) Loading consensus...
(3/5) Loading transaction pool...
panic: page xxx already freed

(Sorry the stack trace not in my hand)
```

**Expected Behavior**
`siad` startup normally

**How to reproduce it (as minimally and precisely as possible)**

1. Clean `consensus` and `transactionpool` directories
2. Decompress `consensus.db.gz`  in `consensus` directory
3. Start `siad` with `siad -M gctwh -d E:\sia`

**Environment**
* Sia version: 1.3.2
* OS: Windows 10 Home Fall Creators Update 
* 8GB RAM

**Comment by ChrisSchinnerl** [comment]
@tsangsir your collateral is most likely not burnt yet. Depending on your configured window size you should have around 1 week to submit your storage proof after the contract ends. So assuming you have a bunch of contracts ending right now you would still have a week to provide the proof before losing your collateral.
If you are on a ssd you can try to delete your `consensus` and `transactionpool` folder again and sync it yourself from the network. 
Also make sure that your Sia-UI is actually running siad 1.3.2 by typing `siac version` in your terminal tab.

**Comment by tsangsir** [comment]
Just saw #2790, seem similar but has a different stack trace. Is it needed to let `siac` 1.3.2 download and build consensus.db bit by bit, but not bootstrap from `https://consensus.siahub.info/` ?

I don't use Sia-UI but directly use `siad` . Therefore I know I was running the correct version.

And here is the actual stack trace:

```
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/5) Loading siad...
(1/5) Loading gateway...
(2/5) Loading consensus...
(3/5) Loading transaction pool...
panic: page 883708 already freed

goroutine 83 [running]:
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*freelist).free(0xc0421685a0, 0x30f18, 0x157bec000)
        /home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/freelist.go:143 +0x450
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*node).free(0xc04df3fb20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/node.go:556 +0x9e
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*node).rebalance(0xc04df3fb20)
        /home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/node.go:455 +0x9d1
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Bucket).rebalance(0xc0421576d8)
        /home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/bucket.go:633 +0x96
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc0421576c0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/tx.go:153 +0xd5
github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt.(*DB).Update(0xc042120780, 0xc0593f1330, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/vendor/github.com/coreos/bbolt/db.go:680 +0xef
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc04212aa00, 0xc04a29c000, 0xa, 0xa, 0x0, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:244 +0x41a
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc04212aa00, 0xb3e840, 0xc05453e920, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4dc
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb3e840, 0xc05453e920, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420ca840, 0xc0421fd380, 0x13, 0xa9ee68, 0xa, 0xc042176320, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2b2
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420ca840, 0xc0421fd380, 0x13, 0xa9ee68, 0xa, 0xc042176320, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xcb
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc04212aa00, 0xc0542e9f18, 0xc0542e9ec0, 0xc0542e9ec8, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x11f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc04212aa00, 0x0, 0x0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc04212aa00, 0xc042154590, 0xb3f5a0, 0xc0420ca840)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x37a
created by github.com/NebulousLabs/Sia/modules/consensus.New
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x5f3
```

And here are several lines from `transactionpool.log` illustrating  how `siac` restart at 136xxx and made no progress for many hours. 

```2018/03/22 15:45:04.386340 persist.go:86: STARTUP: Logging has started. Siad Version 1.3.2
2018/03/22 15:45:04.465346 update.go:175: CCID 851d95f8 (height 136898): 1 applied blocks, 0 reverted blocks
2018/03/22 15:45:04.472386 update.go:175: CCID 71cab364 (height 136899): 1 applied blocks, 0 reverted blocks
...
2018/03/22 15:45:01.652951 update.go:175: CCID badd631d (height 137097): 1 applied blocks, 0 reverted blocks
2018/03/22 15:45:04.386340 persist.go:86: STARTUP: Logging has started. Siad Version 1.3.2
2018/03/22 15:45:04.465346 update.go:175: CCID 851d95f8 (height 136898): 1 applied blocks, 0 reverted blocks
```

When `siad` started, it worked on height 136898. In above example, it crashed after reaching height 137097 (sometimes it reaches nearly 139000). And `siad` was restarted, it worked on 136898 again.

**Comment by ChrisSchinnerl** [comment]
We updated our database from boltdb to bbolt between 1.3.1 and 1.3.2 since boltdb seemed to be corrupting randomly which caused unexpected behavior.
The only way to be 100% sure that your database wasn't built using boltdb is by syncing it yourself.

**Comment by tsangsir** [comment]
That means in order to upgrade from 1.3.1 to 1.3.2, it is needed to sync the consensus from scratch?

If I want to avoid this, can I continue hosting with 1.3.1 (+ consensus from https://consensus.siahub.info/) ? 

And is burnt collateral deducted from "Locked collateral" (`siac host` output)? That means, if I see the Locked Collateral dropped but no contract complete, the amount was burnt?

**Comment by ChrisSchinnerl** [comment]
@tsangsir Using 1.3.1 you will get host score penalties and your database might get corrupted again eventually. It is not recommended to not run the latest version.

You should only see the locked collateral dropping when a contract is completed (either by providing a valid proof or missing the proof) and you have until the end of the contract to submit your storage proof.
