### ISSUE TITLE
Procedure for Creating a Contract

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#290]
1. Renter contacts host with proposed terms. 

- FileSize
- Window size (how many blocks a host has to submit each proof)
- Window start points (which block each window will start at) (each window should start an equal number of blocks apart)
- Client contribution towards payout each window
- Host contribution towards payout each window
- Valid Proof Address
- Missed Proof Address

2. If the host agrees with the contract, the host will allocate space for the file and send an agreement message. Host should agree with the client contribution and the host contribution, should agree that the window size is large enough, that the start points are acceptable, and that the distance between window start points is acceptable, the total duration of the contract is acceptable (total duration starts from the current height, not from the starting point of the first window).

3. The renter will upload the file

4. The renter will upload a transaction containing all of the contracts, and inputs, with a signature. 'whole transaction' should be set to false  when the renter signs the transaction.

5. The host will check that everything matches the prior agreement. There should be one contract for each window, the payout for each contract should be (client payout per window + host payout per window). Each contract should have a start point lined up with the `window start points` and and end point that is `window size` after the start point.

Each contract should now have a merkle root, and that merkle root should match  the merkle root of the file uploaded to the host.

6. the host adds ('host contribution each window' * number of windows) funds to the transaction and signs 'whole transaction', and submits it to the blockchain.

7. Renter watches blockchain for submitted transaction + contracts. If they don't appear in time, the renter knows to try again with a different host. ('in time' means that the transaction appears in the blockchain before the first window starts. Otherwise the signatures will all be invalidated).

**Comment by lukechampine** [comment]
implemented in #306

**Comment by DavidVorick** [comment]
ah sorry
