### ISSUE TITLE
Feature Request: Progress Bar for Scanning the Blockchain

### ISSUE THREAD

**Issue by chriseling** [NebulousLabs/Sia#2903]
It would be great if there was a progress indication when scanning the blockchain.  I'm new to SIA and the new user experience is important for adoption.  I'm not sure how long the scanning will take and then the program on Mac hide and I unlocked my wallet and it started scanning the blockchain again.  I get why it's important to scan, but for a new wallet and new users, progress indication would be a nice feature.

**Comment by tbenz9** [comment]
This issue belongs in the Sia-UI repo at https://github.com/NebulousLabs/Sia-UI.
