### ISSUE TITLE
have not been 3 transactions in the wallet SiaUI

### ISSUE THREAD

**Issue by sherhan05** [NebulousLabs/Sia#2904]
Hello!
Coins were sent to the siaui wallet, 3 of all transactions did not come to the wallet, and the rest were credited. Whether there are such failures? Will my coins come with time? Or should something else be done?

**Comment by sherhan05** [comment]
no one will answer? or all weekend?)

**Comment by tbenz9** [comment]
This is not the best place to get support for Sia.  I recommend you ask your question in the Sia Discord #Help channel.  The devs are not going to be able to help you without more information.  Can you tell us where you sent the coins from?  What the TXid is?  You can follow these steps for lost transactions: https://siawiki.tech/wallet/lost_transactions_troubleshooter

I recommend you try the link I sent, ask for help on Discord, email "hello@sia.tech". I'm closing this issue as there is no actionable item for a dev.
