### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by Jdibened423** [NebulousLabs/Sia#2911]
# BUG REPORT

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 4.0938922 seconds

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: 1.3.2
* OS: Windows

**Comment by Bojak4616** [comment]
Looks like everything loaded up fine! Try launching Sia-UI and not `siad` directly to get GUI access

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
