### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by acdop100** [NebulousLabs/Sia#2921]
# BUG REPORT

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 7.6944621 seconds
runtime: VirtualAlloc of 41943040 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0xacb591, 0xd)
	/usr/local/go/src/runtime/panic.go:605 +0x9c
runtime.sysMap(0xc67c070000, 0x2800000, 0x1, 0xf28bb8)
	/usr/local/go/src/runtime/mem_windows.go:122 +0x154
runtime.(*mheap).sysAlloc(0xf0eec0, 0x2800000, 0xadd6ef)
	/usr/local/go/src/runtime/malloc.go:470 +0xde
runtime.(*mheap).grow(0xf0eec0, 0x1400, 0x0)
	/usr/local/go/src/runtime/mheap.go:887 +0x67
runtime.(*mheap).allocSpanLocked(0xf0eec0, 0x1400, 0xf28bc8, 0x3)
	/usr/local/go/src/runtime/mheap.go:800 +0x33b
runtime.(*mheap).alloc_m(0xf0eec0, 0x1400, 0x45ca0101, 0x0)
	/usr/local/go/src/runtime/mheap.go:666 +0x126
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:733 +0x54
runtime.systemstack(0x45cafe60)
	/usr/local/go/src/runtime/asm_amd64.s:360 +0xb5
runtime.(*mheap).alloc(0xf0eec0, 0x1400, 0x45010101, 0x415172)
	/usr/local/go/src/runtime/mheap.go:732 +0xa8
runtime.largeAlloc(0x27ffee8, 0x1c0101, 0x100000000000036)
	/usr/local/go/src/runtime/malloc.go:827 +0x9f
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:722 +0x4d
runtime.systemstack(0xc04201a000)
	/usr/local/go/src/runtime/asm_amd64.s:344 +0x7e
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1125

This is only a small excerpt of the crash report because the actual one would be about 20 pages long I think.

**Expected Behavior**
Not crash

**How to reproduce it (as minimally and precisely as possible)**
Happens when the blockchain begins to sync. Used to take a while but now it happens almost immediately after opening SiaUI. Using task manager it looks like SiaUI's RAM usage spikes to 2.5gb (out of my 8) before giving me the "Siad has quit unexpectedly."

**Environment**

* Sia version: 1.3.2
* OS: Win10 latest update

**Comment by kumar25051995** [comment]
same proplem i want solution

**Comment by mtlynch** [comment]
As a workaround, you can try running this in a Docker container with limited memory. If you [install Docker](https://store.docker.com/editions/community/docker-ce-desktop-windows) on your machine, then run the following from PowerShell, it will run `siad` but keep it limited to 1 GB of RAM.

```powershell
mkdir sia-data
docker run `
  --detach `
  --volume "$($pwd.Path)/sia-data:/sia-data" `
  --publish 127.0.0.1:9980:9980 `
  --publish 9981:9981 `
  --publish 9982:9982 `
  --memory "1g" `
  --name sia-container `
   mtlynch/sia
```

Afterwards, you'll be able to use Sia normally with `siac` or Sia-UI in the same way as if you were running `siad` directly.

More details: https://blog.spaceduck.io/sia-docker/

**Comment by tbenz9** [comment]
I'm going to close this issue for a number of reasons.
1: It sounds like Sia-UI is the issue, in which case this issue belongs in the Sia-UI repo.
2: There is not sufficient information for the devs to recreate the issue.  If you can identify what aspect of Sia is using 2.5GB of RAM they would probably want to take a closer look.

Because of the reasons listed there is not much a dev can do right now.  User mtlynch provided a workaround, and I would suggest seeing if you get the error when running siad via commandline.
