### ISSUE TITLE
accidentally turned off the computer, now I can not continue the synchronization of the wallet

### ISSUE THREAD

**Issue by 4InStas** [NebulousLabs/Sia#2929]
the computer turned off, did not manage to synchronize the wallet
# BUG REPORT

* Sia version:
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.0870803 seconds
* OS: windows

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
