### ISSUE TITLE
error loading

### ISSUE THREAD

**Issue by dspisso** [NebulousLabs/Sia#2936]
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.105006 seconds
panic: bolt.DB.meta(): invalid meta pages
	panic: bolt.DB.meta(): invalid meta pages

**Comment by DavidVorick** [comment]
Was this after upgrading from a previous version?

**Comment by WalRibeiro** [comment]
Almost the same. I can't start Sia-UI after upgrade!
![sia_error](https://user-images.githubusercontent.com/36580749/38784661-bec41a88-40eb-11e8-9744-3e85509dd506.png)

**Comment by tbenz9** [comment]
Those are two different errors.  Both are known errors that are being tracked in other GH issues.

Use the guide below to work around the issue: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
