### ISSUE TITLE
RegisterRPCs should all be in one function

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#294]
All of the JSON API calls are registered in one function, `d.listen` (formerly `d.handle`). I feel that this serves as good "self-documentation." The RPCs should be the same way. Currently, some are registered by `NewTCPServer`, and the rest are initialized by `newDaemon`.

**Comment by lukechampine** [comment]
One downside to this is that it means we have to export the network RPCs. Right now, functions like `sharePeers` are unexported, which means they can *only* be called via RPC. Not a big deal, but enough to make me reconsider this plan.

**Comment by DavidVorick** [comment]
should sharePeers only be accessible via RPC? That seems odd to me. I would think that you would export any function that was going to be accessible to the world at large.

**Comment by lukechampine** [comment]
`sharePeers` is not very useful except via RPC, because it only returns 10 peers.

**Comment by DavidVorick** [comment]
I believe this has been addressed?

**Comment by lukechampine** [comment]
Almost. All of the RPCs are registered in `createDaemon` except for `Ping`, which is registered by `NewTCPServer`. With the addition of the Gateway, though, `Ping` could be moved the Gateway and the `TCPServer` would no longer register anything itself.
