### ISSUE TITLE
No Sync

### ISSUE THREAD

**Issue by mattyfresh51** [NebulousLabs/Sia#2941]
having trouble getting my wallet to sync

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.442865295 seconds

**Comment by DavidVorick** [comment]
do you have more information? Do you have peers? Are blocks coming in slowly, is it stuck at a particular height?

This output looks fine to me, that's what you would expect to see if it is syncing in the background.

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
