### ISSUE TITLE
host unreachable issue

### ISSUE THREAD

**Issue by Synosky** [NebulousLabs/Sia#2943]
Hi guys,
I had this issue, please try and make this easier for users, it really doesn' help with adoption, incredibly frustrating when your doing all you can and can't host after having more than 20 contracts and haven't changed anything. Please make it easier or address more thoroughly in guides:

https://forum.sia.tech/topic/1015/host-unreachable

**Comment by DavidVorick** [comment]
It's in the backlog, right now we have enough hosts able to get things working, and a huge over-supply of hosts.

Today we are focused on getting more renters to balance the equation, and then once the renting experience is a lot smoother and cleaner, we'll come back and do a lot of work on the hosts. We have a lot of things we want to get to with the host, but we need to be focusing our limited attention on the renter for now.

**Comment by Synosky** [comment]
Makes sense thank you. I’ll get some people/small companies signed up as renters in the UK over the next few weeks.
Martin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tbenz9** [comment]
I'll add that many of the "host unreachable" issues are outside the control of Sia.  For example, 
- some users may run firewalls that block Sia traffic causing the "host unreachable" error.  
- Different ISPs could theoretically block the traffic without notice.
- Routing, DNS, or general network problems are a common cause for this error and Sia can't do much to fix those.
