### ISSUE TITLE
 BUG REPORT

### ISSUE THREAD

**Issue by PombaGira** [NebulousLabs/Sia#2944]
# BUG REPORT

 Error Log:

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 6.3153745 seconds

the program was running and the error was suddenly

* : v1.3.2
* OS: W 8.1 PRO X64

**Comment by PombaGira** [comment]
goroutine 12 [running]:
runtime/debug.Stack(0x446d6e, 0xc05d299dd0, 0xc05d299d98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc05d299ed8, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc0420027a0, 0xc05d299ed8, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc0420a8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:45 +0xed
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc0420a8000)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:33 +0xbd
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:122 +0x3ae
Severe error: ERROR: failed to apply database update: mmap allocate error: truncate: truncate C:\Users\Ballet\AppData\Roaming\Sia-UI\sia\transactionpool\transactionpool.db: There is not enough space on the disk.
panic: Consensus change series appears to be inconsistent - we are applying the wrong block.

goroutine 11 [running]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc0420a8000, 0xda6391c75f2f9eb2, 0x63dd2bc00f9c2899, 0x17ad3d962ec8ce8e, 0xefd1e6c8eb24eb32, 0x0, 0x0, 0x0, 0xc064c0c900, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:223 +0x2b68
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc042258000, 0x0, 0x0, 0x0, 0xc04b7020c0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc042258000, 0xc054a4d400, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x61e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc042258000, 0xdf80e0, 0xc04b7de560, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdf80e0, 0xc04b7de560, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420a8840, 0xc0421b7f40, 0x12, 0xac7049, 0xa, 0xc042256440, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420a8840, 0xc0421b7f40, 0x12, 0xac7049, 0xa, 0xc042256440, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc042258000, 0xc04ee6fef0, 0xc04ee6fe98, 0xc04ee6fea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc042258000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc0421bc0b0, 0xc042258000, 0xdf87e0, 0xc0420a8840)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**Comment by DavidVorick** [comment]
Looks like there's not enough disk space. Sorry that the error is not a bit easier to read.

**Comment by DavidVorick** [comment]
"There is not enough space on the disk."

**Comment by PombaGira** [comment]
Ah ok ^^, thx.
