### ISSUE TITLE
Keeps shutting down. Can't sync wallet

### ISSUE THREAD

**Issue by mrrealer** [NebulousLabs/Sia#2945]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
There is no error message here.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
