### ISSUE TITLE
Keeps Shutting Down Wallet

### ISSUE THREAD

**Issue by mrrealer** [NebulousLabs/Sia#2946]
# BUG REPORT

**Stack Trace or error message**
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
listen tcp 127.0.0.1:9980: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
**Expected Behavior**
Wallet should startup and sync
**How to reproduce it (as minimally and precisely as possible)**

**Environment**
win 10
* Sia version:
* OS:
Windows 10

**Comment by tbenz9** [comment]
This error occurs when you try to start Sia when it's already running.  Make sure Sia is completely shut down before trying to open it again.
