### ISSUE TITLE
Lots of failed storage obligations (lost revenues + Tx fees)

### ISSUE THREAD

**Issue by nielscastien** [NebulousLabs/Sia#2952]
There are a lot of failed storage obligations on my host. Looking at the data I can see that there are no `SectorRoots` on the failed obligations, `OriginConfirmed` and `RevisionConfirmed` are both `true` and all potential revenues are always 0.

The following code will fail the obligation when there are no `SectorRoots` leading to lost revenues for the host (`ContractCost` and spend `TransactionFeesAdded` for submitting the file contract revision):
https://github.com/NebulousLabs/Sia/blob/6f6ef34bc345963c8ca4142db32a3c46a8652a66/modules/host/storageobligations.go#L761-L777

If the renter never uploads any data, it is not correct to fail the storage proof. Since these (empty) contracts lock up a lot of collateral, it's fair to be paid at least the contract cost to cover the transaction fees.

Issue is also reported in #2138

**Comment by ChrisSchinnerl** [comment]
@nielscastien take a look at `FormContract` in `formcontract.go`. The initial revision of the filecontract returns all the collateral to the host even if the storage proof was not provided because no data has been uploaded yet. The host simply can't provide a storage proof without any data to create it.

**Comment by nielscastien** [comment]
@ChrisSchinnerl I am not saying the collateral not returned, it is. And because we are talking about empty contracts, there is no risked collateral. So far so good. I am saying that the contract cost is not awarded to the host to cover transaction fees. To be more specific, over 25% of my contracts are empty contracts where I have to lock a lot of collateral for long periods of time (25 weeks). This prevents me from accepting other (more valuable?) contracts because locked collateral has reached its upper limit. And in the end the host has to submit a revision and pays for the transaction fees. This just doesn't feel right...

If it is impossible to supply a storage proof with empty contracts or to return the contract cost to the host, we should prevent the host from submitting revisions to the block chain for empty contracts.

**Comment by lukechampine** [comment]
@nielscastien an empty contract pays out both the collateral and the contract cost to the host:

https://github.com/NebulousLabs/Sia/blob/6f6ef34bc345963c8ca4142db32a3c46a8652a66/modules/renter/proto/formcontract.go#L57-L58

https://github.com/NebulousLabs/Sia/blob/6f6ef34bc345963c8ca4142db32a3c46a8652a66/modules/renter/proto/formcontract.go#L74-L87

It sounds like we should confirm this with a test, though.

Btw, looks like if a contract has `Filesize: 0`, consensus will accept any proof:

https://github.com/NebulousLabs/Sia/blob/6f6ef34bc345963c8ca4142db32a3c46a8652a66/modules/consensus/validtransaction.go#L200-L202

So we might as well have the host submit storage proofs even for empty contracts.

**Comment by nielscastien** [comment]
@lukechampine thanks for the quick reply! If for an empty contract any proof will do, we can change the line 768 in the code of my first post (remove `|| len(so.SectorRoots) == 0`) and everything will be ok. Or am I missing something?

**Comment by lukechampine** [comment]
On second thought, there's a good reason not to send the proof -- it takes up space on the blockchain.

I think the right approach here is to fix the host's internal accounting, so that it doesn't count these empty contracts as "missed."

**Comment by nielscastien** [comment]
I don't agree with the statement that it takes up space on the blockchain and therefore we shouldn't pay the host. With submitting the storage proof, the host gets paid the contract cost to

1. cover the transaction fees that the host paid and
2. to cover the risk of locking up collateral for the contract period.

BTW: there is nothing wrong with the host's internal accounting in this respect. The problem are the huge amount of `Missed storage proof. Revenue would have been 3000000000000000000000000` (where `300...` will be equal to the contract cost setting) in the host log that is worrying the hosts.

**Comment by lukechampine** [comment]
You misunderstand -- the host will be paid regardless of whether the proof is submitted or not. If the proof is successful, the contract's `ValidProofOutputs` are used; if not, the `MissedProofOutputs` are used. But for an empty contract, both sets of outputs are the same.

The host is spitting out scary `Missed storage proof` logs, but it doesn't actually lose money. We should handle the empty contract case specially in the host, preferably with some custom logging so that hosts understand what's happening.

**Comment by nielscastien** [comment]
Yes, you're right. I missed the fact that the contract cost is part of the `MissedProofOutputs`.
Than we only have to fix the host counter update and the logging as it's not a failed obligation. But I think that has not a very high priority right now. Thanks for clarifying!

**Comment by tbenz9** [comment]
@nielscastien would you be willing to create a new feature request issue with the specific logging task?  That might be a good task for a community member (unless you're planning on doing it).

**Comment by nielscastien** [comment]
@tbenz9 see PR #2959

**Comment by tbenz9** [comment]
I'm closing this as it appears Sia is working as expected and the only pending action item is being tracked in #2959.

If you think this was closed prematurely please feel free to reopen with a comment saying why you believe it was closed prematurely.
