### ISSUE TITLE
Sia Daemon v1.3.1 Loading... (0/6) Loading siad... (1/6) Loading gateway... listen tcp :9981: bind: address already in use

### ISSUE THREAD

**Issue by Noam1974** [NebulousLabs/Sia#2953]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
This usually means Sia is already running.

See this for more info: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
