### ISSUE TITLE
Siad has exited unexpectedly. Please submit a bug report including the error log here.

### ISSUE THREAD

**Issue by gabayarden** [NebulousLabs/Sia#2954]
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.095626723 seconds

Wallet: scanned to height 150497...
Done!
goroutine 1 [running]:
runtime/debug.Stack(0x1045ec7, 0x0, 0xc42003b948)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42003bac8, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7fff5fbffd4c, 0xe, 0x7fff5fbffd78, 0x5, 0x7fff5fbffd67, 0x5, 0x0, 0x7fff5fbffdcd, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x588
main.startDaemonCmd(0xc4200a6fc0, 0xc420078550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200a6fc0, 0xc42000e0d0, 0x5, 0x5, 0xc4200a6fc0, 0xc42000e0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a6fc0, 0x16e1b17, 0x3b, 0xc420093ae0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200a6fc0, 0x1b0a200, 0x16ca346)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.

**Comment by S-anasol** [comment]
https://github.com/NebulousLabs/Sia/issues/2228#issuecomment-322032996

**Comment by tbenz9** [comment]
This bug is being tracked at NebulousLabs/Sia-UI#670

It was previously tracked at #2406

There is no sure workaround that I'm aware of but you can try the instructions linked in the issues above. My understanding is this only affects MacOS. You can also try completely reinstalling Sia, only a small subset of users report this issue
