### ISSUE TITLE
How can I build a private chain of Sia?

### ISSUE THREAD

**Issue by zyding1983** [NebulousLabs/Sia#2955]
How to reproduce it

**Comment by siegfried415** [comment]
Look at [Sia-Ant-Farm](https://github.com/NebulousLabs/Sia-Ant-Farm) .

**Comment by zyding1983** [comment]
Thank you! @siegfried415 
However, an error when I run the "go get -u github.com/NebulousLabs/Sia-Ant-Farm/..."
The error information is as follows "go/src/github.com/NebulousLabs/Sia-Ant-Farm/ant/job_host.go:70:16: j.client.HostAcceptingContractsPost undefined (type *client.Client has no field or method HostAcceptingContractsPost)"

**Comment by siegfried415** [comment]
Sorry, I 'm not maintainer of Sia, but I suggest you to check if there is a `HostAcceptingContractsPost` function in Sia/node/api/client/host.go, if not, your Sia 's version may be too old.  Accroding to the readme.md of Sia, you can run `go get -u github.com/NebulousLabs/Sia/...`    again  to keey Sia  up-to-date.

**Comment by ChrisSchinnerl** [comment]
@zyding1983 sry we broke the build with a recent change to the `node.api.Client` package. Should be fixed now.
