### ISSUE TITLE
sia deposit 

### ISSUE THREAD

**Issue by dspisso** [NebulousLabs/Sia#2962]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by dspisso** [comment]
I need to recover 5 siacoin  deposit made to this address  468f81593800680c0ba08da46f7368dd307aaa17fd157b44e474902d5da5b5bda36a22c59d3d
I download the sia file I run the exe file and still synchronizing from days ago. I use the address to make the deposit but I not save the  address.

I would like to have the coins deposit to my poloniex address

**Comment by tbenz9** [comment]
Please ask for help on the Sia Discord at https://discord.gg/sia

This GitHub repo is for bug reporting and feature tracking.
