### ISSUE TITLE
Replay attack risk when transfer siacoin

### ISSUE THREAD

**Issue by hupengbuaa** [NebulousLabs/Sia#2965]
I currently implement SC wallet for transfer , which only covers  `SiacoinInputs`, `SiacoinOutputs`,`MinerFees` fields, it seems very likely to risk a replay attack, cause there is no sequence number  staff in these fileds.  What's the suggest?

**Comment by hupengbuaa** [comment]
A transfers some account SC to B, the minimal viable transaction may look like:<br>
```
siacoin_inputs:[{
parent_id:"tx_id"
unlock_conditions:{ 
algorithm:"ed25519",
key:"A's public_key"}
}],
siacoin_outputs:[{
unlockhash:"B's unlockhash",
value:1sc
}],
miner_fees:[0.1sc],
transaction_signatures:[{
signatures:"signature fullfil siacoin_input's unlockconditions",
others:...
}]
```

Would it be possible to send this transaction multiple times, cause the signature will always valid?

**Comment by ChrisSchinnerl** [comment]
@hupengbuaa Yes, it would be but that's no problem. Siacoin Inputs can't be spent multiple times.
