### ISSUE TITLE
Siad has exited unexpectedly - please help

### ISSUE THREAD

**Issue by cnpark** [NebulousLabs/Sia#2976]
# BUG REPORT

**Stack Trace or error message**

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.2162339 seconds

**Expected Behavior**

I don't know how to stop sia and re-start it again using Sia-UI application.   There is no clear guidance.

**How to reproduce it (as minimally and precisely as possible)**

I entered "stop" under terminal command and then click "start siad"

**Environment**
* Sia version: v1.3.2
* OS: Windows 10 Home Version 1709 OS build 16299.371

**Comment by tbenz9** [comment]
I recommend you ask for help in the #help channel on Sia Discord.

There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
