### ISSUE TITLE
./said must bu root ??!!

### ISSUE THREAD

**Issue by deanrobin** [NebulousLabs/Sia#2988]
**go version 1.10.2
**go get ..
And then 
./siad -M cgtwe -d /data/Sia --api-addr "xxx:9900" --authenticate-api --disable-api-security
~$ Enter API password 
Sia Daemon v1.3.2
WARN: compiled without build commit or version. To compile correctly, please use the makefile
Loading...
listen tcp xxx:9900: bind: cannot assign requested address

xxx is my IP

And, If I use sudo ./siad ....
This is OK . why??

**Comment by ChrisSchinnerl** [comment]
That port might already be in use by another application.

**Comment by deanrobin** [comment]
which port must be unused？No application use port 9980

**Comment by ChrisSchinnerl** [comment]
You specified the custom port `9900` in your description.
