### ISSUE TITLE
Loading siad... (1/6) Loading gateway... (2/6) Loadingction pool... (4/6) Loading wallet... (5/6) Loading host... (6/6) Loading renter... Finished loading in 0.1

### ISSUE THREAD

**Issue by energievolt** [NebulousLabs/Sia#2994]
Download stop at 74%  . I had this code    Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.147084869 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1045ec7, 0x0, 0xc4201bf948)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4201bfac8, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7fff5fbffd23, 0xe, 0x7fff5fbffd4f, 0x5, 0x7fff5fbffd3e, 0x5, 0x0, 0x7fff5fbffda3, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x588
main.startDaemonCmd(0xc4200aefc0, 0xc420070550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200aefc0, 0xc420074010, 0x5, 0x5, 0xc4200aefc0, 0xc420074010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200aefc0, 0x16e1b17, 0x3b, 0xc4200939a0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0xc4200aefc0, 0x1b0a200, 0x16ca346)
	/home/luke/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x790
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.

**Comment by deanrobin** [comment]
I alse get like this 
``Wallet: scanned to height 40099...goroutine 15 [running]:
runtime/debug.Stack(0x445ec7, 0x0, 0xc43561edf8)
	/root/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/root/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc43561eea0, 0x2, 0x2)
	/root/go/bin/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42022e3f0, 0xd29b3e4c118b3f9a, 0xbc0386dfc3ac4270, 0xdb0dfc4f34cb9afc, 0x42db71a0230992f1, 0x0, 0x0, 0x0, 0xc4214f79e0, 0x1, ...)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0xd4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc420178780, 0x0, 0x0, 0x0, 0xc4261aa1c0, 0x1, 0x1)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420178780, 0xc42044ec00, 0xa, 0xa, 0x0, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x5d9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420178780, 0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4d5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2ab
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xc4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420178780, 0xc43561ff18, 0xc43561fec0, 0xc43561fec8, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x118
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420178780, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420178780, 0xc4201765e0, 0xb48ac0, 0xc420020b00)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x373
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x5ec
Critical error: explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Wallet: scanned to height 40299...goroutine 15 [running]:
runtime/debug.Stack(0x445ec7, 0x0, 0xc4208d8df8)
	/root/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/root/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4208d8ea0, 0x2, 0x2)
	/root/go/bin/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42022e3f0, 0xa6d326b277e1dfdc, 0xacbc765f28211962, 0x42f9b9ec9d573e6a, 0x6e6086f5510504c3, 0x0, 0x0, 0x0, 0xc4316f19e0, 0x1, ...)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0xd4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc420178780, 0x0, 0x0, 0x0, 0xc423927740, 0x1, 0x1)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420178780, 0xc420047800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x5d9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420178780, 0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4d5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2ab
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xc4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420178780, 0xc4208d9f18, 0xc4208d9ec0, 0xc4208d9ec8, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x118
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420178780, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420178780, 0xc4201765e0, 0xb48ac0, 0xc420020b00)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x373
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x5ec
Critical error: explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 15 [running]:
runtime/debug.Stack(0x445ec7, 0x0, 0xc4208d8df8)
	/root/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/root/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4208d8ea0, 0x2, 0x2)
	/root/go/bin/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42022e3f0, 0x82c680d687212581, 0x2f25923dd39b5a02, 0x9eed9084c29b764, 0x19e3ba3e96e8e97d, 0x0, 0x0, 0x0, 0xc42203ed20, 0x1, ...)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0xd4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc420178780, 0x0, 0x0, 0x0, 0xc42da085e0, 0x1, 0x1)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420178780, 0xc420047800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x5d9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420178780, 0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4d5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2ab
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xc4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420178780, 0xc4208d9f18, 0xc4208d9ec0, 0xc4208d9ec8, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x118
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420178780, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420178780, 0xc4201765e0, 0xb48ac0, 0xc420020b00)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x373
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x5ec
Critical error: explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 15 [running]:
runtime/debug.Stack(0x445ec7, 0x0, 0xc4208d8df8)
	/root/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/root/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4208d8ea0, 0x2, 0x2)
	/root/go/bin/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42022e3f0, 0xb67b28d29dcd3497, 0x25c1f52c68f7268c, 0x1fc0c3e34d37c93d, 0x35dda8c2ef884434, 0x0, 0x0, 0x0, 0xc42c5a6240, 0x1, ...)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0xd4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc420178780, 0x0, 0x0, 0x0, 0xc4208c8bc0, 0x1, 0x1)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420178780, 0xc420047800, 0xa, 0xa, 0x0, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x5d9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420178780, 0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4d5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb47da0, 0xc42424f200, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2ab
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc420020b00, 0xc4200250e0, 0x10, 0xaa5c03, 0xa, 0xc420176580, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xc4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420178780, 0xc4208d9f18, 0xc4208d9ec0, 0xc4208d9ec8, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x118
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420178780, 0x0, 0x0)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420178780, 0xc4201765e0, 0xb48ac0, 0xc420020b00)
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x373
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/root/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x5ec
Critical error: explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues``

**Comment by energievolt** [comment]
Hi   ,

 i deleted Sia and i re-download sia'app, but no working. I have only this
message

A critical error loading Sia has occured: Siad unexpectedly exited. Error
log: Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
panic: Consensus change series appears to be inconsistent - we are applying
the wrong block.

goroutine 30 [running]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc4200c8000,
0x8dcaed4aea308d25, 0x39a6a06fc2636adb, 0x6d504423516c4e66,
0xbdef242f1dce80c0, 0x0, 0x0, 0x0, 0xc4224b42a0, 0x1, ...)
/home/luke/go/src/
github.com/NebulousLabs/Sia/modules/transactionpool/update.go:223 +0x2b61
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc42



What can i do now?


André

**Comment by tbenz9** [comment]
@energievolt The `panic: Consensus change series appears to be inconsistent - we are applying
the wrong block.` is usually caused when Sia find corruption in one of it's databases; corruption is usually caused by a crash or improper shutdown.

In your case, it looks like the corruption is in the host.db file, if you're not planning on hosting you can simply disable that module by following the instructions to "Prevent the host module from starting" here: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda#prevent-the-host-module-from-starting-in-sia-ui-windows-only

If you need more help try the #help channel on the Sia Discord.

**Comment by tbenz9** [comment]
@deanrobin Your error appears to be unrelated to the original error in this issue.  Please open your own issue.

**Comment by energievolt** [comment]
Ok Thanks


André
