### ISSUE TITLE
./siad run some hours later, error: explorer update failed

### ISSUE THREAD

**Issue by deanrobin** [NebulousLabs/Sia#3001]
OS: CentOS6.9
GoVersion: 1.10.2

go get -u github.com/NebulousLabs/Sia/...
And then ` ./siad -M cgtwe -d /data/Sia --api-addr "myIP:9980" --authenticate-api --disable-api-security`
I use another terminal `./siac wallet init .........`

Maybe some hours later, first terminal show me these

`goroutine 15 [running]:
runtime/debug.Stack(0x445ec7, 0x0, 0xc4255c0df8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4255c0ea0, 0x2, 0x2)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42021a3f0, 0xd901d32b47a75d8a, 0x82d459b5abfe3fe9, 0x6ef09e222cf2a953, 0x47c1464c3feda5ef, 0x0, 0x0, 0x0, 0xc426ee7860, 0x1, ...)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/explorer/update.go:282 +0xd4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc420178780, 0x0, 0x0, 0x0, 0xc426f430a0, 0x1, 0x1)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17d
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420178780, 0xc4330ad000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x5d9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420178780, 0xb49e80, 0xc426dc1f00, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x4d5
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xb49e80, 0xc426dc1f00, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc4200e46e0, 0xc420023f60, 0x12, 0xaa6d83, 0xa, 0xc420c485f0, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2ab
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc4200e46e0, 0xc420023f60, 0x12, 0xaa6d83, 0xa, 0xc420c485f0, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xc4
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420178780, 0xc4255c1f18, 0xc4255c1ec0, 0xc4255c1ec8, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x118
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420178780, 0x0, 0x0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x14a
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420178780, 0xc4201765e0, 0xb4aba0, 0xc4200e46e0)
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x373
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/usr/local/go/bin/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x5ec
Critical error: explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues`

And these error code more and more....
I am not Go developer, So I hope you can know what I want to tell you and please answer me most clear.
Thank you

**Comment by ChrisSchinnerl** [comment]
The explorer is currently not very stable. Do you need it? If not I'd recommend running `siad` without it.

**Comment by deanrobin** [comment]
And , @ChrisSchinnerl
First running `siad` will sync block and download it.
But, it's too slow, and `Wallet API` need block all synced and download??
I mean "synced" must be true, then I can use other wallet API.
Maybe synced become true need one day, or more than 30 hours...
I running my application, about 20 hours, but synced still false, height is 139640
I think, how about Wallet API  can visit some block like block's height less application now synced height

**Comment by ChrisSchinnerl** [comment]
If you only need the wallet you can run `siad -M gctw`.
If you also need the renter run `siad -M gctwr`.
Syncing takes a long time if you are on a hdd. The current blockheight is 153843.

**Comment by deanrobin** [comment]
thank you, you're good man
