### ISSUE TITLE
How can I remove the  data which synced by sia ui from my hard disk in Mac？

### ISSUE THREAD

**Issue by xzjcool** [NebulousLabs/Sia#3002]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by ChrisSchinnerl** [comment]
Simply follow the steps from our official [FAQs](https://support.sia.tech/article/RVHd7ydu0K-how-do-i-uninstall-sia).
