### ISSUE TITLE
error in wind

### ISSUE THREAD

**Issue by pelmeni** [NebulousLabs/Sia#3007]
# BUG REPORT

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 6.8333909 seconds
goroutine 21 [running]:
runtime/debug.Stack(0x446d6e, 0xc04886ddd0, 0xc04886dd98)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x29
github.com/NebulousLabs/Sia/build.Severe(0xc04886ded8, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x8c
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc042204260, 0xc04886ded8, 0x2, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xd3
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).syncDB(0xc04221c160)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:45 +0xed
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc04221c160)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:33 +0xbd
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:122 +0x3ae
Severe error: ERROR: failed to apply database update: mmap allocate error: truncate: truncate C:\Users\pichugin\AppData\Roaming\Sia-UI\sia\transactionpool\transactionpool.db: There is not enough space on the disk.
panic: Consensus change series appears to be inconsistent - we are applying the wrong block.

goroutine 50 [running]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).ProcessConsensusChange(0xc04221c160, 0x946aa1fff4a97658, 0xe34bd804f9c8b6cf, 0x2d6476c423da0956, 0x4cd526807b7e95cc, 0x0, 0x0, 0x0, 0xc05c81e0c0, 0x1, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/update.go:223 +0x2b68
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).updateSubscribers(0xc0420b3b80, 0x0, 0x0, 0x0, 0xc0643fa8a0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:118 +0x17f
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc0420b3b80, 0xc04b284000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:311 +0x61e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc0420b3b80, 0xdf80e0, 0xc059376be0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x500
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xdf80e0, 0xc059376be0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x45
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc0420a69a0, 0xc04200f0c0, 0x10, 0xac7049, 0xa, 0xc0421c9150, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x2c9
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc0420a69a0, 0xc04200f0c0, 0x10, 0xac7049, 0xa, 0xc0421c9150, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd8
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc0420b3b80, 0xc065bdfef0, 0xc065bdfe98, 0xc065bdfea0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12e
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc0420b3b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x151
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc042144500, 0xc0420b3b80, 0xdf87e0, 0xc0420a69a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3eb
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:144 +0x656

**How to reproduce it (as minimally and precisely as possible)** i have just start client

**Environment**
* Sia version: last
* OS: windows

**Comment by tbenz9** [comment]
`There is not enough space on the disk.`  It looks like you ran out of storage space.  Can you check and report back?
