### ISSUE TITLE
Initialize missing fields in `renter.SetSettings`

### ISSUE THREAD

**Issue by ChrisSchinnerl** [NebulousLabs/Sia#3009]
In `modules/renter/renter.go` in the `Settings` method we currently don't initialize all the fields of the `RenterSettings` (ratelimit fields are missing):

https://github.com/NebulousLabs/Sia/blob/7a92bcca28e3c6e31a9ea2afb989dbf53e3e1735/modules/renter/renter.go#L344-L349

This causes a call to the `/renter` endpoint with a new set of settings (e.g. allowance change) to always reset the bandwidth.

**Comment by MSevey** [comment]
- [ ] Create a GetRateLimit method if it doesn't exist
