### ISSUE TITLE
1.3.3 RC2: "renter allowance cancel" destroys all renter contracts and data

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#3013]
# BUG REPORT

**How to reproduce it (as minimally and precisely as possible)**

1. Create renter contracts with `siac renter setallowance`
1. Disable contract renewal with `siac renter allowance cancel`

**Expected Behavior**

Sia maintains existing contracts, but does not automatically renew them.

**Actual Behavior**

Sia destroys all contracts and loses all data.

**Environment**: 
* Sia version: Sia 1.3.3 RC2
* OS: Ubuntu 16 (Docker container)

**Logs**

* [Before allowance cancel](https://gist.github.com/mtlynch/b8cbb08ff6bc22d88bd528ffbc211dd2)
* [After allowance cancel](https://gist.github.com/mtlynch/d13988ef5a9189bb59aee72ab7a4d0f9)

**Comment by tbenz9** [comment]
@lukechampine can you confirm that this is the expected behavior?

**Comment by DavidVorick** [comment]
This is intended behavior, though there was some internal disagreement when it was implemented over whether it was the right way to design the api call.

I'm in favor of changing the call so that instead of destroying all of the contracts, it just collapses the allowance and stops renewing.

**Comment by lukechampine** [comment]
that seems much more reasonable to me. Shouldn't be too difficult to implement.
