### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by megagepard** [NebulousLabs/Sia#3016]
Hello. An error occurs during synchronization:
"Siad has exited unexpectedly. Please submit a bug report including the error log here."

Error Log:
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.4570853 seconds

# BUG REPORT

**Stack Trace or error message** Siad has exited unexpectedly. Please submit a bug report including the error log here.

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: Sia-UI-v1.3.2
* OS: Windows 10 x64

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
