### ISSUE TITLE
Feature Request: add additional warning to `renter allowance cancel`

### ISSUE THREAD

**Issue by tbenz9** [NebulousLabs/Sia#3017]
Feature Request:
Add a confirmation to `siac renter allowance cancel` that says something like:
```
Canceling your allowance will destroy all your contracts and uploaded files immediately.
Do you want to continue? [y/N]: 
```

Related to #3013

**Comment by fanux365** [comment]
I correctly understand that here it is necessary to add this feature?
https://github.com/NebulousLabs/Sia/blob/6f6ef34bc345963c8ca4142db32a3c46a8652a66/cmd/siac/rentercmd.go#L274

**Comment by fanux365** [comment]
Is this normal?
https://github.com/NebulousLabs/Sia/pull/3021

**Comment by tbenz9** [comment]
> Is this normal? `All checks have failed`
Can you identify why the checks are failing?  And if you run the tests locally do they pass?  Occasionally the continuous integration testing fails for reasons not related to the code you modified.
