### ISSUE TITLE
Report 404 errors according to API.md

### ISSUE THREAD

**Issue by zhaoweigao** [NebulousLabs/Sia#3020]
# BUG REPORT

**Stack Trace or error message**
![consensus_block](https://user-images.githubusercontent.com/37134069/39982244-49332492-5786-11e8-8570-42cf1c528919.jpg)

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by tbenz9** [comment]
I believe the `/consensus/blocks` API endpoint is new and will be released in Sia v1.3.3.  If you're still running version 1.3.2 it would not work.

@ChrisSchinnerl may be able to confirm if my memory is correct.

**Comment by tbenz9** [comment]
Also, make sure you're consensus if fully synced.  The first command worked fine for me:
```
root@sia1:~# curl -A "Sia-Agent" "localhost:9980/wallet/transactions?startheight=1&endheight=250"
{"confirmedtransactions":null,"unconfirmedtransactions":null}
```

**Comment by zhaoweigao** [comment]
@tbenz9   The latest version is 1.3.2，[https://github.com/NebulousLabs/Sia/releases](url)  where can I get version 1.3.3;

**Comment by tbenz9** [comment]
Version 1.3.3 has not been officially released yet.  You can build from source if you want this feature, or wait a few days for 1.3.3 to be released.
