### ISSUE TITLE
socket hang up loading wallet from seed

### ISSUE THREAD

**Issue by gmarc13** [NebulousLabs/Sia#3031]
socket hang up error pops up every time when trying to load wallet from seed

'Siad has exited unexpectedly'

When starting siad again, reverts back to 94.6% synced every time.

Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 4.676912861 seconds

Verison 1.3.2
Mac OS

**Comment by tbenz9** [comment]
Reverting back to 94% is normal, when Sia starts it doesn't know if it is synced or not so it assumes it is not.

We need more information to help you solve your problem.  Follow the instructions below to include your error.  I'm closing this issue for now as there is not enough info to troubleshoot, if you add your logs we can re-open it and try to fix the problem.

https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
