### ISSUE TITLE
Persist Renter Settings

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#3043]
Currently the renter stream cache size and the renter memory bandwidth limits are not persisted, I believe that most users will prefer to have these values persisted.

Before we release v1.3.3 and get into compatibility issues, we should patch this up. Giving it to @MSevey

**Comment by DavidVorick** [comment]
The renter has a renter.json file. JSON has easy backwards compatibility, so we should be fine just adding these new fields to the JSON file when we save and load, and then adding a test to see that the values are being persisted correctly, and also that nothing funky happens if you upgrade from a renter.json that doesn't have those values recorded in it.

Overall this should be a pretty easy thing to change.

**Comment by MSevey** [comment]
@DavidVorick I am pretty much done.  Chris has PR #3029 that adds params to the `testnode` that I need to finish the `RestartNode` method for the Siatest.  Let me know when you can merge that PR
