### ISSUE TITLE
Gateway only requests blocks from outgoing peer-to-peer connections.

### ISSUE THREAD

**Issue by ChrisSchinnerl** [NebulousLabs/Sia#3046]
It seems like a node will only request blocks from peers that it connects to and not from incoming connections. That caused a NDF in some tests in which all the nodes of a `TestGroup` would actively connect to a new peer which prevented the new peer from syncing.

**Comment by ChrisSchinnerl** [comment]
This will be fixed in [#3029](https://github.com/NebulousLabs/Sia/pull/3029)

**Comment by lukechampine** [comment]
if so, the issue should be closed by referencing it in the commit message.
