### ISSUE TITLE
Sia Ui won't load on Mac Sierra 10.12.4 

### ISSUE THREAD

**Issue by Tyz49** [NebulousLabs/Sia#3053]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by Tyz49** [comment]
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.883216582 seconds

**Comment by Tyz49** [comment]
Sia Daemon v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.82516918 seconds

**Comment by soon1ee** [comment]
How to fix the problem

v1.3.2
Git Revision 72938f5
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
panic: Consensus change series appears to be inconsistent - we are applying the wrong block.

**Comment by tbenz9** [comment]
@Tyz49 
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

@soon1ee 
often a restart of Sia will fix that error.  If not, use the link above and follow the instructions for "Delete your transactionpool.db file"
