### ISSUE TITLE
Help with host has reached its collateral budget and cannot accept the file contract

### ISSUE THREAD

**Issue by uclnj** [NebulousLabs/Sia#3063]
I started noticing a few hundred messages like these on my host.  How have I reached the collateral budget and not be able to accept more contracts?

All of this coincided with the [drop in storage](https://siahub.info/host/6938) against the server.

```
2018/05/30 05:22:39.659659 errors.go:151: internal error: error with 83.157.240.249:57568: incoming RPCFormContract failed: contract verification failed: host has reached its collateral budget and cannot accept the file contract
2018/05/30 11:41:08.910462 errors.go:151: internal error: error with 82.2.156.164:49276: incoming RPCFormContract failed: contract verification failed: host has reached its collateral budget and cannot accept the file contract
```

I exported every transaction and totaled them in Excel.  Of the 5K+ transactions I have a positive 22K SC balance with 47K SC put into the host and 24K SC in negative transactions.

The wallet data shows:

```
Height:              156809
Confirmed Balance:   40.33 KS
Unconfirmed Delta:  +0 H
Exact:               40329343419388740458843325591 H
Siafunds:            0 SF
Siafund Claims:      0 H
```

And the host stats show:

```
Host Internal Settings:
        acceptingcontracts:   Yes
        maxduration:          25 Weeks
        maxdownloadbatchsize: 17.83 MB
        maxrevisebatchsize:   17.83 MB
        netaddress:           siahost.uclnj.com:9982 (manually specified)
        windowsize:           24 Hours

        collateral:       100 SC / TB / Month
        collateralbudget: 40 KS
        maxcollateral:    5 KS Per Contract

        mincontractprice:          1 SC
        mindownloadbandwidthprice: 5 SC / TB
        minstorageprice:           5 SC / TB / Month
        minuploadbandwidthprice:   5 SC / TB

Host Financials:
        Contract Count:               502
        Transaction Fee Compensation: 607 SC
        Potential Fee Compensation:   1.272 KS
        Transaction Fee Expenses:     0 H

        Storage Revenue:           233.3 SC
        Potential Storage Revenue: 87.47 SC

        Locked Collateral: 39.99 KS
        Risked Collateral: 439.2 SC
        Lost Collateral:   0 H
```

**Environment**

Ubuntu 16.04

* Sia version:

Sia Client
        Version 1.3.2
        Git Revision 72938f5
        Build Time   Tue Mar 13 19:48:47 EDT 2018
Sia Daemon
        Version 1.3.2
        Git Revision 72938f5
        Build Time   Tue Mar 13 19:48:47 EDT 2018

**Comment by tbenz9** [comment]
Your `collateralbudget` is set to 40KS and your `Locked Collateral` is at 39.99KS.  You don't have any collateral budget left to accept new contracts.

I recommend you do some research on what the ideal numbers would be for your situation.  If it were my host I would reduce the `maxcollateral`.


> How have I reached the collateral budget and not be able to accept more contracts?

With a `maxcollateral` of 5KS it would only take 8 contracts to exhaust your 40KS `collateralbudget`.
8 contracts x 5KS max collateral = 40KS collateral budget

**Comment by tbenz9** [comment]
I'm going to go ahead and close this issue as there is no action for the Sia devs to take.  I'd be happy to continue the conversation and discuss your settings more in the #hosting channel of the Sia Discord.
