### ISSUE TITLE
Add a renter endpoint to clear the download history

### ISSUE THREAD

**Issue by ChrisSchinnerl** [NebulousLabs/Sia#3068]
Currently the download history is only cleared upon a restart of siad. For most of the long-running nodes, the history is just sitting there in memory and using up RAM.
I'd suggest adding one or two api endpoints to the renter that let you clear the whole download history or just single entries. Those endpoints might also prove to be useful for GUIs to avoid cluttering the interface.

**Comment by MSevey** [comment]
adding additional functionality to clear before and clear after a point in time
