### ISSUE TITLE
Encoding/Marshalling Specification

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#308]
An encoding/marshalling specification is all that remains  to finish the rough draft specification, to a level of completeness that someone else could write their own implementation and follow all the rules with no ambiguity. Everything else is ready to go.

which might seem daunting but I think most of it will be done in the next 3 days.

**Comment by lukechampine** [comment]
The specification more or less exists already in the docstring of `Marshal`. I can pull it out into a separate file though.

**Comment by DavidVorick** [comment]
Can you put it in Consensus.md, below the section 'Cryptographic Algorithms"?
