### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Tyz49** [NebulousLabs/Sia#3091]
# BUG REPORT
Sia Daemon v1.3.3
Git Revision 910034d
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 3.040879366 seconds
**Stack Trace or error message**

**Expected Behavior**
restart
**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: 1.3.3
* OS: 10 mac

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
