### ISSUE TITLE
Critical error: streamHeap and streamMap are not the same length

### ISSUE THREAD

**Issue by pdxwebdev** [NebulousLabs/Sia#3094]
I didn't actually notice anything wrong but I saw this in my terminal. Feel free to remove this bug report if it's nothing.

# BUG REPORT

goroutine 2887318 [running]:
runtime/debug.Stack(0x445e67, 0x0, 0xc45824dd68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc45824de10, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
github.com/NebulousLabs/Sia/modules/renter.(*streamCache).pruneCache(0xc42032af90, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/streamcache.go:108 +0x18b
github.com/NebulousLabs/Sia/modules/renter.(*streamCache).Add(0xc42032af90, 0xc44ef76120, 0x8, 0xc49f75a000, 0x27ffee8, 0x3bffe5c)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/streamcache.go:80 +0x92
github.com/NebulousLabs/Sia/modules/renter.(*unfinishedDownloadChunk).threadedRecoverLogicalData(0xc467940000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/downloadchunk.go:226 +0x78b
created by github.com/NebulousLabs/Sia/modules/renter.(*worker).managedDownload
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/workerdownload.go:60 +0x42a
Critical error: streamHeap and streamMap are not the same length

**Environment**
* Sia version: 1.3.3
* OS: Ubuntu 16.04

**Comment by MSevey** [comment]
Hey @pdxwebdev can you try checking out the branch i just created `stream-cache-bug` and try recreating the error?  I updated the build critical error message to show the lengths of the Heap and Map to help with debugging

**Comment by pdxwebdev** [comment]
Just got it built, tested it, then I come back here... Aaaaand it's closed. lol

FWIW, the issue did not occur again on `stream-cache-bug`.
