### ISSUE TITLE
No Transactions Showing up after upgrade to 1.3.3

### ISSUE THREAD

**Issue by DaveKoz** [NebulousLabs/Sia#3096]
# BUG REPORT

**How to reproduce it (as minimally and precisely as possible)**

Have version 1.3.2 that has lots of transactions.

Update to 1.3.3 no old or new transactions show
![sia bug](https://user-images.githubusercontent.com/1183431/41231384-8bc74978-6d48-11e8-9a89-26c45799e5ab.png)

* Sia version: 1.3.3
* OS: Max OSX 10.13.4

**Comment by timolow** [comment]
This is an issue for me on ubuntu

**Comment by ChrisSchinnerl** [comment]
This should be fixed now in the most recent release binaries on the website so I'm closing this.
