### ISSUE TITLE
Flexible encoding

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#310]
When nodes establish communication, they should agree on what encoding they will use to pass messages. This can be done in a similar manner to the choice of signature algorithm.

**Comment by lukechampine** [comment]
This may introduce some vulnerability; it's possible that some encoding algorithms will be more susceptible to attack than others. The data is decoded before being passed to the state, so a broken encoder won't allow an attacker to break consensus too. But a particular algorithm might be more susceptible to, e.g., DOS attacks. As a simple example, encoders that use compression need some way to safeguard against zip bombs. This gets worrisome when you realize that every implementation that wants to support compression *needs* to implement this safeguard.

Another crazy thought: nodes could *charge you just to communicate with them*. The encoding algorithm would initiate each communication by requesting payment to a specific address. They could even bill proportionally to the message size...not unlike a lawyer.

**Comment by DavidVorick** [comment]
I do think that the final destination for talking is going to be with micropayment channel charging. You'll pay nodes that relay you blocks, and miners will pay nodes that relay transactions with fees.

I forgot about problems like zip bombs in the encoding scheme. I would imagine though there are existing libraries to manage encrypted and compressed network communications which protect against all forms transfer-level attacks such as zip bombs.
