### ISSUE TITLE
404 error for some api methods listed in the doc

### ISSUE THREAD

**Issue by teja42** [NebulousLabs/Sia#3100]
So I was playing around with the siad api and some of them seem to be returning 404 errors while others work fine. The `/renter/file/*siapath [GET]` and `/renter/stream/*siapath [GET]` paths returned 404 errors while other's worked fine. Why is that? If there are intentionally disabled, is there a way I can enable them?

I'm running siad version 1.3.2 on Linux

**Comment by MSevey** [comment]
@teja42 both those end points are features of 1.3.3 and so won't work on 1.3.2
