### ISSUE TITLE
I can not read out transactions via CLI

### ISSUE THREAD

**Issue by jensamberg** [NebulousLabs/Sia#3114]
# BUG REPORT
When I try to read out with "siac wallet transactions"
the transactions i get a error message.

**Expected Behavior**
Get the list of transactions
root@siacontainer:/siadata/Sia-v1.3.3-linux-amd64# ./siac wallet transactions

Could not fetch transaction history: parsing integer value for parameter `endheight` failed: strconv.ParseInt: parsing "18446744073709551615": value out of range
root@siacontainer:/siadata/Sia-v1.3.3-linux-amd64#

**Environment**
Linux Ubuntu
* Sia version:
1.3.3
* OS:
Ubuntu 16.04 LXC Container

**Comment by fozzysec** [comment]
Same problem here with 1.3.3 on Mac.

**Comment by DavidVorick** [comment]
I believe this has been fixed on master, we'll be pushing out a v1.3.4 probably later this week.

**Comment by MSevey** [comment]
I can confirm `siac wallet transactions` lists out transactions as expected on the latest version of master.  closing issue
