### ISSUE TITLE
Can open the Wallet after Synchronized.

### ISSUE THREAD

**Issue by HoHoward2018** [NebulousLabs/Sia#3121]
MacOS / iMac

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.203465363 seconds

Wallet: scanned to height 144169...
Wallet: scanned to height 144308...
Wallet: scanned to height 144437...
Wallet: scanned to height 144576...
Wallet: scanned to height 144684...
Wallet: scanned to height 144850...
Wallet: scanned to height 145023...
Wallet: scanned to height 145221...
Wallet: scanned to height 145350...
Wallet: scanned to height 145515...
Wallet: scanned to height 145711...
Wallet: scanned to height 145882...
Wallet: scanned to height 146081...
Wallet: scanned to height 146276...
Wallet: scanned to height 146345...
Wallet: scanned to height 146519...
Wallet: scanned to height 146702...
Wallet: scanned to height 146872...
Wallet: scanned to height 147034...
Wallet: scanned to height 147219...
Wallet: scanned to height 147399...
Wallet: scanned to height 147509...
Wallet: scanned to height 147675...
Wallet: scanned to height 147864...
Wallet: scanned to height 147995...
Wallet: scanned to height 148171...
Wallet: scanned to height 148275...
Wallet: scanned to height 148471...
Wallet: scanned to height 148623...
Wallet: scanned to height 148771...
Wallet: scanned to height 148917...
Wallet: scanned to height 149079...
Wallet: scanned to height 149266...
Wallet: scanned to height 149454...
Wallet: scanned to height 149611...
Wallet: scanned to height 149784...
Wallet: scanned to height 149993...
Wallet: scanned to height 150192...
Wallet: scanned to height 150380...
Wallet: scanned to height 150594...
Wallet: scanned to height 150812...
Wallet: scanned to height 151033...
Wallet: scanned to height 151199...
Wallet: scanned to height 151452...
Wallet: scanned to height 151660...
Wallet: scanned to height 151919...
Wallet: scanned to height 152124...
Wallet: scanned to height 152396...
Wallet: scanned to height 152657...
Wallet: scanned to height 152923...
Wallet: scanned to height 153221...
Wallet: scanned to height 153527...goroutine 1 [running]:
runtime/debug.Stack(0x1043db7, 0x0, 0xc4240ed960)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc4240edad0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7ffeefbffccd, 0xe, 0x7ffeefbffcf9, 0x5, 0x7ffeefbffce8, 0x5, 0x0, 0x7ffeefbffd4f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x53c
main.startDaemonCmd(0xc4200e5b80, 0xc42008e550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200e5b80, 0xc42001c0d0, 0x5, 0x5, 0xc4200e5b80, 0xc42001c0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200e5b80, 0x16dba5a, 0x3b, 0xc4200aba40)
	/home/luke/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc4200e5b80, 0x1b19e00, 0x16c2910)
	/home/luke/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x6fe
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.

**Comment by tbenz9** [comment]
This bug is being tracked at NebulousLabs/Sia-UI#670

It was previously tracked at #2406

There is no sure workaround that I'm aware of but you can try the instructions linked in the issues above. My understanding is this only affects MacOS. You can also try completely reinstalling Sia, only a small subset of users report this issue
