### ISSUE TITLE
# BUG REPORT

### ISSUE THREAD

**Issue by TomTramo** [NebulousLabs/Sia#3122]
# BUG REPORT

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.3252524 seconds

**Comment by MSevey** [comment]
@TomTramo this isn't a bug, this is how siad loads.  If you need help with siad please consult the help documentation or reach out to the help channel on discord.
