### ISSUE TITLE
Chrome Browser crashes with Sia UI on macOS

### ISSUE THREAD

**Issue by remic20** [NebulousLabs/Sia#3126]
# BUG REPORT

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.617104358 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043db7, 0x0, 0xc426039960)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc426039ad0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7fff5fbffd07, 0xe, 0x7fff5fbffd33, 0x5, 0x7fff5fbffd22, 0x5, 0x0, 0x7fff5fbffd89, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x53c
main.startDaemonCmd(0xc4200f5b80, 0xc42009c550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200f5b80, 0xc42001c0d0, 0x5, 0x5, 0xc4200f5b80, 0xc42001c0d0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200f5b80, 0x16dba5a, 0x3b, 0xc4200b99a0)
	/home/luke/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc4200f5b80, 0x1b19e00, 0x16c2910)
	/home/luke/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x6fe

**Stack Trace or error message**

**Crashes both Sia UI and Chrome Browser**

**If computer goes on sleep/screensaver mode for long period both application crashes. Sia UI application needs to completely shutdown before Chrome Browser to execute properly. Otherwise, Chrome will continue to crash on its own.**

**Environment**
* Sia version: v1.3.3
* OS: macOS Sierra 10.12.6

**Comment by tbenz9** [comment]
Is this stack trace truncated?  Usually, they are much longer and I'm not seeing the information I'm looking for in what you've included.

Use this guide to find your full error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

**Comment by remic20** [comment]
Yes, I truncated the bottom "critical error tcp too many files open in the system"
I got another crash, I'll paste the error log again on the next one using the guide.

**Comment by tbenz9** [comment]
Ah, that helps.

This bug is being tracked at NebulousLabs/Sia-UI#670

It was previously tracked at #2406

There is no sure workaround that I'm aware of but you can try the instructions linked in the issues above. My understanding is this only affects MacOS. You can also try completely reinstalling Sia, only a small subset of users report this issue
