### ISSUE TITLE
SIA UI WALLET will not snch , quits and gives error .. thx friends namaste

### ISSUE THREAD

**Issue by kindcrypto** [NebulousLabs/Sia#3133]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:
OSX 

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.857290951 seconds

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
