### ISSUE TITLE
Sia shutdown suddenly 

### ISSUE THREAD

**Issue by phoeniix1** [NebulousLabs/Sia#3134]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:1.3.3
* OS:Mac

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.414027106 seconds
goroutine 1 [running]:
runtime/debug.Stack(0x1043db7, 0x0, 0xc422e55960)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc422e55ad0, 0x1, 0x1)
	/home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:16 +0x93
main.startDaemon(0x0, 0x0, 0x7ffeefbffcc7, 0xe, 0x7ffeefbffcf3, 0x5, 0x7ffeefbffce2, 0x5, 0x0, 0x7ffeefbffd49, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:212 +0x53c
main.startDaemonCmd(0xc4200ffb80, 0xc4200a0550, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/daemon.go:236 +0x162
github.com/spf13/cobra.(*Command).execute(0xc4200ffb80, 0xc4200a2010, 0x5, 0x5, 0xc4200ffb80, 0xc4200a2010)
	/home/luke/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0xc4200ffb80, 0x16dba5a, 0x3b, 0xc4200c3b80)
	/home/luke/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0xc4200ffb80, 0x1b19e00, 0x16c2910)
	/home/luke/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/cmd/siad/main.go:174 +0x6fe
Critical error: accept tcp 127.0.0.1:9980: accept: too many open files in system
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
Shutdown complete.

**Comment by tbenz9** [comment]
This bug is being tracked at NebulousLabs/Sia-UI#670

It was previously tracked at #2406

There is no sure workaround that I'm aware of but you can try the instructions linked in the issues above. My understanding is this only affects MacOS. You can also try completely reinstalling Sia, only a small subset of users report this issue
