### ISSUE TITLE
Error log issue

### ISSUE THREAD

**Issue by orimar18** [NebulousLabs/Sia#3138]
# BUG REPORT

Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.765304499 seconds

**Stack Trace or error message**
error log

**Expected Behavior**
syncing wallet and stuck at 81% and then get the following error every time. 

**How to reproduce it (as minimally and precisely as possible)**
read above.

**Environment**
sia wallet on Mac.
* Sia version:1.3.3
* OS: mac os, current version.

**Comment by tbenz9** [comment]
There is no error message here, all the data you've included is normal output.

Try this to find your error message: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda
