### ISSUE TITLE
Currency Changes

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#316]
First, we need testing.

But second, the currency methods can't be pointer receivers :(

Many of the objects that contain a currency are supposed to be immutable.

Finally, c.of should be c.overflow, because I feel that your variable names should be fully spelled out inside of the data structures.

**Comment by DavidVorick** [comment]
There's a corner case around the siafund pool. Because the siafund pool is additive and never decreases, it should be okay for the siafund pool to overflow. Which puts us in a bit of a weird place, because SiafundOutputs have the siafund pool object.

So I'm thinking that the siafund pool type needs to be a big, and we'll have a (*wince*) big.Int in one of our types...

>.<

Maybe we should have just made them all big.Int in the first place.

**Comment by lukechampine** [comment]
I think this is fine as long as we can use a 1-byte length prefix :P

**Comment by DavidVorick** [comment]
fixed by #322
