### ISSUE TITLE
hmmm.. cannot restore

### ISSUE THREAD

**Issue by geoabw** [NebulousLabs/Sia#3168]
Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 2.4314961999999998 seconds

# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by MSevey** [comment]
This is how siad loads.  If you have questions on how to use siad please look at our documentation and visit the help channel on discord.
