### ISSUE TITLE
Siad has exited unexpectedly.

### ISSUE THREAD

**Issue by thePR0M3TH3AN** [NebulousLabs/Sia#3172]
# BUG REPORT

**Stack Trace or error message**
"Siad has exited unexpectedly. Please submit a bug report including the error log here.
_______
Sia Daemon v1.3.3
Git Revision 94ea84e
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 10.5141507 seconds
_______

**Expected Behavior** 
To act normally.

**How to reproduce it (as minimally and precisely as possible)**
Was uploading a folder with various files. Came back a day later and it starting flickering the above error.
The error is persistent and does continue after SiaUI restart. 

**Environment**
Home

* Sia version: 
 v1.3.3

* OS: 
Windows 10

![sia bug](https://user-images.githubusercontent.com/7219112/42973096-db2d0728-8b7f-11e8-8877-7592e1e4e477.png)

**Comment by dustyfield** [comment]
i'm having the same issue

**Comment by dustyfield** [comment]
i hit Ctl Alt Del and ended task, now seems to open fine

**Comment by IntrepidColo** [comment]
I'm having the same issue.
