### ISSUE TITLE
Sia Daemon v1.3.3

### ISSUE THREAD

**Issue by simpskat** [NebulousLabs/Sia#3175]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version:
* OS:

**Comment by EvilRedHorse** [comment]
Uptime is no longer being reported by 1.3.3

**Comment by lukechampine** [comment]
I don't appreciate being accused of playing favorites. None of the devs are currently running serious hosting operations anyway. Please keep your comments confined to your existing issue (#3141).
