### ISSUE TITLE
localhost:9980/consensus

### ISSUE THREAD

**Issue by snehap007** [NebulousLabs/Sia#3176]
After connecting the SIA daemon, I am trying to call consensus API but every time I am getting "synced: false".  please guide me to getting "synced: true" from this API.

**Comment by lukechampine** [comment]
`synced` returns true when you have downloaded the entire blockchain. It may take a few hours. You can monitor the progress by checking the `height` field.

**Comment by snehap007** [comment]
@lukechampine  thanks for the reply, can you please provide me any link to download entire blockchain?

**Comment by lukechampine** [comment]
As long as your node is able to connect to peers, it will automatically download the blockchain. You can check the number of peers with the `/gateway` endpoint.
