### ISSUE TITLE
Sia can't make dependencies Windows 7 x64

### ISSUE THREAD

**Issue by zlalvani** [NebulousLabs/Sia#323]
When running "make dependencies" on Cygwin, I get the following error: 

```
$ make dependencies
go install -race std
# cmd/cover
runtime.main_main: main.main: not defined
runtime.main_main: undefined: main.main
# cmd/vet
runtime.main_main: main.main: not defined
runtime.main_main: undefined: main.main
Makefile:63: recipe for target 'dependencies' failed
make: *** [dependencies] Error 2
```

**Comment by DavidVorick** [comment]
Hi! Thanks for trying out our project.

At this point we've never been able to make the project on Windows, we do all of our development on Linux and then cross compile. You might have better luck running Linux in a VM.

It seems like the error you are running into is a golang problem, you might not have configured golang correctly.

I should warn you, the project is not terribly usable at the moment. If you are looking to help with development, that's fantastic. If you are looking to try out Sia, it might be best to wait 2-3 weeks and check back.

**Comment by DavidVorick** [comment]
You can grab a copy of the Windows version of the software at siacoin.com

**Comment by lukechampine** [comment]
May be the same issue described here: https://github.com/golang/go/issues/7542
>this is working fine on 386. It also works fine on amd64 if you have the 386 toolchain compiled. It only fails if you have the 64-bit MinGW toolchain compiled to build amd64 binaries.
