### ISSUE TITLE
Minimizing Wallet IO

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#335]
The wallet does a lot of IO once it starts to get big, because it writes the entire file every time. We need some way to minimize this, perhaps by using append. I was also thinking we could break it into many files and then occasionally pool them together into a larger file.

Not worth worrying about for now, but needs to be in the queue of stuff to look at. This is one of those things that's definitely a problem beyond 1000 keys, and 1000 keys is pretty reasonable considering we'll make a dozen or so new keys every time we upload a file.

**Comment by Kroese** [comment]
Is there a need for the wallet to write to disk that often? If not, then its just a matter of storing the image in RAM, and if there is a need, then why is that? Can't the wallet just be regenerated from a seed of you loose it?

**Comment by lukechampine** [comment]
The wallet file is frequently written to disk as a safety precaution, to ensure that no keys are lost. If it were stored in RAM, an interrupt (or worse, a power failure) could prevent keys from being saved to disk. With the present scheme, this can still happen, but it will affect at most 1 key.

@DavidVorick can chime in on the subject of generation.

**Comment by DavidVorick** [comment]
Right now we don't support HD wallets, which is what would allow you to generate a large number of wallets from a single seed. It's the type of thing that we could implement, but we have higher priorities for the moment.

Eventually, we will be using HD wallets.

**Comment by Kroese** [comment]
It seems a weird design-choice not to just fork Bitcoin for the blockchain-stuff, so that the project can focus on the storage-proof part. Now all issue resolve around things Bitcoin already implemented years ago.

**Comment by DavidVorick** [comment]
This is true. When we originally started, we were actually doing something very, very different from Bitcoin (and consequently, very insecure).

Forking the Bitcoin code meant inheriting something like 30k lines of C++ that neither of us would understand well, at least initially. It would mean needing to deal with a lot of the bugs that can't be fixed in Bitcoin (like the off-by-one error in the Multisig opcode). Right now, because we know our entire codebase, we've got a good idea when something's not working as to what the problem is. We also get the advantages of using a garbage collected language.

On the other hand, it also means we're less familiar with the solutions that Bitcoin has come up with, it makes it harder to ask for help when there's something we don't understand, and it also means that we're inherently contributing less back to Bitcoin, to whom we owe a significant portion of our existence. Any bugs that we found or features that we added we could have PR'd back to the Bitcoin repo, which is good for everyone.

At the same time, I don't think that bitcoin core uses HD wallets. Some of the problems that we're running into have been solved by bitcoin core, and some have not. But I also think that my mastery of cryptocurrencies would be substantially lower than it would be if I had just forked Bitcoin. Especially when designing the protocol, I got to revisit a lot of the design choices of Bitcoin and needed to reconsider all of the advantages and disadvantages, and was able to learn from the 4+ years of regrets and reassurances of Bitcoin. There are a lot of design choices that the bitcoin devs wish they could change. At the same time, there are a lot that seem to have been just right. Sia has hopefully kept all of the just-right choices while improving on the less great design choices.

What it comes down to though, is at this point I think it's easier to keep using our own codebase than it is to switch to using a fork of Bitcoin.

**Comment by lukechampine** [comment]
I'm in favor of a BoltDB that maps addresses to keys. We could optionally add an "export" button that converts it to a traditional wallet.dat, but both would essentially contain the same data.

**Comment by DavidVorick** [comment]
I am assigning Luke this issue as he's going to be working on the other persist stuff. Seems like the decision we've made is to have a boltdb file that stores all of the addresses.

**Comment by DavidVorick** [comment]
fixed
