### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#340]
Things I can think of that require benchmarking:

- crypto: hashing, merkle trees, keypair generation, signing, signature verification.
- consensus: `AcceptBlock`, `ValidTransaction`, more?
- encoding: `Marshal` and `Unmarshal` for common data types, especially `Block`.
- network: `Ping`, and possibly generic data transfer speed. These are less useful because they vary so much by user.
- siad: `CatchUp`, though this probably won't be built-in, but rather manually run using the Linode as our bootstrap.

Once we're saving/loading more stuff to and from the disk, we'll want to benchmark most of that as well. I'm gonna benchmark the shit outta Bolt. B)

Feel free to add more.

**Comment by DavidVorick** [comment]
hold off on this until we've got a usable frontend.

We'll optimize the crap out of everything over the next year and a half but first stuff just needs to work

**Comment by lukechampine** [comment]
Yeah definitely not an immediate priority. I was just bugged because `TestSigning` takes 20 seconds on my laptop.
