### ISSUE TITLE
Any application can access the http api

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia#342]
It's important that, before release, we create some kind of password system for the HTTP API to prevent any application on the computer from manipulating the siad process.

**Comment by DavidVorick** [comment]
Hmm. What is the threat model we are defending against? I'm not sure how much this would protect against malware on the user's computer.

**Comment by lukechampine** [comment]
I don't think we should be seriously concerned with malware for a long time. It just isn't something that we can defend against 100%. We can make things slightly harder for them (by encrypting the wallet file, etc.) but a good keylogger is hard to thwart.
At the end of the day, you can't protect users from themselves; it's at least partially their responsibility to ensure that their computer is free of malware.

Going to close this for now. We may reopen it someday.
