### ISSUE TITLE
Transaction slices

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#343]
Transactions are composed of slices. Slices are pointers to memory. Therefore, when you pass a Transaction (even by value), the receiver can modify the Transaction's memory.

This is a potentially major problem, because we want to keep the consensus types as immutable as possible. Currently, if you pass the same Transaction to two different functions, there's no way to guarantee that they are seeing the same data.

The only method I can think of for dealing with this is defining a new Transaction method, `Copy`, which would return a newly-allocated copy of that Transaction. Even then, we need to be vigilant about copying Transactions before sending them around.

This issue may affect other parts of the codebase as well. Essentially, we need to be really careful when using slices.

**Comment by DavidVorick** [comment]
:(
