### ISSUE TITLE
SendBlocks doesn't pull from currentPath

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#346]
SendBlocks calls `HeightOfBlock` to determine which of the received block IDs has the highest BlockHeight. However, `HeightOfBlock` checks the State's `blockMap`, not its `currentPath`, which means the "highest ID" may be on a different fork. We need a way to ensure that the highest ID is in the `currentPath`.

I also think it should be possible to fetch the blocks-to-be-sent more efficiently. Right now it happens in a loop that calls `BlockAtHeight`, which requires a lock, map lookup, and unlock for every call. A function like `func (s *State) BlockRange(start, end BlockHeight) ([]Block, error)` would be vastly better. I'll probably do this when I change `currentPath` to a slice -- i.e. not for a while :P

**Comment by DavidVorick** [comment]
It's a bit dirty, but right now the fix for this is to call `BlockAtHeight` after calling `HeightOfBlock` and checking that they match. If not, you do the same thing as if `BlockAtHeight` had returned !exists.

**Comment by lukechampine** [comment]
fixed in #378
