### ISSUE TITLE
Magic bytes

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#347]
Bitcoin prefaces all network messages with 4 "magic bytes." This is primarily used for confirming that the nodes are sending Bitcoin protocol data and not some other protocol. Another interesting use case, however, is that it allows the receiver to seek to the next message when the stream state is unknown. That is, if the message is corrupted for any reason, you can simply discard bytes until you see the 4 magic bytes again.

I'm still not 100% convinced this is necessary for Sia; non-protocol messages should be rejected pretty quickly anyway. As for the latter use, almost all of our messages are sent 1 per connection, so if there's an error the connection will simply be closed.

Bitcoin also prepends each message with a double SHA of its contents, presumably as a more rigorous checksum. I believe we discussed this previously and concluded that the built-in TCP checksums are sufficient, at least for now.

**Comment by DavidVorick** [comment]
I don't see the need to use magic bytes or attach a cryptographic checksum.

**Comment by lukechampine** [comment]
I agree, but I'm leaving it open because magic bytes seem to be very widely used. I'll close this if we can be sure that they don't benefit us at all.

**Comment by DavidVorick** [comment]
closing this because it's very much on the backburner. Mental backburner is good enough, doesn't need an issue open.
