### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by cyrozap** [NebulousLabs/Sia#351]
The `make dependencies && make` that Travis does doesn't seem to be enough to get a dev environment set up on Arch--some documentation would be helpful to help developers get started on the project.

**Comment by DavidVorick** [comment]
Hmmm. We've tried our best to make it sufficient to run `make dependencies && make`, however we might have missed a few things.

One thing that is required is a working go environment, and I think you need 1.3 or later. This should probably be added to Developers.md.

Can you post the errors you are getting?

**Comment by cyrozap** [comment]
I'm running Go 1.4.2, so the version shouldn't be a problem. Where I'm having issues, though, is getting the dependencies installed and, after messing around with the Makefile to get that to work, running `make` on the project. It appears as though the `go install -tags=dev ./...` step fails when it can't find any of the subpackages in `$GOROOT` or `$GOPATH`. That's the only step I'm stuck on. I fixed the `make dependencies` issue by commenting out `go install -race std` and `go get -u golang.org/x/tools/cmd/cover` since they seemed to conflict with Arch's packaged distribution of Go.

Here's a sample of the errors I get running `make`:

```
consensus/fork.go:4:2: cannot find package "github.com/NebulousLabs/Sia/crypto" in any of:
	/usr/lib/go/src/github.com/NebulousLabs/Sia/crypto (from $GOROOT)
	/home/cyrozap/.go/src/github.com/NebulousLabs/Sia/crypto (from $GOPATH)
```

**Comment by DavidVorick** [comment]
oh. This happens if you're using a sim link. I'm not sure how to fix it, so I just set up bash aliases to cd to the Sia folder. I'll add this to the documentation if I can't find a better solution.

**Comment by cyrozap** [comment]
I don't have any symlinks in either of those paths, so I don't know why I'm getting that error. Once I do, though, I'll write a small how-to on avoiding this issue.

**Comment by DavidVorick** [comment]
It's difficult for me to guess without seeing your machine, but did you make sure to call `git clone` in `$GOPATH/github.com/NebulousLabs`? Simply cloning Sia into the gopath isn't going to be sufficient, that's also not documented anywhere.

**Comment by cyrozap** [comment]
Ah, I see, I needed to clone Sia inside that path and work on it in there.
