### ISSUE TITLE
Gateway behavior tweak

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#354]
The gateway should only broadcast blocks and transactions that are valid. To help make this an inherent property, I'm tweaking the behavior a bit.

The gateway will only broadcast blocks as they are added to the consensus set. This essentially means listening on a state subscription and doing a broadcast whenever new blocks appear in the BlocksSince() function. When the gateway receives blocks, it just uses them to call AcceptState(), and doesn't do anything more (error or not). If it's a block that should be broadcasted, it'll appear in a BlocksSince call a few seconds later.

For transactions, the transaction pool will import the gateway, and call RelayTransaction() whenever a transaction is accepted. I know this is backwards from how the state does things, but you can't really subscribe to the transaction pool because the structure is much less formal.

If invalid blocks or transactions start getting broadcasted, DoS vectors open up.

I'm working on this now, just wanted to explain where the changes are coming from and why.

**Comment by lukechampine** [comment]
??? isn't this already the case?
```go
func (g *Gateway) RelayBlock(b consensus.Block) (err error) {
	err = g.state.AcceptBlock(b)
	if err != nil {
		return
	}
	g.broadcast("RelayBlock", b, nil)
	return
}
```
`RelayBlock` will return if the state doesn't accept the block.
