### ISSUE TITLE
Rename all 'mu' to 'mutex'

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#355]
we're probably going to want to pull this tooth sooner rather than later.

Maybe there's something fancy we can do with awk or the go rename tool to make it not so bad.

**Comment by lukechampine** [comment]
I don't see the need. If it's good enough for the stdlib, it's good enough for us. `mu` only ever appears in the code when it's being locked or unlocked. Its meaning is unambiguous.

**Comment by DavidVorick** [comment]
:(

**Comment by DavidVorick** [comment]
hm
