### ISSUE TITLE
Siad Testing

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#362]
Using only siad, and where it makes sense, using only API calls, you should test the following things:

- [x] Can you start the miner? Does it mine blocks? Does the wallet balance change as it mines blocks? (with the test constants, the outputs are not given to you for 3 blocks, so mine at least 4 before checking that the balance has increased)
- [x] Can you send coins to another address? Does the first balance decrease? Upon receiving coins, does the balance increase?
- [x] Can the host announce itself to the blockchain? When it does, does the hostdb update and add the host to the hostdb?
- [x] Can the renter upload a file? Once it has uploaded, can it be downloaded? Can you check the status on the download in progress? Does the renter's balance decrease after uploading the file?
- [x] Does the host report having new contracts after a renter has uploaded a file? Once the file contract ends, does the host's balance increase appropriately?
- [x] Do unconfirmed transactions appear on everyone's machine? Does the transaction broadcasting work right?
- [x] Do blocks appear on everyone's machine? Does block broadcasting happen correctly?
- [x] Does a bootstrapping party catch up immediately? What if there are 2500 800kb blocks to download?
- [x] Do peers propagate well enough? If someone joins the network, will everyone get the new peer? Will people stop collecting peers before they are broadcasting to an unreasonable number of people?

I think that this will cover everything well enough. But I'm not sure how you're going to manage testing the stuff that happens asynchronously. We might need to do some of these tests outside of go.

**Comment by DavidVorick** [comment]
Synchronize is broken. Mostly, it seems like it's not being called, but if you look at the synchronize function there seems to be TODOs that are incorrect.

**Comment by DavidVorick** [comment]
So, using the channels was good for simple situations, but it started giving me problems, I think I was using them incorrectly or something (making calls but not checking the channels).

I've replaced it all with the spinning method of synchronizing for now (just checking and sleeping in a for loop). The disadvantage to that approach is that, while it'll make sure stuff works if everything is working, the output (a several hundred thread panic) isn't terribly useful in the event that things aren't correct. You don't get helpful information and the timer might explode somewhere that's not looping forever.

I think a better solution (if we continue using spinsync) is to have the spinsync call panic itself after a second or so, and then just not include any spinsync tests in the short tests. Then we at least see where the panic was called, which is going to be nearly as useful as a t.Error or t.Fatal

**Comment by lukechampine** [comment]
I think we'll be able to improve this if/when we make siad a module. Then we could pass in a special "testing Gateway" that tracks RPCs.

**Comment by DavidVorick** [comment]
done
