### ISSUE TITLE
Eliminating host config parameters

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#374]
My thought is that we should remove some of the items from the host configuration, and let the host figure those out automatically. These are currently the configuration items supported by the API:

TotalStorage
MinFilesize
MaxFilesize
MinDuration
MaxDuration
Price
Collateral

I propose we reduce them:

TotalStorage
MaxDuration
Price
Collateral

Where both price and collateral can either be ints or the string "auto". If they are set to auto, the host will automatically determine the most profitable price and collateral to set based on the network conditions. (not recommended at first, b/c people can currently easily spoof supply and demand.)

**Comment by DavidVorick** [comment]
The same should probably follow for what is returned when "/host/status" is called. I don't think we should simplify the interfaces though, because the modules need more information than the user does. I just want to simplify the api.

**Comment by lukechampine** [comment]
How will power users change these parameters?

**Comment by DavidVorick** [comment]
Something like optimal MinDuration is pretty easy to calculate I would think. Same thing with the file sizes. I don't think a power user actually has much chance of doing it better than the host would automatically, they'd only risk setting worse values.

Not sure though.

**Comment by DavidVorick** [comment]
I decided we should leave them.
