### ISSUE TITLE
Error could not unmarshal type []wallet.savedKey

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia#375]
```
Warning: config file not found. Default values will be used.
Failed to create daemon: could not unmarshal type []wallet.savedKey
```

**Comment by lukechampine** [comment]
This seems to happen if/when the wallet file gets corrupted. Deleting it should fix the problem. We should implement safer wallet management though.

**Comment by DavidVorick** [comment]
Yes let us just delete the wallet.

=/

Maybe there's something we can do in the Load() function to more gracefully handle wallet corruption. And we really should be keeping 2 backups of the wallet file, of which only 1 is open at a time.

We should implement this today.
