### ISSUE TITLE
change upload parameters for renter

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#390]
Instead of accepting a readerseeker, I think it should accept a filepath. This allows it to look at the file later, and potentially upload the file later. It does mean that you'll need siad and that you can't use a web browser interface.

But we've got atom-shell now, which solves that problem. I think that the advantages of having the original filepath when trying to do things like repairs are greater than the disadvantages of not having the more general solution.

**Comment by lukechampine** [comment]
agreed. `ReaderSeeker` was a nice solution for the problem we had, but it's no longer necessary. This should go hand-in-hand with formally removing the multipart ("datastream") upload API call.

**Comment by DavidVorick** [comment]
I'm going to close this issue as premature.
