### ISSUE TITLE
Marshal does not panic on unexported struct fields

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#393]
Bizarrely, it seems to simply deadlock instead. This behavior made it particularly difficult to track down a certain bug.

**Comment by lukechampine** [comment]
hmm. What's strange is that it *should* already be panicking; the docstring of [`Interface`](http://golang.org/pkg/reflect/#Value.Interface) says it will panic if called on an unexported field. So I'm not quite sure why this is happening.

**Comment by DavidVorick** [comment]
this would appear to be fixed.
