### ISSUE TITLE
Download quotum

### ISSUE THREAD

**Issue by kroese** [NebulousLabs/Sia#399]
Renters should be able to agree upon a numbers of downloads in the contract with the host. That way the host can adjust pricing based on how many times it will be accessed.

But more importantly, the host and the renter can construct a proof of a download, I call it a fetch-proof. This is signed by both sides, and if the host adds it to the chain it automaticly cancels out the next storage-proof.

Now you can make a contract that says: 

   - Store this for 50 years OR 1 download. 

Now the host has an incentive to upload the file instead of asking a free, because else he has to keep it around for 49 years because of the storage-proof.

**Comment by DavidVorick** [comment]
This is already supported by the protocol thanks to contract terminations. After a certain number of downloads, the host and renter can sign a contract termination and replace it with a different, shorter contract or something that pays more money.

**Comment by DavidVorick** [comment]
The new renter-host relationship structure (coming in a few months) will completely change how downloads work.
