### ISSUE TITLE
All peers can be lost

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#417]
Sometimes the linode will be the only peer, and sometimes there will be no peers at all.

Just like we continuously synchronize, we should have backup plans for the cases where all peers get removed (perhaps the linode or other hardcoded peers are automatically readded). Also, there should probably be some behavior where the linode is occasionally re-queried for a peer list.

TL;DR: the peerlist is still pretty fragile, we need some way to beef so peers don't get disconnected from the network. A secondary goal would be making malice difficult.

**Comment by DavidVorick** [comment]
Is this still a problem?

**Comment by lukechampine** [comment]
The gateway doesn't remove peers anymore, and it will continuously try to form connections, so this is no longer a relevant issue. We just have to remain careful in the future not to ban peers too aggressively.
