### ISSUE TITLE
Gateway failure modes

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#421]
The gateway is occasionally kicking all peers, which desynchronizes the network the isolates peers. The gateway needs some sort of failure mode that it regularly checks (perhaps every time a peer is potentially removed? Or perhaps a gothread that just runs a check every 5 minutes?) if there are peers available.

If there are less than 3 peers, it re-adds all the peers that it knows, even the abusive ones, giving priority to the hardcoded peers and the user-input peers.

The network is still a pronounced weakpoint of the software.

**Comment by lukechampine** [comment]
The gateway no longer kicks peers; if you lose a peer, it's because your connection to them was lost. When we bring back the strike/banning code, we'll be careful not to remove peers when we fall below the "well-connected" threshold.
