### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by charlesvickery** [NebulousLabs/Sia#433]
I want to use [Sourcegraph](https://sourcegraph.com) for Sia code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/NebulousLabs/Sia. (It should only take 30 seconds.)

Thank you!

:+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by DavidVorick** [comment]
wish granted
