### ISSUE TITLE
siad catches interrupt during testing

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#439]
If you try to abort a test with ^C, siad (actually, graceful) will catch it, so you have to interrupt it twice.
This could be fixed by not catching the interrupt if the `testing` build tag was set.
graceful has been bugging me in general, so maybe we should switch back to the standard http server and implement the necessary functionality ourselves.

**Comment by DavidVorick** [comment]
I remember that we switched to graceful because we were having problems, but I don't remember what the problems were. I would be happy to reduce the dependency graph of our project.
