### ISSUE TITLE
Notes from local test (gateway)

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#446]
Steps:

**1:** Start mining on :9971

**unwanted result**: :9971 added the linode as a peer, even though :9971 is running dev constants and the linode is running release constants. This is true for all other nodes I ran too.

**2:** Add :9981 as a peer to 9971

**unwanted result**: 9981 is not catching up, despite being sent blocks

:9981 log file has a lot of entries like this:
```
2015/04/19 13:31:45.274430 rpc.go:123: INFO: handling RPC "AcceptBl" from 127.0.0.1:44647
2015/04/19 13:31:45.274487 rpc.go:125: WARN: incoming RPC "AcceptBl" failed: block has no known parent
2015/04/19 13:31:45.274497 synchronize.go:42: INFO: synchronizing to 127.0.0.1:44647
2015/04/19 13:31:45.274597 synchronize.go:47: ERR: synchronization to 127.0.0.1:44647 failed: dial tcp 127.0.0.1:44647: connection refused
```

**3:** Add :9971 as a peer to :9991 

**unwanted result**: :9991 is not synchronizing. I had to call 'synchronize' manually. After manually calling synchronize, things seem to work.

**unwanted result**: :9971 does not have :9991 as a peer. Perhaps being on localhost is corrupting things, my ports aren't forwarded so any attempt to contact the actual IP address won't work. (it might be nice to have :9971, :9981, and :9991 all forwarded to 10.0.0.11)

**4:** Add :9971 as a peer to :9981. Set :9971 to :9981's only peer. The 2 minute re-sychronize loop should synchronize them eventually.

**unwanted result**: synchronization does not happen, even after waiting 10 minutes. Resynchronization loop is broken

**5:** Call synchronzie manually for everyone. Everything catches up. As :9971 has :9981 as a peer, :9981 remains caught up. :9991 falls behind immediately. Does not catch up.

The resynchronize loop is broken.

**6:** Close and restart :9981. Reload. :9981 has :9971 as a peer. :9971 also has :9981 as a peer. :9981's previous blocks have all loaded.

**unwanted result**: upon loading, the gateway does not call 'synchronize'.  :9981 is stuck at a lower block, despite being sent new blocks.

=========

Other notes:

calling 'synchronize' manually didn't always work the first time when the linode was also a peer. Sometimes I had to call it a few times to get the synchronization to happen.

Once the peer graph was fully connected, things stayed synchronized. But I had to manually add all of the peer connections.

When restarting, it sometimes took a while for the api to become responsive. Maybe 3-5s. There was no message indicating that that the api was not yet ready, and no message indicating when the api was finally ready. My guess is that isn't not responsive b/c it's loading all the blocks from the database and processing them all. It's probably better if the program can accept requests before it's done loading.

**Comment by lukechampine** [comment]
I suspect a number of these problems may be caused by having the linode as a peer. You're definitely right that we need some way to prevent peers with different constants from adding each other. (Bitcoin uses an initial "version" message to accomplish this.)

**Comment by lukechampine** [comment]
Okay, I've mostly reproduced this. I think the main confusion has to do with peer connections. Specifically, when you add a peer, that peer doesn't automatically add you back. (This will change with my next PR.) This means that you won't receive blocks from them, and thus no synchronize will be triggered.
The random port issue is still a mystery though. I'm looking into it now.

**Comment by lukechampine** [comment]
ugh. Each dial uses a random outgoing port. Seems so obvious in retrospect.
So basically I need to get persistent connections working ASAP.

**Comment by DavidVorick** [comment]
I tried with the new code:

1. connect :9971 to :9981. They each add eachother.
2. connect :9991 to :9971. They each add eachother.
==> :9991 and :9981 don't see eachother, even though they have a peer in common.

Ideally :9991 and :9981 would find eachother through :9971.

----

(unrelated) the hostdb completely failed :(. I couldn't get anyone to find a host. So that's going to be my day tomorrow.

**Comment by DavidVorick** [comment]
Things seem better now.
