### ISSUE TITLE
Use in-memory database during (most) tests

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#454]
The disk I/O incurred by BoltDB is dramatically slowing down tests. It's true that we want the database to be well-tested, but it should be possible to do this without slowing other tests. Otherwise, any test that interacts with the database will need to be marked as a long test.

**Comment by DavidVorick** [comment]
I'm not sure how ramdisks work but it might be possible for us to mount ram to one of the /tmp folders.

**Comment by DavidVorick** [comment]
I'm closing this as 'low priority'.

Not that we don't need it, but we have 10 million things to do and I'm trying to keep the focus as narrow as fits the size of our engineering team.
