### ISSUE TITLE
RPC errors

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#460]
déjà vu?

in general, it would be nice to know *why* your RPC failed. In certain cases, the error may be vague or even inaccurate (to prevent certain attacks), but it's still better than `"no data"`.

I'm imagining a monadic-style system where you can set an error value at any point during communication, and further reads/writes will be no-ops. We'll see.

**Comment by DavidVorick** [comment]
Can you provide an update on this issue? How relevant is it, how important is it long term, etc.

**Comment by lukechampine** [comment]
At this point I don't think they're going to be implemented. As we saw with contract negotiation, remote error messages can be dangerous for both parties. If your errors are too descriptive, you can leak information, making yourself vulnerable to future attack. And if you branch on a received error, you open yourself to manipulation by parties who lie about their error message. So I'm going to pass on this.
