### ISSUE TITLE
use POST for /renter/files/loadascii (and others)

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#467]
URL length restrictions will likely prevent pasting a large .sia file into a query string. It makes more sense to use a POST request here anyway. Wikipedia says:

>POST's place in the range of HTTP methods is to send a representation of a new data entity to the server so that it will be stored as a new subordinate of the resource identified by the URI. For example, for the URI `http://example.com/customers`, POST requests might be expected to represent new customers.

However, POST's use has since expanded to cover any "non-idempotent" operations, i.e. those with side-effects. As such, I think we should use POST for the following calls:
- `/consensus/synchronize`
- `/daemon/stop/`
- `/daemon/updates/apply`
- `/gateway/peers/add`
- `/gateway/peers/remove`
- `/host/configure`
- `/miner/start`
- `/miner/stop`
- `/renter/files/delete`
- `/renter/files/load`
- `/renter/files/loadascii`
- `/renter/files/rename`
- `/renter/files/upload`
- `/wallet/send`

**Comment by DavidVorick** [comment]
some of those calls don't take any input. Does using POST change anything?

**Comment by lukechampine** [comment]
it will change the semantics of how they are called, and it will change the specific bytes that are sent to the server.

**Comment by DavidVorick** [comment]
this is fixed?

**Comment by lukechampine** [comment]
loadascii still uses the query string. The others are fixed though.
