### ISSUE TITLE
Synchronize to new peers

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#469]
The current gateway+consensus architecture makes it difficult for the State to call `Synchronize` on new peers. This is because the State has no way of knowing when a new peer connects, except by polling the gateway's `Peers` method. The current solution is to simply rely on `threadedResychronize` to eventually (i.e. within 2mins) sync to a peer.

One way to solve this would be to add a `RegisterConnectRPC(rpc string)` (or similar) method to the gateway. This would tell the gateway to call `rpc` on new peers as soon as they are connected. I think the gateway might benefit from using this internally as well.

Another approach would be to add update architecture to the gateway. The State would then have to wait on the update channel, call the `Peers` method, figure out which peer was added, and call `Synchronize` on it.

Both of these approaches seem a bit overkill; I don't think any modules besides consensus will use `RegisterConnectRPC`, and I'd really rather avoid mucking up the gateway with update architecture just for the sake of one feature.

A third approach would be to keep the polling, but do it more intelligently. The State could actively "keep tabs" on each peer, storing information such as their block height and last synchronize time. It could poll more frequently during initial startup and then level off.
 
Perhaps the best thing to do for now is to simply decrease the `threadedResychronize` loop time to 30 seconds.

**Comment by lukechampine** [comment]
I think `RegisterConnectRPC` is the way to go. There are now three RPCs we want to call on connect:
- Tell the peer our callback address
- Ask the peer for its node list
- Synchronize to the peer
IMO, this is enough to make the abstraction worthwhile.

**Comment by DavidVorick** [comment]
Okay. But after this next release.

**Comment by lukechampine** [comment]
That's what the long term tag means

**Comment by DavidVorick** [comment]
I missed that, sorry
