### ISSUE TITLE
update directory

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#483]
The current update model assumes that `siad` and `siac` are being run from the same directory that the binaries are in. This is obviously broken when you are running them from your GOPATH, and more importantly when you are running them via Sia-UI.

It should be relatively easy to do this using the [osext](https://github.com/kardianos/osext) package.

**Comment by DavidVorick** [comment]
Even more high priority is getting signed updates working.

**Comment by lukechampine** [comment]
fixed by 038c476172772e0e608c566b7c629f97534397f2
