### ISSUE TITLE
Siad exits without internet connection

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#485]
Siad seems to exit if there's no internet connection. This is a problem because it makes the UI unusable.

**Comment by lukechampine** [comment]
Probably due to the [gateway](https://github.com/NebulousLabs/Sia/blob/master/modules/gateway/gateway.go#L122).

Clearly Sia is pretty useless without internet, but we should at least support viewing the wallet balance, and maybe mining.

**Comment by lukechampine** [comment]
This is no longer the case.
