### ISSUE TITLE
Don't relay blocks during synchronize

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#486]
The linode's gateway.log is full of thousands of lines of duplicate blocks being rejected. Even worse is that each entry corresponds to a full block being sent over the network. So essentially when a peer downloads the blockchain from the linode, the linode winds up downloading the blockchain from the peer too. This obviously won't scale.

As always, the Bitcoin approach: https://en.bitcoin.it/wiki/Satoshi_Client_Block_Exchange#Long_Orphan_Chains

It seems like it would be beneficial for peers that are catching up to help out peers that are behind them, but I see that more as an optimization than a must-have.

**Comment by DavidVorick** [comment]
I believe that you also broadcast all of the blocks every time you load them from disk. I plan on addressing this when I add testing to the consensus package. I'm thinking that there will be multiple functions for checking blocks and transactions.

There's also a need to verify blocks without checking the block header (ie just a bundle of txns)

**Comment by DavidVorick** [comment]
fixed
