### ISSUE TITLE
Gateway Peer Spreading

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#491]
When ports are forwarded, peer spreading seems to work very well.

When ports are not forwarded, it seems to be buggy. My laptop set up on port :9951, which was not forwarded. It immediately found the kimsufi, the linode, and luke's desktop. After a good deal of extra time, no additional peers were discovered. My desktop was available and had ports forwarded though.\

Perhaps the problem is that, despite being on port :9961, my desktop was advertising itself at :9981? 

I can probably leverage Josh tomorrow to get more data. His ports are forwarded.

**Comment by lukechampine** [comment]
things get weird when you have multiple peers behind the same IP. Still, you should have been able to connect to your desktop. Hmm.

**Comment by DavidVorick** [comment]
It seems like whatever loop is in charge of reaching out and finding nodes when you are below 8 is not working.
