### ISSUE TITLE
"too many files" host bug

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#493]
When starting siad:
```
open host/3: too many open files
open host/10: too many open files
```
Not sure what's causing this.

**Comment by DavidVorick** [comment]
I was getting this problem from the gateway.

I think that it has something to do with loading all of the blocks at once. They all get broadcast, which opens a bunch of connections, which perhaps count as open files?

**Comment by lukechampine** [comment]
using `lsof -p $(pgrep siad)` I believe I have traced this back to the host. I'm seeing hundreds of entries like:
```
siad    13479 luke 1013u  IPv4 73713444      0t0     TCP 10.0.0.12:50741->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1014u  IPv4 73713445      0t0     TCP 10.0.0.12:50742->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1015u  IPv4 73713446      0t0     TCP 10.0.0.12:50743->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1016u  IPv4 73713447      0t0     TCP 10.0.0.12:50744->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1017u  IPv4 73713448      0t0     TCP 10.0.0.12:50745->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1018u  IPv4 73714256      0t0     TCP 10.0.0.12:50746->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1019u  IPv4 73714257      0t0     TCP 10.0.0.12:50747->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1020u  IPv4 73714258      0t0     TCP 10.0.0.12:50748->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1021u  IPv4 73714259      0t0     TCP 10.0.0.12:50749->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1022u  IPv4 73714260      0t0     TCP 10.0.0.12:50750->178.130.36.81:9982 (SYN_SENT)
siad    13479 luke 1023u  IPv4 73714261      0t0     TCP 10.0.0.12:50751->178.130.36.81:9982 (SYN_SENT)
```

9982 is the default host port, so I assume it has something to do with the host pinging hosts too frequently.

**Comment by DavidVorick** [comment]
huh.

That might also be why I'm getting 'no hosts found' errors after restarting. Good catch, I'll look into it.

**Comment by lukechampine** [comment]
seems to be caused by `insertHost`. For some reason it's trying to insert way more hosts than expected. Add a println to `insertHost` and restart siad, you'll see what I mean.

**Comment by DavidVorick** [comment]
threadedScan() opens up to 300 connections simultaneously. Is that too many?

It only runs every few hours. I could make it run more often and scan fewer connections each time.

**Comment by lukechampine** [comment]
I think the default maximum is 1024 open files, so 300 should be okay. Nothing else in the codebase opens nearly that many files.
