### ISSUE TITLE
Add getwork/submitblock API for external miners

### ISSUE THREAD

**Issue by cyrozap** [NebulousLabs/Sia#494]
This was touched upon in #325, but I thought it might be good to make this a separate issue since it'll be easier to get an API for this working first than it'll be to implement an OpenCL miner.

**Comment by DavidVorick** [comment]
I was thinking about this more, and I think these api calls make sense:

'/miner/blockforwork'
```
Block types.Block
MerkleRoot crypto.Hash
Target types.Target
```

'/miner/submitblock'
```
Block types.Block
```

In blockforwork, the parentid and the nonce can be found inside of the block. (Block.ParentID and Block.Nonce). Though the merkle root can be derived from the block, we're not sure if the miner has the right libraries to calculate the merkle root correctly, so we just give it as a freebie.

When a block is found, you just provide the winning block. All that's changed from the original block is the nonce.

---

One more requirement - every block returned by /miner/blockforwork must be unique. This can be easily achieved by adding a single transaction to the begginning that is empty except for the 'Arbitrary Data' field, which has a single random 16 byte string. Doing this means that the miner can request as many blocks as it wants and always start from nonce 0 without risking any overlapping computation.

**Comment by DavidVorick** [comment]
In light of Forest and I getting confused at little endian, I've added an optional argument, 'Nonce', to submitblock. The nonce will be ignored if zeroed out.

**Comment by lukechampine** [comment]
we should probably just change the nonce type in the block to a `[8]byte`. There's no real reason for it to be a `uint64`, other than that it makes it easy to increment.

Performing a little-endian conversion is not difficult though. In C it's annoying because I don't think there's a builtin function to do it, but it's just a google search away.

**Comment by DavidVorick** [comment]
it's even more annoying when writing an fpga or an asic - you're basically manipulating logic gates

**Comment by cyrozap** [comment]
FPGAs can actually do bit-order manipulation fairly easily, so I wouldn't worry about it. Either way, there will be a program in-between siad and the FPGA anyways, so as long as the FPGA gets something it can change, it doesn't matter whether it's BE or LE. The Python program I'm using to talk to my FPGA can handle the data as it's in this patch just fine. I don't think the `nonce` parameter in the `submitblock` API will be necessary since as we found out, my issues are with the FPGA generating non-deterministic hashes, not the nonce.
