### ISSUE TITLE
Testnet -> Fullnet Turbulence

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#495]
Everybody's persistence stuff is going to be for the testnet.

I think the only ones that really cause problems are Host and Consensus, the rest of everything should be fine to not replace.

But there should probably be something that checks the genesis block and deletes/replaces the folders if and only if they are for the pre-June 7th testnet.

**Comment by lukechampine** [comment]
yeah, this occurred to me too. Isn't this what the version numbers are for though?

**Comment by DavidVorick** [comment]
Are we ready for things to be moved from testnet to fullnet? We should test this.

**Comment by lukechampine** [comment]
Most of the modules do not support loading older versions of their persist files. IMO we should just tell people to start fresh (i.e. full reinstall). There isn't much value in carrying over the old persist data.

**Comment by DavidVorick** [comment]
I'm just worried they get errors and can't start the program, not that they will be losing data.

**Comment by lukechampine** [comment]
right, but that will only happen if they're running the new Sia-UI with the old persist data, which we can deter by telling people to delete their old Sia-UI folder first.

In the future, we'll have to support this sort of thing. It just may not be feasible for this release.

**Comment by DavidVorick** [comment]
well, this happened and it didn't go poorly.
