### ISSUE TITLE
Pointless address sharing

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#499]
If a peer is behind NAT, there's no reason for it to share it's callback address, since you won't be able to connect to it anyway. So ideally only port-forwarded peers would advertise their address. But how do we tell when we're port-forwarded? Maybe try to dial ourselves?

**Comment by DavidVorick** [comment]
looking at the gateway peer list suggests to me that you fixed this?

**Comment by lukechampine** [comment]
Nah, that won't really tell you anything. If you look at gateway/nodes.json, you'll see it's full of `:9981` addresses, even though most of those aren't connectable.

**Comment by DavidVorick** [comment]
oh

**Comment by DavidVorick** [comment]
This is fixed by ignoring people from the same ip address?

**Comment by lukechampine** [comment]
lol no, it's a separate issue. The only way to fix this is to check that an address is reachable before sharing it.

**Comment by DavidVorick** [comment]
oh sorry, I thought this was the double-address thing

**Comment by lukechampine** [comment]
duplicate of #618
