### ISSUE TITLE
gh-pages download page

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#509]
Right now the footer has 6 downloads. I like this, but I think we should also have a download page linked from the footer, because in total we have 13 downloads (6 for the UI - 64 + 32 bit, and 7 for siad, because we also support ARM).

**Comment by lukechampine** [comment]
We could just add a "Other platforms" link for UI and siad that just links to the github release pages.

**Comment by DavidVorick** [comment]
That might be sufficient. We should indicate that the direct links are 64 bit
