### ISSUE TITLE
Download queue duplicates

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#529]
The UI gets confused when the download queue contains duplicates, i.e. the same file download to the same destination. Namely, it won't show a progress bar for the download at all.

Perhaps the download queue should only show downloads that are in progress. Once `Download` is synchronous, you can simply wait for it to complete to determine when the download is finished.

**Comment by DavidVorick** [comment]
I think that the downloadqueue should have finished downloads. It's useful to see the stuff you queue'd that you forgot about, especially once we get something like Sunfish integration.

**Comment by lukechampine** [comment]
maybe the solution is to add a "date/time downloaded" field. That's how most download histories work after all. (e.g. Firefox)

also, if we want to use the download queue as a full download history, it should be saved.

**Comment by DavidVorick** [comment]
both those sound reasonable to me.

**Comment by lukechampine** [comment]
partially implemented in #532, but the UI still seems to have issues when you download the same file to the same location. I'll look into it more, but I think it's a UI bug now, not a siad bug.
