### ISSUE TITLE
[IDEA] Use STUN to get ip?

### ISSUE THREAD

**Issue by whitj00** [NebulousLabs/Sia#534]
https://github.com/NebulousLabs/Sia/blob/a1bfa27056099b351e6fb870e98e21e19e8c5607/modules/gateway/gateway.go#L128

If this is cool, i'll can code it

**Comment by lukechampine** [comment]
The plan right now is to do what Bitcoin does and use UPnP for both port-forwarding and IP discovery. gmaxwell weighed in on STUN here: https://bitcointalk.org/index.php?topic=134731.0

Keep in mind that the IP itself is useless if your ports aren't open. We can also discover our external IP just by asking peers that we make outbound connections to. STUN requires centralized servers, so we'd like to avoid it.
