### ISSUE TITLE
Include genesis hash in peer connection protocol

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#539]
Peers should require a matching genesis hash before connecting to each other. This should be done separately from the version.

**Comment by DavidVorick** [comment]
We cannot make a testnet until this issue is resolved

**Comment by lukechampine** [comment]
hmm. I still can't think of a good way to hard-code it into the connection protocol. We could, however, add it as an `OnConnectRPC`, supplied by consensus, just like `Synchronize`. Then you would just forcibly disconnect any peer that did not supply the right hash. This definitely feels like a hack though; we shouldn't be connecting in the first place.
Perhaps better would be to use a special version string for the testnet. It's not a perfect solution, but it would work well enough.

**Comment by DavidVorick** [comment]
It feels like a hack to ask them what their genesis block is?

**Comment by lukechampine** [comment]
The hack aspect is that we connect and then immediately disconnect instead of just rejecting the connection outright. Also, I'm not what the consequences are of disconnecting while other RPCs are running (though I suspect it wouldn't be a big deal).

Ideally, nodes on the testnet would only know about other testnet nodes.
...
wait, so why can't we run a testnet now? If you bootstrap to a testnet node, then you'll only get other testnet addresses, so what's the problem?

**Comment by DavidVorick** [comment]
Only as long as nobody switches between networks, like I would be doing. Once my ip address is in the testnet, peers will connect to me because I'll be in the peer list.

When I disconnect and switch to prodnet, peers from the testnet will still connect to me because I'm in the full list of possibly connectable nodes. Then the entire prodnet ip list will be dumped into the testnet lists.

**Comment by DavidVorick** [comment]
as discussed in meatspace, it will be sufficient to use a '-testnet' (or some other suffix) when communicating as a node that's not trying to connect to the production network.

**Comment by VoidingWarranties** [comment]
Going through old issues...

What do you mean use '-testnet' as a suffix? Suffix to what?
