### ISSUE TITLE
Progress bar for larger file does not move

### ISSUE THREAD

**Issue by rj134a** [NebulousLabs/Sia#543]
I am on Windows. I uploaded a 350MB file and 14MB file successfully. When I download the 14MB the progress bar fills up correctly and the file downloads successfully. When I try to download the 350MB  file the progress bar does not show any movement. The file shows up on the desktop but stays at 0 bytes even after a while. However, if after a while I choose to download the smaller 14MB file which of course it does successfully, it seems to trigger the previous 350MB file to show as completed and sure enough on the desktop the file now says 350MB and is completed.

**Comment by DavidVorick** [comment]
Thanks for reporting this, we will look into the problem.

**Comment by lukechampine** [comment]
My hunch is that this is caused by the ["duplicate download" bug](https://github.com/NebulousLabs/Sia/issues/529), or something similar.

**Comment by DavidVorick** [comment]
@lukechampine has this been resolved?

**Comment by lukechampine** [comment]
The downloading algorithm has changed significantly, so this can be closed for now. If a similar problem presents itself under the new algorithm, we can open a separate issue.
