### ISSUE TITLE
Downloading a file in Windows I have to retype file name

### ISSUE THREAD

**Issue by rj134a** [NebulousLabs/Sia#544]
When downloading a file in Windows when the box pops up asking where to download the file, usually for Windows users we are used to having a default file name there already and can change it if we want. 

But in Sia when downloading, the file name is blank and its a pain to have to type in the name manually.

**Comment by lukechampine** [comment]
I attempted to address this here: https://github.com/lukechampine/Sia-UI/commit/cb05fb7d3c5a786e65dfd02a24bf667f01aabdfe
But it still isn't behaving ideally. Specifically, it only fills in the filename if the file already exists on disk. Otherwise it's blank. I'm not sure why this is.

**Comment by rj134a** [comment]
Yea, sorry. I meant to go to Sia-UI but had Sia bookmarked and didn't pay attention. Happens to me a lot.

**Comment by lukechampine** [comment]
Unfortunately it seems like autofilling the filename is not supported by electron. David is going to file a bug report. In the meantime, we'll have to close this as a "can't fix."

**Comment by DavidVorick** [comment]
@rj134a, @lukechampine: https://github.com/atom/electron/issues/1855#issuecomment-108653674

Seems like there's only a problem on Linux, and that our fix works for Windows and Mac. After the next release you shouldn't have to type the filename yourself unless you are a linux user.
