### ISSUE TITLE
Bootstrapping semantics

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#545]
Currently, bootstrapping looks like this:
- Bootstrap nodes are full nodes, i.e. they mine and relay blocks/txns
- In fact, bootstrap nodes run the same binary as everyone else
- After connecting to a bootstrap node, the peer will request up to 10 addresses from it
- If a bootstrap node has too many peers, it disconnects old peers to make room for new peers

Eventually, bootstrapping should look like this:
- Bootstrap nodes do not run the full Sia protocol, i.e. they cannot mine or relay blocks/txns
- Bootstrap nodes use a different networking protocol (no need for full RPC)
- Bootstrap nodes perform a single function: disseminating addresses
- When a peer connects to a bootstrap node, it is sent up to 1000 addresses
- The peer can optionally send it's own address, to be added to the bootstrap node's address list
- The bootstrap node will verify that this address is connectible
- The bootstrap node will then terminate the connection

**Comment by DavidVorick** [comment]
how does the bootstrap node get addresses?

**Comment by DavidVorick** [comment]
closed for now
