### ISSUE TITLE
Blocks Sometimes get Stuck

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#548]
We've now had two users report of instances where they download the blockchain and get stuck. Clearing the db and re-downloading doesn't seem to help?

We should add some logging to the consensus package that can sort this out. I'm not sure what type of timeline the bugfix would be on though.

**Comment by lukechampine** [comment]
This seems like a difficult bug to reproduce so I agree that logging is our best bet.

**Comment by DavidVorick** [comment]
Perhaps there is a small bug somewhere in consensus/synchronize.go (a file with little testing) that is causing this to pop up on occasion.

**Comment by DavidVorick** [comment]
we haven't seen this in a while, I'm tempted to call it fixed
