### ISSUE TITLE
Muxado safety

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#574]
I'd like to investigate whether the use of muxado constitutes an attack vector. My gut says that it would be possible to trigger a panic on any peer simply by sending malformed traffic. We should ask to @inconshreveable about this possibility, and work with him to patch any discovered vulnerabilities.

**Comment by inconshreveable** [comment]
There should be no way in which garbage traffic can cause a panic, but if there is that's a serious bug. Also, you should be working off the `wip` branch: https://github.com/inconshreveable/muxado/tree/wip

**Comment by lukechampine** [comment]
The specific problem we ran into -- `invalid memory address or nil pointer dereference` --  seemed to be triggered by heartbeats. I'm not totally sure what happened, but my theory is that the heartbeat code doesn't like talking to non-muxado connections.

The build log is [here](https://travis-ci.org/NebulousLabs/Sia/builds/66107392) (grep for "TestListen").
The TestListen code is [here](https://github.com/NebulousLabs/Sia/blob/cb9fd87f9f6055a9d236b7b91b4f67ae9de82a23/modules/gateway/peers_test.go#L25).
Commit ee8a04f7fe4 seemed to resolve the problem.

**Comment by DavidVorick** [comment]
we might want to consider vendoring the `wip` branch

**Comment by lukechampine** [comment]
Good news: bug is not present in `wip`. Bad news: `wip` does not preserve compatibility. That gives us two options:

1. Fork the master branch of muxado and try to patch the nil deref bug
2. Switch to `wip` (or [another multiplexer](https://github.com/inconshreveable/muxado/issues/13)) and make the gateway backwards-compatible 

The former seems more sane to me, since we haven't experienced any real issues with muxado other than it segfaulting during testing. Making the gateway backwards-compatible sounds tricky -- need to abstract its functions so that they work on both connection types, and then use the version string during the initial connection to determine which protocol to use. And we'd need to preserve that compatibility for who-knows-how long...still, it's tempting to make the switch now instead of later.

**Comment by DavidVorick** [comment]
Muxado is known to be a temporary solution anyway. We need a well defined wire protocol and iirc the muxado wire-protocol is very... muxado.

Probably best not to spend a lot of time on it right now though, just be aware that it's going to change dramatically in the future. So I guess I would pick option 1 until we're at a point where it makes sense to sack another 2+ weeks into the gateway.

**Comment by lukechampine** [comment]
presumably fixed in 07356e2d40d9aa6d0eee73c2eba48990038ace51
