### ISSUE TITLE
Support websockets for a subset of functions

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#583]
The miner could use a websocket instead of needing to curl a webpage. Libcurl is a roadblock for windows developers.

The GUI could use some pipeline of information that tells it when there's been an update, instead of polling every 1/3 second.

**Comment by lukechampine** [comment]
The miner will have to replace libcurl with a websocket library. Looks like we can use [libwebsockets](https://libwebsockets.org/trac/libwebsockets) and bundle it with the binary though, which would be preferable.

**Comment by lukechampine** [comment]
This would also mean converting siac to websockets as well.

**Comment by DavidVorick** [comment]
Maybe I got websockets confused with sockets, but I didn't think you needed a library to get two programs talking to each other on the same computer. I thought it was like 20 lines of boilerplate or something simple in C.

We wouldn't be replacing or deleting the web-api calls, the sockets would be an on-top type thing. siac wouldn't need any changes.

**Comment by DavidVorick** [comment]
For the time being, this has been shelved.
