### ISSUE TITLE
Streamlined versioning process

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#584]
We forgot to update the version strings from 0.3.3 to 0.3.3.1

Also, there's no api call for versioning.

finally, our current method of grepping for the version string is bound to fail us at some point. There should be 1 place or 1 script we use to update everything.

**Comment by DavidVorick** [comment]
what is left for this?

Also, we never updated the readme

**Comment by lukechampine** [comment]
The version now lives in one place, `build.Version`. The persist files still use their own individual versions though.

**Comment by DavidVorick** [comment]
So we should switch them to just checking for 'version greater than X'?, but they still follow the global version?

**Comment by lukechampine** [comment]
that's my thinking, yeah. Then we maintain one "load old format" function in case the version check fails.
We'll still be susceptible to another scenario, which is trying to load a future format with an outdated siad. You'll get a normal decoding error in that case.

**Comment by DavidVorick** [comment]
oh yeah. Maybe for files, it should be the opposite way. "version must be lower than"

**Comment by lukechampine** [comment]
I think it's fine for it to just return an error. Actually, since the `LoadFile` function knows both the current version and the version it's trying to load, it could just say `couldn't load file with format v0.12. The format may have changed since v0.3 (your version). Try updating to a later version.`

**Comment by DavidVorick** [comment]
I think we made enough progress here
