### ISSUE TITLE
Address format needs to be more robust

### ISSUE THREAD

**Issue by cyrozap** [NebulousLabs/Sia#588]
The current address format is susceptible to corruption; I suggest a checksum be appended and the new address be base-58 encoded. This would make it more similar to [Bitcoin's address format](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses).

**Comment by DavidVorick** [comment]
why base-58?

We will add a checksum but I kind of like using hex. Makes things easier when going between languages, there's broad support for it.

**Comment by cyrozap** [comment]
I guess you could keep using hex, but a checksum is a must-have. It also might be a good idea to have a version number in the address, so different address types can be supported.

**Comment by DavidVorick** [comment]
fixed :)
