### ISSUE TITLE
Add Units to Siac

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#593]
I believe all units in siac right now are base units, we should add support for S, KS, MS, GS to be recognized.

**Comment by lukechampine** [comment]
:+1:
Right now `/wallet/send` accepts floating-point notation (e.g. `1e27`) but `1 SC` is clearly more natural.
What if you want to send less than 1 SC though?

**Comment by DavidVorick** [comment]
mS and uS
