### ISSUE TITLE
Block Explorer database design

### ISSUE THREAD

**Issue by triazo** [NebulousLabs/Sia#607]
I'm thinking of using a key value store for a database (bolt db).

Buckets:
BlockID -> Block{}
TxID -> Transaction{}
Address -> []Txid
SiacoinOutputID -> Txid
SiafundOutputID -> Txid
FileContractID -> Txid
Hash -> Hash Type (an enum or something similar, provides an entry point for a hash with no context)

I'm considering moving the transactions into the block that contains them, and then the siacoin output id's would point to a block and a transaction number.

**Comment by lukechampine** [comment]
This mostly looks good to me. I support moving txns into blocks. That way we minimize redundancy; all we store is blocks and references to blocks.

I am a little confused as to the function of the Hash bucket.

**Comment by DavidVorick** [comment]
I think it's there so you can get some random unknown hash and figure out what type of object it is.

**Comment by triazo** [comment]
I don't plan on using in many of the internal queries, as we should know what type of hash it is. However, this type of lookup is something that many block explorers implement, and storing an extra bucket at the top shouldn't complicate things too much. For example: http://www.blocktree.io/e/BITB

**Comment by DavidVorick** [comment]
If we wanted to follow an output around:

outputID -> txid
txid -> txn
txn -> scan inputs and outputs
inputs and outputs -> more txids

looks good to me. That's the biggest use case I'm looking for right now.

**Comment by triazo** [comment]
A few revisions and additions:

BlockID -> Block{}
Address -> []Txid
FileContractID -> Txid, []Txid, Txid (File Contract, []Revisions, Storage Proof)
TxID -> (Block, TxNum)

SiacoinOutputID -> Txid (output)
SiacoinOutputID -> Txid (input)
    Could also do SiacoinOutputID -> Txid, Txid, and leave the latter as 0 until the output is spent

SiafundOutputID -> Txid
SiafundOutputID -> Txid
Should mimic Siacoin outputs

Height -> BlockID
Hash -> Hash Type

The second bucket for each siacoin output is to find where a output is spent. Given my scheme in the OP, that would require searching through the chain.  

There will be a fair amount of searching through transactions to do many of the lookups, but ideally a transaction will be small enough to search through quickly. Alternatively, we could store more data (e.g. SiacoinOutputID->(Txid, outputNum)). This would move the complexity from executable code to the data structure given the many different sources of outputs (maybe ID->(Txid, type, Num)?)

**Comment by triazo** [comment]
Might also be a good idea to include more data about each block, such as the child target and its block height, neither of which are easily obtainable given just the block.

**Comment by DavidVorick** [comment]
Best to start small, and do more iterations. You learn things each iteration.

What you have now looks good to me.
