### ISSUE TITLE
Update checking

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#617]
Instead of applying the update automatically, we should just notify the user that an update is available. We could do this by using the GitHub API; then we wouldn't need to update the linode for each version.

**Comment by DavidVorick** [comment]
I believe this is resolved?

**Comment by lukechampine** [comment]
well, SIa-UI now has this behavior. But this issue was more about using the GitHub API rather than the linode.
In theory we could even auto-update by fetching the GitHub download URL, unpacking the archive, etc.

**Comment by lukechampine** [comment]
I'm considering removing the update code + API calls, which would make this entirely a Sia-UI issue. In that case it would definitely have to use the GitHub API though.

**Comment by DavidVorick** [comment]
Right now updating is something of a PITA for the users. I think we're also nearing the point where it actually makes sense to use in-client updating.  Then we can implement an update process that's more than just refreshing the binary, we can migrate all the files and stuff too.

Maybe we are too quick to throw the code away. Should probably start getting regular use as of 0.5.0.

**Comment by DavidVorick** [comment]
Rolling this into the general 'update is not a supported feature' bucket. Hopefully we can have support soon.
