### ISSUE TITLE
Only advertise connectible addresses

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#618]
The node list is full of unreachable addresses. This is because nodes advertise their address even if they haven't forwarded their ports. We could add a simple check, like the host does, to confirm that the address is connectible before sharing the address.

However, some people have reported that the host check is reporting false even though standard port checks show that they are connectible. We should investigate this further.

Regardless, this won't solve the problem of the node list being full of unreachable addresses. We'll need a different tactic to prune that list effectively.

**Comment by DavidVorick** [comment]
seems like the recent pruning is sufficient.
