### ISSUE TITLE
Explorer Api Additions

### ISSUE THREAD

**Issue by triazo** [NebulousLabs/Sia#634]
We already have two api calls to the blockexplorer: status and blockdata

To access the rest of the database, only one api call is strictly needed: some sort of getHash call.

The Hashes bucket stores a map from hash to hash type, so this can be used to automatically return the correct type of data:

Return value based on hash type:

   Hash Type       | Return Value                    
  ---------------- | --------------------------------
  SiacoinOutputID | (txid, txid)                    
   SiafundOutputID | (txid, txid)                    
   FileContractID  | txid, []txid, txid
   TransactionID   | full transaction OR sparseblock 
   Block ID        | Block                           
   Address         | []Txid

The reason for putting txid's in instead of full transactions is that addresses and SiacoinOutputId's may be used in a block as a miner payout, in which case the 'txid' will actually be a block id. Siafunds and Filecontracts cannot be created this way

A sparseblock is a block with each transaction replaced with it's txid.

Alternatively, each of the above calls can be split up into separate more well defined calls, and have the getHash api call simply return the type of hash that it is, requiring the api user to perform multiple calls in some cases, but saving a database lookup in others.

**Comment by DavidVorick** [comment]
ok, this looks sufficient

**Comment by triazo** [comment]
I think this has all been implemented.
