### ISSUE TITLE
Select Entire folders when uploading

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#643]
When you are uploading, doing one file at a time is too tedious. You should be able to pick an entire folder.

**Comment by DavidVorick** [comment]
An addendum: the viewer should also support folders.

**Comment by lukechampine** [comment]
How do we handle nicknames in this context? We obviously can't ask the user to supply a nickname for every file. Should we just use the filename?

**Comment by DavidVorick** [comment]
That's what I was thinking. And if you are scanning subdirs, the nicknames should include the '/' as well.

**Comment by DavidVorick** [comment]
maybe you could specify a prefix, or a 'parent dir', so that all files scanned from whatever folder are given the nickname 'parent/$(file)'

**Comment by lukechampine** [comment]
in that case, is it still reasonable to supply nicknames for individual files?

My thinking is that you never supply a nickname when uploading files, but you can still rename them. This is how most cloud storage services work. Renaming a folder actually means renaming all of its constituent files.

With regard to the API, we will probably wind up mimicking Dropbox, where your endpoints match the path of the file you're retrieving, e.g. `GET /renter/files/path/to/file.jpg`

**Comment by DavidVorick** [comment]
> My thinking is that you never supply a nickname when uploading files, but you can still rename them. 

Sounds okay  to me. 98% of the time you want to keep the same name anyway.

>  Renaming a folder actually means renaming all of its constituent files.

Fine for a naive implementation, but the order notation for larger folders makes me queasy a bit. Especially if you have to update the '.sia' file on disk for every time that's getting renamed.

> `GET /renter/files/path/to/file.jpg`

maybe even `GET /renter/path/to/file.jpg`, regardless seems reasonable to me.

**Comment by lukechampine** [comment]
latter is ambiguous if the path conflicts with an existing call (e.g. you upload a folder called `downloadqueue`)

The notation is pretty bad if you have you read, edit, and write back to disk. That's going to be necessary any time you rename something though.

**Comment by DavidVorick** [comment]
It's one thing for it to be necessary to do it once. It's worse if you have to do it 500 times or 50,000 times (in an industrial setting, for example). But I think it's premature optimization at this point to worry about that.

ambiguity is bad, `renter/files/path` is the better choice

**Comment by DavidVorick** [comment]
for the time being this feature has been outsourced to the GUI. At some point we may add a 'watch folder' feature, but not near enough to belong in the issue tracker.
