### ISSUE TITLE
Responsive siad startup

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#645]
the api should be responsive in the first 500ms of starting siad.

This should get a lot easier once we move everything to a database.

**Comment by DavidVorick** [comment]
June 2015... ha

**Comment by lukechampine** [comment]
Does this mean we can remove the startup output?
```
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
```

**Comment by lukechampine** [comment]
(and maybe add more output to the wallet unlock command, to give some indication of progress?)

**Comment by DavidVorick** [comment]
You can still need a rescan at startup, it's useful to know what is doing the rescanning.

**Comment by DavidVorick** [comment]
Also, was thinking it'd be pretty easy to add some sort of progress output to the rescan.

**Comment by DavidVorick** [comment]
e.g. "5000 out of 48,431 blocks'... '10,000 out of 48,432 blocks', etc.
