### ISSUE TITLE
Error calling /host/announce : host address not reachable; ensure you have forwarded port 9982

### ISSUE THREAD

**Issue by yurikoles** [NebulousLabs/Sia#646]
Some people, including me, report this problem on this linux.org.ru [announcment thread](https://www.linux.org.ru/news/opensource/11728695). I'm pretty sure that port is forwarded since I have DMZ setup on my router pointing to my machine. Online checkers report that port is open.

**Comment by DavidVorick** [comment]
The port forwarding check doesn't always work for some reason.

You can however use 'siac' to make the host announcement anyway. If you haven't actually forwarded your ports, then you will be unable to get file contracts. (There is not much demand for storage right now - it may take a while to get file contracts even if you have forwarded your ports). The command is 'siac host announce --force'

**Comment by lukechampine** [comment]
Worth noting that a good sign you are *not* connectible is having 8 peers or less. siad only makes 8 outgoing connections, if you have more than 8 it means at least one peer was able to reach you. So I would recommend using `--force` only if you have more than 8 peers.

**Comment by DavidVorick** [comment]
There is now improved support in the GUI for port handling.

There should probably be something that detects whether foreign renters are finding you, because if you are properly announced you should be receiving dozens of pings.
