### ISSUE TITLE
Remove strike system

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#653]
They aren't being used; there isn't really a need for high-granularity punishments. If they do become necessary in the future, it's easy to add them back (they do not break compatibility).

A timestamp approach would probably work just fine. Every time you talk to a peer, you reset their "last heard from" timestamp. If the timestamp is too far in the past, you disconnect. Timestamps could also be used to select which nodes to connect to on startup.

**Comment by DavidVorick** [comment]
progress?

**Comment by lukechampine** [comment]
Strikes are not used anymore, but I left this open due to the discussion of timestamps. Perhaps a new issue is more appropriate.

**Comment by lukechampine** [comment]
Closing this for now. We will reconsider strikes/bans at a later time. The gateway's threat model needs thorough examination, as peer management tends to be one of the trickiest parts of p2p systems.
