### ISSUE TITLE
-p flag in siac

### ISSUE THREAD

**Issue by ufm** [NebulousLabs/Sia#654]
I think -p flag should support not only port for communicate with siad, but address also.

**Comment by lukechampine** [comment]
I don't quite understand what you mean by "address."

**Comment by ufm** [comment]
I can start siad like:
siad -d="/var/lib/sia/" -a="192.168.4.3:9980"

but I can not use siac -p="192.168.4.3:9980"

As result siad start and work, but I can not control it.

**Comment by lukechampine** [comment]
ah, gotcha. This should be easy to fix.

**Comment by DavidVorick** [comment]
@ufm 

Be careful about putting the api on a public ip address. There are no security controls in place right now. If someone can ping your siad, they can also get your balance and spend your coins. There's no password protection or anything else.

**Comment by ufm** [comment]
@DavidVorick 

I know, thnx.
