### ISSUE TITLE
Binary organization

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#656]
With the addition of siae (and soon siam?), I think we need to have a discussion on how these tools should fit into the Sia project.

Our current approach is to implement each new tool as a module, add its endpoints to the API, and then build a new binary in the style of siad that initializes an API server with the desired set of modules. To this end, the API server now checks for nil modules so that it only serves requests for non-nil modules.

An alternative would be to package everything into one binary, and then use build tags to select which modules would be included (e.g. `make release modules=consensus,gateway,explorer` for siae). This breaks when you want siae to use different flags from siam, though.

Another option would be to separate these tools into their own repo(s) instead of implementing them as modules. After all, siae and siam are not used by the other modules. This would mean reimplementing the API server (albeit in much simpler fashion) for these tools. A nice result of this would be the removal of the nil checks in the current API server, and a cleaner separation of these tools from the primary codebase. This is the option I'm leaning towards.

**Comment by triazo** [comment]
I'm partial to build flags, as it would keep the code centralized for future changes, but could also produce binaries dedicated to one function.

To put another alternative out there, we could use runtime flags to determine which modules to load (e.g. `siad +explorer -wallet -renter -miner -host` ...) with sane defaults for ordinary use.

**Comment by DavidVorick** [comment]
I don't see why we can't just have runtime flags.

siad by default would have `--renter`, and then optionally you could enable `--miner --host --explorer --minerpool` or you could disable `--renter`. 'siac' I think makes sense as a separate binary - it's completely different from everything else.

Each of those will automatically pull in all the dependencies needed. Renter has wallet + hostdb as dependencies, and those two would pull in things like consensus and gateway.

I'm also in favor of ditching cobra if possible, as well as gcfg (which I don't think we use at all anyway). 'siac' is okay to keep cobra, the use-case seems very strong.

**Comment by lukechampine** [comment]
Hmm. I'm waffling on this one. I think it really depends on what sort of functionality the block explorer and the mining pool will have. I worry that we are succumbing to feature bloat and straying from "do one thing well."

**Comment by DavidVorick** [comment]
It makes sense for everything to be in one larger binary because the amount of shared code is extraordinary.

**Comment by lukechampine** [comment]
Not really. The majority of what's shared can be easily imported. If you moved siae to its own repo, it would just be the files in /modules/blockexplorer and /siae. You wouldn't need to copy over consensus, gateway, etc.

**Comment by DavidVorick** [comment]
true, but you're still doing things like subscriptions, which is unique to the 'siad' group of modules.

All that the binaries do is grant access to the api of the module system of siad.

I am wary of fragmenting.

**Comment by DavidVorick** [comment]
Siae and siad have been merged.
