### ISSUE TITLE
check ip address/ports

### ISSUE THREAD

**Issue by ufm** [NebulousLabs/Sia#658]
In some (not rare) cases access to the "external" ip address unavailable from computer behind firewall. As result - all work fine except "siac host announce" without "-f" flag.

For resolve this trouble needs external tester.

**Comment by lukechampine** [comment]
I don't understand what sort of behavior you are suggesting.

**Comment by DavidVorick** [comment]
he's saying that our test for the host determining if its port is open is insufficient, and instead of trying to ping yourself, you should have someone else try to ping you, or otherwise use a third party service.

I think.

**Comment by ufm** [comment]
@DavidVorick 
Yes.

**Comment by lukechampine** [comment]
gotcha. Perhaps when we transition to the new bootstrapping protocol (#545) we can also use the bootstrap nodes to verify connectivity.

**Comment by lukechampine** [comment]
obsolete as of https://github.com/NebulousLabs/Sia/commit/feb65f28b2141271d0b10f33fc035524029bede4
