### ISSUE TITLE
Rebroadcast address every 24 hours

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#660]
This should mitigate the issue of connectible hosts being removed from node lists.
It would still be nice if unconnectible (non-port forwarded) addresses did not advertise themselves at all. Maybe they could just not rebroadcast? Not sure.

**Comment by DavidVorick** [comment]
What is the status on this?

**Comment by lukechampine** [comment]
I don't see a scenario where this would cause major problems. When you join the network, your address is propagated fairly quickly, and anyone you're connected to is going to share your address with people who ask them for nodes.
