### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#662]
Our startup process should be more sophisticated. Modules can take a while to load (esp. consensus, which will only take longer as the blockchain grows) and the API should be available before that. Similarly, the gateway may take up to 3 seconds to learn its external IP (and forward ports if using UPnP).

Perhaps all we need is an `Init()` method, distinct from `New`, that performs module initialization. I'm not sure what the best approach is.

**Comment by DavidVorick** [comment]
It would also be nice to give the gateway a longer time to startup than just 3 seconds, since sometimes ip address discovery can take that long.

**Comment by lukechampine** [comment]
Closing this as no longer relevant. "Startup" is too vague to define what needs to be done here. The biggest contributor is now the block db, which is undergoing heavy optimization.
