### ISSUE TITLE
Encoding package test coverage

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#666]
```go
// if the array is addressable, we can optimize a bit here
if val.CanAddr() {
        return e.write(val.Slice(0, val.Len()).Bytes())
}
```

This code is never reached during the encoding package tests. It needs test coverage.

**Comment by lukechampine** [comment]
non-rigorous testing has confirmed that this code is reached with significant frequency during normal use, providing a nominal speedup. You are right though, an automated test is needed.
