### ISSUE TITLE
Renamne the blockexplorer to explorer

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#668]
I've decided that the block explorer module should have extended exploring capabilities. Things like querying known sunfish servers for stats, things like crawling the network to count the number of nodes, things like trying to observe relay times, and displaying the up/down status of various important services on the Sia network.

and that merits a name change, because the responsibilities of the module have been made more broad.

**Comment by lukechampine** [comment]
Sunfish and other services are conceptually separate from the main Sia repo. Does it still make sense for the explorer to live in Sia as a module if it is querying those services?

**Comment by lukechampine** [comment]
This issue has been closed, but my question stands. I think your suggestions are reasonable except for Sunfish and other services. It would certainly be useful for us to run a server that displayed uptime of various services, but I don't think that functionality belongs in the Sia repo itself.

**Comment by triazo** [comment]
As it currently stands, the explorer needs running consensus and gateway modules, which justifies it being in the Sia repo. Transaction pool stats also justify this. Perhaps the queries for other services like sunfish could be done in the web front end server, but that would mean having two distinct data stores. Alternatively, we could have the explorer repo import the consensus and gateway modules directly from Sia, keeping one instance of the explorer database with information on more topics. Having consensus/gateway being run by another program altogether doesn't seem right. Perhaps push updates out over the api somehow?

**Comment by lukechampine** [comment]
I think it would be fairly easy to add availability checks to the `Sia-Block-Explorer` repo (which also needs renaming now?).

**Comment by triazo** [comment]
It's been renamed already.

It probably wouldn't be hard to do availability checks, but we design a bit before doing so. The `Sia-Explorer` repo is basically stateless currently, querying the siae api several times for each request. Either we re-check availability of services every time, or shift the design to have some cache. It wouldn't be hard to add something in, but it currently wasn't designed to have any type of persistence.
