### ISSUE TITLE
Hosting toggle

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#674]
This has been discussed before: most nodes aren't hosts, but we currently create a host module for every node. If your host port is open, there is no way to prevent people from forming contracts with you.

This came up now because of UPnP stuff. If UPnP fails to determine your IP or forward your ports, `host.New` should probably return an error. But we can't do that now, because many people would get errors despite not wanting to be a host in the first place.

Easiest way to do this would be to use the existence of a hosting port to decide whether a host module should be created. i.e. unless the host port is set manually, we assume you don't want to be a host. However, this causes problems for the UI, because you can't specify that information when you double-click the UI executable
An alternative would be to create the host, but have it "lie dormant" until explicitly turned on via an API call. (It probably makes sense to have a "toggle hosting" API call anyway, to address the issue discussed in the first paragraph.)

**Comment by DavidVorick** [comment]
fixed a while ago
