### ISSUE TITLE
Consider uTP for data transfer

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#693]
uTP is a novel UDP-based file sharing protocol, designed to mitigate latency and congestion issues. It was designed by the BitTorrent project as a replacement for traditional TCP transport. uTP is also able to slow down its transfer rate when it is impacting the performance of other programs, e.g. a web browser.

These are all desirable features for Sia. I suspect that, long term, we will want to switch away from naive TCP connections in order to maximize upload/download speed. However, I am not yet sure that uTP is the best choice, since the BitTorrent is more "symmetrical" than Sia. There may be other options worth considering as well.

**Comment by DavidVorick** [comment]
too long term to belong on the issue tracker.
