### ISSUE TITLE
Gateway not closed after test completion

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#704]
Instances of the Gateway are not being closed when a test completes (notably in the consensus tests). This causes goroutines to leak, which may be the cause of some testing instability. We need a way to perform teardown after each test. I suggest adding a `Close` method to `consensusSetTester` (and others, as needed) that should be deferred in each test.

**Comment by DavidVorick** [comment]
:'(

ok

**Comment by triazo** [comment]
I'll add this in on top of my pr to make things work.

**Comment by lukechampine** [comment]
`makeOutboundConnections` is definitely leaked. Not sure how to best address that.

`threadedHandleConn` will leak if the peer is malicious (meaning it continues to send muxado heartbeats, but never sends any data).

`acceptConn` will leak if the peer does not send any data (muxado has not been layered on the connection yet).

**Comment by DavidVorick** [comment]
all safelocks are leaked.

It will be pretty easy to add a close function to the safe locks.

**Comment by DavidVorick** [comment]
I believe this specific issue is fixed. The broader issue of things not closing during testing still remains.
