### ISSUE TITLE
Break unwiedly api doc into multiple files

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#718]
The api doc is now very large and should probably be broken up into a separate file per module.

Right now the wallet and consensus are the only ones that are implemented, so this is a bit more of a long term issue.

I'm open to other ideas for breaking up the api doc. Perhaps we could put it on learn.siacoin.com instead of github? Then we can use javascript to make it fancier.

**Comment by Mingling94** [comment]
Yeah. Either Wikipedia style index shortcuts or expanding hidden sections would make it easier to navigate. Though it should still be one doc

**Comment by Fornax96** [comment]
I can think of another good spot to place documentation... https://github.com/NebulousLabs/Sia/wiki

Github also provides easy ways of navigating the wiki.

**Comment by DavidVorick** [comment]
I still haven't used a wiki that I enjoyed, but maybe one day I'll warm up to them. I'm not sure how the github one works, but I definitely wouldn't want anything in our api docs changing without approval from the team.

**Comment by VoidingWarranties** [comment]
Would a table of contents suffice? I don't think separating it into multiple files is the way to go. I added a table of contents with links to each section in #1223, try it out!

If we really want to improve the API docs we should be using something other than markdown.

**Comment by VoidingWarranties** [comment]
@Fornax96 Checkout how [IPFS uses their wiki](https://github.com/ipfs/ipfs/wiki)

They don't have any content in the wiki itself. They link to content outside the wiki. It might be a good idea to do this to provide a good starting point for new users and developers.

The wiki would also be a good place to link to the guides @mnsl has been writing.

**Comment by Fornax96** [comment]
That's also an option. 

I personally like the way Ethereum does their documentation: https://github.com/ethereum/go-ethereum/wiki

**Comment by DavidVorick** [comment]
I like the ipfs method of having a wiki that points to .md files in a github repository. We can likely have something like that, a wiki that links to a bunch of things.

The reason that I want the API broken up into multiple files is because it's likely that you are not going to want to see all of the api calls at once. Even with a table of contents, it's an overwhelming amount of information, and generally I view it as a bad thing to have files that are greater than 400 lines long. Even over 250 is undesirable.

I agree that we should be using something better than markdown to document our api, but we don't have time before 1.0, markdown will have to continue being sufficient.
