### ISSUE TITLE
Unlocking the Wallet During IBD

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#735]
If you unlock the wallet while downloading a bunch of blocks, the program seems to freeze up. I'm not sure if it's because of a deadlock, or because the lock scheduling is really bad, or something else, but it seems to be very bad to try to unlock the wallet before downloading all the blocks.

**Comment by unsystemizer** [comment]
It doesn't really freeze, after a while you can press CTRL+C to get past that (and verify by trying to unlock again, after which it'll tell you the wallet is already unlocked). 
But still, it should behave better (and I seem to have experienced database corruption around the time I was playing with CTRL+C, which may or may not be related, but in any case it's best not to use CTRL+C).

**Comment by DavidVorick** [comment]
If you press ctrl+c twice, it'll fast-kill the process, which will usually corrupt the database. If you just press it once it'll give the process time to close properly, leaving the database intact.

**Comment by DavidVorick** [comment]
fixed
