### ISSUE TITLE
Mining Pool - current state and TODO list

### ISSUE THREAD

**Issue by JoshVorick** [NebulousLabs/Sia#742]
Currently the mining pool / miner do all the communicating they should ever need to do (connecting, negotiating payment channel, and submitting blocks). There are still some checks missing as far as validating block submissions and payment channels. I think that it is all decently documented, but there may be some outdated comments. Feel free to contact me with any questions/clarifications.

Here is a verbose, mostly exhaustive list of things that need to be done (in no special order):
-  Only start mining pool if a flag is passed in (e.g. --miner ":9984")
-  Pool should generate a new address for each miner to pay to (this is then used in the channels map to access that miner's payment channel)
-  Pool (and miner) should have a persistence layer so that they can keep track of payment channels between sessions.
-  Pool should subscribe to tpool and check for when miners close their channels.
-  Pool should use big.Rat for PercentPayout variables.
I feel like I'm missing some thing(s), but I can't think of them now. I'll update the issue when I do.

**Comment by DavidVorick** [comment]
:'(

no mining pool for now
