### ISSUE TITLE
Allow host transfer without penalty

### ISSUE THREAD

**Issue by modwizcode** [NebulousLabs/Sia#749]
Sometimes a host might need to be shutdown, either to perform a software upgrade or because the system was setup to test Sia before being moved to a more permanent system. Given that host announces are stored in the chain, if a host needs to switch ip addresses, they could lose their file contracts and potentially be given a bad rating for the future on the original ip.

Unless I'm mistaken there is no safe way to handle this situation, one solution would be something like signing and publishing a change of address message.

**Comment by DavidVorick** [comment]
> Unless I'm mistaken there is no safe way to handle this situation, one solution would be something like signing and publishing a change of address message.

You are not mistaken. This is one of our concerns, especially given that some people have dynamic ip addresses on their home connections.

For more dedicated/advanced setups, you can actually put a domain name in your host announcement, such as 'thisismysiahost.com:9982'. For people needing an immediate solution, we recommend using a domain name and then relying on the DNS system to handle changing IP addresses.

Improvements to things such as this are targeted for the 0.5 and 0.6 releases.
