### ISSUE TITLE
UPnP mapping conflicts

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#755]
It looks like UPnP will complain about prior existing port mappings instead of silently overwriting them. To ensure the port is correctly forwarded, we should clear the old mapping first (although if I had to guess, clearing a non-existent mapping will return an error as well...)

**Comment by Zatvobor** [comment]
I've been running `said` just only from docker container and seems like `UPnP` mapping does not work. (as I don't see actual port forwarding whereas my router has the `UPnP` support and works well for another containers)

**Comment by lukechampine** [comment]
interesting. Is there output in your `gateway.log` that describes the error?

**Comment by Zatvobor** [comment]
```
2015/12/03 09:30:06.176674 upnp.go:82: WARN: could not automatically forward port 9981: no UPnP-enabled devices found
2015/12/03 09:30:06.287624 upnp.go:68: INFO: our address is x.x.58.20:9981
```

**Comment by DavidVorick** [comment]
also a bunch of dumb stderr messages get dumped to the terminal, which is not ideal

**Comment by lukechampine** [comment]
closing this since it's harmless

**Comment by lukechampine** [comment]
(fixed output in https://github.com/NebulousLabs/go-upnp/issues/3)
