### ISSUE TITLE
database bad after unclean shutdown

### ISSUE THREAD

**Issue by crypto750** [NebulousLabs/Sia#795]
FreeBSD 10, Sia compiled from sources 2 days ago.
I did an accidental reboot, the Sia db didn't shut down cleanly. You may be interested to see the logs.

Reading symbols from /lib/libthr.so.3...done.
[New Thread 801c55c00 (LWP 100086/siad)]
[New Thread 801c55800 (LWP 100082/siad)]
[New Thread 801c3b800 (LWP 100081/siad)]
[New Thread 801c20800 (LWP 100080/siad)]
[New Thread 801c06c00 (LWP 100079/siad)]
[New Thread 801c06800 (LWP 100078/siad)]
[New Thread 801c06400 (LWP 100075/siad)]
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
[Switching to Thread 801c55c00 (LWP 100086/siad)]
runtime.sys_umtx_op () at /usr/local/go/src/runtime/sys_freebsd_amd64.s:45
45		MOVL	AX, ret+32(FP)
(gdb) bt
#0  runtime.sys_umtx_op () at /usr/local/go/src/runtime/sys_freebsd_amd64.s:45
#1  0x0000000000431e82 in futexsleep () at /usr/local/go/src/runtime/os_freebsd.c:78
#2  0x000000c208218458 in ?? ()
#3  0x000000000000000f in ?? ()
#4  0x0000000000000000 in ?? ()
Current language:  auto; currently minimal

Loading...
A lock was held for too long, id '28561'. Call stack:
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:74'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:231'
A lock was held until deadlock, subsequent call to unlock failed. id '28561'. Call stack:
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:80'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:231'
A lock was held for too long, id '28560'. Call stack:
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/transactionpool/subscribe.go:52'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:140'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/siad/daemon.go:54'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/siad/daemon.go:107'
	File: '/root/.gosrc/src/github.com/spf13/cobra/command.go:503'
	File: '/root/.gosrc/src/github.com/spf13/cobra/command.go:586'
A lock was held until deadlock, subsequent call to unlock failed. id '28560'. Call stack:
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/transactionpool/subscribe.go:50'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/modules/miner/miner.go:140'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/siad/daemon.go:54'
	File: '/root/.gosrc/src/github.com/NebulousLabs/Sia/siad/daemon.go:107'
	File: '/root/.gosrc/src/github.com/spf13/cobra/command.go:503'
	File: '/root/.gosrc/src/github.com/spf13/cobra/command.go:586'
Loading...
database guard indicates inconsistency within database

**Comment by DavidVorick** [comment]
should be fixed after I made all the database changes. Can repoen if there are still problems.
