### ISSUE TITLE
Not enough hosts error during uploading

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia#799]
I find that `upload.go` starts throwing the error `Could not upload file: Upload failed: not enough hosts to support upload`. It seems a bit erratic when this happens, but perhaps especially so after a period of bulk uploading (10+ files). Even then, some files get uploaded, while others fail. It does not seem to depend on filesize or interval beween file uploads. Overall, more than 75% of files fail to upload due to this error. I have confirmed that my node is always well connected with peers by running `siac hostdb`.

Here's a quick bash script to test. Setting the sleep to 10 seconds seems to match the time it takes `upload'.go` to give up before it throws the error.

```bash
#!/bin/bash

i=1
for i in {1..10}
do
   echo "uploading file $i"
  ./siac renter upload test.txt $i.txt &
  sleep 1
done
```

**Comment by lukechampine** [comment]
This sort of error will always be nondeterministic, in part because the hosts are selected randomly. It should become less of a problem as the number of hosts increases and the host selection algorithm improves.

**Comment by DavidVorick** [comment]
What version are you using? This problem will be more prevalent on 0.3.3.3 than 0.4.x. We're working on the uploading process right now, so that files will stop uploading at partial redundancy.

**Comment by pmknutsen** [comment]
@DavidVorick I am using 0.4.2
@lukechampine Even if hosts are (understandably) selected at random, why do some upload then fail and others succeed? 

In 'upload.go', line 187
```
	hostUploader, err := r.newHostUploader(randHosts[i], totalsize, up.Duration, f.masterKey)
		if err != nil {
			continue
		}
````
the list of hosts shrinks when continue is hit, thus the condition on line 194 fails:

```
if len(hosts) < up.ErasureCode.MinPieces() {
```

throwing the "Not enough hosts" error.

It seems that `for i := range randHosts` should be replace with a `while` loop until the right number of hosts have been found, or something to that effect.

**Comment by lukechampine** [comment]
the problem with a simple `while` loop is that it will never terminate if the hostdb does not contain enough unique hosts. But yeah, we could probably improve this code by looping a few times to maximize the chance of selecting enough hosts.

`newHostUploader` is defined in negotiate.go. It returns an object that implements the `uploader` interface.

**Comment by pmknutsen** [comment]
The way its now, if any of the randomly selected hosts are down, file upload fails. Probabilistically, there is a very high chance of that with few hosts (as today). Even as the network grows, this will continue to be a problem to annoy users. If there are enough hosts available on the network, it will be best to locate those regardless. A simple `while` loop with a timeout built in should suffice I think.

**Comment by lukechampine** [comment]
>if any of the randomly selected hosts are down, file upload fails

not true if by failure you mean the "not enough hosts" error. That error is displayed when you weren't able to form contracts with at least `MinPieces` hosts (of `NumPieces` total), which in the current implementation means 2 out of 12.

at any rate, I'm working on a patch for this now. It should land in the next release, v0.4.3.
