### ISSUE TITLE
TestIntegrationComplexReorg is flaky

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#826]
I'm seeing failures on TestIntegrationComplexReorg even when I haven't made functional changes to the code. Seems that this is a false negative and it's failing when the code is still correct:
https://travis-ci.org/NebulousLabs/Sia/builds/87403942

**Comment by DavidVorick** [comment]
There's an error in boltdb that causes it to sometimes drop a whole bunch of elements in the database in a larger tx. We're still hunting for the fix, but it only seems to be a problem during reorgs.

It might have something to do with adding and removing an element with the same key and value multiple times within one tx.

**Comment by DavidVorick** [comment]
this has been fixed :)
