### ISSUE TITLE
Price reported incorrectly in `hostdb/hosts/active`

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia#833]
Prices charged by hosts is reported incorrectly by `/hostdb/hosts/active`. Example:

`curl -s -X GET http://localhost:9980/hostdb/hosts/active -A "Sia-Agent"`

returns (for one of the active hosts):

```
{
      "UnlockHash": "b6d303f2372188aff5790d72051091e711fdf3bbdc51c7c428a8b06f8ae505a373eafb87e882",
      "Collateral": "0",
      "IPAddress": "54.179.132.31:9982",
      "TotalStorage": 2.8e+10,
      "MinFilesize": 1000,
      "MaxFilesize": 1e+10,
      "MinDuration": 5,
      "MaxDuration": 30,
      "WindowSize": 288,
      "Price": "4629629629629"
    },
```

Correct price in this example should be 19e+23 hastings. Also, note the repeating 3 digist in the price presumably due to some incorrect rounding in the code.

Other examples of prices returned:
```
92592592592592
4398148148148
11574074074074
2314814814814
13657407407407
```

note the repeating 3 digits in all instances.

**Comment by DavidVorick** [comment]
What makes you think it should be reported as 19e23 hastings? That's a very high price.

The price returned by the api call is 'hastings per byte per block'. To get 'SC per GB per Month', you need to multiply by 4.32 and then divide by 1 trillion.

**Comment by pmknutsen** [comment]
Duh... I thought the price reported was GB/mo, and didn't pay attention to `/doc/API.md` which does clearly state hastings per byte per block. Apologies! But hey, its not every day I get to close a ticket!
