### ISSUE TITLE
Explorer api returns all lowercase strings for parameter names

### ISSUE THREAD

**Issue by agundy** [NebulousLabs/Sia#857]
I suggest we attempt to follow the Google JSON style guide which calls for camelcase parameter names. https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Guidelines the long completely lowercase strings are unconventional and make human readability difficult.

**Comment by DavidVorick** [comment]
@lukechampine can you comment on this? If we're going to switch styles we need to do it soon.

**Comment by lukechampine** [comment]
I'm in favor of camelcase. It seems to be the standard for JS property names like `window.userAgent`, which is where JSON originated.
Changing all the names everywhere could be a pain. Should we just start with the explorer API? Or perhaps change them all at once in a new release?

**Comment by DavidVorick** [comment]
yeah just grep for `json` and see what breaks.

**Comment by DavidVorick** [comment]
I'm counting 241 fields that need to be modified.

**Comment by DavidVorick** [comment]
That will unfortunately break `siac` (which is already broken) and `Sia-UI` (which Ming can probably tune up pretty quickly), and the explorer (which I need to modify a bit anyway)
