### ISSUE TITLE
Host and HostDB should store Merkle trees

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#864]
In order to enable long-term host relationships, the HostDB needs to save the current state of the Merkle tree to disk. We can get away without doing this now because the revisions are always "one-shot" -- the contract is created and revised to completion in one session, so the Merkle tree just lives in memory. But if we want to revise across sessions, this would require re-reading all of the contract data, which is neither trivial nor desirable. Fortunately, Merkle trees are small and storing them should not require much code to implement.

The Host, since it always has access to the full contract data, can simply rebuild the Merkle tree from scratch upon each revision. But storing the Merkle tree is far more efficient, so there's no reason not to add persistent trees to the Host at the same time as the HostDB.

**Comment by DavidVorick** [comment]
If we get to the point where hosts are doing entire file contracts at 4TB, it's going to be hugely desirable to have a file where the merkle trees are available, such that the amount of disk access and hashing can be kept well below 1GB.

I'm not sure when I plan to add this optimization, but I feel that it's absolutely necessary for any sort of scaling system. Storing the merkle tree object is not enough, you need all of the n-layer leaves (say... the merkle root of each set of 16MB).

**Comment by DavidVorick** [comment]
They now do this
