### ISSUE TITLE
Dockerfile proposal

### ISSUE THREAD

**Issue by Zatvobor** [NebulousLabs/Sia#866]
Hi there. 

I pleased to share with community a [siad.dockerfile](https://gist.github.com/Zatvobor/3e16110385133219d36b) that contains a complete solution for deployment and further maintenance. 

In additional, I'm ok to send a PR into any of appropriate `NebulousLabs` repo.

**Comment by DavidVorick** [comment]
That is cool, thanks a bunch. I'm not sure where to put it yet, but we'll find a place to add it to the repo.

**Comment by DavidVorick** [comment]
Okay, took a while but I checked out the docker file.

Two issues:

1. It has hardcoded v0.4.8, it would be nice if the dockerfile could do a lookup to get the latest version
2. It always grabs the 32bit version of the binary. If docker is always 32bit, that's not a problem.

**Comment by Zatvobor** [comment]
It's ok to hardcode particular version if `Dockerfile` is under git control (it's true both for standalone repository and when `Dockerfile` is a part of main repository). Secondly, a version of the binary would be managed through environment variable, similar `SIA_VERSION`.

**Comment by mtlynch** [comment]
I created something similar:

http://mtlynch.io/sia-via-docker/
