### ISSUE TITLE
Moving available file Contracts to another node

### ISSUE THREAD

**Issue by Zatvobor** [NebulousLabs/Sia#869]
I've been running an experimental file storage, got some file contracts. Secondly, I would like to move some of these to another hosting ring. 

I wondering, Is there available option at all?

**Comment by lukechampine** [comment]
technically you could, but since your IP address would change (I assume), the uploader would no longer be able to retrieve the file.

**Comment by DavidVorick** [comment]
It would work if you announced yourself from a domain name, using something like dyDNS. But I don't think we have support for moving file contracts around

**Comment by Zatvobor** [comment]
got it. Thanks
