### ISSUE TITLE
safeFile data loss

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#887]
`safeFile.Commit` calls `os.Rename` without calling `os.File.Sync` first. As described in slides [74](http://www.slideshare.net/nan1nan1/eat-my-data/74) to [87](http://www.slideshare.net/nan1nan1/eat-my-data/87) of [Eat My Data: How Everbody Gets File IO Wrong](http://www.slideshare.net/nan1nan1/eat-my-data), `fsync` needs to be called before rename. AFAIK `os.Rename` directly makes the syscall and does not automatically sync. I'll add the fix to PR #886.

**Comment by DavidVorick** [comment]
lol slide 79

**Comment by DavidVorick** [comment]
ouch - slide 106. What is the point of a syscall if it's legally allowed to do nothing?

**Comment by VoidingWarranties** [comment]
Slide 99 omits the rest of the quote which rationalizes it.
>If _POSIX_SYNCHRONIZED_IO is not defined, the wording relies heavily on the conformance document to tell the user what can be expected from the system. It is explicitly intended that a null implementation is permitted. This could be valid in the case where the system cannot assure non-volatile storage under any circumstances or when the system is highly fault-tolerant and the functionality is not required. In the middle ground between these extremes, fsync() might or might not actually cause data to be written where it is safe from a power failure. The conformance document should identify at least that one configuration exists (and how to obtain that configuration) where this can be assured for at least some files that the user can select to use for critical data. It is not intended that an exhaustive list is required, but rather sufficient information is provided so that if critical data needs to be saved, the user can determine how the system is to be configured to allow the data to be written to non-volatile storage.

[src](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fsync.html)

With regards to slide 98 calling out OS X, this [mailing list archive](http://lists.apple.com/archives/darwin-dev/2005/Feb/msg00072.html) explains it. TLDR: OS X flushes the data to disk, but does not tell the drive to flush the data from the drive's buffer, which is only a concern during power failure.
