### ISSUE TITLE
Wallet Weirdness

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#924]
If you unlock and then relock the wallet within a short span of time, you get wallet weirdness.

The solution is not as simple as adding a lock, because unlocking does some stuff with consensus. The unlocking process is likely to require a bool covered by a separate lock.

**Comment by lukechampine** [comment]
is this still an issue?

**Comment by DavidVorick** [comment]
Yeah, just because the wallet needs to have an 'unlocking' state, instead of just a binary locked/unlocked state.

**Comment by DavidVorick** [comment]
I believe I fixed this at some point.
