### ISSUE TITLE
siac documentation

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#932]
siac's README documentation is out of date. It's also redundant as there is already documentation for commands with the `--help` flag. If we need to keep the README we could autogenerate it from the `--help` docs so that it never diverges.

**Comment by lukechampine** [comment]
wow. I totally forgot that README existed. It can probably just be deleted outright.

**Comment by VoidingWarranties** [comment]
Cobra has markdown generation from cobra commands https://github.com/spf13/cobra/blob/master/doc/md_docs.md.

**Comment by DavidVorick** [comment]
Siac should have a readme. It should explain how to make use of the help menu.
