### ISSUE TITLE
Large transactions can fail

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#94]
sometimes we'll send like 25,000,000 coins and it'll produce an invalid signature, but the wallet won't realize it and won't try again.

I think it's a problem with either one of the inputs in particular, or just a problem when you have 30+ inputs to your transaction. Needs more investigation.

**Comment by DavidVorick** [comment]
Now that we have unit tests, it's pretty clear that it's unrelated to large transactions, it just happens sometimes and it seems to happen more often when your transactions are large.

**Comment by lukechampine** [comment]
any theories as to why? How does the codepath for a large transaction differ from that of a small transaction?

**Comment by DavidVorick** [comment]
The biggest difference is that there are multiple signatures. Three ideas:

1. There's a bug or race condition in the wallet somewhere that only triggers once in a while.
2. There's a bug in the encoding library somewhere that only triggers once in a while.
3. Either we're misusing the crypto library or that has a bug that only triggers once in a while.

I have a good way to probe this further, I'll get to it soon. Should be pretty easy to figure out where the mistake is by making thousands of small transactions.
