### ISSUE TITLE
Can't delete .sia folders

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia#940]
Upload a file to `foo/file.ext`
Do `siac renter delete foo/file.ext`

Result:
`foo/file.ext` is removed from renter
`foo/file.ext` is removed from disk
`foo/` remains on disk (which is the bug)

**Comment by lukechampine** [comment]
I think this behavior is reasonable. The real problem is that (IIRC) there isn't a way to delete a folder directly, i.e. `siac renter delete foo`. In general, we should try to make the renter "filesystem" behave isomorphically to a traditional filesystem.

**Comment by DavidVorick** [comment]
Opening a new programming task issue for this
