### ISSUE TITLE
siad directory flag default

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#951]
The `-d, --sia-directory` flag for siad does not indicate that if the flag is not specified, the current directory will be used. It's all too easy to startup siad from the wrong directory, creating a bunch of clutter files and downloading the blockchain all over again.

option 1:
Make the `-d, --sia-directory` flag required.

option 2:
Indicate in the flag usage that the current directory is the default.

As a new user my first instinct is often to run the command. For siad, this would be undesirable. Option 1 would prevent this.

**Comment by DavidVorick** [comment]
hmm. It's a daemon, it's got the `d` suffix, I feel like it should be pretty clear. I think that's how most daemons work?
