### ISSUE TITLE
Trailing Spaces - siac and sia-ui

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#962]
Sia-UI will not correctly delete a file with a trailing space.

Siac does not make it clear when a filename has a trailing space. Though, I'm not really sure the best way to test for that, except maybe to highlight the text.

**Comment by VoidingWarranties** [comment]
`ls` does not highlight the extra space, but this is less of a problem because of tab completion. Having tab completion in the renter would be great!

**Comment by DavidVorick** [comment]
I'm not sure that makes sense, at least in the API. Tab completion for siac might make more sense, though I don't know how much work that will be.

But this is also a problem in the UI, where the UI will be unable to delete or rename files with a trailing space.
