### ISSUE TITLE
Saving/Loading the blockchain

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#98]
Once we stop pretending the blockchain can exist in RAM forever, things are going to get tricky. We're going to want to store the block chain in a database of some sort, and I don't trust us to write one, at least not an efficient one.

It looks like the official Bitcoin client uses [LevelDB](https://github.com/google/leveldb). There's a detailed write-up of the Bitcoin database [here](http://bitcoin.stackexchange.com/a/29418). It's probably in our best interest to stick to this as close as possible (at least wherever our needs are aligned).

LevelDB uses Snappy, a compression library designed by Google. It optimizes for speed over compression ratio (anywhere from 20% to 100% larger than zlib), so it may not be the best choice. Depends on how many reads/writes you're doing, I suppose.

Broadly speaking, my opinion is that our initial client should make design decisions that benefit the average, "non-enthusiast" user. In this case, that would mean choosing a database scheme that minimizes the size of the blockchain on disk, at the expense of slower reads/writes.

**Comment by DavidVorick** [comment]
When this gets implemented, we should save all of the block nodes. That'll make it easy to navigate between forks or rebuild from 0 without having to do all of the expensive verification.

We can also save the state. Keeping really old diffs might not actually even be necessary (where really old is defined as a few weeks lol). And for most nodes, saving really old blocks shouldn't be necessary either. It should be sufficient to view the blocks once, confirm everything for yourself, and then discard everything. People who want to catch up from the very beginning can talk to archive nodes or full nodes, or maybe even... we store the old blocks on Sia using File Contracts with very heavy missed proof penalties.

There's no reason for a the whole blockchain to be mandatory downloading for everyone

**Comment by Kroese** [comment]
Maybe this wrapper is suitable: https://github.com/tecbot/gorocksdb Its based on LevelDB, and its the database that Monero used when they switched from RAM to persistant storage.
