### ISSUE TITLE
Unknown Host URL for Announce

### ISSUE THREAD

**Issue by trismegistis** [NebulousLabs/Sia#980]
Hi in Sia latest client I can't even use it because of strange visual glitches, so I moved to 0.5.0-rc.

Now when I try to host some GB and announce my hosting, it asks for me to specify a URL to announce on.. what URL do I use??

**Comment by LuccoJ** [comment]
Your IP, or your hostname if you have one.

**Comment by DavidVorick** [comment]
Don't use the release candidates. They have substantially altered constants and are not fit for regular use. They are just meant to pilot new features.
