### ISSUE TITLE
Add timeouts to all gateway operations

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#988]
If a connection is dropped in the middle of an RPC the RPC func will hang forever. `Conn.SetDeadline` can be used to timeout a read/write to a conn.

**Comment by lukechampine** [comment]
yup, the host already does this by setting a 5-minute deadline on every incoming call. RPCs can extend the deadline if they desire.

**Comment by DavidVorick** [comment]
*can extend the deadlines a bounded number of times

**Comment by DavidVorick** [comment]
status update on this?
