### ISSUE TITLE
on OpenBSD/amd64  as of commit d461e3422695f4f0f047972b1b1d17649f62bcfa Sia/siad and Sia/siac do not build

### ISSUE THREAD

**Issue by toddfries** [NebulousLabs/Sia#990]
<pre>
l$ go build .
# github.com/NebulousLabs/Sia/persist
../persist/log.go:57: undefined: log.LUTC
# github.com/NebulousLabs/Sia/api
../api/server.go:63: undefined: signal.Reset
l$ pwd
/home/todd/go/src/github.com/NebulousLabs/Sia/siad
</pre>

go version go1.4.2 openbsd/amd64

**Comment by DavidVorick** [comment]
I believe log.LUTC was not added until go1.5. Additionally, a security vulnerability was found in versions earlier than go1.5.3, therefore it's strongly recommended that every upgrade to at least go1.5.3.

I'll reopen the issue if the problem persists after upgrading.
