### ISSUE TITLE
Add constants for 'rc'

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#998]
Just like we have dev, testing, and release constants, I think it makes sense to have rc constants which submit shorter proofs, have lower file limits, use less hosts, etc. Then we don't have to switch up the constants every time we want to release an rc, we can just know that we've got functional rc constants.

**Comment by lukechampine** [comment]
Jordan and I were discussing this, and it occurred to me that the constants we want to change usually depend on what functionality was introduced by the RC. So I'm not sure that hardcoding RC constants makes sense.

**Comment by DavidVorick** [comment]
Some of them you probably want to change regardless. For example, you want the upload times to be short enough that you can get a full upload cycle through (with renewing and whatnot) before the full release is out.

That's the only major one I can think of off the top of my head, but I'm guessing that if we were to go through the full list of constants we'd find a few other things that everyone would agree should be changed for all rc releases.
