### ISSUE TITLE
goroutine 171983 [chan receive, 30 minutes]

### ISSUE THREAD

**Issue by wiseguy12851** [NebulousLabs/Sia#999]
I started up a linux ubuntu 64-bit server to begin uploading to and using the sia network. After setting it up, opening and unlocking a wallet, and issuing the files to upload I closed out of it to do some other things. The next day I logged back into the server to find out that the daemon had crashed, I knew this was all beta so I reopened the daemon to try again however by the day-after it had crashed again.

Heres the error I'm getting:

    ...
    goroutine 171974 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc8499b93e0, 0x16, 0xc8499b93a0, 0x1b, 0xb9b8, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171975 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc83754efa0, 0x16, 0xc83754ef60, 0x1b, 0xb8e0, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171976 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc82e664060, 0x16, 0xc82e664020, 0x1b, 0xb8f7, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171977 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc823284fe0, 0x15, 0xc823284f60, 0x1a, 0xb835, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171978 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc84aa4bc20, 0x16, 0xc84aa4bbe0, 0x1b, 0xb89d, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171979 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc82fc96260, 0x16, 0xc82fc96220, 0x1b, 0xb91f, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171980 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc8232232e0, 0x16, 0xc823223280, 0x1b, 0xb875, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171981 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc8215e36a0, 0x16, 0xc8215e3660, 0x1b, 0xb910, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171982 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc823a2f6a0, 0x16, 0xc823a2f640, 0x1b, 0xb88b, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

    goroutine 171983 [chan receive, 30 minutes]:
    github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop.func1(0xc843dc2cb0, 0xc839b74420, 0xc823c60300, 0xc841a7de00, 0x16, 0xc841a7ddc0, 0x1b, 0xb8ab, 0x40c701)
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:220 +0x68
    created by github.com/NebulousLabs/Sia/modules/renter.(*Renter).threadedRepairLoop
            /home/luke/go/src/github.com/NebulousLabs/Sia/modules/renter/repair.go:223 +0x48d

It goes on further upwards, shown here is the last bit of the error messages. Hope that helps and let me know if you need anything else

**Comment by lukechampine** [comment]
Generally the most important part of the stack trace is at the top. Do you have that info?

**Comment by wiseguy12851** [comment]
I don't, the stack trace was so long that it scrolled past the maximum buffer. I'll try again and attempt to increase the buffer or send the output to a file.

**Comment by DavidVorick** [comment]
Given that the repair loop has changed substnatially, I'm closing this as 'probably no longer applies'.
